### ISSUE TITLE
Reblog Display Options Refresh Bug

### ISSUE THREAD

**Issue by ospreysoul** [new-xkit/XKit#1002]
Changing my reblog style from nested to flat or vice versa causes a small prompt to open saying the changes won't take effect until I refresh. The Refresh button on the prompt doesn't work. I have to hit Cancel instead, which still causes the change to take effect once I've refreshed the page.

**Comment by nightpool** [comment]
Are you on Firefox?

**Comment by ospreysoul** [comment]
Nope, the latest update for Chrome.

**Comment by nightpool** [comment]
couldn't reproduce
