### ISSUE TITLE
Old Sidebar hiding notes from Notifications+

### ISSUE THREAD

**Issue by nyna237** [new-xkit/XKit#1004]
When I hover on a notification to view the number of notes, the sidebar is hiding the little flag with the number in it (see attached picture). This wasn't the case before the most recent Old Sidebar update this week.

![capture](https://cloud.githubusercontent.com/assets/17316941/14050274/c7eefb18-f288-11e5-93b7-a4328afbedd7.PNG)

**Comment by nightpool** [comment]
@estufar not sure if you're following the repo or not, so thought I might tag you here

**Comment by estufar** [comment]
Yeah, I'll take a look at this

**Comment by nightpool** [comment]
No stress, thanks.
