### ISSUE TITLE
Polyvore standalone ad appeared

### ISSUE THREAD

**Issue by ryulong** [new-xkit/XKit#1005]
Ended up temporarily blocking it with adblock and it gave tumblr.com##.standalone-ad-container as the resultant filter, but I unblocked it after realizing it disrupted the keyboard scrolling.

**Comment by ryulong** [comment]
I've come across it again and managed to get the element inspection html http://pastebin.com/ZPtndC09

**Comment by coderpatsy** [comment]
Anti-Capitalism hides that ad container. Also Tumblr Savior.

**Comment by nightpool** [comment]
Yeah I'm confused about the problem here—that seems to be an ad we're
already dealing with.

**Comment by ryulong** [comment]
I haven't had anti-capitalism active and haven't seen any of these. Also, I've just discovered anti-capitalism and these new ads disrupt the keyboard scrolling

**Comment by nightpool** [comment]
Wait, if you didn't have anti-capitalism activated why would you expect the ads to have been blocked?

**Comment by ryulong** [comment]
I've never had the ads show up otherwise and it just seemed weird that these would show up suddenly.

**Comment by nightpool** [comment]
okay, well, we don't block any ads so this isn't an xkit issue?
