### ISSUE TITLE
New notes on dash broke the "Retags" extension.

### ISSUE THREAD

**Issue by wooziwoozi** [new-xkit/XKit#1008]
I don't know what to title this. Sorry. 

When you click on '### notes" on the dash, "retags" used to show the tags here. I know there is a "veiw tags" extention, and such, but I prefer using the default 'notes' as I could click the blogs and it would open in peepr.

[Screencap in case I don't make sense.](http://i.imgur.com/4JkRLLV.png)

[This is how it used to look.](http://i.imgur.com/78feNBo.png)

**Comment by nightpool** [comment]
see https://new-xkit-extension.tumblr.com/post/141884563304/update-on-retags-extension and #1006. Please follow our blog if you're not already, so you can see announcements like these!

**Comment by wooziwoozi** [comment]
Oh sorry!! I was just told to report errors to the github by someone and to not use the Tumblr before. Sorry to be a hassle. I will remember to check there next time!!

**Comment by nightpool** [comment]
@wooziwoozi reporting errors to the github is correct, but you should make sure they're not duplicates before reporting them :D

**Comment by wooziwoozi** [comment]
Yea, makes sense, I will keep that in mind!
