### ISSUE TITLE
Wonkey Notifications with new Tumblr Update

### ISSUE THREAD

**Issue by ElliSpeaks** [new-xkit/XKit#1010]
IDK if this is the right place to put this, since it's a Tumblr bug not an XKit bug, but with the new update and bringing back replies, it seems as though now notifications are doubling.

![image](https://cloud.githubusercontent.com/assets/15959327/14287902/87e61658-fb09-11e5-9d61-8a760ea66bb6.png)

This shows in the drop down and the Classic Notifications as well. Is there anything that can be done to hide the duplicate?

**Comment by nightpool** [comment]
closed as not an xkit bug and probably something not in scope for us, sorry!
