### ISSUE TITLE
Editable Reblogs & Glitched Notifications

### ISSUE THREAD

**Issue by Kikaromi** [new-xkit/XKit#1011]
![strange](https://cloud.githubusercontent.com/assets/13576045/14303134/ac50d802-fb6d-11e5-9e20-eadb3c269a19.png)

I was checking my Activity Feed and noticed this notification chain, all from the same post (though not all reblogging the original post itself) that was created by myself. It seems the person who reblogs it from me keeps having a notification pop up twice, and now it'll notify me when I myself reblog the post; this wasn't the case in the past.

It seems to only be affecting posts as of recently AND were originally created by yourself, as I went farther down to make sure I wasn't assuming things:
![strange2](https://cloud.githubusercontent.com/assets/13576045/14303263/b7d97c82-fb6e-11e5-8447-78bb3b82f2fb.png)
From a post that's NOT mine

![strange3](https://cloud.githubusercontent.com/assets/13576045/14303314/3c37e07c-fb6f-11e5-9f64-3a24939da4b2.png)

From a post 11 days ago that I'm still the source of

Any idea as for why this suddenly happened?

**Comment by ElliSpeaks** [comment]
This was something that got changed and is a Tumblr bug when they released Replies. I put in a request about the duplicates since I didn't know if it was something xKit could address, but they closed it saying there was likely nothing they could do. Take out a ticket with Tumblr Support.

**Comment by Kikaromi** [comment]
Did you also make a request about the reblogging yourself notifications too? I don't know if that would also be a by-product of that same bug. If it is though, I'll close the issue.

**Comment by ElliSpeaks** [comment]
I did not include that (mostly because I don't mind that so much); but it's still a Tumblr issue not an xKit issue. Doesn't mean they might not do something about it though :)
