### ISSUE TITLE
On-Blog icons are semi-broken.

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#1014]
![ss 2016-04-09 at 06 01 46](https://cloud.githubusercontent.com/assets/13604430/14401655/9df9f952-fe18-11e5-83c6-c561d39a6ae1.png)

At least this is what it looks like to me. (Chrome-user)

**Comment by cdddddd** [comment]
![image](https://cloud.githubusercontent.com/assets/18541402/14623431/21671db8-05a0-11e6-881d-78a61bbb90eb.png)
Same; also a Chrome User.

**Comment by version365** [comment]
![k4soovn](https://cloud.githubusercontent.com/assets/12146319/14944786/65ad8526-101c-11e6-9545-d251de93473c.png)
![tbdurxq](https://cloud.githubusercontent.com/assets/12146319/14944787/6c454612-101c-11e6-9f8d-06f1fe7ad209.png)
![vjd6bxq](https://cloud.githubusercontent.com/assets/12146319/14944789/9431dbea-101c-11e6-9229-76184251fb1f.png)

Same happens on Firefox..
