### ISSUE TITLE
Go-to-Dash not working

### ISSUE THREAD

**Issue by ValensHawke** [new-xkit/XKit#1017]
At least on Chrome, 
There is no more "View" button. In fact, none of the X-kit buttons that popup when you go to a blog and view a post are there anymore.

**Comment by EtherealV** [comment]
I'm also having this issue. It's been broken for about a week now.

**Comment by ValensHawke** [comment]
This bug is definitely related to #1014 as for some blogs, none of the icons show up, are broken as referenced in #1014 or show up mostly but are cut off. Also, not appear entirely seems to be when you visit the blog then click on a post. If you click on a post in your dash and go to their blog, I get broken icons like in #1014. However, some blogs I can mostly see the icons before they get cut off.

**Comment by nightpool** [comment]
dupe of [#1014 On-Blog icons are semi-broken.](1014)
