### ISSUE TITLE
[Code: 101] Can't reach XKit servers?

### ISSUE THREAD

**Issue by blacRose** [new-xkit/XKit#1019]
Just as simple as that error. On latest OS (10.11.5 Beta) and newest Safari Technology Preview (V2). On other tumblr tabs, tries to initialize forever…

**Comment by Diva3802016** [comment]
My Xkit works fine, but this error message keeps popping up on my dashboard after XKit tries to initialize (because it thinks it has to for some reason), and I have to wait for it for several minutes for it to get to this error message before I can click ok and continue surfing my Tumblr dashboard. Super annoying. Hope this will be fixed soon.

**Comment by waltrehs** [comment]
also running 10.11.5 Beta and Safari Technology Preview. In Safari Technology Preview the "installing XKit 7.7.1 appears and hangs for approximately 15 minutes when it finally give up and gives the 101 error. No issue on Safari Version 9.1.1 (11601.6.16), Google Chrome Version 50.0.2661.86 (64-bit), and Firefox 46.0 all running on OS 10.11.5

**Comment by hobinjk** [comment]
Thanks for the report! Safari Technology Preview changed the behavior of JSON.stringify when called on XMLHttpRequest objects to break what XKit tries to do. This should be fixed on our end eventually by changing https://github.com/new-xkit/XKit/blob/master/Safari/global.js#L99

**Comment by Diva3802016** [comment]
This is still not fixed for me...

**Comment by nightpool** [comment]
@hobinjk we're waiting on apple review, right?

**Comment by hobinjk** [comment]
@nightpool Yep, it took several weeks last time.
@Diva3802016 Apple will eventually review it, but before then you can manually install it from https://github.com/new-xkit/XKit/releases/download/safari-v7.7.2/New.XKit.safariextz
