### ISSUE TITLE
[minor] Dashboard bookmark button is missing a tooltip

### ISSUE THREAD

**Issue by raingloom** [new-xkit/XKit#1023]
As the title says, all other buttons on posts have tooltips, but this one doesn't. Frankly I'm not even 100% sure it's from the bookmark extension, given how many extensions I've enabled, but the icon looks like a bookmark.

If no one takes this up, I'll do it myself sometime after this week. I've been wanting to practice some JS.

**Comment by nightpool** [comment]
can you provide a screenshot? not sure which button you're talking about off hand

**Comment by raingloom** [comment]
The red one on the picture.

_(colored in GIMP for presentation, that's probly not the exact color it turns when clicked)_

![1461674229](https://cloud.githubusercontent.com/assets/8085052/14818681/b5f0d7ac-0bbe-11e6-9782-3adc23022268.jpeg)

**Comment by ThePsionic** [comment]
Bookmarker extension. If no one else picks this up I'll do this tonight.
