### ISSUE TITLE
Z-ordering issues on dashboard

### ISSUE THREAD

**Issue by raingloom** [new-xkit/XKit#1028]
_Not sure if this has already been reported. It's a huge bug but I couldn't find it, so I'm reporting just in case._
1. The "flag this blog" interface opens, but the semitransparent blue layer that usually appears when opening something on the dash is above it, completely blocking input to the interface. When I click on it, it just closes.
2. Can't reblog anything from a blog that was opened on the dash for a similar reason. In this case the ordering is (from the bottom): reblog, blue tint, open blog on side _(idk its name)_

Also, the quick reblog interface no longer opens for these _(or opens below)_, but it does work on the feed and some directly opened blogs.

I have a ton of add-ons, so I have no idea what's causing it just yet.

**Comment by nightpool** [comment]
When did this start happening?

**Comment by AprilSylph** [comment]
fixed in #1389
