### ISSUE TITLE
Old Sidebar only half working

### ISSUE THREAD

**Issue by citrusella** [new-xkit/XKit#1029]
When I refresh Tumblr, the person dropdown opens (like it typically does for me just before it loads the old sidebar), and then the old sidebar just... doesn't load. If I go into the settings for the extension and toggle it on and off, the sidebar comes back until the next refresh (but toggling it on/off in settings has the following behavior: go in and see it's on [after the refresh when it's not working] > toggle it off [the bubble is still filled in as if it's toggled on] > toggle it on [bubble is filled and extension is behaving normally] > toggle fills and unfills bubble as expected [and extension turns on and off]).

I've not installed any other extensions lately (~~though I might put the soft refresh in just so I don't lose the sidebar whenever I want to see new posts~~ <-had soft refresh installed already but disabled); my current list is [here](https://gist.github.com/cfe82379c1964cffc5af0e606e471724), though some of those are disabled. I've tried multiple refreshes and starting and restarting the browser. It also came after a browser reopening after I'd done some things in a private window (on Tumblr blogs I didn't want to stay on), but something tells me that's not related.

**Comment by estufar** [comment]
It looks like Tumblr made a very recent change that broke it. I'm taking a look at it right now to see how to fix it.

**Comment by citrusella** [comment]
I... don't know if it's just me, but (I'm assuming the update I got to the extension contains the #1033 fix) I'm still getting the same behavior, just without the menu appearing (and with inability to access it because it immediately disappears). Doing the switch on/off trick still makes it function correctly until a new refresh.

Did Tumblr change yet again? Or is this something busted in my own XKit/browser setup?
