### ISSUE TITLE
Editable Reblogs causes tumblr to claim Post Is Empty

### ISSUE THREAD

**Issue by promise-reprise** [new-xkit/XKit#103]
So every time I tried to reblog something with the Editable Reblogs extension, tumblr said the post could not be empty. Uninstalling Editable Reblogs fixed the issue.

**Comment by dlmarquis** [comment]
Can you give us information on your OS, browser, and other extensions? This is likely specific to your configuration.

**Comment by promise-reprise** [comment]
Actually it's been fixed already from what I can tell. I dunno, maybe it
was just a weird glitch?

**Comment by nightpool** [comment]
must have been. Let us know if it happens again!
