### ISSUE TITLE
Blog Tracker Broken

### ISSUE THREAD

**Issue by kssuki** [new-xkit/XKit#1032]
As the title says, it appears that the blog tracker is broken atm as well, as the several blogs I'm following all show error next to their names. I'm assuming that the problem is likely not too different than what's going on with the old sidebar, but I thought I'd report it as a heads up.

**Comment by ValensHawke** [comment]
Can confirm on Chrome.

**Comment by ValensHawke** [comment]
Now it seems to be working?
