### ISSUE TITLE
One-Click Postage sticking pop out sidebar

### ISSUE THREAD

**Issue by aplouis7777** [new-xkit/XKit#1036]
It seems with Firefox suddenly my One-Click Postage is causing the pop up account list/sidebar to stick. It happens on refresh, page change, blog switch. It's very annoying. Nothing has changed here. I'm not using the Old Sidebar extension that I know there are issues with now. The second I disable that it works fine but that's a very important extension for me. I've tried changing some options in it but nothing seems to fix it. 

I'm using Firefox 46 with the latest xkit installed. I completely reset firefox, xkit, all my other FF extensions. I even tried going back to FF 45 and 43 with the same results. I assume whatever Tumblr changed yesterday that broke the Old Sidebar extension has somehow done something to this one but it only affects certain FF users.

I was in the support chat and given this by nightpool to try but didn't have any success there either.
https://gist.githubusercontent.com/nightpool/ddbcc6d2746bf033eee1287b4405252e/raw/aaf66026bb15893b9609365f2cb10208387085a6/test1.js
They thought they might have an idea of the problem but didn't have time to further troubleshoot and asked me to submit a github issue.
![2016-04-29_8-06-47](https://cloud.githubusercontent.com/assets/18745696/14932221/2a1e1110-0e41-11e6-8daa-855002e9408a.png)

**Comment by nightpool** [comment]
I'm able to reproduce this on firefox. haven't been able to look into it yet

**Comment by aplouis7777** [comment]
I've talked to several other FF users today that are having this issue but didn't realize it was the OCP until I told them. :)

**Comment by aplouis7777** [comment]
Don't mean to bug you but just curious of you had a chance to look into this further. I'm stuck using Chrome just for tumblr because that window is so bothersome trying to scroll or post. Thanks for all you do!! :)

**Comment by nightpool** [comment]
I've been working on finals for the past five days. Will take a look as
soon as I'm moved and settled and etc.

**Comment by aplouis7777** [comment]
Okay just wanted to remind you I was here :)

**Comment by aplouis7777** [comment]
Perhaps someone else can look into this? I honestly can't even use Firefox with Tumblr anymore because of this. :(

**Comment by nightpool** [comment]
I'll look into this today

**Comment by couchpotahto** [comment]
Thank you, nightpool!

**Comment by aplouis7777** [comment]
I think you fixed it! I saw an xkit update on Chrome but not on Firefox so I updated manually and it's good!!!

**Comment by nightpool** [comment]
Yeah, there are still some lingering behind the scenes issues to clean up, but it should at least stop opening the sidebar every time the page loades
