### ISSUE TITLE
Hermes deleting captions on posts when scrolling back up

### ISSUE THREAD

**Issue by radialarch** [new-xkit/XKit#1039]
Kay, on chrome 50.0.2661.94 m (but I think it was happening on chrome 49 too), all chrome extensions disabled except new-xkit, all xkit extensions disabled except hermes, tumblr dash set to infinite scroll:

So for example here's a photo post on my dash:

![hermes before](https://cloud.githubusercontent.com/assets/18364609/15025104/aeedccc4-1205-11e6-9f8b-119a00e01dd7.PNG)

When I scroll down far enough to see the loading bar at the bottom before more posts load, and then scroll back up, the photo is replaced with a placeholder, like it's supposed to do:

![hermes placeholder](https://cloud.githubusercontent.com/assets/18364609/15025113/b63ad792-1205-11e6-8def-e73c115caa8c.PNG)

But if I scroll up all the way to the top of my dash, the favicon turns into the loading wheel for a minute, and then the pictures will reload properly, but the caption gets deleted, like this:

![hermes after](https://cloud.githubusercontent.com/assets/18364609/15025115/ba84009e-1205-11e6-8e57-75d0fc14091c.PNG)

Some thoughts:
- happens for photo posts, photosets, vines/video posts
- if multiple reblog comments, they all get deleted; inspecting the html, it's the entire .reblog-list that gets stripped

![div1](https://cloud.githubusercontent.com/assets/18364609/15025627/21f39706-1208-11e6-9785-891beb9658ef.PNG)
![div2](https://cloud.githubusercontent.com/assets/18364609/15025626/21f3a9bc-1208-11e6-8618-3353ae24d493.PNG)

**Comment by hobinjk** [comment]
Fixed in #963. Thank you for the report!
