### ISSUE TITLE
In the absence of bundles, quick tags should prompt you to add them

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#104]
From an ask
> im not sure if this has been asked before but when i go to quick reblog it says "You have no custom tag bundles. You can use XKit Control Panel > Quick Tags to define your own" and i dont want to put custom tag bundles so how do i make the notification go away?? Thanks!!

This sounds like both Quick Tags and One Click Postage are enabled. In the absence of tag bundles Quick Tags should display either nothing or a create tag bundle button where it would normally have the bundle buttons.

**Comment by ThePsionic** [comment]
I'm currently working on a feature for this.
