### ISSUE TITLE
mass+ seems to not work

### ISSUE THREAD

**Issue by ErraticFox** [new-xkit/XKit#1042]
When I install mass+ and enable filter by tag and go to a archive, I can't use it or I don't see anything to use it.

**Comment by Aquaj** [comment]
The link to access the MegaEditor is not present on your archive but underneath the "Posts, Drafts, ..." list when you're on a blog's dashboard.

![massposteditor](https://cloud.githubusercontent.com/assets/2871879/15104148/5d406ad2-15b4-11e6-8f89-5c8cd26416cc.png)

You can also access it at the url : https://www.tumblr.com/mega-editor/<name-of-the-blog>

You should then see the options to edit and filter.

![masseditpage](https://cloud.githubusercontent.com/assets/2871879/15104176/be771e54-15b4-11e6-8dd3-bbaa17d548a9.png)

Hope that helps !

**Comment by nightpool** [comment]
Yeah, like @Aquaj said, mass+ only modifies the Mass Post Editor, not the archives page
