### ISSUE TITLE
editable reblogs + tweaks forces edited queue posts to post immediately

### ISSUE THREAD

**Issue by radialarch** [new-xkit/XKit#1046]
I know ER has been having issues since tumblr did...whatever tumblr does, but I thought I'd file this because it seems kind of specific:

(chrome 50.0.2661.94 m, xkit 7.7.1, issue only happens with the combo of Editable Reblogs and Tweaks -- specifically "Move the edit/remove buttons out of gear menu" option -- enabled)

As far as I can see, this is an issue that only comes up if I
1. queue a post that ER applies to (e.g. reblogs of text posts, or photosets with captions, things like that)
2. from the queue, click the "edit" button on the post
3. (optional: edit things. I noticed the issue because i was adding a tag, but the issue persists even if you don't actually edit anything.) press the "queue" button to re-queue the post.

This results in the queue'd post being posted directly to the blog instead of saving to queue.

**Comment by rimbaum** [comment]
I have a similar problem with posts in my drafts.
