### ISSUE TITLE
Update Blacklist to catch tag spam?

### ISSUE THREAD

**Issue by katyggls** [new-xkit/XKit#1049]
Lately there's been a ton of spam in the tags, and they've gotten clever enough that it can't be blocked with the Blacklist feature. What they do is just use an image, and then have the image link back to a goo.gl url. Here's an [example](http://kostyushkinaxuj.tumblr.com/post/144686349798) of such a post. Because there's no text in the actual post itself, Blacklist won't block it, even if you add something like goo.gl*. However, the extension [Tumblr Savior](http://bjornstar.com/tumblr-savior) will work using this method. Which is great, but it'd be nice if the function was built into Blacklist so that people don't have to have Xkit (with blacklist enabled) and Tumblr Savior on top of it.

**Comment by hobinjk** [comment]
I can't find any spam now that I'm looking for it, but Blacklist should be able to block these posts with `goo.gl*` as of #1054

**Comment by katyggls** [comment]
Thank you! Yeah, I think staff went on a bot blocking spree, but this kind of spam periodically crops back up, so we'll have to see how the updated blacklist handles it during the next "outbreak". :)
