### ISSUE TITLE
Quick Tag: Choosing tag-bundles does not work on other blogs

### ISSUE THREAD

**Issue by Snowrisk** [new-xkit/XKit#1051]
Hi,

for me "quick tags" don't work on Tumbrl blogs. It works perfectly on my dashboard but on other blogs 
the popup (from One-Click post) opens but I can't choose any tag-bundle:
![unbenannt-1](https://cloud.githubusercontent.com/assets/7990156/15473549/d8dfc56e-2100-11e6-92d9-2991102bb97f.jpg)

I can't click the bundles. 

The issue occurs on Chrome (50.0.2661.102 m) (also tested on Firefox 46.0.1).
Installed Extensions:

XKit version 7.7.1
extensions:
   xkit_main: 1.3.3
   xkit_patches: 6.2.8
   xkit_preferences: 7.3.1
   xkit_updates: 2.0.2
   xinbox: 1.9.5
   one_click_postage: 4.3.0
   one_click_reply: 2.0.7
   tweaks: 5.2.2
   go_to_dash: 1.2.1
   xcloud: 1.1.0
   activity_plus: 0.3.4
   auto_tagger: 0.6.8
   quick_tags: 0.5.6
   drafts_plus: 0.2.4
   mass_plus: 0.4.2
   shuffle_queue: 2.0.6
   postarchive: 1.0.1
   stats: 0.3.3
   autoloadimages: 0.1.2
   mass_deleter: 0.1.3
   anti_capitalism: 1.2.4
   outbox: 0.10.0
   reblog_yourself: 1.3.1
   find_inactives: 0.3.1
   separator: 1.1.3
   cleanfeed: 1.5.2
   lethe: 1.2.0
   people_notifier: 0.5.0
   messaging_tweaks: 1.7.0
   read_more_now: 1.4.5
   replyviewer: 0.2.7
   tagviewer: 0.4.1
   view_my_tags: 0.4.3
   open_in_new_tabs: 1.1.6

OS: Windows 8.1 64Bit

**Comment by nightpool** [comment]
The fix for this is to just disable one click post on Tumblr blogs,
unfortunately.

**Comment by Snowrisk** [comment]
Hmm..... I remember it worked a time ago.....

**Comment by nightpool** [comment]
Pretty sure this has been broken for as long as New XKit has had the
ability to run on main blog pages

**Comment by ThePsionic** [comment]
Yep, Tumblr-provided themes tend to use the same classes on reblog buttons as the dashboard, and this functionality was never meant to actually work. Perhaps we can look into disabling OCP on blog pages?

**Comment by bgiesing** [comment]
This is happening to me on the search results page also

**Comment by nightpool** [comment]
Can you make a new issue? Thanks!

**Comment by ThePsionic** [comment]
Fixed in #1160
