### ISSUE TITLE
Xkit not showing up in Firefox

### ISSUE THREAD

**Issue by couchpotahto** [new-xkit/XKit#1053]
As of today Xkit is not showing up in Firefox. I tried disabling and enabling different extensions and I also updated Xkit to the 7.7.3-amo-unlisted version. I am currently on version 46.0.1 of Firefox.

**Comment by couchpotahto** [comment]
I think I figured out the problem. It looks like in order for Xkit to work I have to enable third party cookies in Firefox via the "Remember History" setting under Privacy :/

**Comment by nightpool** [comment]
oh! shoot yeah I completely forgot about that firefox bug!! you don't need
to enable third party cookies, but you DO need to have a custom history
setup. here's a link that talks about this a little more:
https://new-xkit-support.tumblr.com/post/130559880838/roflcopterbot-make-sure-if-youre-using-firefox

**Comment by couchpotahto** [comment]
I didn't even make the connection those two were related when I was looking through that blog for known issues. Sigh.
Thank you for bringing that to my attention. At the very least I can now disallowed third party cookies. Cheers!
