### ISSUE TITLE
One click reblog icon broken?

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#1055]
![ss 2016-05-25 at 12 49 16](https://cloud.githubusercontent.com/assets/13604430/15522445/b7e80958-2212-11e6-8cab-283257ae2c7b.jpg)

I am not sure if it has been like this for a while now or not... but I thought that the grey button disappears while the post is processed into a reblog?

**Comment by ThePsionic** [comment]
It technically should, but it's been happening for a long while if I recall correctly.

**Comment by ThePsionic** [comment]
Pretty sure this was fixed long ago.
