### ISSUE TITLE
One Click Reblog might have issues with MultiFox AddOn

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#1057]
I started using Firefox and wanted a similar extention as MultiLogin, which is MultiFox. It's useful when logging into multiple accounts on multiple tags of the same page (i. e. multiple RP blogs).

However I've gotten error messages reblogging on the tabs used by the AddOn and screencapped the error messages of course.

![ss 2016-05-25 at 03 25 39](https://cloud.githubusercontent.com/assets/13604430/15541576/66436356-228d-11e6-9dc2-a63233cb818c.png)

![ss 2016-05-25 at 03 25 03](https://cloud.githubusercontent.com/assets/13604430/15541575/65e3f420-228d-11e6-9a3c-ed25fcdc7027.png)

**Comment by Wolvan** [comment]
Multifox is not compatible with a bunch of XKit extensions. There is nothing we can do about it, the fault is on Multifox's cookie implementation iirc. Sorry.

**Comment by nightpool** [comment]
Also, multifox is not longer being developed, so you're not going to get any response there. See hultmann/multifox#249
