### ISSUE TITLE
xcloud don´t work

### ISSUE THREAD

**Issue by xThreeh** [new-xkit/XKit#1068]
I have placed my data and has not let me connect to my account for my extensions and preconfigurations

**Comment by Wolvan** [comment]
are you using the old XCloud Servers? They don't work anymore

**Comment by Maniello** [comment]
Doesn't work for me either, I am trying to migrate my setup from Chrome to Safari. I tried cloudsyncing and local import too but the process seems to get stuck at around 2/3 of the loading bar

**Comment by nightpool** [comment]
dupe of #1099
