### ISSUE TITLE
show_picture_size: Misterious AJAX call on clicks on pictures

### ISSUE THREAD

**Issue by TiMESPLiNTER** [new-xkit/XKit#1069]
I'm the author of the `show_picture_size` extension. Since about 2 days I have something strange going on when the extension is enabled. While the extensions still works perfectly fine when I click on any picture which has been processes by the extension the following AJAX call gets fired:

```
https://www.tumblr.com/svc/indash_blog/posts?tumblelog_name_or_id=683x1024&post_id=&limit=10&offset=0
```
I never fire such a call on the extension. The tumblelog_name_or_id=`683x1024` is indeed the resolution of the picture. The response of the request gets displayed in the sidebar where tumblr blogs get loaded during you stay on the dashboard. The URL appears in the `view on dash` extension but I don't even have installed this extension.

Can someone give me a hint why this happens so that I can fix this issue?

**Comment by Wolvan** [comment]
This should be closed by #1092
