### ISSUE TITLE
TagViewer broken

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [new-xkit/XKit#1070]
Activating it gives

```xkit/tagviewer.js:127 Uncaught TypeError: Cannot read property 'split' of undefined```

from this line of code

```var blog_name = post_url.split("/")[2];```

Using Chrome 51.0.2704.84 m (64-bit)

**Comment by ThePsionic** [comment]
For future reference: `post_url` ([L124](https://github.com/new-xkit/XKit/blob/master/Extensions/tagviewer.js#L124)) comes back as undefined, making `.split` ([L127/L128](https://github.com/new-xkit/XKit/blob/master/Extensions/tagviewer.js#L127-L128)) impossible.

**Comment by ThePsionic** [comment]
https://github.com/new-xkit/XKit/commit/33392bbfd7687696d5c34d4435209d251d19a1ad
