### ISSUE TITLE
Pressing Alt makes top go ew

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1073]
![alt](https://cloud.githubusercontent.com/assets/842080/16083349/fc09f930-3314-11e6-91f4-616250c2023c.png)
Apparently the XKit icon is a bit wider than the help icon, showing some sprites around it.

**Comment by cnestor** [comment]
Probably better to use the actual glyph for the icon instead of the sprites png... that'll make it display smoother too. Hex code for the help glyph is \EA4B.
