### ISSUE TITLE
New sidebar layout: Ongoing issues

### ISSUE THREAD

**Issue by invalidCards** [new-xkit/XKit#1078]
- ~~The links to the Mass Post Editor and Blog Settings in the sidebar are now contained in an ad `div`, which means it is blocked by AdBlock and such. (See also: #1075)~~
- ~~There is an ad in the sidebar that scrolls with the dash now - #1075 has been created to fix this, but the aforementioned issue has to be resolved first.~~
- ~~Enabling fixed width header with the old sidebar tweak makes things very off-center~~
- ~~The sidebar fix changes CSS in the `.pagination` class, which is also often used on blogs and the likes for pagination; a fix to this would be to not allow the tweak to run on blogs.~~
- ~~The bookmark section has moved between the Radar section header and the Radar itself.~~
- The sidebar tweak should not be allowed to run on `/following`.

**Comment by katyggls** [comment]
This probably has something to do with the css .pagination issue described above, but when I have the Tweaks exctension enabled, it messes up the forwards/backwards pagination text on my blog. This is even if I have the sidebar fix tweak disabled though. The only thing that fixes it is to disable the entire Tweaks extension. Screenshots:

![image](https://cloud.githubusercontent.com/assets/13756649/16148924/e8b9d20a-345a-11e6-8a0b-db79b1e8464c.png)

![image](https://cloud.githubusercontent.com/assets/13756649/16148975/5aac44ba-345b-11e6-876d-9f36d6a3066e.png)

**Comment by ThePsionic** [comment]
This is exactly the issue described in the OP, yes.
