### ISSUE TITLE
Stop using Tumblr API demo key

### ISSUE THREAD

**Issue by ceyko** [new-xkit/XKit#1083]
It looks like you're using the demo key to access the Tumblr API. Can you please register a new app at https://www.tumblr.com/oauth/apps and use its key instead? You will see increasing amounts of 429s by continuing to use this key, and it may even eventually stop working entirely. Thanks.

**Comment by hobinjk** [comment]
Thank you for bringing this to our attention! Which key is the demo key?

**Comment by ceyko** [comment]
Oh, I didn't notice that there were multiple keys in the project. `fuiKNFp9vQFvjLNvx4sUwti4Yb5yGutBN4Xh10LXZhhRKjWlV4` is the one in question.

Also, please use only a single key for your entire application. I see at least two others from a quick check, so you can converge on one of those, or make a new one entirely. Just make sure that at least one of you has access to the key at https://www.tumblr.com/oauth/apps so you can make changes to it if necessary.

**Comment by nightpool** [comment]
I think it's the one in blog tracker. Well get this fixed right away.

**Comment by hobinjk** [comment]
It's present in: ```
Extensions/audio_downloader.js
Extensions/notifications_plus.js
Extensions/post_limit_checker.js
Extensions/postarchive.js
Extensions/profiler.js
Extensions/people_notifier.js
Extensions/replyviewer.js
Extensions/tag_replacer.js
Extensions/tagviewer.js
Extensions/timestamps.js
Extensions/stats.js
Extensions/view_my_tags.js
Extensions/view_on_dash.js
```

**Comment by nightpool** [comment]
This update just went out @ceyko. You should see XKit usage of this key drop steadily over the next 12 hours and be completely gone by the end of that time period. We haven't yet completely an audit of all of our existing keys so we might still have some lurking somewhere in the codebase that are tied to different accounts, but this should account for >90% of our API usage.

**Comment by ceyko** [comment]
Just to close the loop here, everything looks good on our end. Thanks for the quick fixes :)

**Comment by nightpool** [comment]
Thanks Michael. Feel free to hit us up here or at new.xkit@gmail.com if you
ever need to get in contact.
