### ISSUE TITLE
Black screen on Xkit Editor

### ISSUE THREAD

**Issue by creatrixtiara** [new-xkit/XKit#1085]
When I open up an extension in Xkit Editor and click on the code to try and edit it, that side of the screen goes all black and I can't do anything.

This is on Google Chrome v Version 51.0.2704.103 (64-bit) on a Macbook Pro.

**Comment by creatrixtiara** [comment]
Figured it out! Conflict with Grammarly!

**Comment by andrewmyles** [comment]
I don't have grammarly and still have the black screen

**Comment by nightpool** [comment]
@andrewmyles seems like a different issue. I'll open a new ticket
