### ISSUE TITLE
Requesting fix: Like button does not appear on dashboard posts from group blogs if the user is an admin for that blog

### ISSUE THREAD

**Issue by tellovishous** [new-xkit/XKit#1087]
Hi there, I have a Tumblr issue I was wondering you guys could fix. I've known about it for a while but hadn't bothered to make a ticket about it until now.

So I'm part of a group blog on Tumblr, and last year I was promoted to an admin in this group. But then after this happened, I noticed that for some odd reason any posts from this group, which I also follow, no longer have the like button on them in the dashboard. However, if I view a post from the group directly on it's own page, the like button _does_ appear on the top of the page and I can like the post from there.

I'm not really sure why Tumblr does this or how long it's been going on. Aside from the aforementioned workaround, I was still able to like these kinds of posts on the Android mobile app for a time, but then the like button disappeared there as well not too long ago.

I recently talked with @nightpool about this in the chat, and he said he's also aware of this issue. So, think you guys could add a fix for this? (Perhaps in Tweaks?) Would be great to be able to like my own groups' posts normally.

**Comment by AprilSylph** [comment]
closing this because i'm fairly sure this is now impossible - the like button no longer appears on post pages' iframes and the like button on posts themselves do nothing if you own/are admin of the blog in question
