### ISSUE TITLE
Reblog interface bug: stationary content, floating editables/post parameters

### ISSUE THREAD

**Issue by ninevah** [new-xkit/XKit#1088]
When reblogging outside of the one-click/quick-select menu, the content remains fixed while the editables (caption, tags, reblog button) scroll; as a result, I can't see the positioning of the fields and it makes reblogging a chore. I have to sorta guess every single time.

**Comment by nightpool** [comment]
Can you post a screenshot? I'm having a hard time figuring out what you're
trying to describe.

**Comment by ninevah** [comment]
![reblog bug 1](https://cloud.githubusercontent.com/assets/20157097/16368354/283e8e62-3bf3-11e6-846f-08d7d97f50f7.jpg)
![reblog bug 2](https://cloud.githubusercontent.com/assets/20157097/16368355/283eb7de-3bf3-11e6-89b6-01c4fffff84e.jpg)

And it gets even worse the bigger the post is/the more images there are.

**Comment by ninevah** [comment]
That's what happens when I try to scroll down on a reblog.

**Comment by nightpool** [comment]
Okay, I don't have any idea what could be causing this issue, but it looks incredibly unrelated to XKit. Can you reproduce the issue after specifically turning off XKit in the browser extension menu? (chrome://extensions for chrome and about:addons for firefox)

**Comment by nightpool** [comment]
If the problem persists after disabling XKit, then unfortunately this issue is caused by some other extension or addon you have installed, and there isn't really anything we could do to help :( sorry about that.
