### ISSUE TITLE
[RFC] new support infastructure

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#109]
working on some additions to xkit to help with support stuff. plan is to create a button that will give you a github gist url containing 

 - Browser/OS
 - XKit version
 - enabled plugins
 - plugin versions

anybody have any other ideas on stuff I could include? 

stretch goal is if I can get xkit to add this to all new-xkit-extension asks transparently.

**Comment by nightpool** [comment]
created this to get feeback/ideas on what stuff I should include.

**Comment by Wolvan** [comment]
I'd suggest we add this to the XKit Control Panel as it's own tab.
Additionally we could have a textarea where the user can type their problems into.
Is there a REST API call to github to open new issues in a project?

**Comment by nightpool** [comment]
@wolvan I'm going to be adding it to the xkit support tab. 

I considered using github issues, but that requires people to have github logins. (or have all the issues be associated with one of our user accounts, I guess, which would be harder as we'd need some sort of intermediary server infrastructure)

**Comment by Wolvan** [comment]
@nightpool I don't see a reason for any intermediary server infrastructure. We'll just push issues with the POST /repos/:owner/:repo/issues API to github and supply OAuth (I think it works with OAuth) of an account made only for issues

**Comment by nightpool** [comment]
@Wolvan but then anyone could use that account to do other stuff, without
us being able to know about it, because they'd have the oauth token to
control it.

**Comment by Wolvan** [comment]
@nightpool Shit, you're right. I didn't think of that. Does gist allow posts without an API Token/Account though?
Also, I did some scripting in google apps script recently, could we use that as our intermediary server?

**Comment by nightpool** [comment]
@Wolvan You need an application client token, but nothing more then that IIRC.

**Comment by Wolvan** [comment]
@nightpool gotcha. Although it would probably still be a lot easier for support to automatically open issues. You didn't answer me about the idea with google apps script yet, though

**Comment by nightpool** [comment]
@Wolvan lets wait to bikeshed this until there's some working code. I think there are going to be more difficulties with using github issues, including de-duplicating them effectively and dealing with support requests that aren't bugs but end up in the repo anyway, but I don't think we need to hammer this out right now. I'm just trying to incrementally improve it right now but having it auto-generate the information I've been manually asking people for in issues. Whether and when we want an issue-reporting framework should probably be a different ticket altogether.

**Comment by Wolvan** [comment]
@nightpool Point taken. If you only want the basics so far I'd say you push the gist idea back and simply print all of the required into into a textarea on the support page so they only have to copy and paste it

**Comment by hobinjk** [comment]
As far as a copy-paste solution goes, we could kill two birds with one stone by making this use a more generic Save/Restore function that would locally replace XCloud. Then when someone has a problem they send us their XKit backup file and we have their exact setup.

**Comment by nightpool** [comment]
I had considered that, but I decided having the entire configuration of
someone's xkit had vaguely weird privacy-configurations, so I'm sticking
just to a list of extensions for now.

I'm probably going to make a save/restore function anyway, at least to help
with migrating from old xkit if nothing else.

**Comment by nightpool** [comment]
I'm finding a *lot* of hand-rolled html and string concatenation in here... does anyone have a preferred templating library or should I just pick one?

**Comment by Wolvan** [comment]
Couldn't we go with just a json string here? It's easy to get back into a readable form and it's a single string

**Comment by nightpool** [comment]
@Wolvan we have functions with complexity counts in the hundreds because they're recreating by hand all of the loops and if conditions a proper templating language would provide for us. 

also, escaping :/

**Comment by nightpool** [comment]
I don't even want to think about how many potential XSS attacks are lying in wait in the xkit source code.

**Comment by hobinjk** [comment]
I'm not sure that I see where a templating engine would benefit the internal representation of a transferable list of extensions.

As far as using templates in the interface, I will be interested to see if there are any solutions that will not require significant changes to the build or to the extension. Unless there is a great solution with no impact to backwards compatibility or user experience the readability improvement of going from `"<a href=\"" + message + "\">" + name + "</a>"` to `"<a href=\"{object.message}\">object.name</a>"` doesn't seem worth it.

The best solution for providing templates that I can see coexisting with the current extension format would be to add an extension.html in addition to the existing extension files. This would require some work from the core platform but would definitely allow a good separation of concerns while not breaking everything.

I believe that the discussion of introducing a templating framework is worthy of its own issue and should be discussed independently of creating this feature. It's worth taking the time to get this right, but XKit's first priority is to work, not to have shiny internals.

**Comment by nightpool** [comment]
@hobinjk I basically agree with you, but its useful to note that
xkit_preferences is over 2500 lines of code, and the majority of that is
hacked-together string based html manipulation. (including dozens of nested
if statements in each function, oodles of copy-and-pasted code, and all the
other problems that plague the majority of the "classic" xkit codebase)

however I can acknowledge that xkit_preferences is a outlier and templating
doesn't really have a lot to offer the majority of xkit extensions.

**Comment by Wolvan** [comment]
The code of XKit deserves a heavy cleanup, but that should be put in it's own issue, I agree with @hobinjk here.
It's still something we have to look into in the future, such messy code makes developing for XKit an absolute pain. It takes you at least 2-3 days to even understand what XKit is doing where the way it is right now

**Comment by nightpool** [comment]
@hobinjk style question—when should I put stuff into xkit_patches as opposed to xkit.js? For example if I wanted to make a new XKit.tools function?

Is there a good guideline or is it just kinda whatever?

**Comment by hobinjk** [comment]
@nightpool xkit_patches is a much better location because it updates automatically. Anything in xkit.js requires going through Chrome and Firefox's distribution channels.
