### ISSUE TITLE
Stop Blogs From Redirecting to Dashboard

### ISSUE THREAD

**Issue by Gizmaton** [new-xkit/XKit#1094]
I've been having an issue lately with some blogs forcibly redirecting to my dashboard and opening up in the annoying blog sidebar instead of a regular webpage. I've tried opening the URL in a new tab, I've used the "Open in Tabs" extension, I've tried opening the URL without XKit installed... but nothing seems to work. 

I'm pretty sure this behavior is linked to the "Allow logged-out users to see this blog" feature. Is there any way to view blogs who disable this normally?

**Comment by nightpool** [comment]
![image](https://cloud.githubusercontent.com/assets/233815/16506878/88214c72-3ef3-11e6-8988-36f4ca04400d.png)

**Comment by hinum009** [comment]
i don`t konw
maybe let xkit run in ***.tumblr.com

**Comment by nightpool** [comment]
@hinum009 this isn't possible, unfortunately.
