### ISSUE TITLE
Extension to flag if post has already been reblogged? 

### ISSUE THREAD

**Issue by toddmbloom** [new-xkit/XKit#1096]
Thanks for the extension! :)

I don't know if this is possible but I've looked in the gallery and didn't see anything like it so I figured I would ask. Is there a way to make an extension that will tell you if you've already reblogged a post or when the last time you did was as you're scrolling through your dash?

**Comment by ThePsionic** [comment]
One-Click Postage has a bit of functionality called AlreadyReblogged, which turns the reblog arrow green if you've reblogged the post before. It even allows you to hide already reblogged posts completely.

**Comment by nightpool** [comment]
Why do we have a "question" label, by the by?

**Comment by ThePsionic** [comment]
For this kind of stuff :P
