### ISSUE TITLE
Post Archiver new xkit extension will not work

### ISSUE THREAD

**Issue by drillcommander** [new-xkit/XKit#1098]
While I can view the top of the archive, I can not scroll down, or click on anything within the archive. 

_This is the only thing I see when I click on it._ 
[http://i.imgur.com/GPKauB1.png](http://i.imgur.com/GPKauB1.png)

I'm guessing this is some sort of bug

**Comment by nightpool** [comment]
We had trouble reproducing this the first time we tried it in support chat, if anyone else is having this problem it would be nice to narrow down

**Comment by nightpool** [comment]
closed due to lack of activity
