### ISSUE TITLE
Notifications on Activity Page cut off when selecting "retags/reblogs only"

### ISSUE THREAD

**Issue by creatrixtiara** [new-xkit/XKit#110]
<img width="559" alt="Activity page" src="https://cloud.githubusercontent.com/assets/8474427/9027433/b4eb9848-3909-11e5-95bd-5e69ad4ac3fc.png">
<img width="208" alt="Relevant extensions" src="https://cloud.githubusercontent.com/assets/8474427/9027434/b4ece590-3909-11e5-91fe-aeb220507988.png">

For some reason the notifications on my Activity Page get cut off when I ask to show retags & reblogs only. They show up OK if I unselect that.

Relevant extensions are Classic Notifications, Activity+, Iconified Notifications, and Notifications+.

edit: This is on Chrome for Mac, xKit version 7.6.5.

**Comment by ThePsionic** [comment]
Unable to reproduce on Firefox with XKit 7.7.1. It's an old issue and I haven't heard anything similar about it, so I'm closing this. @creatrixtiara, if you still have this issue, feel free to re-open.
