### ISSUE TITLE
XKit 7.7.2 for Safari fails to install on 10.12 Beta (16A238m)

### ISSUE THREAD

**Issue by wonaldson** [new-xkit/XKit#1100]
XKit 7.7.2 for Safari fails to install on macOS 10.12 Beta 16A238m.

Reproduce:
1. Double-click the .safariextz file downloadable from https://github.com/new-xkit/XKit/releases/tag/safari-v7.7.2.

Actual behavior:

Safari pops an error dialog stating:

> "Safari can't install this extension
> An error occurred while installing the extension “New XKit”."

Console shows this error several times in a row:

<img width="408" alt="screen shot 2016-07-08 at 3 20 16 am" src="https://cloud.githubusercontent.com/assets/280610/16680194/ed6447e8-44ba-11e6-93bd-0a1d26d11001.png">

Expected behavior:

Safari installs the extension.

Notes:

I am able to load the extension by building it and loading it in manually through the Extension Builder, but as I don't have the certificates necessary it won't simply use the settings I already had in the release extension. Because of this, I'm assuming all that needs to be done to get it to load here is simply to re-build it properly on macOS Sierra.

Additionally, please let me know if there is a way I can get more detailed logs for you regarding the error on this. Thanks!

**Comment by hobinjk** [comment]
Here's a temporary build that should work in Sierra. Sorry for the delay!

[New Xkit.safariextz.zip](https://github.com/new-xkit/XKit/files/420544/New.Xkit.safariextz.zip)

**Comment by nightpool** [comment]
@hobinjk where did we land on this? I have people in the ask box saying that XKit is completely broken on safari 10

**Comment by hobinjk** [comment]
The only question is whether the build is backwards compatible with older safari versions. I can check that later today and upload the new version to the gallery if it works

**Comment by nightpool** [comment]
Okay leaving this open until we get this into the gallery.

**Comment by ajanjigian** [comment]
The version linked above does not work on Sierra/Safari 10, at least for me. I get the error:

> "Safari can't install this extension
> An error occurred while installing the extension “New XKit”."

**Comment by hobinjk** [comment]
@ajanjigian Could you try https://github.com/new-xkit/XKit/releases/download/safari-v7.7.3/New.XKit.safariextz and report whether it works for you?

**Comment by ajanjigian** [comment]
Nope, sorry. Same error on installation.

**Comment by ajanjigian** [comment]
Sorry. That worked. I had to be sure to uninstall the previous version before I double-clicked it. Thank you.

**Comment by hobinjk** [comment]
Awesome! Hopefully it works for other people without losing their data or anything else untoward. I've submitted this new version to the App Store

**Comment by nightpool** [comment]
@hobinjk is there any changes other then a new build?

**Comment by hobinjk** [comment]
@nightpool The only other change is that I had to renew the Safari Extension Certificate

**Comment by nightpool** [comment]
@hobinjk did this ever get reviewed by the app store?

**Comment by hobinjk** [comment]
@nightpool No, Apple has not reviewed it yet.

**Comment by nightpool** [comment]
High rather then critical because Safari doesn't have a huge install base

**Comment by nightpool** [comment]
Closed b/c I think the new version is now in the app store. (as far as I can tell)
