### ISSUE TITLE
Remove new audio ads auto-playing in background

### ISSUE THREAD

**Issue by Federer343** [new-xkit/XKit#1104]
The past couple days I've been having audio ads auto play on my dashboard with no way of muting them or clearing them, it just autoplays nonstop until I reload the page.  Normal adblock extension don't seem to work either through xkit or chrome itself.

**Comment by terribleriddle** [comment]
I have the same problem but it happens with any video on my dash. Luckily, I have adblock so it isn't happening with ads but if there are any posted videos they all play at once without actually starting the video. It's just audio. Starting the video and stopping it does not fix the problem. I end up just muting the entire tab.

**Comment by xAPRIC0T** [comment]
Same here, problem exists with multiple of my mutuals, friends and followers. Won't use tumblr until there's a fix for that problem since it spooked the heck out of me when suddenly the Don't Hug Me I'm Scared video audio started playing and I couldn't find a way to turn it of (or even find the source). Tumblr even managed to avoid Adblocker with these ads.

**Comment by nightpool** [comment]
Did @terribleriddle's comment get deleted? I was interested in that issue.

**Comment by nightpool** [comment]
Anyway, there should be an update to anti-capitalism going out tonight that addresses this

**Comment by ElliSpeaks** [comment]
Mine still is not working...
![image](https://cloud.githubusercontent.com/assets/15959327/16956535/b5618fa0-4d8d-11e6-9b77-c653b3a9eadc.png)
![image](https://cloud.githubusercontent.com/assets/15959327/16956555/bfe7d48e-4d8d-11e6-8b71-5a3751162b91.png)

It was playing awful ukulele music over and over.

**Comment by ElliSpeaks** [comment]
I have the page source saved if that helps at all.

**Comment by nightpool** [comment]
@ElliSpeaks 

Try disabling other ad-blockers. Early investigation seems to indicate that there’s a conflict with other types of ad-blockers, including possibly the Anti-Capitalism “Hide Sponsored Posts” option. Also, make sure you’re on version 1.3.1, not 1.3.0, and you’ve disabled or updated Vanilla Videos if you happen have it installed.

**Comment by ElliSpeaks** [comment]
1. The screenshot shows that I have 1.3.1...
2. No adblockers in place and I don't have Vanilla Videos.

**Comment by ElliSpeaks** [comment]
Second instance of it. I'm happy to send whatever code you might need just let me know what I should look for...

**Comment by nightpool** [comment]
@ellispeaks I think we have all the info we need right now. Untangling this
snarl of logic on tumblr's end might be a bit of a challenge though. I'll
take a crack at it when I get off work.

**Comment by ThePsionic** [comment]
@nightpool Should this issue be re-opened then, as it is still ongoing?
