### ISSUE TITLE
Xkit broken

### ISSUE THREAD

**Issue by TacticianLyra** [new-xkit/XKit#1105]
Reinstalling it did not work. No matter what I try or how long I wait, it just looks like [this](https://66.media.tumblr.com/a62a08e434471c483473c2756106622e/tumblr_oajg2slX4H1t6ovhbo1_1280.png).
I've tried contacting the managers via their blog, but that appears to be horrendously broken.

**Comment by nightpool** [comment]
You probably blocked something important to xkit using ad block plus custom rules, try disabling that to see if it helps, or removing any custom rules that look like `.content`

closing as this is a support request, not an bug report
