### ISSUE TITLE
Editable Reblogs/a few other extensions including outbox won`t play nice with multifox

### ISSUE THREAD

**Issue by wukongandsun** [new-xkit/XKit#111]
much like a similar post previously, I am having issues with the multifox and xkit meshing. But it outright won`t allow any of the blogs on my multifox use editable reblogs. I`ve tried it on several now, and it just hates this I suppose.

**Comment by nightpool** [comment]
closing as this is most likely a multifox issue.

**Comment by nightpool** [comment]
(also even if it isn't its a dupe of #108)
