### ISSUE TITLE
Receiving 101 Error

### ISSUE THREAD

**Issue by rinlynn** [new-xkit/XKit#1111]
I've been using the New Xkit (key word here; THE NEW XKIT) for a long time. Just recently, when I get on Tumblr, it says it cannot connect and gives me the 101 error like the original XKit did that made us all switch to the new Xkit. I have restarted my browser, uninstalled New Xkit, reinstalled it, etc. To no avail. It is absolutely slaying me right now because I cannot find any help anywhere. 

The original XKit extension has been removed since I installed the new Xkit, which shouldn't even matter since this issue only started a couple of weeks ago. Even still, I double checked to make sure.

I use the latest version of Chrome and to my knowledge, did nothing to cause this :( Please halp.

![image](https://cloud.githubusercontent.com/assets/20550699/16975332/d4b552b0-4e0a-11e6-8628-da6ea82d60ab.png)

I should also mention, this error since it is just like the 101 error for the original XKit, takes me to the original XKit's help site via that troubleshooting option.

**Comment by nightpool** [comment]
Please either send us an ask or use the live chat for support, thank you. Github is for active project bugs and features.
