### ISSUE TITLE
Quick Tags doesn't work on search pages

### ISSUE THREAD

**Issue by hmmmmmmm** [new-xkit/XKit#1116]
Quick Tags doesn't work properly on search pages, either in conjunction with One Click Postage or in the regular post window.

([Another user had the same issue here.](https://github.com/new-xkit/XKit/issues/1051#issuecomment-224163900))

In the regular post window, the Quick Tags button just doesn't show up.
![d015d82783efc8db0935f0d0a563a9f5](https://cloud.githubusercontent.com/assets/15641129/17122253/c455b6fa-52d1-11e6-8c6e-0cdf48e459a1.png)

In the OCP window, Quick Tags is displayed, but only as plaintext, without any interaction.
![f8e23697403735a97826e7ce1b92b831](https://cloud.githubusercontent.com/assets/15641129/17122254/c456859e-52d1-11e6-8754-03f47eb2a8b1.png)

**Comment by nightpool** [comment]
Fixed as part of https://github.com/new-xkit/XKit/issues/1160
