### ISSUE TITLE
reply viewer doesn't link to blogs correctly

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1118]
> Hi, I wanted to tell y'all about something (you might already know?). ReplyViewer appears to be broken. I used to be able to click on peoples' names and get taken to where they'd reblogged the post, but now if I click it i just get taken to an "undefined" page. This isn't a critical bug since I can work around it by clicking Notes (which now helpfully works much the same way), but i'm still used to clicking on TagViewer and then ReplyViewer, and it's sad to see one of them broken.

**Comment by ChuckL** [comment]
I was able to repro it. 

1. Click Reply viewer icon on a poste
2. Click on a link that the reply viewer gives back.
3. It goes to https://www.tumblr.com/undefined instead of the actual post.

**Comment by oct2pus** [comment]
I'm checking this issue currently, links work correctly if the response was a reply, however, links are broken if the response was a reblog.

**Comment by oct2pus** [comment]
The issue is with this block of code
`
$(commentaries).each(function() {

				console.log($(this));
				var blog_username = $(this).attr('data-tumblelog');
				var post_url = $(this).find("action").attr('data-post-url');
				XKit.console.add($(this).attr('data-tumblelog'));
				XKit.console.add(document.getElementById("action").attributes);
				var blog_avatar = $(this).find("img.avatar").attr('src');

				var reply_container = $(this).find("blockquote");
				var content = "";
				var only_text = false;

				if ($(this).find(".answer_content").length > 0) {
					content = $(this).find(".answer_content").html();
					only_text = true;
					post_url = "http://" + blog_username + ".tumblr.com";
				} else {
					content = $(reply_container).find("a").html();	
				}

				XKit.extensions.replyviewer.add_tags(blog_username, content, post_url, blog_avatar, only_text);
				XKit.extensions.replyviewer.found_count++;

			});
`
namely post_url tries to get an attribute from action that no longer exists. Fixing the problem is outside the scope of my abilities.

**Comment by nightpool** [comment]
To clarify, the /dashboard/notes api no longer returns **any** links to source or reblogged posts. we need to replace it with the /svc/notes api that TagViewer users.
