### ISSUE TITLE
xkit support on pale moon

### ISSUE THREAD

**Issue by owlspice** [new-xkit/XKit#112]
Pale Moon is a web browser based on firefox, but trying to install the new xkit brings back "not available for firefox 24.9." Is there a workaround or fix for this?

**Comment by nightpool** [comment]
does pale moon support the Addon SDK? If so then it shouldn't be too hard
to provide support for it.

**Comment by nightpool** [comment]
(as distinct from the extension api, that is)

**Comment by Zarggg** [comment]
Pale Moon uses their own GUID, I believe.

https://forum.palemoon.org/viewtopic.php?f=24&t=8740
https://forum.palemoon.org/viewtopic.php?f=1&t=5440

**Comment by nightpool** [comment]
the relevant section:

>Jetpack (Add-on SDK) extensions

>For Jetpack style extensions, this is a much more complex story, since Mozilla has been recommending people to make extensions with the SDK that pulls approved target apps from the SDK itself. Pale Moon is not part of that list; the GUID does not get compiled into the final Jetpack extension, and they will not function (at least, not without some editing and even then it may not suffice).

I don't think we're going to be building extensions with the pale moon sdk, but it seems like it should be an almost drop in replacement if you want to build the extensions yourself.

**Comment by owlspice** [comment]
Hmmm, about what I expected. Oh well, thanks for your time, everybody!

**Comment by Wolvan** [comment]
Reopening due to Palemoon support being a possibility (See #900)

**Comment by NamelessRumia** [comment]
Close the issue if you're just going to abandon the idea. >:V
