### ISSUE TITLE
Extension to fix broken audio posts

### ISSUE THREAD

**Issue by akunohomu** [new-xkit/XKit#1121]
Working but very ugly example: http://pastebin.com/TR3fsLWB

I'm not a JS programmer so this is probably terribly written, but it adds a native HTML5 audio player to all audio posts that (so far) always works, even when Tumblr's audio player doesn't.

Known bug: search page full of audio posts (filter by audio posts) looks terrible/unusable.

If someone could take this and turn it into a proper extension that replaces Tumblr's audio player completely (I cannot, don't know enough JS/HTML) that would be great. Also probably needs more testing, I wrote it today.

**Comment by Wolvan** [comment]
Looks good, but why don't you add this as a PR?

**Comment by akunohomu** [comment]
In its current form it's not suitable (no uninstall, causes issues on search page) for merging and I don't understand how PRs work on GitHub.

**Comment by nightpool** [comment]
@wolvan probably also needs some post listener infrastructure.

**Comment by Wolvan** [comment]
What do you mean no uninstall?
And PRs are easy, you just fork this repository with the fork button and then there is a create new file button.
Just add a `audio_player.js` file in the Extensions sub directory and paste the contents

@nightpool what exactly do you mean?

**Comment by nightpool** [comment]
@wolvan the destroy function for the linked code is basically just a stub

also, it need to be in a post listener so that we actually do it when we
get new posts, rather then just affecting the posts that are loaded at the
beginning.

**Comment by Wolvan** [comment]
@nightpool, please
```
run: function() {
    XKit.post_listener.add("audio_player", this.add_audio);
    add_audio();
},
````

**Comment by nightpool** [comment]
Simple audio fixed this
