### ISSUE TITLE
Post icons in Peepr don't line up properly

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1127]
![](http://i.imgur.com/hOSPbQW.png)

Not sure if this is Tumblr-native since the messaging icon is on the higher line, although I have a feeling XKit plays a part in this.

**Comment by nightpool** [comment]
yeah this just happens when stuff overflows. there's not enough room for the post icons on the line. What do you think should be the correct behavior?

**Comment by ThePsionic** [comment]
I expect the XKit icons to be added neatly to the bottom right, to the left of the reblog and like icons.

**Comment by nightpool** [comment]
we could probably tweak this a little but I don't think this is really a bug, unless you can think of a compelling reason this is bad for users.
