### ISSUE TITLE
Queue+ Shuffle Erronous Error 

### ISSUE THREAD

**Issue by MatthewT1** [new-xkit/XKit#1130]
When I shuffle my queue it works as expected, but I get an error saying it didn't work:  

![queue error](https://cloud.githubusercontent.com/assets/5216489/17553212/426fa70e-5eca-11e6-976b-0072a165bf51.png)

**Comment by blackjackkent** [comment]
I can't reproduce this on my end. Does it seem to be happening with a specific post in the queue or anything like that? Or is it constant?

**Comment by MatthewT1** [comment]
Not sure what changed, but its not happening anymore - closing out
