### ISSUE TITLE
source links gone on dashboard/likes

### ISSUE THREAD

**Issue by kitsunegari101** [new-xkit/XKit#1131]
After moving from Chrome to Opera, this is the only issue I've noticed. I checked through the settings I have with Tweaks and can't find anything that might be causing source links to disappear. Normally this wouldn't be a problem...except if the OP has switched URL and there's no redirect page.
![tfw no source link](https://cloud.githubusercontent.com/assets/14188767/17647679/2bba891c-61c1-11e6-9711-f94ba02104fa.png)

**Comment by coderpatsy** [comment]
Are you using Tumblr Savior? Iirc it hides sources by default (whether or not it should...).

**Comment by nightpool** [comment]
this is a tumblr savior "feature"

**Comment by nightpool** [comment]
see also https://github.com/bjornstar/Tumblr-Savior/issues/35
