### ISSUE TITLE
Enhanced Queue shuffling only a few posts

### ISSUE THREAD

**Issue by invalidCards** [new-xkit/XKit#1133]
> I'm not sure if this is really a bug or anything, but the Enchanted Que isn't really shuffling the entire que. It's only shuffling between about 4 or 5 posts (usually the first ones you see on the que)

**Comment by izub** [comment]
You are correct, the current functionality is that only currently loaded posts in the queue are shuffled. Not exactly ideal and kind of confusing for uninformed users.
