### ISSUE TITLE
Weird Bug with Timestamps and Asks

### ISSUE THREAD

**Issue by Kikaromi** [new-xkit/XKit#115]
In the Timestamps app, if you set it to display the relative time (I.E. 5 minutes ago) either by itself or not, for Asks it'll only display "an hour ago" until the ask is 2 hours old, then it displays the normal "2 hours ago" so on and so forth. 

This bug doesn't affect posts on the dash; it's only asks. 
; w; Just thought to mention it.

**Comment by albinakarambura** [comment]
Inbox timestamps don't work right for me too. I get asks from the future with "in eight hours". I think it probably depends on the time zone of the sender.

**Comment by nightpool** [comment]
@albinakarambura make sure you have your timezone set correctly on your
computer—otherwise XKit won't be able to calculate the proper offset.

**Comment by nightpool** [comment]
@albinakarambura [this page](https://jsfiddle.net/xn29871z/embedded/result/) will show you the current local time and timezone xkit thinks it's in. If either one of these is wrong, you'd have problems like you're seeing currently.

**Comment by albinakarambura** [comment]
I am 100% sure that timezone on my computer is set correctly, but I just checked anyway, and it is.
That page determines my local time and timezone correctly.

**Comment by nightpool** [comment]
Interesting. Make a new issue, please?

**Comment by WyohKnott** [comment]
We use moment.js to calculate the relative time. As per the doc ( http://momentjs.com/docs/#/displaying/fromnow/ ), "one hour ago" is displayed when the message has been received between 45 and 90 minutes from now.

**Comment by nightpool** [comment]
@Kikaromi can you be a little more explicit about what you're seeing on the dash vs. in asks that you expect to be the same?

**Comment by nightpool** [comment]
[deleted posts that moved to #116]

**Comment by Kikaromi** [comment]
Sorry for the late response; my issue was tied to the "Asks From the Future" problem with the time zone conflicts.
