### ISSUE TITLE
Find Blogs broken

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1151]
Find Blogs does not show any button for which to activate Find Blogs. Chrome 53.0.2785.116 m (64-bit).

**Comment by hobinjk** [comment]
The error appears to be that XKit.interface.where() does not behave according to specification. What it should do on the dashboard is set `user_url` to the user's main blog's url. Instead, it leaves it blank. The current logic to find user_url on most blogs was created in https://github.com/new-xkit/XKit/commit/3123c6b1ce63b4dd3bbffca5252726b57ce9d310 and probably just needs to be updated for whatever new thing Staff has introduced.

**Comment by genevera** [comment]
Any idea on whether this will be fixed?

**Comment by genevera** [comment]
Nevermind - this should probably work: https://github.com/new-xkit/XKit/pull/1271

**Comment by nightpool** [comment]
another zombie issue
