### ISSUE TITLE
One-Click Postage does not work properly on the "standard" search pages. Also cosmetic issues.

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1153]
When going to a standard search page or the explore page, One-Click Postage shows a broken, non-working layout (Quick Tags can't be clicked).

The search page in general doesn't look too spiffy, likely because of the multitude of bottom-post icons we add, making each column basically non-stop.

**Comment by nightpool** [comment]
I had a fix for the second part, somewhere. Let me see if its still on my computer...

**Comment by ThePsionic** [comment]
Found out part of the reason of issue 1 - on the dashboard Quick Tags adds a chunk of CSS in the `head` (`<style id="xkit-css-added-by-quick_tags">`) which, for some reason, does not get added on Search and Explore pages.

**Comment by nightpool** [comment]
Issue 2 is addressed in #1159
