### ISSUE TITLE
Inbox timestamps from the future

### ISSUE THREAD

**Issue by albinakarambura** [new-xkit/XKit#116]
![image](https://cloud.githubusercontent.com/assets/1273206/9047521/35796e9a-3a3b-11e5-909d-5cecde440a92.png)

Relative time doesn't work right for timestamps on the asks.
That's the ask I got 6 hours ago, it displayed "in 8 hours" at the time.

**Comment by Kikaromi** [comment]
Oddly enough mine is the opposite; mine is an hour in the past. 
![ask](https://cloud.githubusercontent.com/assets/13576045/9047915/ba92f998-39fa-11e5-97a8-07d60ccf59f8.jpg)

Just in case I checked whether or not Xkit was correct with my time zone and sure enough it is: 
![time-zone](https://cloud.githubusercontent.com/assets/13576045/9047920/cc93719a-39fa-11e5-9bc2-bd62d9cbcecc.jpg)

If I can throw out a guess, maybe xkit is stuck on a certain timezone for everyone?

**Comment by albinakarambura** [comment]
So I just sent myself an ask to recheck everything, and it appears that it's not only relative time that glitches in the inbox:

![image](https://cloud.githubusercontent.com/assets/1273206/9048365/41f19d4a-3a41-11e5-9de7-8432d4d5b68e.png)

And after refreshing:
![image](https://cloud.githubusercontent.com/assets/1273206/9048349/2aa96bd6-3a41-11e5-9ac8-e40fcaa77630.png)

This one is still correct:
![image](https://cloud.githubusercontent.com/assets/1273206/9048137/68d89b4a-3a3f-11e5-9efa-1f3d4def2d84.png)

This is only happens inside the inbox, dashboard timestamps work correctly.

**Comment by hobinjk** [comment]
The way the API we use for timestamps works is that it gives back Tumblr's server time. When fixing this issue originally I assumed that this would always be New York time. It's possible that they have different timezones, which would be annoying.

Please make sure that your version of XKit is at least 7.6.5 and your version of Timestamps is 2.7.3.

**Comment by albinakarambura** [comment]
![image](https://cloud.githubusercontent.com/assets/1273206/9049004/4fbedd02-3a46-11e5-803a-260628b05e41.png)
![image](https://cloud.githubusercontent.com/assets/1273206/9049011/5f6980ea-3a46-11e5-9fd9-9c3b071b7710.png)

**Comment by Kikaromi** [comment]
@hobinjk 
Well the timestamps seems to display relative time correctly for me now after changed my Blog Settings' Timezone to EST and back to mine (CST). 

If anything you could make that a temporary fix?

**Comment by hobinjk** [comment]
This definitely merits more investigation. I think the answer may be that Timestamps needs to read the user's timezone settings. Hopefully it won't need to try to guess the server timezone. I can take a closer look at this once I am off work.

**Comment by albinakarambura** [comment]
I checked my blog setting, and tumblr doesn't have my timezone correctly:
![image](https://cloud.githubusercontent.com/assets/1273206/9049363/f7982968-3a49-11e5-8fdf-8d5aae318382.png)
That's correct cities, but it should be GMT +3:00.

**Comment by hobinjk** [comment]
Upon looking into this it turns out that Tumblr serves asks to people using their locally configured timezone (I assumed mine was PDT, I was wrong). This will likely require a gross cached solution to be fast.
