### ISSUE TITLE
XKit was unable to contact XCloud servers.

### ISSUE THREAD

**Issue by acqcolor** [new-xkit/XKit#1168]
Attempted to login to old XCloud servers using the "Check to use the old XCloud servers" option under XCloud, but getting the following error message:
>Can't connect to server
>XKit was unable to contact XCloud servers.
>Error code: 1003
>Please try again or send a bug report

The old version of XKit wasn't working either due to issues connecting to servers. If it's actually true that the old XKit XCloud servers are no longer accessible, there should be a message indicating this instead of a checkbox.

**Comment by nightpool** [comment]
Yeah, the old XCloud servers have gone down for good since the latest
update to the extension was made. We'll look into correcting the error
message.
