### ISSUE TITLE
"please update xkit" popup links to old xkit page

### ISSUE THREAD

**Issue by Xolroc** [new-xkit/XKit#1170]
As the title says. Recently got a popup on tumblr saying to update xkit to version 7.7.4 from 7.7.3 or whatever the version was--and then the popup linked me to the old no-longer-updated xkit.info page.

**Comment by Xolroc** [comment]
Further details: Going to the downloads on this site and attempting to install the xpi leads to firefox complaining that the addon is unsigned. To my knowledge, signing the addon is not a complicated process and I would strongly recommend signing all your releases.

**Comment by Sudrien** [comment]
Same issues.

Logical link update would be to https://github.com/new-xkit/XKit/releases

As @hobinjk made the 7.7.4 release - @nightpool made 7.73 when the firefox signing issues were first addressed - I'd wonder if a new signing key has to be generated, or an old one has yet to be exchanged.

**Comment by nightpool** [comment]
@Sudrien @Xolroc I'm not sure why the release uploaded originally wasn't signed. I've gotten a copy of the signed release from Mozilla and will be testing it momentarily.

**Comment by nightpool** [comment]
@Sudrien @Xolroc updating XKit from the about:addons page should now work. We've stopped notifying users of the update for now, and we'll fix the link and re-enable it shortly.

**Comment by nightpool** [comment]
Critical because this is blocking us re-enabling update notifications

**Comment by nightpool** [comment]
oh, shit. I've been thinking this is a different issue then it was. brb
