### ISSUE TITLE
Safari storage breaks when encoding non-ascii characters

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1178]
base64-encoding any non-ascii on safari, such as when saving it to storage, will cause a nasty error. This means some extensions can't be loaded on safari, some posts can't be archived, xcloud fails sometimes etc. etc.

I haven't checked recently to confirm this is still an issue, though I doubt it got fixed.

**Comment by ThePsionic** [comment]
I remember there being a unicode issue with extensions - #1081 was made a while ago to fix a similar issue - not sure if it also applies to storage, but sounds likely.

**Comment by nightpool** [comment]
Yeah, sorry, just made this issue because I knew it was outstanding but I
couldn't find a ticket for it. I haven't had a lot of time to look into it,
but it definitely has to do with how the safari bridge handles storage.
