### ISSUE TITLE
Full Config Export is broken

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1188]
Always creates a gist containing just `{}`. We don't use it as much as the normal edump, but still not good that it's broken.

**Comment by nightpool** [comment]
This is just chrome, and there's a pr I was just looking at the other day
that fixed it. The problem is that gm_listValues returns nothing. The other
problem is that the entirety of xkit storage needs to be rewritten from the
ground up, so.

tags: B-Chrome, bug, P-Medium

**Comment by AprilSylph** [comment]
resolved by #1536
