### ISSUE TITLE
xkit-extension.tumblr.com dead, several links not working

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1190]
Broken links are:
- `bridge.js`
  - [L76](https://github.com/new-xkit/XKit/blob/1375a0e188e5bba3e85e4757506bbd1828f2ded4/Chrome/bridge.js#L76)
  - [L102](https://github.com/new-xkit/XKit/blob/1375a0e188e5bba3e85e4757506bbd1828f2ded4/Chrome/bridge.js#L102)
- `xkit_installer.js`
  - [L43](https://github.com/new-xkit/XKit/blob/1375a0e188e5bba3e85e4757506bbd1828f2ded4/Extensions/xkit_installer.js#L43)
- `xkit_patches.js`
  - [L26](https://github.com/new-xkit/XKit/blob/f16525cc99cb9b82d4400836bf1a1ca70a492577/Extensions/xkit_patches.js#L26)
- `people_notifier.js` (not actual link, just rebranding)
  - [L486](https://github.com/new-xkit/XKit/blob/71585beeed796a9411583f2bf78bff3851711e7c/Extensions/people_notifier.js#L486)
  - [L498](https://github.com/new-xkit/XKit/blob/71585beeed796a9411583f2bf78bff3851711e7c/Extensions/people_notifier.js#L498)
- `old_notifications.js` (same as above)
  - [L4](https://github.com/new-xkit/XKit/blob/1375a0e188e5bba3e85e4757506bbd1828f2ded4/Extensions/old_notifications.js#L4)
- `servant.js` (same as above)
  - [L122](https://github.com/new-xkit/XKit/blob/1375a0e188e5bba3e85e4757506bbd1828f2ded4/Extensions/servant.js#L122)
  - [L150](https://github.com/new-xkit/XKit/blob/1375a0e188e5bba3e85e4757506bbd1828f2ded4/Extensions/servant.js#L150)

**Comment by nightpool** [comment]
note: all the content is still online, it just got moved because of inactivity. xkit-extension-blog.tumblr.com has all of the old pages

**Comment by nightpool** [comment]
Yeah saw this last weekend. Did it get renamed to
xkit-extension-blog.tumblr.com?
