### ISSUE TITLE
Profiler partially failing

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1194]
Timezone and mutual following are currently stuck on infinite loading. Part of the problem is that there is one API call not done via HTTPS, which triggers a MixedContent error. If that bug is fixed, the attempt to parse the received data into JSON (https://github.com/new-xkit/XKit/blob/master/Extensions/profiler.js#L440) fails, and stops the extension altogether. Additionally, a 404 error is thrown while trying to access the `followed_by` SVC call.

High priority since it breaks a significant part of the extension.

**Comment by nightpool** [comment]
Timezone works for me? Followed by is going to be addressed soon.

**Comment by nightpool** [comment]
Downgrading to papercut because its a less-used extension and its only one small part (timezone)

**Comment by hobinjk** [comment]
I fixed timezone in #1197 but forgot to reference this issue in the PR.
