### ISSUE TITLE
"Hide installed extensions" breaks after search

### ISSUE THREAD

**Issue by shutterspeak** [new-xkit/XKit#1196]
After doing a search, the "hide installed extensions" toggle no longer hides your installed extensions, if that makes sense. It does what's expected of it before the search, but afterwards, checking the box does nothing (the extensions no longer hide).

**Comment by nightpool** [comment]
Can you be a little more specific? How does it break?

**Comment by shutterspeak** [comment]
After doing a search, the "hide installed extensions" toggle no longer hides your installed extensions, if that makes sense. It does what's expected of it before the search, but afterwards, checking the box does nothing (the extensions no longer hide). I made a quick video, but I couldn't upload it. Working on that now.

**Comment by shutterspeak** [comment]
https://drive.google.com/file/d/0B5XtNm_gU8QEQVFmenFEME52a2M/view?usp=sharing

**Comment by nightpool** [comment]
Thanks. I edited the issue with that information, and triaged it.
