### ISSUE TITLE
ER doesn't work; reblog chain detection messed up again?

### ISSUE THREAD

**Issue by kitsunegari101** [new-xkit/XKit#1200]
It's happening again...the thing where when you go to reply to and reblog a post, the previous reblog chain is deleted. Tried all the old fixes (single quotes, bolding/italicizing/making the previous urls smaller) and nothing's worked so far. Might be an ER bug, but it might also be Tumblr after adding or removing the spooky messaging noises?

**Comment by punkerbones** [comment]
I'm having the same problem as well. I made a post illustrating the issue. [http://punkerbones.tumblr.com/post/152608193912/punkerbones-alrightim-about-to-lose-my-mind](http://punkerbones.tumblr.com/post/152608193912/punkerbones-alrightim-about-to-lose-my-mind)

**Comment by kitsunegari101** [comment]
I found a temporary fix, and that's to put a space between the last symbol of each URL in the chain and the colon, but I don't know how long it'll last since Tumblr breaks things quite often.

**Comment by minawakitten** [comment]
Is the problem really related to the ER? Because I dont use it on my XKit but, when I reblog a post and add something, I can see it from /blog/xxxx or I can see it while viewing the post on mobile but I CANNOT see it from the blog itself.

**Comment by nightpool** [comment]
Fixed in #1201, unfortunately.
