### ISSUE TITLE
Firefox disables add-on due to lacking verification

### ISSUE THREAD

**Issue by teyla86** [new-xkit/XKit#1203]
Firefox 49.0.2 disables New XKit 7.7.4 due to lacking verification despite xpinstall.signatures.required already being set to false.

**Comment by nightpool** [comment]
Where are you getting an unverified version of 7.7.4? That version should
be signed.

Xpinstall.signsture.required has been disabled for over 9 months now, it
was only ever a temporary measure to ease transition.
