### ISSUE TITLE
Bug: Tag Tracking+

### ISSUE THREAD

**Issue by NuclearVacuum** [new-xkit/XKit#1206]
The _Tag Tracking+_ extension is failing to notify me about _all_ new updates. It continues to show my tags are (incorrectly) inactive.

I currently watch over 10 tags, with only three of them showing me daily updates (while the rest remain blank). This has been going on for about a year not. I've tried contacting X-Kit directly on Tumblr, yet have never received any reply. This is extremely frustrating and I have nowhere else to turn. I would appreciate any help to fix this bug. Thank you.

**Comment by nightpool** [comment]
Please don't intentionally create duplicate issues, thanks.
