### ISSUE TITLE
Quick Tags breaks video posts

### ISSUE THREAD

**Issue by Benedict-SC** [new-xkit/XKit#1207]
- Create a Youtube video post by pasting a url
- Add a tag or tags using the Quick Tags extension
- Note that the video is replaced with a "Watch on url.tumblr.com >" link

Probably related: when I make a video post with no caption, Quick Tags fails completely, returning Unable to edit post, error code QT01A200, Post cannot be empty.

Behavior is consistent whether or not the original post included tags.

(I haven't really looked around in your codebase, but I'm guessing the video portion of the post content is ignored when generating the edit content to post back with the API, so a post with no caption is treated as an empty post. Probably an easy fix depending on whether Tumblr's API is garbage and makes this difficult for some reason?)

**Comment by nightpool** [comment]
Just to be clear, this is a *video* post, right? not a post with an embedded video?

if so, this should be fixed by #1044, which I can probably just approve now

**Comment by Benedict-SC** [comment]
Yep, but checked embedded video to be sure and that's working fine. Thanks!
