### ISSUE TITLE
Read More Now breaks on custom "Keep reading" links

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1217]
Opening [this post](http://norcumi.tumblr.com/post/153460768694/photographer-endangers-his-life-to-capture-lava) on the dashboard creates a Read More Now button, even though the "Keep reading" link goes off-site. Clicking the button replaces the post with another entirely unrelated post. The button should be hidden in these scenarios in order to ensure nothing breaks.

**Comment by nightpool** [comment]
is there a way to fix this without breaking custom domains?

**Comment by ThePsionic** [comment]
Not sure, actually, since all links are automatically turned in to t.umblr.com redirects. However, recreating on my own blog with custom domain doesn't quite work - clicking Read More Now on [this post](http://tumblr.thepsionic.com/post/153517678535/this-is-a-test-post-do-not-notice-it-pls-keep) just expands the "Keep reading" link to be a direct link to GitHub rather than a t.umblr.com redirect.

**Comment by ThePsionic** [comment]
[This post](http://tumblr.thepsionic.com/post/153517765545/test-post-2-keep-reading), however, does seem to get the issue - a problem with Keep Reading links in blockquotes maybe?

**Comment by ThePsionic** [comment]
Oh! I seem to have found it out. The Read More Now button seems to take the latest reblog of the person's blog and appending that reblog chain to the post. Testing both previously linked posts now result in that behavior.
