### ISSUE TITLE
one click reply not opening text post.

### ISSUE THREAD

**Issue by ectochoir** [new-xkit/XKit#1218]
Instead, the button is just leading back to side blogview like clicking on the reply itself.

**Comment by Dhwty** [comment]
I'm having the same problem. The reply button on the activity page still works as intended, but the one on the dash opens the post in the sidebar view. Clicking on the reply itself will open the post in the usual manner, whether that's the sidebar or a new tab, depending on the blog settings.

**Comment by nightpool** [comment]
Which browser?

**Comment by Dhwty** [comment]
For me, Firefox 49.02. Notably, it seems to only be affecting reply notifications, and not reblogs or likes. Fishing for another reply right now, so I can see if it's still broken, or if this was Tumblr being temporarily screwed up.

**Comment by nightpool** [comment]
Fix coming shortly.
