### ISSUE TITLE
pokes update doesn't actally download

### ISSUE THREAD

**Issue by bluefairykino** [new-xkit/XKit#1221]
so the new pokes update that sorts out the storage and stuff? it doesn't actually update. i've refreshed so many times, but the prompt to update never goes away. thus, i can't do anything on tumblr. the box blocks the posts and i can't click on anything while it's up. what is going on here?

**Comment by Wolvan** [comment]
Sounds like storage doesn't properly set. Can you open the developer console check for errors?

**Comment by bluefairykino** [comment]
....i'm sorry, im not good with code stuff, how do you open it?

**Comment by Wolvan** [comment]
Are you on chrome? Press F12

**Comment by bluefairykino** [comment]
firefox actually (im so sorry i should have said that sooner)

**Comment by Wolvan** [comment]
@ThePsionic help me out here, I use FF dev tools so rarely

**Comment by Regulith** [comment]
I'm having the same problem. Trying to load a page like the new-xkit blog only shows this in console, though I have no clue if it's even related. I'm also using Firefox.
> Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

**Comment by Wolvan** [comment]
neither of these errors are related. Can you try opening dev console and THEN activating the storage transfer?

**Comment by Regulith** [comment]
Sure. Nothing else appears in the console.

**Comment by Wolvan** [comment]
firefox?

**Comment by Regulith** [comment]
Yes.

**Comment by ThePsionic** [comment]
@Wolvan @bluefairykino Ctrl+Shift+J to open the console in Firefox

**Comment by nightpool** [comment]
@Wolvan firefox addons don't show up in the console, getting their logging
output is this whole process.

Looks like someone else in support is having the same issue

**Comment by Wolvan** [comment]
>firefox addons don't show up in the console

Oh great, thanks Firefox. How can you get XKit's logs again?

**Comment by nightpool** [comment]
I'm looking into it now

**Comment by nightpool** [comment]
Labeling P-Critical because it prevents all use of XKit if you have Pokés installed.

**Comment by Regulith** [comment]
Sorry, I guess I've been looking at some other console. I'm extremely code-dumb! Here's what comes up when I try doing the transfer.
>new-xkit: Exception { message: "Component returned failure code: 0x…", result: 2147942487, name: "NS_ERROR_ILLEGAL_VALUE", filename: "resource://gre/modules/Preferences.…", lineNumber: 123, columnNumber: 0, data: null, stack: "Preferences._set@resource://gre/mod…", location: XPCWrappedNative_NoHelper }  core.js:106

**Comment by nightpool** [comment]
Hmm, that's good. Thanks. We'll take a look.

**Comment by nightpool** [comment]
Downgraded to high because it looks like this isn't affecting everybody on firefox
