### ISSUE TITLE
NotificationBlock still shows reblogs in Activity.

### ISSUE THREAD

**Issue by nightpcople** [new-xkit/XKit#1225]
Reblogged posts are _still_ showing in activity **despite** the fact that I've used NotificationBlock. It's actually insane since it used to work  so well and now all of a sudden it doesn't do what it says it does in  the Activity.

**Comment by mackenbrose** [comment]
Also worth nothing that it's _only_ reblogs that aren't being blocked as the extension seems to be blocking liked posts just fine on my end.

**Comment by blackjackkent** [comment]
Resolved by #1240
