### ISSUE TITLE
Activity+ - Group notification by post

### ISSUE THREAD

**Issue by MyshkaMoya** [new-xkit/XKit#1232]
The above feature isn't working as it used to anymore. Instead of grouping notifications of the same post, it now just throws random posts in a group. 

![image](https://cloud.githubusercontent.com/assets/23398008/21493338/4a9868e0-cc0b-11e6-86d9-11a72185c60c.png)

![image](https://cloud.githubusercontent.com/assets/23398008/21493291/0d5f6226-cc0b-11e6-8571-5c0b8843cca2.png)

**Comment by nightpool** [comment]
I *think* I might have some code on my computer that fixes this. Will get back to you on that.

**Comment by nightpool** [comment]
Oh, wait, no. This is definitely a subset of the changes that also broke NotificationBlock. great....

**Comment by MyshkaMoya** [comment]
glad i could help haha
