### ISSUE TITLE
Problem with logging in

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1244]
Unconfirmed, from the askbox:

> i've been using xkit on chrome for ever, but recently - over the last few days to about a week - if i log out of the account and try to log back into it, i get a notification from tumblr saying there's a problem logging in. this happen repetitively, effectively locking me out of the account. i tried on browsers without xkit installed and i was able to log in/log out/log in again without problem - same after i deleted xkit from chrome. i know at least a couple others with the same problem. help?!

can someone look into this asap? this is super bad if true.

**Comment by blackjackkent** [comment]
I was able to repro the issue -- but I was also able to repro it in an incognito session with XKit removed from Chrome. This is some sort of Tumblr bug with the login process, nothing to do with us.

**Comment by nightpool** [comment]
Sounds good! I'll answer the ask
