### ISSUE TITLE
ER crashes Chrome on Windows

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1249]
Unconfirmed, from the support chat:

> 
> `XKit|87096` Everytime I try to reblog/post something, it crashes.
> 
> `nightpool` What browser are you on?
> 
> `XKit|87096` It says, 'aw snap!@
> 
> `nightpool` can you link me the post?
> 
> `XKit|87096` google chrome
> `XKit|87096` it wont let me post anything
> 
> `nightpool` What version of Editable Reblogs do you have?
> `nightpool` You can find this under XKit > Editable Reblogs
> 
> `XKit|87096` 3.3.6
> `XKit|87096` Could it be because of the update?
> 
> `nightpool` 87096: I really don't think so...
> `nightpool` xkit crashing your browser is really really weird, for one thing
> 
> `XKit|87096` It's really frustrating. I cleared my history and etc
> `XKit|87096` I unistalled the extension and it worked perfectly. It's just the editable reblogs
> 
> `nightpool` what version of chrome are you using?
> 
> `XKit|87096` Version 55.0.2883.87 m (64-bit)
> `XKit|87096` Version 55.0.2883.87 m (64-bit)
> `XKit|87096` Version 55.0.2883.87
> 
> `nightpool` what OS?
> 
> `XKit|87096` on windows
> `XKit|87096` i just tumblr searched editable reblogs and it seems people are having troubles too

**Comment by nightpool** [comment]
Obviously, P-Critical if substantiated.

**Comment by danamhx** [comment]
I have been having the same issue regarding chrome crashing yet works fine if I disable it.

**Comment by blackjackkent** [comment]
Sustantiated. I'm working on this now. Drafted an announcement to the extension blog if osmeone could approve.
