### ISSUE TITLE
New extensions from current github marked as "third party" in control panel

### ISSUE THREAD

**Issue by rimbaum** [new-xkit/XKit#126]
Is there a way to remove these flags? I don't think it's top priority to get new icons for some of these newer extensions, but people seeing that they're flagged as third-party when they're downloadable from the extensions framework of the New Xkit might worry people and make them distrust the extensions.

**Comment by hobinjk** [comment]
The offending code is https://github.com/hobinjk/XKit/blob/master/Extensions/xkit_preferences.js#L1256 and is relatively easy to fix

**Comment by nightpool** [comment]
this is part of the bigger problem of us having a ton of old branding in
our code still.

**Comment by Wolvan** [comment]
@nightpool Do you suggest a rewrite?

**Comment by nightpool** [comment]
@Wolvan I meant that we should replace all of the stuff that says
STUDIOXENIX, and all of the stuff that says "xkit guy" and everything like
that.

**Comment by Wolvan** [comment]
@nightpool alright, I getcha. That shouldn't be too hard using notepad++'s find in files feature. Is there anything we should replace the branding with? Or just remove it completely

**Comment by rimbaum** [comment]
@Wolvan @nightpool it's just my opinion, since I can't code for beans and can't contribute more than helping to point out bugs, but I would recommend all new branding.

**Comment by nightpool** [comment]
@Wolvan figuring out what to replace it with is the reason I haven't just done it yet :D

@rimbaum right, the problem is just trying to figure out what we need... are we happy with "New XKit"? "The New XKit Team"? Or what?

**Comment by bvtsang** [comment]
Is this where we have a heated argument about what our new studio name is? :P

**Comment by nightpool** [comment]
nah its the point where we realize that naming things is hard.

**Comment by Wolvan** [comment]
@nightpool I'd actually go with something that has team in it, simply for the reason that it's multiple people actively working on the extension now, not like it was before with only xenix doing all the work himself

**Comment by Wolvan** [comment]
Oh, and we should also still put xenix into at least the support page, without him this wouldn't have been possible

**Comment by nightpool** [comment]
oh, absolutely. this isn't about erasing him from the project by any means.

I'm also in favor of something like "New XKit Team" but that's just my
suggestion

**Comment by hobinjk** [comment]
@Wolvan Atesh wasn't actually the only person to work on old XKit, there were also the lovely WyohKnott and 0xazure.

One of my plans for the immediate future (like five minutes from now) is to form the new-xkit github organization. I think the short form of our name should be "new-xkit" with the long form being "New XKit Team"

**Comment by nightpool** [comment]
And I'm not really in love with "New XKit" but its certainly short and to
the point.

**Comment by nightpool** [comment]
also the new-xkit.tumblr.com url is available if we want to grab it :D

while I'm name squatting things I also grabbed the #xkit channel on
freenode if we want to do the IRC thing.

**Comment by Wolvan** [comment]
I for one vote for new xkit team

**Comment by bvtsang** [comment]
As an alternative to IRC, we may want to try [Gitter](https://gitter.im/).

And I'm also fine with New XKit Team.

**Comment by 0xazure** [comment]
+1 :+1: for Gitter.  I've played around with it a bit, and it's really nice to only have to auth with GitHub.  I'd imagine it would be easier for less-technically-savvy individuals to sign up for GitHub and join the Gitter room than have them muck around trying to get IRC to work, but I could be wrong.

Gitter also does some nice organizational stuff for Orgs, if that's the direction we end up going.

**Comment by nightpool** [comment]
Flash irc things are a lot easier because you just have to go to a webpage
and type in a nick, so its generally easier then gitter. I also didn't like
it aesthetically last time I used it. But we could try out both and see
what which works better.

**Comment by bvtsang** [comment]
I haven't tried Gitter, but I prefer it over IRC because it keeps history. Integration with Github is a bonus.

**Comment by nightpool** [comment]
dupe
