### ISSUE TITLE
dark bold tags (maybe a/b?)

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1261]
Some users are seeing dark tags on their computers:
![](https://68.media.tumblr.com/4d0bf42223c05746363bdaf4f7f8cf72/tumblr_okk2hihBtX1r7ealro1_1280.jpg) (credit to unwrapping.tumblr.com for the graphic)

We should investigate whether this is a real A/B  (using a Tumblr flag or other mechanism) or just a bug, and add a tweak to suppress it. The "dark bold tag style" is really really bad imo.

**Comment by AprilSylph** [comment]
problem no longer seems present
