### ISSUE TITLE
Moving future contributions to new-xkit organization

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#127]
Advantages of organization:
  - Better permissions model
  - If I am hit by a bus other people can continue
  - It's more "professional" and consistent
  - People will need to put in more effort to dox me.

Of all of these, only the last two require a new organization. However, I quite like the last one, especially since someone tagged something as "xkit (hobinjk)" the other day.

The only disadvantage this has is that people who are currently only using the Github web UI will need to delete their fork of hobinjk to replace it with one of new-xkit.

Comments, questions, or concerns?

**Comment by hobinjk** [comment]
(issues can be migrated easily using this google tool I found)

**Comment by nightpool** [comment]
can't we just migrate this repo?

**Comment by nightpool** [comment]
![image](https://cloud.githubusercontent.com/assets/233815/9076589/f7a235a2-3ae9-11e5-9de6-96c5e042bddc.png)

seems a lot easier, and it sets up git and web redirects IIRC

**Comment by hobinjk** [comment]
I was considering that as a secondary option, the main unknown there is how long the Github Pages stay up. If http://hobinjk.github.io/test_pages/ doesn't disappear then transferring the repository is definitely a better choice.

**Comment by nightpool** [comment]
Hmmm either it will make the 301, or we could just recreate a dummy repo
for the transitionary period.

**Comment by bvtsang** [comment]
What is the process for onboarding new contributors to the organization? Will the migrated issues preserve the comments from the original issues?

**Comment by 0xazure** [comment]
+1 :+1: for an organization, [as I had suggested on the upstream repo last October](https://github.com/atesh/XKit/issues/173#issuecomment-59096553).  I agree with the points, especially the last one.  I'm still not sure why people feel the need to add personal identifiers to projects like that.

As far as repo transfer vs some kind of push/migrate strategy, what about transferring the repo to the org (thereby ensuring an easy transfer of issues), and have @hobinjk immediately fork from the org repo to maintain the Pages during the transitionary period.  Per GitHub's support docs, [GitHub Pages associated with the repository are **not** redirected](https://help.github.com/articles/transferring-a-repository/#whats-transferred-with-a-repository).

What are the thoughts on splitting up the original repo into separate concerns within the org?  For example: one repo for Chrome, another for Firefox, the Extensions, XKit core, etc.  Dependencies could be linked in through git submodules or [a dependency manager](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).  Or would that go against the desire to [make it easy for @atesh to accept changes from this fork back into the upstream project](http://new-xkit-extension.tumblr.com/post/124689305939/idk-about-ur-opinion-on-this-but-did-you)?

**Comment by nightpool** [comment]
Yeah an immediate fork sounds like the best option (if github allows it?)

If github doesn't, could you do something like putting it in a subdirectory
of your global user github.io repo?

**Comment by nightpool** [comment]
I don't really think there's enough code to weren't the hassle of git
submodules. Each bridge is like, one file, super lightweight.

**Comment by nightpool** [comment]
@0xazure Also, contra the docs, http://hobinjk.github.io/test_pages still seems to work. (even after he migrated it).

It seems the correct solution is still:

 - Move hobinjk/xkit to new-xkit/xkit 
 - Fork new-xkit/xkit to hobinjk/xkit

(if github allows you to do that, which I think it does)

**Comment by bvtsang** [comment]
Just to keep track, once the repository is moved/transferred we need to:

- Migrate issues and their comments from hobinjk/XKit to new-xkit/XKit
- In the code:
  - Update all references to `hobinjk.github.io` to `new-xkit.github.io` (and update Github Pages configuration accordingly)
  - Update all references to `github.com/hobinjk` to `github.com/new-xkit`
- Change the "Broken Shit We Know About" link on [the New XKit Tumblr](http://new-xkit-extension.tumblr.com) to point to new-xkit/XKit's issues page
- Update Github links in the [New XKit Tumblr's FAQ](http://new-xkit-extension.tumblr.com/faq)
- Update Github link in the New XKit Tumblr's blog description

Is there anything else I'm missing?

**Comment by nightpool** [comment]
@bvtsang if the repository is moved/transferred then all the comments and issues will go with it. that's the benefit. (also there will be a fork at hobinjk.github.io to handle the transition period probably)

**Comment by hobinjk** [comment]
I'm going to push the big red button after all of the content required for the switch is in place. The transfer will happen in about 5 minutes.

**Comment by hobinjk** [comment]
It is done, hopefully very few users will be left behind

**Comment by bvtsang** [comment]
Looking nice! There are a couple of loose ends though:

- Update Github links in [FAQ](http://new-xkit-extension.tumblr.com/faq), specifically in "How can I help out?"
- Update Github link in the New XKit Tumblr's blog description (where it says "We've decided to update XKit. It's harder than it looks. We're not in contact with the original XKit Guy, nor do we have access to xkit.info. We currently operate at this blog and on GitHub.")

**Comment by nightpool** [comment]
it would be nice for collaborators to be able to edit/tag/assign/close issues. thoughts?

**Comment by bvtsang** [comment]
@nightpool +1 your suggestion.

**Comment by Wolvan** [comment]
make this a +2, @nightpool

**Comment by ThePsionic** [comment]
imma sneak in with that +3 @nightpool

**Comment by hobinjk** [comment]
Issue editing comes with a host of other permissions detailed in https://help.github.com/articles/permission-levels-for-an-organization-repository/. I'll bump up the permission level and rename Collaborator to Admin to reflect the far-reaching powers you get.

I would greatly recommend not pushing directly to new-xkit because code reviews are your friend. I will also try to be less hypocritical about this. This is especially relevant because pushing to production requires running `create-extensions-dist.sh` in a clean directory with all of the planets in alignment. Getting a bot to do that post-receive is one of my priorities for automation.

**Comment by nightpool** [comment]
@hobinjk yeah I was hoping the fine grained permissions beta would help but apparently id doesn't :(

**Comment by Wolvan** [comment]
@hobinjk You should be able to do the automation through github's webhooks I guess. But I absolutely agree that we should never push to the repo directly. Instead what about having at least 1 or 2 contributors/admins look over the code and approve before a merge is allowed to happen?

**Comment by hobinjk** [comment]
@Wolvan Yes, right now all PRs are getting reviewed by either me or @dlmarquis. As long as the person reviewing the code really knows what they are doing I have no qualms about other people performing reviews other than the whole create-extensions-dist thing.

**Comment by nightpool** [comment]
getting errors from gitter when I try to create a room. someone else want
to take a crack at it?

**Comment by Wolvan** [comment]
@nightpool I think I managed to open a gitter. I added you and @hobinjk (Although he still hasn't signed up to gitter). Who else do we need?
