### ISSUE TITLE
No Recommended targets tracked tags as well

### ISSUE THREAD

**Issue by blackjackkent** [new-xkit/XKit#1274]
From the help chat:

NewXKitBot @NewXKitBot 20:17
SG i have No Reccomended extension and it was working how i wanted it to, but then i started following a tag and it started hiding that too

**Comment by nightpool** [comment]
This is by design. I think there's an option to turn it off.

We can fix if you think it seems confusing though.

**Comment by blackjackkent** [comment]
Nope, the three options for No Recommended are:

* Get rid of recommended likes
* Get rid of two-column recommended blogs
* Hide recommended posts under permalinked posts on user blogs

Blocking tracked tags in this extension seems odd to me since unlike the sorts noted above, a tracked tag is something you've explicitly requested be on your dash.
