### ISSUE TITLE
Old Sidebar Isn't Working

### ISSUE THREAD

**Issue by Tumblrgirl** [new-xkit/XKit#1280]
When I use Old Sidebar, it fails to load the sidebar with "error" in its place in capitals, I have no idea why this is happening, this extension's worked perfectly for me before....

**Comment by nightpool** [comment]
@estufar

(this may be a private blog problem? you use the API right?)

**Comment by nightpool** [comment]
Should be fixed by #1302. Let us know if you're still seeing this!
