### ISSUE TITLE
Default Tumblr theme obscuring One-Click Postage extension buttons

### ISSUE THREAD

**Issue by Ulrome-Bardsea** [new-xkit/XKit#1284]
Tumblr seem to have redesigned their default theme in such a way that the search box/button bar at the top now obscures the One-Click Postage (and other) buttons making them unreachable on any page using the default theme. 
As a way around this, and also as a form of ‘future proofing’ should Tumblr decide on future re-designs, could you add the option to reposition the One-Click Postage buttons either top, bottom, left edge or right edge rather as you can with tabs on some browsers ? I’m guessing that this optional button repositioning would be simpler than getting the buttons to float over the default Tumblr theme.

**Comment by dgblackout** [comment]
this has spread to all blogs. One-click post/queue no longer works on any tumblr.

**Comment by m2pt5** [comment]
For the same reason, View On Dash doesn't work anymore either.

**Comment by nightpool** [comment]
upgrading to P-Medium now that this is on all blogs.

**Comment by Dhwty** [comment]
Resolved, but not closed, by #1380 .

**Comment by nightpool** [comment]
whoops
