### ISSUE TITLE
Tag Replacer's option is confusing/broken

### ISSUE THREAD

**Issue by akunohomu** [new-xkit/XKit#1289]
What I expected leaving `Case Sensitive` disabled to do: Change `tag` and `Tag` to `Replacement Tag`

What it actually does: Changes `tag` and `Tag` to `Replacement Tag` *and lowercases all other tags on every modified post*

---

What I expected enabling it to do: Change `Tag` to `Replacement Tag`

What it actually does: Breaks. Definitely fails to find any results if the tag has a space in it, might break in other times

---

Will try and fix later.

**Comment by akunohomu** [comment]
`if (encodeURIComponent(m_tags[i]) === XKit.extensions.tag_replacer.t_replace) {`

can be changed to

`if (encodeURIComponent(m_tags[i].toLowerCase()) === XKit.extensions.tag_replacer.t_replace.toLowerCase()) {`

to fix case sensitive mode. Of course, now it's not case sensitive. But it also isn't totally broken. At this rate I'll have this fixed in a month

(fixed my tags though so I'm still winning)

**Comment by nightpool** [comment]
My feeling is that this is probably the least of tag-replacers problems.

**Comment by lostklown** [comment]
Tag replacer is only recognising about 1/3rd of the tags I try and replace. I know they exist b/c I can pull them up on my blog. It's extremely frustrating as at first I thought it was b/c the tags had characters like ones with parenthesis or | in them, but i get error messages with simple text tags as well & it will then go on to find & replace complicated tags.
