### ISSUE TITLE
Firefox Nightly is disabling X-kit due to not being Multi-process compatible

### ISSUE THREAD

**Issue by the-nothingman** [new-xkit/XKit#1290]
With Firefox starting to make the change to multiprocess/webextension only add-ons they're stating to disable anything that isn't up to date in Nightly (55.0a1). For now there is a about:config tweak to disable the check (extensions.allow-non-mpc-extensions) but not sure how long they're going to keep that allowed.
More info: https://wiki.mozilla.org/Add-ons/ShimsNightly

![2017-05-04](https://cloud.githubusercontent.com/assets/7260835/25709686/fce2c43a-30b7-11e7-9e38-68a77520f9db.jpg)

**Comment by nightpool** [comment]
I'll look into this on Monday if no one gets around to it before then.

**Comment by OughtaCrawl** [comment]
Thank you all for working on this. It's invaluable.

**Comment by caitmuenster** [comment]
Yay! Thank you -- this extension is really valuable to me and I'm so happy to hear that it's on a path to make the transition.

**Comment by nightpool** [comment]
This issue was resolved by #1293. It doesn't use a WebExtension yet, which was postponed to a further release because we're already multiprocess compatible, and just needed to flip the e10s switch.

**Comment by nightpool** [comment]
https://github.com/new-xkit/XKit/pull/1291 tracks web extension support
