### ISSUE TITLE
Old Sidebar pushes dashboard content off of the page

### ISSUE THREAD

**Issue by ShotgunsAndSass** [new-xkit/XKit#1303]
It seems that Tumblr has done something to mess up Old Sidebar, as now it's too wide and the dashboard appears below Old Sidebar, for some reason.

![image](https://cloud.githubusercontent.com/assets/18859835/26023451/97c008bc-37b3-11e7-95e0-0c54020ec15a.png)

Can this be fixed? I can't use it like this and this is an extension i'm addicted to. All that I think would need doing is making Old Sidebar slightly thinner, or transporting the dash slightly to the left.

**Comment by nightpool** [comment]
This is a bug in the sidebar narrowing extension, I'll take a look at it
today.

**Comment by citrusella** [comment]
Posted the below when I wasn't sure whether a new issue should be started or I should have commented on the issue that was referenced two hours ago (news flash: I did the second option XP). Was told to repost it here so here it is copied with a few edits:

>~~I don't know if this should be noted here or in a new issue, but~~ the update made my sidebar push the content area of my dash (the part where the new post buttons and actual posts are) down so that it doesn't show up until below the Tumblr Radar.

>I do have the dashboard-narrowing extension active, though. (But the real rub is that this problem is apparently preventing my access to the XKit menu (clicking the icon does nothing... actually now that I'm testing none of the links on my dash do anything) so I can't disable it to see if that fixes it unless there's a way to do it on the "backside" (which I think I remember there being but I need to go find it, if it existed).)

>EDIT: I can access the XKit settings via the activity page (even though it has the same thing happen with the jumping down, but links still work there). Checking and unchecking "return sidebar to original width" fixes it, but only until it's refreshed (unchecking it entirely works all the time). It appears that when the sidebar first loads, it loads at full width, even though when the "return to original width" option is selected it should theoretically be narrower. Then because that option is checked, the dash tries to be where it would if the sidebar were the thinner width but that doesn't work because the sidebar is its full width. That's a layman's observation as opposed to something from someone with tech know-how, though. XP

>EDIT 2: Even with the width fix, no links work on the dash with the extension enabled. (They can probably be right clicked, though I didn't test that for sure.)

**Comment by nightpool** [comment]
@citrusella I can't reproduce the link thing—can you open a separate issue for that? thanks!

**Comment by nightpool** [comment]
P-High because it majorly affects the user experience of a large subset of the users of a commonly used extension.

**Comment by citrusella** [comment]
>@citrusella I can't reproduce the link thing—can you open a separate issue for that? thanks!

I'll play around first to see if I can figure out exactly what's causing it if it's not the extension (for all I know it's an intermittent thing on Tumblr's end; it was happening off/on before the update for no clear reason but seemed consistently linked to when the Old Sidebar extension was on last night). Or maybe I'll do it immediately and play around. I just don't wanna make the vaguest issue ever. :-/
