### ISSUE TITLE
NotificationBlock not working on the Activity Page

### ISSUE THREAD

**Issue by mackenbrose** [new-xkit/XKit#1317]
With Tumblr's changes to the Activity Page, the NotificationBlock extension is also broken again.

**Comment by nightpool** [comment]
thanks for reporting!

**Comment by katyggls** [comment]
I'm confused about how NotificationBlock is supposed to work now that we don't have classic notifications anymore. When the Classic Notifications extension for xkit was working, there was a little block button to block notifications for that post in the notifications for that post that showed up on the dashboard. Now I go to the activity page, and there's no way I can see to actually add a post to NotificationBlock? I hover over a notification for one of my posts and I get the x to block the user who liked the post, but no button to block notifications for the post itself. I've checked the settings and I have 'Show the NotificationBlock button on notifications' option checked.

**Comment by nightpool** [comment]
@katyggls It looks like that option is still broken, which is tracked as issue #1086. At the moment, the "correct" way to block notifications on posts is using Go To Dash
