### ISSUE TITLE
Profiler (and possibly other extensions) broken by User Menus+ putting 'undefined' in place of usernames

### ISSUE THREAD

**Issue by canmom** [new-xkit/XKit#1331]
While trying to use the Profiler extension, information for the blog undefined.tumblr.com would come up instead of the blog I was trying to find out about.

![image of the Profiler extension, showing undefined.tumblr.com instead of the target blog](http://i.imgur.com/0apFKsM.png)

I looked into the code for this extension, and the problem seems to come in User Menus+ (or show_more in the extension editor). There are some kinds of links to blogs, such as reblog headers and mentions, which are not correctly updating the information used by User Menus+ when they're moused over.

---
Profiler gets the URL of the blog the user is asking about from a `data-url` attribute on its User Menus+ menu entry ([source](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/profiler.js#L175)):

```javascript
menu_clicked: function(e) {

	var m_object = $(e.target);

	if (!m_object.hasClass("xkit-profiler")) {

		while (!m_object.hasClass("xkit-profiler")) {
			m_object = m_object.parent();
		}

	}

	/*...*/

	var user_url = $(m_object).attr('data-url');

	XKit.extensions.profiler.show(user_url);

},
```
This `data-url` attribute is defined in the function Profiler uses to add its User Menus+ entry ([source](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/profiler.js#L147)):

```javascript
XKit.extensions.show_more.add_custom_menu("profiler", function(data) {
	var user_url = data.name;

	$(document).off("click", ".xkit-profiler-button-" + user_url, XKit.extensions.profiler.menu_clicked);
	$(document).on("click", ".xkit-profiler-button-" + user_url, XKit.extensions.profiler.menu_clicked);

	return "<div data-url=\"" + user_url + "\" class=\"xkit-profiler-button-" + user_url + " xkit-profiler\">Profiler</div>";
});
```

with a similar function for non-Classic menus. This depends on the `data` object passed to this function having the correct information.

Going over to User Menus+, we find the `data` that gets passed to this function is defined by an object called `popup_data` ([source](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/show_more.js#L572), likewise [here](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/show_more.js#L215) for Classic menus).

```javascript
if (XKit.extensions.show_more.custom_menu_extension.length >= 0) {

	var m_data = XKit.extensions.show_more.popup_data;

	for (var i = 0; i < XKit.extensions.show_more.custom_menu_extension.length; i++) {

		var returned_menu = "";

		try {
			returned_menu = XKit.extensions.show_more.custom_menu_function[i](m_data);
		} catch (e) {
			returned_menu = "";
		}

		m_html = m_html + returned_menu;
	}

}
```

`popup_data` is updated by two functions `store_data_username` ([source](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/show_more.js#L439)) and `store_data_avatar` ([source](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/show_more.js#L495)). Of the two, mousing over an avatar (`store_data_avatar`) appears to work correctly - Profiler returns information about the target blog rather than 'undefined'.

`store_data_username` is called in two ways. It's called directly when mousing over the CSS selectors `.post_info_fence a, .post_info a, a.username` ([source](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/show_more.js#L116)). `.post_info_fence a` and `.post_info a` appear in the usernames at the top of posts, and these cases still appears to be working correctly (Profiler returns correct information).

Once a link triggers `store_data_username`, it attempts to get 'popover' information. First it checks for a `data-tumblelog-popover` attribute, and if one exists, [takes the data from it](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/show_more.js#L449). This is the case for links at the top of posts, the `.post_info a` ones. If there isn't a `data-tumblelog-popover`, it attempts to get this information [via a HTTP request to the Tumblr API](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/show_more.js#L463), at the URL

```javascript
url = "http://www.tumblr.com/svc/tumblelog_popover/" + real_username + "?is_user_mention=false"
```

The problems arise with any links in the body of the post - links in reblog headers, and mentions.

The first problem is that they don't match the three selectors used to call `store_data_username` directly. Instead, there is a catchall function `store_data_username_if_userlink` that attempts to identify any other instances of a link to a blog, checking any other links to see if they end in `.tumblr.com` and calling `store_data_username` if it fits the pattern ([source](https://github.com/new-xkit/XKit/blob/938c0e93b2689b6d6596e4b8c3c9149728186400/Extensions/show_more.js#L421)):

```javascript
store_data_username_if_userlink: function(e) {

	var m_obj = $(e.target);

	if (typeof $(m_obj).attr('href') === "undefined") { return; }

	var m_url = $(m_obj).attr('href').toLowerCase();

	if (m_url.substring(m_url.length - 1) === "/") {m_url = m_url.substring(0, m_url.length - 1); }

	if (m_url.substring(0, 7) === "http://" && m_url.substring(m_url.length - 11) === ".tumblr.com") {
		var m_username = m_url.substring(7, m_url.length - 11);
		XKit.extensions.show_more.store_data_username(e, true, m_username);
	}

},
```

Unfortunately, there aren't very many links that fit this pattern. Links in reblog headers always point to a specific post, for example:

```html
<a class="reblog-tumblelog-name post_info_link" href="http://darmokontheocean.tumblr.com/post/161660731739" data-peepr="{&quot;tumblelog&quot;:&quot;darmokontheocean&quot;, &quot;postId&quot;:&quot;161660731739&quot;}" style="">darmokontheocean</a>
```

And mentions - inline links of the form `@user` - always use a `tumblr.co` link, for example if I type `@canmom` in a post, the resulting URL is https://tmblr.co/mWdhldRm6uUtUj_Ok1pyQ9w rather than https://canmom.tumblr.com:

```html
<a href="https://tmblr.co/mWdhldRm6uUtUj_Ok1pyQ9w" style="">@canmom</a>
```

The first case, links in reblog headers, could be detected by a slightly more complicated function. We want to catch links of the form `http[s]://[username].tumblr.com/something/else`, and `[username]` should not be `www` or it would match all internal Tumblr links in the sidebar etc.. Rather than the relatively simple matching function above, we could use a regular expression to match all suitable URLs. Here's an alternative version of `store_data_username_if_userlink`, using a regex:

```javascript
store_data_username_if_userlink: function(e) {

	var m_obj = $(e.target);

	if (typeof $(m_obj).attr('href') === "undefined") { return; }

	var m_url = $(m_obj).attr('href').toLowerCase();

	var userlink_re = /https?:\/\/(?!www)([a-z]+)\.tumblr\.com[a-z0-9\/-]*/;
	var test = userlink_re.exec(m_url);
	if (test) {
		var m_username = test[1];
		XKit.extensions.show_more.store_data_username(e, true, m_username);
	}

},
```

Making this change in the XKit Editor solved the problem.

The second case, of `tmblr.co` links in mentions, seems like it would be more of a problem. There's no `data-tumblelog-popover`, nor is there any immediate way to deduce the username from the `href`. Somehow Tumblr is able to identify these links. I checked the request data when I moused over this link, and noticed that Tumblr is sending an HTTP request to

```https://www.tumblr.com/svc/tumblelog_popover/m-0lu6vX7CZfGkYoRqi6tzg?is_user_mention=true```

That's something we can easily do by adding an extra clause to `store_data_username` to deal with mentions, and an extra case for `store_data_username_if_userlink` to handle tumblr.co links.

I think I've worked out how to solve the problem while writing this issue, so I'm going to attempt to make the changes and submit a pull request asap.

**Comment by canmom** [comment]
I did some further investigation, and the regular expression above would capture too many things. While links in a reblog header show the popover with information about the blog, and should therefore update User Menus+, ordinary links to specific posts or pages on a blog do not have the popover.

This might not matter, but it could lead to extra HTTP requests, so it can be fixed by adding an extra check, iff there is material on the end of the URL (such as /post/1234/slug), to see if it has the class `.post_info_link`.

**Comment by canmom** [comment]
I've attempted to write code to make an HTTP request to get the data for mentions, but I'm only getting an empty array back as my response. Not entirely sure what I'm doing wrong here.

I'm detecting mentions with another regex:

```javascript
/* handle tmblr.co links, which appear in mentions*/
m_test = /https?:\/\/tmblr\.co\/([A-Za-z0-9_-]+)/.exec(m_url);

if (m_test) {
	XKit.extensions.show_more.store_data_username(e, true, m_test[1], true);
}
```
This, I've been able to determine, is working fine.

I slightly modified the `store_data_username` function, first adding another argument:

```javascript
store_data_username: function(e, userlink_mode, real_username_or_slug, is_mention) {
```
and then modifying the HTTP request code:
```javascript
url: "http://www.tumblr.com/svc/tumblelog_popover/" + real_username_or_slug + "?is_user_mention=" + is_mention || false,
```
This produces URLs of a form I've seen Tumblr itself sending. If you watch the console when you mouseover a tmblr.co link for the first time since pageload, e.g. when mousing over a link `https://tmblr.co/mWdhldRm6uUtUj_Ok1pyQ9w`, Tumblr sends a corresponding HTTP request
```GET XHR https://www.tumblr.com/svc/tumblelog_popover/mWdhldRm6uUtUj_Ok1pyQ9w?is_user_mention=true [HTTP/1.1 200 OK 173ms]```
This is very similar to the HTTP requests that this extension is already sending, but with the string mWdhldRm6uUtUj_Ok1pyQ9w in place of the name of the blog, and is_user_mention set to true rather than false. However, when I try to send a matching request, I get a valid response that seems to only contain an empty array (going by logging in the XKit console).

I'm not sure how to access the HTTP requests sent by XKit using the Firefox dev tools to see if I can identify a difference.

**Comment by hobinjk** [comment]
This is great work! For this problem, I'd first make sure that you're using `GM_xmlhttpRequest` to perform the request as it will properly set the cookies and headers that Tumblr expects. If you want to see the HTTP requests sent by XKit you can use the Browser Toolbox, accessible from Tools -> Web Developer -> Browser Toolbox. The Network tab in the developer tools that pop up should list every request made by the browser, including XKit.

**Comment by canmom** [comment]
Apologies for leaving this for so long. I'm back to working on it now.

I figured out the cause of the problem - the URL [was being transformed to lower case before being tested](https://github.com/new-xkit/XKit/blob/27dcd7668225c35bdd38246ef92e5fa642206d92/Extensions/show_more.js#L427). This was a problem with tmblr.co links, where the difference between capital and lowercase letters is important. Removing that made correct info be retrieved for mentions.

I noticed another problem: avatars no longer seem to have a `data-tumblelog-popover` attribute so the `store_data_avatar` function no longer works. However, it should be redundant now since avatars link to blogs in a way that should be caught by the regular expression in `store_data_username_if_userlink`. So I'm going to remove this function.

I should be able to submit a pull request shortly!

**Comment by canmom** [comment]
Actually it looks like avatars do, at least under some circumstances, still have data-tumbelog-popover, but not on the 'Posts' page for one of your blogs, but then it's not relevant since you can't get a menu. So I won't be changing that.

**Comment by ElliSpeaks** [comment]
An additional point (IDK if it's relevant) When I use Profiler to rename people, when I Close Window, I can't bring up Profiler again unless I refresh.

**Comment by canmom** [comment]
The pull request fixing this has been merged.

@ElliSpeaks maybe we should make a new Issue for that?
