### ISSUE TITLE
i keep on getting connection failure from github

### ISSUE THREAD

**Issue by supdudessssss** [new-xkit/XKit#1336]
I'm trying to get the extension for firefox, but it won't let me. Is there a way to fix this?

**Comment by nightpool** [comment]
Look into your SSL settings, make sure your timezone is correct, and double check to be sure that you don't have Private Browsing mode on.

**Comment by supdudessssss** [comment]
Where can I find this at?

**Comment by nightpool** [comment]
@supdudessssss if you're still having this issue, swing by our support chat: https://new-xkit-extension.tumblr.com/discord-support so we can help you out! It seems pretty unlikely to be a problem on our end, though, so I don't think the repo is the right place for this
