### ISSUE TITLE
Adding is_mine class to posts in peepr

### ISSUE THREAD

**Issue by chris-pie** [new-xkit/XKit#1338]
Peepr does not tag posts nearly as much as dashboard does, and among others it doesn't give them "is_mine" class, However the posts that should have this class don't have like button. Would injecting the class based on that be good idea? If yes, at what point? It would fix several issues with extensions not working in peepr.

Alternatively we could change how get_posts() and post() work, since those posts won't have a like button on the dashboard either. Or instead of just checking for one of those things, they could check for both. I'm not sure what the best way to implement it would be. Any thoughts?

**Comment by AprilSylph** [comment]
there is no discrepancy between how posts work on the dashboard and peepr on the new dashboard; closing as no longer relevant
