### ISSUE TITLE
I can't reblog anything

### ISSUE THREAD

**Issue by violetta-ee** [new-xkit/XKit#1347]
I don't know if it's the one click postage or what but I can't reblog or queue anything unless I do it the old fashioned way which is as you can understand annoying. Everytime I try to use the one click postage I get the error window with the error code OCP08-403 and I checked all of the reasons above and it's not any of them. I noticed there was an update today but it was working fine up until an hour or so ago.

**Comment by blackjackkent** [comment]
Hello -- we're aware of this issue and working on a fix. Thanks for letting us know! :)
