### ISSUE TITLE
Editable Reblogs posting error

### ISSUE THREAD

**Issue by mel-lightfox** [new-xkit/XKit#1352]
On Safari (Macbook Pro Running Sierra)

![screen shot 2017-07-11 at 11 23 28 pm](https://user-images.githubusercontent.com/30100328/28100462-36caac22-6690-11e7-89ee-ed586ed6cff8.png)

-----------

```
[object Object]
```

System Data |   
----------- | -----------
ER Version | 3.3.7
user | projectlightfox
User Agent | Safari (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4
XKit Version | 7.7.3
Patches Version | 6.8.1
Extensions | xkit_patches, xkit_main, xkit_preferences, xkit_updates, one_click_postage, xinbox, one_click_reply, go_to_dash, tweaks, editable_reblogs, anti_capitalism, drafts_plus, activity_plus
URL | https://www.tumblr.com/edit/162869933636

**Comment by blackjackkent** [comment]
Should be resolved by #1351
