### ISSUE TITLE
Quick tags broken

### ISSUE THREAD

**Issue by defiantlygeeky** [new-xkit/XKit#1353]
Not sure if this is related to the other issues with quick reblog, but I can't use quick tags--when I try I get an error message that tells me it can't edit the post, with the error number QT01B403. Thanks.

**Comment by bedheadblonde** [comment]
I'm also having this issue.

**Comment by blackjackkent** [comment]
We just released a fix for the other quick-reblog issues and with the update I'm not able to reproduce this issue; please run an update-all on your xkit extensions (click the "Other" tab in the control panel and then click "Update All My Extensions", then refresh Tumblr) and let us know if the problem still occurs.

**Comment by nightpool** [comment]
Fixed by XKit Patches version 6.8.2
