### ISSUE TITLE
One Click Postage Malfunctioning

### ISSUE THREAD

**Issue by MamzelleCombeferre** [new-xkit/XKit#1354]
I've been having an issue with the one click postage function stating about an hour ago. Whenever I try to draft, queue, or reblog anything it's shown the error code OCP08-403 pop up. I've tried restarting my computer, closing and reopening the tag and the browser, uninstalling and reinstalling x-kit, uninstalling the one click postage extension, and updating the whole of x-kit, but nothing seems to be working. If there's a fix I'd really appreciate an explanation on how to do it! Thanks!! This is the first big issue I've had with x-kit, which is a testament to how wonderfully you all are running the program!

**Comment by MegasEx5000** [comment]
Hi!, i'm having the same problem as the OP with the One Click Postage, it started about 6-7 hours ago for me, i can only draft ''manually'', not with the extension anymore.

**Comment by particledamage** [comment]
Same issue! I would like to note that this issue seems to be happening primarily to firefox users, if that helps makes things easier. I've spoken to people using Chrome that have had no issue.

**Comment by junshii** [comment]
Hi, got the same problem here for more than 12 hours, also using firefox.
Hope someone knows what to do, thanks for your help!

**Comment by harrywells** [comment]
same :(  i'm using firefox 54.0.1 on mac os 10.13 beta (which i've had for a week and it was working fine until today).

**Comment by blackjackkent** [comment]
Should be resolved by #1351
