### ISSUE TITLE
Using esc to close OCP pop-up deletes tags

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#136]
Full text of ask:

when i type in tags on the little one-click postage popup and hit esc to close the popup, all my tags disappear! if I do that and press R to reblog it, my tags aren't saved. Is there a way to fix this? Right now I'm having to just click the reblog button on the popup after typing my tags. Regardless, I really appreciate all the work y'all are putting into this, thank you so much for saving xkit!!

**Comment by nightpool** [comment]
wait, so the flow goes like:

 - user hovers over reblog, opens OCP
 - user click in OCP to type in tags
 - user closes ocp
 - user expects tags to still be there?

I'm not sure this is how ocp is designed—it discards everything as soon as
you close the window. maybe an enhancement I guess?

**Comment by dlmarquis** [comment]
I think the idea is that all this is a part of the r/q/d quickblogging option, and that hitting esc is supposed to be the step before reblogging with r/q/d, so that the user never has to use the mouse. I could be wrong, though.

**Comment by nightpool** [comment]
@dlmarquis they're two separate features though... maybe we should make it
so something like alt-r, alt-q and alt-d work from the pop-up window?

**Comment by nightpool** [comment]
maybe this used to work though and this is just a regression that we should
fix. (shrug)

**Comment by dlmarquis** [comment]
@nightpool if we do something like alt-r, we have to be careful of Ubuntu users who have alt-r as a default keyboard shortcut. Actually, Tumblr's native quickblogging keys don't work at all on Linux. I think restoring/creating the functionality described is the best of the two options.
