### ISSUE TITLE
Double Xkit

### ISSUE THREAD

**Issue by IceDevice** [new-xkit/XKit#1371]
The problem with Xkit disappearing seems to be fixed as far as I can tell. However, there is now another problem on Firefox wherein the Xkit button and all effects Xkit has on Tumblr are duplicated. For example, there are two "editable reblog" buttons when I reblog, and two "tag replacer" options, and two sets of "tracked tags sidebar". At some times, pressing either button will work, at other times only one will work and it's a matter of picking the right one. At other times, such as with the Outbox extension, neither button works and the extension becomes inaccessible.

**Comment by nightpool** [comment]
Can you post a screenshot of about:addons?

**Comment by IceDevice** [comment]
Actually, this issue, like the last one, seems to have resolved itself pretty quickly. Guess someone at Firefox or Xkit was messing around. I'll take a screenshot and send it if it happens again.
