### ISSUE TITLE
Go-to-Dash/Quick Reblog/Etc. Not Working

### ISSUE THREAD

**Issue by ValensHawke** [new-xkit/XKit#1374]
Tumblr updated the blogs page so how things appear in the top right corner changed. Plugins like go to dash, etc. are now  broke. See attached image.

![image](https://user-images.githubusercontent.com/17369328/28989231-07597378-7942-11e7-986d-d6ae76834cc4.png)

**Comment by nightpool** [comment]
dupe of #1284
