### ISSUE TITLE
editable reblog doesn't include tumblr_blog links

### ISSUE THREAD

**Issue by snifflng** [new-xkit/XKit#138]
When posts used to be rebloggable it'd have a class="tumblr_blog" tag but the new extension doesn't have anyway to add that. That used to be useful if someone wanted to edit the css/style of it in their code

**Comment by nightpool** [comment]
Can you be a little more specific about what's happening and what you
expect to happen? I'm not sure from your issue description where the
tumblr_blog class would go or what purpose it served in the old code.

**Comment by snifflng** [comment]
When reblogs were still editable the url of the commenters at the top would be like 
<a href="http://tumblrpost.tumblr.com/post/125945341268/example" class="tumblr_blog"> 
in the post html and the tumblr_blog allowed you to edit the url of comments on your theme (w/ css). but with the extension it makes it 
<a href="http://tumblrpost.tumblr.com/post/125945341268/example" target="_blank">
and takes out the class="tumblr_blog" so it can't be edited and has no class tag

**Comment by nightpool** [comment]
Hmm ok thanks I'll take a look to see if we can fix this.

in the meantime you can use the attr substring selector to approximate this behavior. `[href*=".tumblr.com/post/"]` should work nicely.

**Comment by nightpool** [comment]
@new-xkit/owners feel free to assign me

**Comment by hobinjk** [comment]
Potentially fixed by #181. I believe that Tumblr is gradually phasing out the tumblr_blog class in any case.

**Comment by nightpool** [comment]
this was fixed a while back by @blackjackkent
