### ISSUE TITLE
XWidgets breaking modal overlays (rebloging, keyboard shortcuts)

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1388]
1. install XWidgets
2. open a blog in peepr/dashboard sidebar
3. try to reblog a post
4. see that the reblog form is *behind* the overlay pane, and that you can't interact with it or finish reblogging the post.

probably some css z-index override issue?

**Comment by Dhwty** [comment]
Is this resolved by #1389 ?

**Comment by nightpool** [comment]
yes
