### ISSUE TITLE
Improve PR automation

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#139]
- Contributor makes a PR
- Travis bot runs jshint and jscs, reporting any errors caused by the commit
- Reviewer comments something like "r+" or "r-"
- If r+, a bot merges the PR and pushes the changes to Github Pages through create-extensions-dist.sh

**Comment by nightpool** [comment]
apparently bors/homu is pretty configurable? http://homu.io/

**Comment by bvtsang** [comment]
Travis CI and @homu have been added. Should this issue be fixed?

**Comment by 0xazure** [comment]
Should probably document what we're using and the expected workflow somewhere, either on the README or somewhere on the project Wiki.

**Comment by hobinjk** [comment]
The only thing missing now is the automatic create-extensions-dist.sh which would require running an independent server as a Github webhook. I'll create a wiki page explaining the test and review workflow.

**Comment by ThePsionic** [comment]
Closing since homu has already been used for a while.
