### ISSUE TITLE
Sidebar Tracked Tag numbers are not clearing after checking...

### ISSUE THREAD

**Issue by ElliSpeaks** [new-xkit/XKit#1401]
![image](https://user-images.githubusercontent.com/15959327/29369179-bb58ba7e-8256-11e7-9fa4-fed6ec7de42f.png)
Usually when I click on a tag, and then refresh the dash the number will disappear. It's not any longer. This sometimes happens if there's someone new trying to post in the tag and it won't show the post yet, but the behavior this morning is different. It's also happening on tracked blogs.

**Comment by ElliSpeaks** [comment]
Something updated, and this is no longer an issue (unless others are experiencing it)

**Comment by nightpool** [comment]
okay! thanks for reporting, let us know if it keeps happening
