### ISSUE TITLE
XKit Editor opens to black screen

### ISSUE THREAD

**Issue by cass-z** [new-xkit/XKit#1410]
Opening the XKit Editor (https://www.tumblr.com/xkit_editor) leads to a brief “There’s nothing here” message, and then black screen with pop-up notification in the bottom-left corner “Welcome to XKit 7.7.7 (c) 2011-2013 STUDIOXENIX.” The XKit Editor worked on earlier versions. I’m using Firefox 55.0.3 on Mac OS X 10.11.6.

**Comment by Dhwty** [comment]
Update to 7.7.8, which fixes the editor.
https://github.com/new-xkit/XKit/releases/download/firefox-v7.7.8/new_xkit-7.7.8.xpi
