### ISSUE TITLE
Release 7.8.0 across Firefox, Chrome, and Safari

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#1418]
- [ ] Merge #1414 or spin off its addition of Xkit.storage.delete and merge that
- [ ] Delete or update version bumps in #1247 and merge it
- [ ] Bump everything to 7.8.0
- [ ] Release Firefox
- [ ] Release Chrome
- [ ] Release Safari

I want to get this done soon because Firefox 57 hits beta on the 28th

**Comment by puxlit** [comment]
I think the bulk of #1414 should sit for a while longer, as I'm still not entirely satisfied with the implementation. Should I cherry-pick 46c11e708fe04c180f8f2364591cff0aace3e6ed—the addition of `Xkit.storage.remove`—into its own PR, or were you planning on doing that?

**Comment by hobinjk** [comment]
@puxlit I can cherry-pick it into a PR with #1247 so that everything's in the same place

**Comment by nightpool** [comment]
closed by #1430......
