### ISSUE TITLE
"Staff picks"

### ISSUE THREAD

**Issue by Ketsuban** [new-xkit/XKit#1422]
So, you know how there was always the annoying radar of people you don't follow on the sidebar, and Xkit provides a way to get rid of it? They moved that to the main dashboard column and called it "staff picks". Now I have to scroll past something banal to see posts by people I actually follow.

Given it's not advertising it doesn't fall under the purview of Anti-Capitalism and should go under Tweaks.

Diagnostic data: Browser is Firefox 55 (64-bit), OS is Windows 10 Pro, extension info is https://gist.github.com/3178d451189beecf33f69dd40729e84b

**Comment by ThePsionic** [comment]
Already fixed in #1420 as part of No Recommended - just needs some final steps to push to live.

**Comment by AprilSylph** [comment]
Fixed by #1420 but the update is yet to go live, sorry for the delay!
