### ISSUE TITLE
Retags isnt working for me! 

### ISSUE THREAD

**Issue by Wanlingnic** [new-xkit/XKit#1423]
Hi there, the activity page is giving me a little trouble. I had the 'Retags' extension, so I used to be able to see the individual retags every time someone reblogged a post from me. but now, I see this instead:
![image](https://user-images.githubusercontent.com/32243467/30784020-8b2456f4-a17f-11e7-91fb-2ec8ea4291d8.png)

The tags at the bottom are my own tags. I cant see other people's tags any more. 

![image](https://user-images.githubusercontent.com/32243467/30784033-cd1d830a-a17f-11e7-81c9-a30bfb57a00d.png)

This started about a month ago when the activity page got an update and started to bunch reblogs together (e.g. "person and 16 others reblogged your post"). 

When I toggle the 'show only retags / responses' switch off, I get something like this:
![image](https://user-images.githubusercontent.com/32243467/30784050-1dc57bd2-a180-11e7-8b32-a8c0b3746984.png)

I'm looking for a solution so I can see the tags people use when they reblog my art again. I asked on the discord but I think not everyone has this problem.

If it's possible to find a fix I would really appreciate that. 

EDIT: Retags works fine when I see the notifications on the dashboard (the temporary little ones between posts) 
![image](https://user-images.githubusercontent.com/32243467/30784116-3e5b7b52-a181-11e7-881c-e5b19f961753.png)

**Comment by nightpool** [comment]
I haven't gotten the activity rollup update on desktop yet, unfortunately. has someone else?

**Comment by Wanlingnic** [comment]
Thanks for trying to help, Nightpool. :) From what I understand not everyone seems to have this problem yet, and I dont know what to do or how to fix it. It's been like this for over a month and it's very frustrating.

**Comment by LCPLibrary** [comment]
The activity "update" seems to have gotten a more widespread release recently. I've noticed another quirk in addition to the issues already noted:
![newxkitreport](https://user-images.githubusercontent.com/7525162/35867814-5fa8ae8e-0b20-11e8-8f0b-4eaa6063f09d.png)
Retags works in the activity drop-down menu (as long as the notes haven't been aggregated into digest mode) but, of course, not on the main activity page.

I hope this helps shed some light!

**Comment by zrllosyn** [comment]
Im currently having the same problem! It only seems to happen, as previously stated, in 'digest mode' or when a bunch of reblogs are placed in one section. 

![2](https://user-images.githubusercontent.com/36611736/36360211-a05e423a-14d6-11e8-88b4-eed186213161.png)

The one above is working just fine.

![3](https://user-images.githubusercontent.com/36611736/36360212-a078b188-14d6-11e8-9c81-a21882d5c2a3.png)

But this one isnt.

**Comment by insectoid5** [comment]
I am seeing the same problem that LCPLibrary reported, of Retags working on the dashboard Activity dropdown, but not on the main Activity page (with "digest" mode turned OFF).  I started noticing it only a couple of weeks ago, so it's probably a newer issue than the OP's.

**Comment by zebzorb** [comment]
The original issue still persists for me with Retags 1.2.5 in Firefox -- that is, multiple reblogs that have been bunched together in one group will only show tags that _I_ applied.

Was the fix only intended for non-grouped reblogs? The majority of my reblog notes are grouped together, so Retags' current usefulness is unfortunately limited (at best) for me.

I appreciate the other fix! But the original issue seems to still be a thing, so I was wondering if it's a WONTFIX.

**Comment by AprilSylph** [comment]
yeah, this shouldn't have been closed since that was only half a fix. #1504 is more progress but I wouldn't consider this fully fixed until true notification unrolling can be done (revealing all notes from a condensed note like on mobile)

**Comment by hobinjk** [comment]
I think #1504 will resolve this. It's main limitation at this point is that it doesn't unfold likes and follows which don't have tags for Retags to get
