### ISSUE TITLE
XKit incompatible with Firefox Quantum beta (Firefox 57.0)

### ISSUE THREAD

**Issue by MasterSteelblade** [new-xkit/XKit#1428]
As per title, XKit is considered a legacy extension in the new beta and cannot be enabled. Attempts to reinstall through the XPI (both 7.7.7 and 7.7.8) show a generic "incompatible with FF 57" notice. Upgrading from a previous release to the new build shows XKit in the Legacy Extensions section, prompting the user to find a replacement or check for an update.

Obviously simple architecture changes within FF, and referenced in #1418 as something happening soon, but now the beta is out it might be worth noting it formally.

**Comment by nightpool** [comment]
closed by #1430
