### ISSUE TITLE
Memory spike when directly visiting blogs

### ISSUE THREAD

**Issue by puxlit** [new-xkit/XKit#1432]
Users on Firefox (tested 55–57) with the latest XKit installed (tested 7.7.7–7.8.0) observe a sharp increase in memory consumption when they visit blogs directly.

Note this does _not_ appear to affect the dashboard.

Problems persist even with only barebones extensions enabled (`xkit_main`, `xkit_patches`, `xkit_preferences`, and `xkit_updates`).

Disabling XKit results in much saner memory usage behaviour.

| Reported by          | FF version | Extensions                                                 | Example                                           |
| -------------------- | ---------- | ---------------------------------------------------------- | ------------------------------------------------- |
| `Dimensional13#2221` | 55         | <https://gist.github.com/7be35e718a3ad6e4d9fea6ecb7d10619> | <http://merrimonster.tumblr.com/>                 |
| `kkkhhk#4320`        | 56         | <https://gist.github.com/85f8d0c9cd854b171df06289fb84411e> | <https://findoworld.tumblr.com/post/165889203818> |
| `puxlit#7190`        | 57         | <https://gist.github.com/6b098d513d162a356f7f1aa063631205> |                                                   |

**Comment by puxlit** [comment]
This miiight have something to do with the extension firing up for every like `iframe`…

**Comment by nightpool** [comment]
Okay let me see if I can repro this on Nightly. Might need to be reported upstream

**Comment by nightpool** [comment]
I can't reproduce this on FF 58 @puxlit. Can you take a look and see if it happens for you on Firefox Nightly?

**Comment by nightpool** [comment]
P-Critical since it affects **all**  of XKit in an incredibly serious and breaking way (by crashing the user's computer) on a full subset of machines.

**Comment by puxlit** [comment]
For posterity, @hobinjk flagged <https://bugzilla.mozilla.org/show_bug.cgi?id=1371255> as the likely root cause.
