### ISSUE TITLE
Comment stating read_posts dimming is broken

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#145]
https://github.com/hobinjk/XKit/blob/master/Extensions/read_posts.js#L37

Testing required

**Comment by blackjackkent** [comment]
The issue seems to be that clicking menu items on a dimmed post undims it (expected) but when those menus are clicked off, the post does not redim (unexpected).

I can take a look at this I think.

**Comment by blackjackkent** [comment]
Addressed in #156
