### ISSUE TITLE
Classic Notifications (I think) throwing "Undefined" as blog name

### ISSUE THREAD

**Issue by ElliSpeaks** [new-xkit/XKit#1450]
![image](https://user-images.githubusercontent.com/15959327/31463690-f2086020-ae83-11e7-8299-a046151e2145.png)
I thought maybe it was Profiler, but I disabled it, and it still showed Undefined. I think it's a Classic Notifications bug?

**Comment by hobinjk** [comment]
I was unable to reproduce this locally. If you see this again can you share your exported Extension info? To get this information open XKit, go to the "Other" tab, click on "Export Configuration", press the "Extension Info Export" button, then paste the resulting link here.

Sorry for the delay in triaging this!
