### ISSUE TITLE
Fix all JSHint Errors

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#146]
For `grunt jshint` to be useful, it needs to normally have no output. I'm about 30% done with eliminating all the errors from every file. This might make some PRs require manual merging. I am most worried about the possibility that some of the comparisons I changed were actually relying on their falsy and truthy conversions.

**Comment by nightpool** [comment]
@hobinjk in most cases where I saw "use ===" errors, I instead removed the equality test entirely. (i.e. turned `if(xkit.preferences.foobar == true)` into `if(xkit.preferences.foobar)`).

this seemed like a less lossy conversion to me, maybe that makes more sense in this case?

**Comment by hobinjk** [comment]
@nightpool It's good in some cases, but there are some really messed up places with things like `if (x != false)`. This would appear to be convertible into `if(x)`, but the conditions for weak inequality to `false` and truthiness are subtly different for things like "0". Thankfully this does not apply to `XKit.preferences.whatever.value` because those are always booleans.

**Comment by nightpool** [comment]
fixed by #155?

**Comment by hobinjk** [comment]
Yes, it is
