### ISSUE TITLE
Find blogs problem

### ISSUE THREAD

**Issue by justagirl5gaia** [new-xkit/XKit#1462]
Hello everyone,

I have installed the new Xkit extension for my tumblr blog and I would really like to use ''Find blogs'' but it doesn't seem to work properly. I have already installed the ''user menus'' and it still doesn't work . The problem is, I don't find the find blogs button anywhere, not in my dashboard, not when I enter a new blog. 
Could someone inform me on why is that happening? I appreciate any help you can provide.

Thanks!

**Comment by AprilSylph** [comment]
hopefully resolved by #1497 - tell us if this is not the case!
