### ISSUE TITLE
Edible Reblogs: stale hotlink to bread asset

### ISSUE THREAD

**Issue by puxlit** [new-xkit/XKit#1463]
<http://pngimg.com/upload/bread_PNG2281.png> is now served at <https://pngimg.com/uploads/bread/bread_PNG2281.png>, though we might want to consider rolling the image into the stylesheet or picking a more stable image host.

**Comment by nightpool** [comment]
it's a little big to roll into the spreadsheet, but maybe just use imgur?

**Comment by hobinjk** [comment]
I'd just like to take this time to thank @puxlit for making the best stale bread pun I've ever heard in my entire life
