### ISSUE TITLE
De-stickify in header options gets rid of demarcating line between header and page content

### ISSUE THREAD

**Issue by citrusella** [new-xkit/XKit#1475]
What the title says. Disabling that option brings back the line, but enabling it takes the line away. I can't find anything that suggests this is intended, so reporting on the assumption it's not.

**Comment by AprilSylph** [comment]
This is intended to make the option give the page a more nostalgic feel - when the header matched the width of the dashboard, there was no line. Is this a problem?

**Comment by citrusella** [comment]
It's throwing me personally off, but I'm sure I'll get used to it. (Much like I apparently got used to the line? XD)

I'll just close the issue; I only reported because I couldn't deduce that it was intended.
