### ISSUE TITLE
troubleshooting thing links to old Xkit troubleshooter

### ISSUE THREAD

**Issue by seebs** [new-xkit/XKit#1478]
Saw new version of noscript, thought I'd see if new xkit could reach update servers, it still can't, but now it offers me a troubleshooting link that's definitely for old xkit. (No reference to versions past 7.4, etc.)

It'd maybe help just to have, say, a list of domains that need to be whitelisted, or something? Unless it just plain can't be run at all ever with noscript until that updates. In which case it might be nice to have a version which, say, doesn't constantly spam the error messages, because as is, it's not actually practical to try to use tumblr at all with both new xkit and noscript...

**Comment by nightpool** [comment]
This issue should be fixed with the latest version of NoScript, it was a bug in their WebExtension version. I meant to make a post on the blog about it, but haven't had time. 

What version of NoScript is installed on your computer?

**Comment by seebs** [comment]
Today's update to noscript, claims to be 10.1.3c3, updated "4 hours ago".

**Comment by seebs** [comment]
Update, now on NoScript 10.1.4, same behavior. If there's a thing we need to be whitelisting in noscript or something, that would be helpful.

**Comment by nightpool** [comment]
The thing they're probably asking you to whitelist is "new-xkit.github.io"
but it really shouldn't be blocking other extensions at all. I'll have to
get in contact with the no script team.

**Comment by insectoid5** [comment]
The Firefox console gives errors about XKit trying and failing to connect to "https://www.xkitcs.com".  I tried whitelisting that in NoScript, but it doesn't help.
