### ISSUE TITLE
New XKit no longer on Firefox addons site?

### ISSUE THREAD

**Issue by nate2014jatc** [new-xkit/XKit#1479]
When I clicked the link to go to the Firefox addon page, I got a "Page Not Found" from firefox

**Comment by nightpool** [comment]
What link? New XKit hasn't been on the firefox addons site since their rules change in 2015

**Comment by AprilSylph** [comment]
@nightpool in the readme.md

**Comment by nate2014jatc** [comment]
@aprilsylph is correct.

Can I manually add the extension somehow?

**Comment by nightpool** [comment]
fixed in https://github.com/new-xkit/XKit/pull/1481

**Comment by nightpool** [comment]
The link to download new xkit for firefox it https://new-xkit-extension.tumblr.com/firefox, which redirects to the newest version.
