### ISSUE TITLE
Get rid of "Conversational Notes"

### ISSUE THREAD

**Issue by eehummings** [new-xkit/XKit#1489]
Tumblr rolled out a new "feature" where if you reply to a post, you start receiving notifications for all the other replies that post receives. My activity page is now flooded with replies coming in from other people's viral posts. 

As far as I can tell the updated feature is not affecting everyone yet.

There doesn't seem to be a way to turn it off.

I'd like a solution where I can get rid of these "conversational notes". I'd settle for a solution where I can just block notes from posts I didn't make. Notificationblock only lets me block notes on posts I myself made/reblogged.

**Comment by eehummings** [comment]
Apparently tumblr does allow you to turn this "feature" off, but the setting can only be changed on the mobile app, which I don't use.

**Comment by Laurelai** [comment]
Bumping, this is seriously distresing

**Comment by AprilSylph** [comment]
Conversational Notes can be turned off on the post they're activated for, via a circled lightning button on the notes container
