### ISSUE TITLE
Pale Moon Support?

### ISSUE THREAD

**Issue by RainbowMagicMarker** [new-xkit/XKit#1502]
I've tried doing some searching but I'm just coming up with old/obsolete answers. With Firefox completely dropping addon support and moving to more restrictive WebExtensions, and deleting all older extensions this spring, are you considering picking up Pale Moon Support? 

As Mozilla makes more and more questionable business decisions in regards to user choice and privacy it's hard to justify continuing to support them just for this one addon.

**Comment by nightpool** [comment]
No, it would be difficult and impractical for us to support pale moon. The move to WebExtensions allowed us to simplify the amount of work we had to do to support new features and improved our consistency across browsers. 

Personally, I've had nothing but hostile interactions with the Pale Moon community, and disagree specifically with their re-distribution policies, which [harm the open source ecosystem](https://github.com/jasperla/openbsd-wip/issues/86). We do not support pale moon and will not be supporting it in the future.

**Comment by nightpool** [comment]
I personally share many of your reservations with the governance of Firefox and Mozilla, but supporting Pale Moon is just not a viable option for us at this time.

**Comment by RainbowMagicMarker** [comment]
Fair enough, but I thought I'd ask since I hadn't been able to find a concrete answer.

I must admit I don't fully understand what you linked, I don't really code myself so the nuances of the argument are beyond me, so I can't really comment.

Thank you for acknowledging my reservations though, I understand your position and appreciate that you can understand mine. Mozilla just does not work for me anymore, it's rampant memory usage, Australis update, and questionable business decisions have made it a nonoption. Very sad because I just can't stand Tumblr without this addon! Thank you for your time and acknowledgement!
