### ISSUE TITLE
Activity+: Filter to only notes of your post

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#1524]
There's apparently an issue where notes of the original post show up in addition to the notes of your reblog of it. I'm hoping that this is not a limitation of the API and is just a simple bug in where we're getting the rollup information from.

**Comment by LCPLibrary** [comment]
I'm seeing this too. I can see which people actually reblogged the post I reblogged by checking in the activity drop-down, but the activity page is showing a lot of other reblog branches - ones with different comments, etc. Mostly just commenting to keep an eye on the bug but let me know if you need screenshots or anything!
