### ISSUE TITLE
One click reply arrow masks the Block button

### ISSUE THREAD

**Issue by WyohKnott** [new-xkit/XKit#154]
On the Activity page, the reply arrow icon needs to be moved further on the left because it overlaps the block icon.
(I'm working on it).

**Comment by nightpool** [comment]
@WyohKnott any updates on this?

**Comment by ThePsionic** [comment]
Closing because the block icon hasn't been around for a while now. @WyohKnott if you still experience this issue, feel free to re-open.

**Comment by ThePsionic** [comment]
(whoops I didn't even close it)
Never mind, I was wrong. Without one-click reply, the block icon is there, but when it is enabled the reply button overlaps the block button.

**Comment by chris-pie** [comment]
I'm going through old issues, this was fixed some time ago.

**Comment by nightpool** [comment]
thanks!
