### ISSUE TITLE
Editable Reblogs posting error

### ISSUE THREAD

**Issue by sydpeca101** [new-xkit/XKit#1545]
I'm having difficulty with editable reblogs. Anytime I edit and shorten a thread it will not let me post, queue, or draft it.  The browser I use is Safari.

*Please describe what actions we can take to reproduce the bug you found, including any links or screenshots that might help us figure out what's going on.*

-----------

```
[object Object]
```

System Data |   
----------- | -----------
ER Version | 3.3.8
user | frzelsa
body | <p><span><a href="http://lilopls.tumblr.com/post/173273469913">lilopls</a></span>:</p><blockquote>
<p><small>“Okay. Fine. But you have to promise you won’t tell a soul.” Lilo held out her pinky finger. She would accept that as a seal Elsa couldn’t break. “<i>Promise</i>.”</small><br></p>
<figure><img src="https://78.media.tumblr.com/2943adf9b40e6b638adfb6d592a48d81/tumblr_inline_p7pm6oBGFe1vwudxi_540.gif" class=""></figure></blockquote>
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
XKit Version | 7.8.2
Patches Version | 6.10.0
Extensions | xkit_main, xkit_patches, xkit_preferences, xkit_updates, xinbox, one_click_postage, one_click_reply, tweaks, go_to_dash, editable_reblogs
URL | https://www.tumblr.com/reblog/173273469913/fk6cuAl0

**Comment by AprilSylph** [comment]
we are aware of this issue - ER is currently broken on Safari (and pre-quantum Firefox) as logged in #1540 and we have a fix coming (hopefully) soon

**Comment by sydpeca101** [comment]
Thanks!
________________________________
