### ISSUE TITLE
OCP can only reblog/queue/draft once per pageload

### ISSUE THREAD

**Issue by AprilSylph** [new-xkit/XKit#1546]
the second XHR POST (`/svc/post/update`) always returns 403 Forbidden on the second attempt (and subsequently) to reblog anything via One-Click Postage. can't find a cause myself.

**Comment by AprilSylph** [comment]
okay, the only difference I can find is that subsequent requests on Firefox seem to use the same `X-tumblr-puppies` header, whereas on Chrome it's different every time. still no clue why though

**Comment by AprilSylph** [comment]
oh my god its case sensitivity
---

**Comment by hobinjk** [comment]
yIkEs
