### ISSUE TITLE
Find inactives error

### ISSUE THREAD

**Issue by topjames2** [new-xkit/XKit#1552]
Every time I try to use Find Inactives I get the error FIA-230 (see attached snip).  This is on Chrome version 66.0.3359.139 (Official Build) (64-bit), on Windows 10
![xkit](https://user-images.githubusercontent.com/38862987/39437559-121ffb1e-4c56-11e8-9717-c023f1279e9a.PNG)

**Comment by AprilSylph** [comment]
This is easily solved by changing or resetting the extension's settings. Sorry that some existing settings have been apparently broken by the recent updates! (Leave another comment here if you've already done this).
