### ISSUE TITLE
Cannot get Old Sidebar working on Firefox

### ISSUE THREAD

**Issue by ValensHawke** [new-xkit/XKit#1553]
This one is weird.

Exported my Xkit from Chrome to Firefox, Old Sidebar was not working.

Finally decided to clear my cache, uninstall, reinstall XKit on FF and just install Old Sidebar, nothing else and... it's still not showing up.

**Comment by AprilSylph** [comment]
see #1311 - Old Sidebar is currently completely disabled on all versions of Firefox due to a bug in it pre-Quantum. thanks bumping this, though!
