### ISSUE TITLE
Vanilla Video doesn't replace player until next page is loaded

### ISSUE THREAD

**Issue by akunohomu** [new-xkit/XKit#1575]
My current feed of my own posts consists of  
[10 non-video posts]
[one video post followed by 9 non-video posts]
[other posts]

When the second page is loaded on sidebar, the video post consistently is still using Tumblr's default player even though I have Vanilla Video enabled.

After scrolling far enough to load the third page, Vanilla Videos gets triggered and the one video post is switched to the native, non-Tumblr player.

This probably happens in other circumstances, but I just noticed it and have no time to attempt debugging.

This only began happening today after XKit updated 18 extensions.

**edit**: It seems like Vanilla Video never activates on first appearance of video, only once the next page is loaded.

**Comment by AprilSylph** [comment]
looks to be a problem with the new post listener being too fast - if I delay the VV `check` function by 10ms it works fine on peepr for me
