### ISSUE TITLE
Garbage Collection - huge memory footprint for Tumblr tab process

### ISSUE THREAD

**Issue by Aanok** [new-xkit/XKit#1578]
Hello!
I'm using Firefox 60.0.2, Xkit 7.8.2, Arch Linux.

I've noticed a pattern in Xkit's memory consuption, in that it grows by 50% to 100% from quiescence whenever the tab gets reloaded (it looks like the bigger the RSS at quiescence, the relatively bigger the spike). The spike lasts for an unpredictable amount of seconds (can be 5 or so, can be more than a minute), then the tab goes back to an RSS sensibly lower, but still higher than before the reload and then very slowly lowers further.

I am in no way a web developer, but looking at the performance log (attached) it looks like this is linked to overworked Cycle Collection. In the example session, the RSS started at 1.0GB, spiked at 1.9GB and settled at 1.2GB.

Please tell me if you need further profiling or information!

[Profile.json](https://www.dropbox.com/s/us3q8txolyti1z4/profile.json?dl=0)

**Comment by hobinjk** [comment]
Thanks for the report! This sounds related to https://bugzilla.mozilla.org/show_bug.cgi?id=1371255 which in turn should be helped by https://blog.mozilla.org/addons/2018/08/03/new-backend-for-storage-local-api/

**Comment by Aanok** [comment]
Indeed! I tested with the latest nightly and the behavior went away. There is still a spike (I'm guessing that's inevitable), but it is ~100MB in size and, most importantly, goes away completely in 15 seconds or so with no memory leaks.

Thank you :)
