### ISSUE TITLE
Mutual Checker doesn't work in Firefox

### ISSUE THREAD

**Issue by abbybeths** [new-xkit/XKit#1590]
Uninstalling/reinstalling and resetting settings hasn't done anything. It stopped working a couple weeks (months?) ago, but I assumed tumblr just "fixed" or "improved" something and the devs knew about it. Only just now reporting it because I went to check something in Chrome and realized it works fine there.

**Comment by AprilSylph** [comment]
unable to reproduce on Firefox 61; what other Firefox add-ons do you use?

**Comment by abbybeths** [comment]
![aah](https://user-images.githubusercontent.com/40620520/42070298-b1d2c460-7b23-11e8-9322-13e8cbe52ff5.png)

other add-ons don't seem to be a factor though. I went though and disabled everything but new xkit and all my other extensions but mutual checker and still couldn't get it to work.

**Comment by abbybeths** [comment]
latest development: i reset firefox, reinstalled everything and installed just mutual checker, and it worked. but as soon as i imported my old xcloud data, the same problem. so i'm thinking the data in that file is corrupted somehow?

**Comment by AprilSylph** [comment]
have you tried resetting Mutual Checker? does importing xcloud data on Chrome break it there too?

**Comment by Zaldos** [comment]
(I know this has been here a while) but I also have this issue. I've debugged it up until it calls Xkit Interface is_following. It enters the method with the correct parameters (so not a settings issue) and then it seems the $.ajax call never returns. 
I see no out going or failing calls to svc/blog/followed_by on my dev tools network tab. May be a JQuery isssue?

**Comment by abbybeths** [comment]
> 
> 
> (I know this has been here a while) but I also have this issue. I've debugged it up until it calls Xkit Interface is_following. It enters the method with the correct parameters (so not a settings issue) and then it seems the $.ajax call never returns.
> I see no out going or failing calls to svc/blog/followed_by on my dev tools network tab. May be a JQuery isssue?

So I'm not crazy! It's still an issue for me. I realized after I got the thread reply email that it seemed to only be an issue after a period of time. At one point I reset Firefox after uninstalling XKit completely and it worked for a little while. I must have done something else too, because I did another reset today and it's still not working. 

Really wish I could be more help in figuring it out, but my code, and especially scripting knowledge is pretty much limited to basic design.
