### ISSUE TITLE
Postblock only blocks the one post

### ISSUE THREAD

**Issue by StarChaser** [new-xkit/XKit#1596]
Using xkit 7.8.2, with PostBlock 0.2.5. If I click the 'hands' icon, the post disappears properly... but I still see later reblogs and preblogs. 
(Original post, 69,105 replies. I hit block post on 69,106, that one disappears, but 1-69,105 and 69,107-on are still there.)

**Comment by AprilSylph** [comment]
PostBlock 1.0.0 definitely shouldn't exhibit this behaviour. Were you trying to block posts from peepr (the blog sidebar)? This never worked, but the latest update removes PostBlock buttons there, so attempting to block posts should always work now.

(Closing issue in assumption this can't occur anymore - I'll be sure to reopen it if this still happens for you!)

**Comment by nightpool** [comment]
well it's not called Post**s**Block

**Comment by StarChaser** [comment]
Forgot I'd posted this a year ago. :P Haven't seen anything yet; mostly it was long role-playing things that I was trying to block, and most of those are gone after the Pornocalypse. Will reply again if it still does it later.
