### ISSUE TITLE
tumblr dash won't update

### ISSUE THREAD

**Issue by idkwgo** [new-xkit/XKit#1606]
I'll get the little blue window on the home button saying that new posts are available on my dash, but when I refresh the page the new posts disappear after a few seconds. I've turned off Xkit to check if they're posts I've blocked and they're not.

**Comment by nightpool** [comment]
When you have XKit turned off, do the posts show up? It's possible they're being blacklisted or blocked as promoted or recommended posts (not from people you follow)

**Comment by idkwgo** [comment]
They do. There are even posts from mutuals and things they've reblogged from me.

**Comment by nightpool** [comment]
What extensions do you have installed? Can you do XKit > Other > Export > Export Extension Info for me?

**Comment by idkwgo** [comment]
XKit version 7.8.2
extensions:
   xkit_main: 2.0.0
   xkit_patches: 7.1.1
   xkit_preferences: 7.5.1
   xkit_updates: 2.1.1
   xinbox: 1.9.12
   one_click_postage: 4.4.5
   one_click_reply: 2.1.3
   tweaks: 5.7.1
   go_to_dash: 1.3.0
   postblock: 0.2.5
   mass_deleter: 0.2.1
   show_originals: 1.2.4

**Comment by nightpool** [comment]
show originals is an extension that makes it so only non-reblogged posts
get shown. any posts that are reblogs, even if they're by mutuals or
reblogged from you, get hidden

**Comment by idkwgo** [comment]
i don't know how it got installed 'cause it wasn't me, 

but i love you.

thank you.
