### ISSUE TITLE
Editable Reblogs hiding text saved from last post

### ISSUE THREAD

**Issue by afairlypudgycat** [new-xkit/XKit#1609]
Particularly frustrating as a RPer. 
![image](https://user-images.githubusercontent.com/13837135/43536945-f1a4a5f4-958b-11e8-895c-b959769c453f.png)
How it appears on the dash board.
![image](https://user-images.githubusercontent.com/13837135/43536980-07872ba8-958c-11e8-8f0a-9694e2336ec9.png)
How it appears under editing

**Comment by AprilSylph** [comment]
resolved by #1610
