### ISSUE TITLE
Tag Tracker Not Showing/Correcting

### ISSUE THREAD

**Issue by EssayOfThoughts** [new-xkit/XKit#1620]
I track multiple tags and all, barring one of them, are working without issue. They show me when there's a new post in the tag, and when I go to the tag, the sidebar shows up, and when I leave the tag it shows no new posts.

One tag is not doing this. In this one tag, when I go to look at it, the sidebar does _not_ appear, and when I leave it acts as though those posts are still new and unseen... even when I've had them. All other xkit things seem to load with ease in this tag, its _just_ the tag tracker. My only theory as to what may cause this problem is that the tag in question is four words long - no other tags I follow are this long - but as it stands I have no proof, just a hunch.

**Comment by ThePsionic** [comment]
Issue was resolved on user's end without known fix.
