### ISSUE TITLE
Unable to add images to answers to asks

### ISSUE THREAD

**Issue by ReddPyramid** [new-xkit/XKit#164]
Title says it all, really.  I force updated everything, closed and reopened chrome, and I can't put images in ask responses suddenly.  I don't know if it's another terrifically stupid tumblr update, a bug, or what, but not even trying to paste the image from somewhere else directly into the post box works.

**Comment by nightpool** [comment]
seems to be broken on tumblrs end—I can reproduce this without xkit installed.

**Comment by nightpool** [comment]
can't reproduce any more—seems like tumblr fixed this pretty fast. Closing for now, but make sure to let us know if it keeps happening!
