### ISSUE TITLE
Sidebar now makes main page entirely invisible

### ISSUE THREAD

**Issue by akunohomu** [new-xkit/XKit#1642]
Previously, opening a blog in the sidebar would add a partially-transparent blue overlay (div class `ui_peepr_glass`) over the rest of the page. Staff have changed that to be entirely opaque. A tweak to change the transparency of that overlay would be nice; I certainly prefer the old look.

**Comment by AprilSylph** [comment]
peepr is no longer opaque and `flag--always-opaque-peepr` no longer exists, resolved

**Comment by nightpool** [comment]
we waited it out successfully

**Comment by AprilSylph** [comment]
if only every other enhancement suggestion could be resolved the same way
