### ISSUE TITLE
J/K across pages doesn't always scroll to bottom of page

### ISSUE THREAD

**Issue by inklesspen** [new-xkit/XKit#165]
Versions: Chrome 44.0.2403.130 (64-bit Mac), New Xkit 7.7.0, J/K 1.1.2

I read my dash in chronological order by bookmarking the most recent post I've read, then going to that bookmark and hitting K to scroll toward the present.

However, recently "J/K Across Pages" stopped autoscrolling to the bottom of the page when I'm at the top and I hit K.

Unfortunately, so far it doesn't seem to exhibit this behavior while I have Chrome's developer console open.

**Comment by bvtsang** [comment]
Possibly a duplicate of or related to #60.

**Comment by blackjackkent** [comment]
Closed as dupe.

**Comment by inklesspen** [comment]
I don't think it's a dupe of #60. I experience both problems at different times.
