### ISSUE TITLE
old blue not working

### ISSUE THREAD

**Issue by bluefairykino** [new-xkit/XKit#1657]
really...the title says it all. everything's up to date, the extension is toggled on, but it isn't working. its still the new, eye-piercing colors.

from what i've seen, i'm not the only one experiencing this, either.

**Comment by nightpool** [comment]
Hey, thanks for filing! We're aware of the issue and are working actively
on a fix.

I'll let you know when we have further updates.

**Comment by nightpool** [comment]
This is fixed in old blue 0.1.0! writing a blog post about it now
