### ISSUE TITLE
styling problems with panorama extension

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#166]
currently the following page parts are still broken in panorama:

 - ask posts:
  ![](https://cloud.githubusercontent.com/assets/233815/9140952/960374a6-3cfa-11e5-9ce5-4880cdb67d52.png)

 - the tumblr scrolling footer
  ![](https://cloud.githubusercontent.com/assets/233815/9140969/b7a6c072-3cfa-11e5-9b78-8e9e6b5f279f.png)

**Comment by ThePsionic** [comment]
Has been fixed by #161 in the meantime.
