### ISSUE TITLE
Retags is hard to style because of !important

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#170]
From an ask:

> This isn’t very broken shit, but I didn’t know how to send it to you. I saw that you got it so retags show up on your actual blog, WHICH IS GREAT!! But you have the color set to !important… so it wont let me style it… I would appreciate if you could remove the !important tag if that is possible. I don’t actually know how this works, but yea! Thanks for doing this. Its great to have xkit back. ♥

I vaguely remember this coming up in the PR discussion. Ideally we don't need !important on our own styles, thoughts?

**Comment by nightpool** [comment]
they could just use a more specific selector then we do *and* include
important :D

i think that important is there for a reason, its the only style with
important on it in the entire file. I'll take a look.

**Comment by bvtsang** [comment]
According to [a previous discussion](https://github.com/new-xkit/XKit/pull/161#discussion-diff-36537720), we put on `!important` when we know we're overriding Tumblr's styles to future-proof our code.

However, the Retags extension creates its own [HTML and classes](https://github.com/new-xkit/XKit/blob/master/Extensions/retags.js#L121), so in this case it might be okay to remove `!important` -- except from [tags in notifications](https://github.com/new-xkit/XKit/blob/master/Extensions/retags.css#L60), which I believe uses CSS from Tumblr.

**Comment by nightpool** [comment]
important is there to override a specific tumblr selector it would be unwieldy to try to override in normal ways. 
![image](https://cloud.githubusercontent.com/assets/233815/9148928/4c6f86ca-3d56-11e5-98dc-c33b6f5560aa.png)

(vs. `div.retags a`)

maybe we can add a specific check to turn this off for on-blogs? I would check but for some reason I can't get retags to render on blogs on my dev profile (but it works fine normally??)

**Comment by hobinjk** [comment]
Another person has commented
>Hi guys. I'm sorry if this comes off as rude, but the retags look really ugly on someone's blog if they have text transform uppercase, because retags is coded with a 12px font size. So might I suggest to add a text transform none and reduce the font size to 10px? or at least have the font size be inherited from the persons blog?

(only tangentially related, but probably not worth a separate issue)

**Comment by WyohKnott** [comment]
I don't get that bug report, the retags only work on the Activity page and Notifications popup, what does it have to do with the style of one's blog? Isn't this related to Themes+?

**Comment by blackjackkent** [comment]
They work on certain on-blog themes I think -- depending on whether the theme uses one of the relevant classes (.reblog, .is_reblog, or .notification_reblog) in its notes display. cf. http://blackjackkent.tumblr.com/post/126256255852/i-didnt-know-you-danced-i-did-once-in with the extension activated.

**Comment by dlmarquis** [comment]
@nightpool Atesh seems to have added !important to all his styling indiscriminately, and some of us here have followed his example because hey, it worked for him. It probably won't break things to remove most if not all the !important markers.

**Comment by AprilSylph** [comment]
> they could just use a more specific selector then we do *and* include
important :D

correct. this is a non-issue, closing
