### ISSUE TITLE
Chrome scrubs responseText?

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#1709]
Steps to reproduce:
Open TagViewer on a post, get flooded with

```
xkit/tagviewer.js:169 tagviewer -> Can't parse JSON at https://api.tumblr.com/v2/blog/dandeedann/posts/info?api_key=5CIOyjHfcrNFlyEJl2D7vnoDTYqV30lNAUaSd4LJKoBFOZOmxp&id=186554458029 -> Unexpected end of JSON input
```

response.responseText is the empty string, this also happens in Retags with similar output. This does not happen in Firefox

**Comment by hobinjk** [comment]
Also appears to be failing in 7.8.1 so this might be extra interesting

**Comment by AprilSylph** [comment]
is this still happening?

**Comment by hobinjk** [comment]
I didn't see this during any of the testing surrounding #1710 so it's probably yet another weird intermittent bug
