### ISSUE TITLE
New Extension Feature Request: EXIF Data Protection

### ISSUE THREAD

**Issue by foreveranon** [new-xkit/XKit#1716]
I don't know if it's possible, but if it is, I'd like to request a new feature to help protect user GPS data from being uploaded when uploading images.

I don't know a lot about it, but I know that Tumblr [apparently doesn't strip EXIF data from image uploads](http://www.gpsfortoday.com/what-social-networks-protect-your-exif-and-gps-location-data-from-other-users/), which can reveal a user's GPS data when uploading images? Which is obviously a huge privacy concern, especially if anyone uploads an image taken at their own house. I tried to use [this project here](https://github.com/sztupy/tumblr-exif-check) to verify whether I had any images which exposed my location, since I've uploaded a lot of pictures of my cats, but I couldn't get it to work.

So my requested feature would have two parts:
1. The ability to scan any of my blogs for any images I've uploaded (whether as a photo post or as an addition to another post) which have GPS data attached to them and provide me a list of problem posts for me to delete or (if reblogged) message Tumblr support about. (For privacy reasons, you'd obviously want to limit this only to the user's own blogs)
2. A warning whenever I try to upload a photo on desktop if the image contains GPS data

I don't know how much work I'm asking for, or how doable this is, but it seems like a really useful feature to help protect privacy from Tumblr's really, really bad decision.

Thanks so much for your time.

**Comment by nightpool** [comment]
Looks like that article is from 2012. to the best of my knowledge, Tumblr now thoroughly strips all location-sensitive information from uploaded photos, but I'm down to do more research

**Comment by foreveranon** [comment]
If you could, that would be a huge relief. I'm hopeful that Tumblr now strips all location-sensitive information, but I don't know if it did it retroactively, and I started uploading photos a long time ago. Thank you so much!

**Comment by foreveranon** [comment]
Were you able to make any headway into your research? I tried to contact Tumblr support to ask about it but they have not given me much in the way of answers, by which I mean anything

**Comment by AprilSylph** [comment]
i hit up tumblr support, and engineering has confirmed that exif data is stripped, save for a few select fields for displaying on themes; none of these fields betray location

my support ticket:

> Hi, I have a technical question regarding the upload of images to Tumblr. I understand if the information is not available to you, or is difficult to obtain.
> 
> I know that some EXIF data is kept on photos uploaded to Tumblr, for the sake of displaying it on themes that support it. I also know that unprocessed images are now inaccessible to the public, since around August 2018.
> 
> My question is, exactly what EXIF fields are kept when an image is processed? I enjoy that Tumblr doesn't treat location data as a feature (unlike Twitter), but would love to be reassured that location data is actually scrubbed on Tumblr.
> 
> (This is assuming that EXIF fields are kept via a whitelist process, rather than a blacklist process; let me know if I'm wrong!)
> 
> Thanks for reading!

replies from tumblr support:

> Hey April,
> 
> Thanks for reaching out. Hope you're doing well!
> 
> I know we keep EXIF data relating to an image's color profiles, but let me get with someone from Engineering to see if we retain anything else. I'll let you know what I find out.
> 
> Best,
> 
> Kat

> Hi April,
> 
> Your question led to a really great discussion today, and I got some answers for you.
> 
> We retain the following fields: 
> ‘Time’
> ‘FocalLength’
> ‘FocalLength35mmEquiv’
> ‘Aperture’
> ‘ExposureTime’
> ‘ISO’
> ‘CameraMake’
> ‘CameraModel’
> ‘Lens’
> ‘SensorWidthMM’
> 
> Those are for use on the web-facing blog via the theme (`{block:Exif}`), like you mentioned. They can also be viewed if you're using the old dashboard.
> 
> We're going to be updating our Help Center ([this article](https://tumblr.zendesk.com/hc/en-us/articles/231453828-Photo-posts), probably) with this information in the very near future, so thank you for bringing it up!
> 
> Let me know if you've got any other questions.
> 
> Best,
> 
> Kat

**Comment by nightpool** [comment]
Possibly still useful to strip this info for fingerprinting purposes? I
don't know how much information this gives—maybe only a couple of bits for
more common cameras, maybe less than that for less common cameras. I wonder
if anyone's done studies on this.
