### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by MissSoulful** [new-xkit/XKit#1733]
After seeing a few errors, I was trying to see what was up on my end and saw this? I'm not too sure if this is on my end or not, but I figured I should post something at least.
![image](https://user-images.githubusercontent.com/56238244/66277621-61fc3800-e85e-11e9-9962-fb721a742b49.png)

**Comment by AprilSylph** [comment]
is this something that's happening repeatedly? we aren't seeing storage failures from anyone else, and a quick search for "Extension context invalidated" suggests to me that you just need to reload the page after the core extension has been auto-updated?

**Comment by MissSoulful** [comment]
I only noticed this today, after I was unable to reblog anything. 
I've tried updating xkit, as well as resetting, cleared those errors from the log, and a few new things came up on the log. I figured I should share those and what pops up when I try to reblog something. Should I try removing the extension from chrome and re-adding it?
![image](https://user-images.githubusercontent.com/56238244/66282874-5c164f00-e87e-11e9-9567-1834cf8f0215.png)
![image](https://user-images.githubusercontent.com/56238244/66282977-d8109700-e87e-11e9-83b5-e8eb48aedc0e.png)
![image](https://user-images.githubusercontent.com/56238244/66283012-f7a7bf80-e87e-11e9-95e7-24d15b9cdeb8.png)
![image](https://user-images.githubusercontent.com/56238244/66283032-08583580-e87f-11e9-9abc-2e4dcdc4c41c.png)

**Comment by AprilSylph** [comment]
the errors about the `applications` key and synchronous XHRs aren't really something to worry about since they're only warnings and not exceptions. OCP01 is an unrelated error - it means that the response when fetching a post is `HTTP 401`, which almost always means that you're blocking/disallowing referer headers on Tumblr
