### ISSUE TITLE
Gifs loading as .gifv files

### ISSUE THREAD

**Issue by Distelhawk** [new-xkit/XKit#1735]
Gifs in gifsets or posts suddenly aren't saved as normal .gif files anymore, but as .gifv. Which means downloading or copying them into a new post is either a pain (removing the v by hand each time) or doesn't work at all (even with the v removed and it saying it saves as .gif, the gif still won't let itself be uploaded). 

Any chance for a fix? 

I know the problem is widespread as in my group, most people have reported the issue at this point. 

Thanks x

**Comment by AprilSylph** [comment]
We can't change how Tumblr handles uploaded media. That's done on the backend, where we have no power.
