### ISSUE TITLE
Bug Report - Mass+ 

### ISSUE THREAD

**Issue by Mormia** [new-xkit/XKit#1739]
Add-on named Mass+ is does not show all shared post on archive history,  just show some stuff.

For example;
If there are 405 posts on May 2017, there will be 150-200 posts they appear on Mass+.

**Comment by AprilSylph** [comment]
Mass+ does not power the Mass Post Editor, and is not responsible for displaying posts. This is a bug with a Tumblr feature, so it should be reported to [Tumblr support](https://www.tumblr.com/support).
