### ISSUE TITLE
Forced Update Overlay Sitting There for 20+ Minutes

### ISSUE THREAD

**Issue by ZaCloud** [new-xkit/XKit#1746]
Hello. On Nov 18, my Tracked Blogs all returned Error messages. Today when I opened tumblr, I get an overlay that says Forcing Extension Updates, telling me to wait on that page for the process. Well, it's been over 20 minutes and it hasn't budged. :/ There's also error messages in the corner saying that it can't reach the New XKit servers to update because I have an "old and buggy version" installed. That seems pretty bad. I mean, if the problem is I have an old version, but it won't connect, how can I update to a new version? I haven't saved my settings too recently onto the cloud (because every time I try, it says there's not enough space due to pages I saved in the Save For Later extension (I don't remember if that's the name of it). I never knew if it saved anything at all, or just skipped the Save For Later pages, since it never seemed to make that clear.

So I'm worried that I'll lose all my settings if I uninstall/reinstall the browser extension.

Is there another solution? What happened to trigger this strange occurrence?
![buggy xkit](https://user-images.githubusercontent.com/5414712/69214989-6cd10a80-0b36-11ea-8820-3e703c428fbd.PNG)

**Comment by ZaCloud** [comment]
I checked the extension properties (still in Chrome on desktop, Windows 8.1.... Is it supposed to say Firefox in the update thingie???). Here's a list of errors it captured:

![xkit errors](https://user-images.githubusercontent.com/5414712/69216135-6728f400-0b39-11ea-8927-35f53672a59d.PNG)

**Comment by AprilSylph** [comment]
you should be able to fix this by going to the "Site access" section of New XKit's Chrome settings (chrome://extensions/?id=inobiceghmpkaklcknpniboilbjmlald) and enabling all the sites

**Comment by nchristiny** [comment]
@AprilSylph Thank you, this worked for me.

**Comment by ZaCloud** [comment]
I had to un-checkmark/re-checkmark things, and restart the browser, but it finally works, thanks. :)
