### ISSUE TITLE
Editable Reblogs Erases Text

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#176]
From an ask:
> If there is a blank spot underneath something you reblog, it will erase everything above it. It's to the point where ya just gotta backspace the spaces away every single reblog. My followers are noticing this problem as well, and it's only happening to those with xkit. It's getting out of hand. =(

**Comment by blackjackkent** [comment]
I can work on this later tonight.

**Comment by bvtsang** [comment]
you never saw that

**Comment by blackjackkent** [comment]
I've tried this on Chrome and Firefox and am having trouble reproing so far. =/

**Comment by blackjackkent** [comment]
Two other people have confirmed we can't figure out how to reproduce this; closing until/unless we get further reports.

**Comment by WyohKnott** [comment]
@hobinjk  Can you put a small notice above the Ask box of the blog, like "please include your browser version"

**Comment by hobinjk** [comment]
@WyohKnott Done! I also told people to specify OS and the output of the extension version button. Whether they do it is up to them

**Comment by rimbaum** [comment]
I have a friend who got this problem. They're using Chrome 44 in Windows 10. Their extension configuration is here: https://gist.github.com/56004db053909da37751

**Comment by blackjackkent** [comment]
Even with those extensions installed I'm having no luck reproducing this. Can you ask your friend to submit a bug request with the specific steps/post content that causes the problem to occur? Thanks. :)

**Comment by rimbaum** [comment]
@blackjackkent I know for a fact it happened when they reblogged a post with extra small text, I'll ask them for more details beyond that. I'm not sure it happened with regular text size.
