### ISSUE TITLE
Editable Reblogs posting error

### ISSUE THREAD

**Issue by nigelcolbie** [new-xkit/XKit#1760]
Attempting to edit a previously reblogged post, I was able to edit the text, but upon attempt to save it came up with the error code attached. I'm currently running it on the desktop version of the Firefox mobile app for Android as well. I'm unsure if the main desktop version has been doing the same thing.
![Screenshot_20200224-174413_Firefox](https://user-images.githubusercontent.com/61437648/75197907-576b0e00-572d-11ea-8ae3-c294c9f0cce9.jpg)

-----------

```
[object Object]
```

System Data |   
----------- | -----------
ER Version | 3.3.10
user | cowboyshvt
body | <br><p><span><a href="https://mattjackson-yb.tumblr.com/post/610869487720349696">mattjackson-yb</a></span>‌:</p><blockquote>It’s Monday.&nbsp; And not dumb at all.</blockquote><p>Ah cool okay, I'm right in avoiding Twitter then cool.</p>
User Agent | Mozilla/5.0 (X11; Linux x86_64:68.0) Gecko/20100101 Firefox/68.0
XKit Version | 7.9.0
Patches Version | 7.2.12
Extensions | xkit_main, xkit_patches, xkit_preferences, xkit_updates, xinbox, one_click_postage, one_click_reply, tweaks, xcloud, go_to_dash, editable_reblogs
URL | https://www.tumblr.com/edit/610882808610750464

**Comment by AprilSylph** [comment]
this is probably due to the tumblr change for post IDs today! sorry i didnt catch this with my initial patch!
