### ISSUE TITLE
Read More Now doesn't handle previous replies correctly

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#177]
> Hi! I couldn't see this on the 'broken shit' section, apologies if it's there! When reblogging a reply that's been hidden under a 'Keep Reading/Read More', the previous reply disappears in the reblog screen and I'm having to paste the last reply in before I do my own. I think this happens pretty much every time if the last reply has been hidden under a cut.

**Comment by WyohKnott** [comment]
Might be related to this: we need to prevent ReadMore to run on Reblog/Edit popup. Currently if one use Editable Reblog, it will copy the HTML of the Read More button, which contains not allowed <div> tag.
Hence it might be related to what I was mentioning here https://github.com/new-xkit/XKit/issues/89#issuecomment-129143674
