### ISSUE TITLE
all XKit extensions broken on new Tumblr dashboard

### ISSUE THREAD

**Issue by Randomfacts137** [new-xkit/XKit#1770]
In just the past day or so, the Tumblr dashboard no longer receives the effects of XKit. Every other page continues to work just fine.

Effects of the error:
- The XKit icon no longer appears
- No effects of any XKit extensions are visible

This occurred on Google Chrome 80.0.3987.149 and persisted through both forced update of XKit and forced update of all extensions.

**Comment by nicolaab** [comment]
I'm experiencing the same issue on Firefox.

**Comment by AprilSylph** [comment]
https://new-xkit-extension.tumblr.com/post/613164737228832768/

**Comment by bifa2** [comment]
Under Chrome `80.0.3987.163` and `81.0.4044.113` I'm seeing the same/similar - timestamps and mutuals checker aren't working. The XKit icon does appear, though I'm pretty sure I'd noticed it not appearing recently. 

Can confirm that selecting to use the old dashboard fixes this.

**Comment by AprilSylph** [comment]
Browser version is irrelevant to this issue. The new dashboard is essentially an entirely different website, which individual parts of XKit must be updated for.

So far, only XKit Preferences, One-Click Postage and Old Blue have been updated.

**Comment by IceDevice** [comment]
I'm having this problem, too. The Xkit icon is there, you can interact with the menus, but none of the features are working. Postblock, Timestamps, No Recommended, Headers. None of them work. The Inbox features still seem to work, but that's because it wasn't affected in the Tumblr Update.

**Comment by AprilSylph** [comment]
issue now properly tracked at #1802
