### ISSUE TITLE
TagViewer Not Working

### ISSUE THREAD

**Issue by IceDevice** [new-xkit/XKit#1785]
TagViewer has stopped showing up, seemingly due to the latest Tumblr update. Updating and re-installing the extension have not worked.

**Comment by AprilSylph** [comment]
TagViewer has been replaced by a vanilla Tumblr feature, "Tag Crawler", which was previously a Labs feature. To view tags on a post, open the notes of a post and click the hashtag button!

closing as duplicate of #1770
