### ISSUE TITLE
Is there a way to hide the number of new dashboard posts on firefox's tabs?

### ISSUE THREAD

**Issue by esotericDisciple** [new-xkit/XKit#1795]
I'm able to block the element for the site's home icon, buy it still shows on the tab/window title...

**Comment by esotericDisciple** [comment]
Never mind, I didn't believe that there were working [addons](https://addons.mozilla.org/en-US/firefox/addon/tab-retitle/) that could do that...

**Comment by AprilSylph** [comment]
Tweaks has the option "Hide the new post bubble when you are not in dashboard", which hides the new post bubble and periodically resets the tab title when not on `/dashboard`. Also, the new dashboard doesn't ever change the tab title.
