### ISSUE TITLE
One-click reblog won't send posts to drafts

### ISSUE THREAD

**Issue by rimbaum** [new-xkit/XKit#180]
This is kind of an important thing to a lot of roleplayers on tumblr, and I and at least one of my rp partners have run into this. The post shows as drafted successfully, the reblog button turns green and stays green on a refresh, but the post never shows up in drafts.

Can't tell you about the setup for other people, but I'm running Chrome 44 on Linux Mint 17.2 (64-bit).

**Comment by nightpool** [comment]
Hmm works for me? Can you paste in your extension information? (From
Xkit>Other>Export Configuation>Extension Info)

**Comment by rimbaum** [comment]
@nightpool https://gist.github.com/cec4a213b333c9ccfdf5

**Comment by nightpool** [comment]
Okay, great I'll see if I have time to take a look tomorrow. Can you find
someone else that has this issue and get them to put their extension info
here too? It really helps when I can narrow down how many extensions I have
to test :D

**Comment by nightpool** [comment]
Question—does the "Saved as a draft on <blog name>" popup show up when you
click on the save as draft button?

**Comment by rimbaum** [comment]
Weird... I tried it again and then both drafts it said I had saved suddenly showed up. Must've been a tumblr thing.

**Comment by blackjackkent** [comment]
Just to confirm -- this is no longer an issue?

**Comment by rimbaum** [comment]
@blackjackkent It doesn't appear to be. I'm chalking it up to something on Tumblr's end.

**Comment by blackjackkent** [comment]
Okie doke. :) Closing then. Thanks!
