### ISSUE TITLE
Missing Pencil

### ISSUE THREAD

**Issue by justwannawrite** [new-xkit/XKit#1800]
Editing pencil is missing on the left-hand side when reblogging posts which means they cannot be edited. Was working perfectly fine earlier then it suddenly vanished out of nowhere (nothing else was changed). Updated Editable Reblogs but it didn't do anything.
![missingpencil](https://user-images.githubusercontent.com/63948167/79682462-8020f880-81f0-11ea-80a6-b3d26406b24b.png)

**Comment by AprilSylph** [comment]
Are you using the new dashboard? The reblog prompt looks the same, but the rest of the dashboard doesn't. For example, on the new dashboard, posts have a menu accessible from the top-right corner, and the "Change palette" option is available in the account menu.

(Editable Reblogs hasn't been updated for the new dashboard yet, so won't work when using it)

**Comment by justwannawrite** [comment]
Nope. Using the Old Dashboard option

**Comment by justwannawrite** [comment]
might've been a glitch since it just popped back up. Is that happening from time to time with the whole changeover?

**Comment by AprilSylph** [comment]
This is the first report of this happening on the old dashboard since the new dashboard's launch. Editable Reblogs has always seemed to have intermittent issues, however.
