### ISSUE TITLE
One-Click Postage pulls up past tags (like suggested autofill)

### ISSUE THREAD

**Issue by kallistoi** [new-xkit/XKit#1840]
i've noticed today that when i start typing tags on auto-tagger, a bunch of what look like autofill suggestions pop up underneath. it seems like it's recorded every tag combo i've used today and brings them up like suggestions, and i'm worried that the longer i continue to use auto-tagger the longer the suggestion list is going to get. here's an example screenshot:

<img width="519" alt="Screen Shot 2020-05-31 at 2 11 47 AM" src="https://user-images.githubusercontent.com/66196132/83345916-119e8280-a2e6-11ea-9b1a-bcffa65c9796.png">

it's only started happening to me today so i was wondering if it's a new feature, but i haven't been able to figure out how to disable it if so. i brought it up on the support server and someone said chrome users (i also use chrome) have been reporting similar things and it might be a browser issue, so i wanted to log it here in case there are any updates.

**Comment by AprilSylph** [comment]
reproduced on Chromium 83.0.4103.61, looks like it should be a one-line fix
