### ISSUE TITLE
Enhanced Queue form-key reordering

### ISSUE THREAD

**Issue by frapbod** [new-xkit/XKit#1845]
Hey wasn't sure where to put this question but did your team hear anything from the developers about switching auth for queue reordering?

I stole your method of shuffling the queue with the form-key for some python script I have, which of course stopped working after the update. I noticed the request now sends different params as well as a Bearer <token>  which I'm pretty sure is oauth2 but the api hasn't been updated to mention anything of the sort. 

Good chance I just don't know enough to know what to look for but was hoping you all heard anything before I try digging deeper.

**Comment by AprilSylph** [comment]
correct, the new dashboard uses the official API now, and is authenticated with OAuth - I assume it's OAuth 1 though, as per the docs.

unfortunately i don't know how to externally piggy-back off the authenticated dashboard; Tumblr has built the `tumblr.apiFetch` javascript method for us to use on-page to make authenticated API calls, so reverse-engineering how to make them hasn't been necessary for us.

also, this type of question is best directed to our Discord server in the `#general` channel.
[FAQ: I have another question. Where can I get answers?](https://github.com/new-xkit/XKit/wiki/FAQ#i-have-another-question-where-can-i-get-answers)
