### ISSUE TITLE
Issue with multiple "Keep reading" links

### ISSUE THREAD

**Issue by albinakarambura** [new-xkit/XKit#185]
I noticed something after I reblogged a post with a "Keep reading" cut and put my response in the "Keep reading" link too.

This happens if you click the second Read More Now! button first.
![readmore1](https://cloud.githubusercontent.com/assets/1273206/9156079/069bf0c0-3ed7-11e5-8312-e236088b2e3c.gif)
The first Read More Now! button just disappears.

This happens if you click the first Read More Now! button first.
![readmore2](https://cloud.githubusercontent.com/assets/1273206/9156113/1bc021dc-3ed8-11e5-906e-6f39c3079848.gif)
Clicking on the first button works fine, but when you click on the second it seems like you haven't clicked on the first one at all. And the first Read More Now! button disappears like in the first case.

I think it would be nice to make it possible to read what's under each "Keep reading" link at the same time on the dashboard. Make it so what's already retrieved by the first button doesn't disappear after clicking on the second one. And if you start with clicking on the second one, make it so the first button itself doesn't disappear.

Maybe the extension needs to count how many "Keep reading" links there are in a post?

**Comment by WyohKnott** [comment]
Actually I have a Pull Request from a few hours ago that is supposed to fix that:
https://github.com/new-xkit/XKit/pull/183 (needs review)

Thanks for the report!

**Comment by albinakarambura** [comment]
@WyohKnott, I don't use Editable Reblogs, so it can't be the issue of them conflicting. And I don't have any issues with making the posts or reblogging them.

To me it seems like "Read More Now" extension just exits after retrieving the content under the cut and hides not only the clicked button, but all the previous ones too.

**Comment by hobinjk** [comment]
Yes, this makes sense as a consequence of how Read More Now inserts the HTML (it inserts the html and doesn't process it for Keep Reading links). I have a fix for this completed and will be PRing it soon.

**Comment by ThePsionic** [comment]
@hobinjk any progress on this?

**Comment by gloomykid** [comment]
I also wanted to add up (even if this is old a/f) that the read mores do not work at all in drafts/private/queue mode. only on the dashboard... 
which is a little pesky for RPers who draft threads and want to read them again later... 
I hope this can get a fix too?!

**Comment by nightpool** [comment]
@gloomykid Can you make a different issue? thanks!

(is this only with editable reblogs enabled? If so, then we're aware of that issue and are working on it as fast as we can, although you may also experiencing #519—check to see if you have FixMyPosts enabled, and disable it if possible)

**Comment by gloomykid** [comment]
@nightpool sorry for not opening a new issue! And yes I'm experiencing both, I'll see about the FixMyPosts thing, I wasn't even aware this was a thing. Thanks!

**Comment by nightpool** [comment]
@gloomykid I misread your comment—there's be a bug with some subset of editable reblog users that breaks *creating* read mores. (not read more now buttons—they can't create any read mores at all, it just shows up as [[MORE]] and the rest of the text rather then the keep reading link)

I assumed you were talking about that issue. I've left a comment on the new issue with more thoughts.
