### ISSUE TITLE
Old dashboard toggle gone

### ISSUE THREAD

**Issue by pingo1387** [new-xkit/XKit#1862]
With the newest update, the toggle to switch back to the old dashboard under dashboard settings is gone. Several other people have had this problem as well.

**Comment by fkaempath** [comment]
there is no going back to the old dashboard , the dongle is gone because the update for the new dashboard has been pushed through .

**Comment by beccasafan** [comment]
The toggle to switch back to the old dashboard was Tumblr functionality, not New XKit.

With the latest update, the new dashboard has been fully rolled out to everyone, so the toggle has been removed.

There is no way to switch to the old dashboard. A way to switch back to the old dashboard is not something New XKit can add.

**Comment by pingo1387** [comment]
@fkaempath dang, really? that's problematic for me. the new dashboard randomly doesn't show me some of my drafts and i'm unable to view the queue. any idea if xkit will have fixes for this in the future?

**Comment by pingo1387** [comment]
@beccasafan the dashboard toggle only existed if you had xkit installed, though. it wasn't there for me until i installed xkit.

**Comment by nightpool** [comment]
@pingo1387 If drafts or your queue aren't showing up, that's not something XKit can fix. Please contact tumblr support!

**Comment by nightpool** [comment]
The toggle for the old dashboard was, weirdly, Tumblr native functionality that they offered only to people that used New XKit. I found it a little weird that they chose to do it that way personally, but ¯\\\_(ツ)_/¯

**Comment by pingo1387** [comment]
@nightpool oh! i see. i forgot xkit and tumblr were working together. thanks for the info, everyone, i'll keep working on the drafts and queue issue :P
