### ISSUE TITLE
Bug: "No Recommended" breaks 'k' scrolling

### ISSUE THREAD

**Issue by gostaks** [new-xkit/XKit#1863]
Sometimes hitting 'k' while scrolling the dashboard will bring you to the top of the page rather than moving 1 post up. After some investigation, here's what I've figured out: 
- The issue typically only appears after scrolling 3-4 pages (infinite scroll), but once it's active it persists through a soft refresh. 
- I went through all of my new xKit extensions and the 'k' glitch only occurs when 'no recommended' is active (deactivating + refreshing the page fixes, reactivating + refreshing breaks it again). 
- I've replicated this issue in both Chrome and Firefox. 
- Forcing an update of 'no recommended' does not currently fix the issue.

In case it helps, I'm running Firefox 77.0.1 (64 bit) and Chrome Version 83.0.4103.116 (Official Build) (64-bit) on a 2011 MacBook Air.

Thank you so much for all the work you do for new xKit!

**Comment by marcustyphoon** [comment]
I copied some code from the no recommended extension in order to hide a larger quantity of posts and had the same problem with much higher frequency, so I think this is probably caused by the "previous" post that the k key should jump to being hidden via `$this.hide()`.

**Comment by nightpool** [comment]
instead of using .hide, i think we can probably do something like height:
0; overflow: hidden to work around this issue
