### ISSUE TITLE
Classic Search removes tracked tags from search bar, confusing to users

### ISSUE THREAD

**Issue by nobodysuspectsthebutterfly** [new-xkit/XKit#1874]
I didn't know whether to label this as a bug, as the new-dash-updated Classic Search is working as intended, hiding the tracked tags from the search bar as it always has -- but unfortunately since Tag Tracking+ isn't working on the new dash yet, it makes followed tags inaccessible, confusing users who don't know why they're gone. Any way to update the extension to not hide them? Or post some sort of public notice warning people? Especially since the search bar tracked tags now link to /tagged/tag instead of /search/tag . Thanks!

**Comment by AprilSylph** [comment]
i think a warning is in order for the time being

**Comment by AprilSylph** [comment]
just noticed there's an actual solution to this: while we clone the `form` without events to replace tumblr's `onSubmit` event on it, the tracked tags dropdown is actually attached to the contained `input` - if we clone tumblr's `input` with events and replace the event-less classic search `input` with it, Classic Search should work and still allow viewing of tracked tags!
