### ISSUE TITLE
Avatars are placed wrongly in the post's body when using function to stop them from scrolling (Tweaks). 

### ISSUE THREAD

**Issue by nautiscarader** [new-xkit/XKit#1877]
A few days ago, I submitted a bug that the avatars are still scrolling, even if that option is disabled in the tweaks. The good news: they no longer scroll!

The bad news: they kinda slide into the post's body now.
![avatar2](https://user-images.githubusercontent.com/67703250/86492318-0b307a00-bd6e-11ea-9f1c-09bbeef225ea.jpg)
But they don't scroll, so there's that.

Just to be sure, i tried disabling other New Xkit extensions, one by one, to see if that fixes avatar's place, up to no avail. I disabled ublock too, and nothing.

**Comment by AprilSylph** [comment]
we're working on this right now!

**Comment by nautiscarader** [comment]
That was fast, thanks :)
