### ISSUE TITLE
Dashboard unreachable in Chrome

### ISSUE THREAD

**Issue by kijikun** [new-xkit/XKit#188]
My dashboard is unreachable with the new xkit installed on chrome as for ten minutes ago. Tested in IE and had no issue.

Chrome is giving this error: ERR_SPDY_PROTOCOL_ERROR

**Comment by kijikun** [comment]
Welp it resolved itself!

**Comment by nightpool** [comment]
disable the new xkit extension and see if the problem persists.

**Comment by kijikun** [comment]
The issue seems to have resolved itself.
