### ISSUE TITLE
Dashboard pages disappeared

### ISSUE THREAD

**Issue by mandzor** [new-xkit/XKit#1884]
Clicking through to the next page of the dashboard no longer sends you to tumblr.com/dashboard/2 etc, every page you click through to remains tumblr.com/dashboard making refreshing or bookmarking your place via your web browser impossible

**Comment by nightpool** [comment]
This isn't an XKit bug, and while we're looking in to possible solutions, it's not something that's easy for XKit to fix. Please contact tumblr.com/support and give them your feedback on the new pagination.

**Comment by beccasafan** [comment]
This is a change on Tumblr's side. It's not something XKit can do anything about. You can reach out to Tumblr Support.
