### ISSUE TITLE
Find Inactives should provide an Unfollow button

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#189]
From an ask:

> When you have the extension for finding inactives, can there be an option to unfollow them? just keep going through and unfollowing them on that pop up screen instead of opening up each blog? c:

**Comment by Wolvan** [comment]
Actually, that was suggested to xenix and he said that he doesn't want that to happen

**Comment by hobinjk** [comment]
It sounds like a logical feature to have. What's the reasoning behind complicating the flow?

**Comment by Wolvan** [comment]
I know that it does sound like a logical feature, just wanted to point out that this was something xenix never wanted to happen. I think his concerns were similiar to the mutual followers/unfollower tracker but I can't fully remember them. I think it was something like he doesn't want to give mass unfollowing tools because he doesn't want the feature abused

**Comment by hobinjk** [comment]
That's a good justification for not having it. Thank you for explaining! I'll close this and leave it for the next time this comes up.

**Comment by ChuckL** [comment]
We discussed this a bit in chat and we're thinking of opening this back up.  Unfollowing blogs is already a feature on that page, we're just filtering the blogs for the user.  The extension would still require user input for each blog.

If anyone thinks this is a bad idea we can discuss it more.  I'll reopen this and start dev this weekend.

**Comment by ThePsionic** [comment]
@ChuckL any progress on this?

**Comment by ChuckL** [comment]
Not much, I've added the button in but haven't hooked it up to the JS yet.
I think I'll probably just shelve this one.  I have an idea for a better followers extension thing that I may play around with.

**Comment by AprilSylph** [comment]
Resolved by #1429
