### ISSUE TITLE
old blue lays over tweak for notification badge style, changes badge colour

### ISSUE THREAD

**Issue by isthisrubble** [new-xkit/XKit#1895]
I noticed this when using the "old red" option, but it does it to the white option too. I guess there is a grey overlay on the header menu within old blue, and it goes over the notification badge.

with the white option it's not too noticeable, but with the red one it's very obvious. looks more like orange than red.

this is what it looks like on the dash: ![image](https://user-images.githubusercontent.com/67852765/86526510-27502a80-bed8-11ea-9451-a9235f984780.png)

this is what it looks like on my inbox page, which is still using the old code: 
![image](https://user-images.githubusercontent.com/67852765/86526521-51095180-bed8-11ea-9a72-cef03a180423.png)

(sidenote the header buttons are a slightly different grey from one to the other, too, but that might be unrelated)

**Comment by invalidCards** [comment]
The new Tweak does not **perfectly** recreate the old red style of header icons. It uses the red colour variable that is provided by Tumblr's CSS, which may chamge depending on dashboard theme. The term "Old Red" was chosen to easily denote the use of a red background with a white text colour.

**Comment by isthisrubble** [comment]
Sorry, I guess I didn't explain it very well:

When JUST the tweak is enabled, the red is the old-style red in 5/6 of the tumblr palates (cybernetic is the outlier). When the tweak AND old blue is enabled, all of 6 of them have an orange badge. Even with cybernetic's different red colour variable, you get the same orange. To me that says old blue is causing the colour to look different, not the new tweak.

As a non-coder I understand the extensions as layers on top of the dashboard, and was wondering if you could put the tweak layer on top of the old blue layer instead of underneath. That analogy is probably bad, though.

**Comment by invalidCards** [comment]
Thanks for the clarification. I'll take a look at the exact cause of this later today and report back when I've found something 😄

**Comment by invalidCards** [comment]
It is as I suspected - Old Blue has the orangey-red assigned to the "red" colour in Tumblr, because that's the colour of red that was used across the site when Old Blue was created (such as in the "Photo" button at the top of the dash when creating a new post). I think the solution here is to create a new notification badge style in Tweaks that is *always* the correct red independent of what theme is being used on the dashboard.

**Comment by invalidCards** [comment]
@isthisrubble Tweaks 6.0.8 includes an option for Old Red (Always red) in the notification badge style dropdown that should keep the button red at all times.

**Comment by isthisrubble** [comment]
got it, it works! thanks very much for that!
