### ISSUE TITLE
xkit tag tracking+ tags not showing up on dashboard

### ISSUE THREAD

**Issue by Yellowcanary1** [new-xkit/XKit#1899]
as of the new tumblr update, the xkit tag tracking+ tags have not shown up on the dashboard. I can still see them in the search bar pulldown menu but not displayed on the right side as usual.

**Comment by AprilSylph** [comment]
we are aware that Tag Tracking+ does not work on the new dashboard; see #1802

**Comment by alllsss** [comment]
will this be fixed? or anything i can do to bring it back?

**Comment by AprilSylph** [comment]
fixed by #1911
