### ISSUE TITLE
Hard refresh/soft refresh

### ISSUE THREAD

**Issue by nhrpls** [new-xkit/XKit#1912]
tumblr defaults to soft refresh with the new update  and there's no option to choose hard refresh (at least on the desktop app)

**Comment by AprilSylph** [comment]
you can hard refresh using F5 or your browser's refresh button. is that insufficient?

**Comment by nhrpls** [comment]
yes, because it takes me back to tumblr.com/dashboard, i.e. the first page.
for example, if i was on page seven of the dashboard looking at posts from a few days ago, which used to have a specific url that i could save if i had to log off/turn down the pc (e.g. tumblr.com/dashboard/29639269264)

now, for example, i'm still on page seven (i.e. clicked seven "nexts") but the url is still tumblr.com/dashboard, which makes it impossible to save and i've already misclicked the tumblr logos/other places and it's impossible to go back to where i was, without clicking seven nexts again.

does that make sense?

**Comment by AprilSylph** [comment]
ah, you're talking about URL-based pagination. this isn't something XKit can do, but it's something Tumblr is bringing back, according to [this post on Tumblr Engineering](https://engineering.tumblr.com/post/623020262357663745/updating-tumblr-on-the-web):
> One piece of feedback we heard a lot was allowing pagination by changing the URL of the dashboard, and that’s something we plan to support. Thank you again for all of the insightful feedback about the new web experience, keep it coming!

**Comment by nhrpls** [comment]
ah i realized yesterday i called it the wrong thing! sorry and thank you so much!
