### ISSUE TITLE
XKit.interface.where() can't figure out that I'm on the "likes" page

### ISSUE THREAD

**Issue by toBeOfUse** [new-xkit/XKit#1917]
The code that's supposed to figure that out is here: https://github.com/new-xkit/XKit/blob/efdfa45c667f8af4235e2246a9b44ccd1c7add8b/xkit.js#L3082-L3085
Tumblr no longer uses a specific class for the page body on the likes page and all internal links to said page do not currently feature a trailing slash in the url, so `XKit.interface.where().likes` is false every time I check it. I propose changing the if statement to just `if (document.location.href.includes("tumblr.com/likes"))` under the assumption that Tumblr will not add any new pages with paths that begin with `/likes`. I could of course open a pull request for that if so desired.

**Comment by AprilSylph** [comment]
this would be resolved by #1903
