### ISSUE TITLE
Investigate post_listener performance improvements

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#192]
post_listener currently requires each separate extension to implement their own version of `$(".post").not("xwhatever-done")`. There is an opportunity to easily speed this up by refactoring post_listener to be more intelligent. Ideally, post_listeners would receive a list of new posts or be called for each new post.

**Comment by Wolvan** [comment]
I think we should make it a new post listener function because I expect changing it to break all extensions using post listener. And I suggest we just give an array of jquery nodes containing the new posts to the post_listeners

**Comment by WyohKnott** [comment]
I've got a local branch with post_listener (with an activity_listener too) rewritten with a MutationObserver instead, it doesn't solve the problem of ```.not("xwhatever-done")``` yet, but I could try to backport it to new xkit.

**Comment by nightpool** [comment]
we're using a mutation observer now, but there IS an opportunity to make this more intelligent.
