### ISSUE TITLE
"No Recommended"'s messages are kinda redundant 

### ISSUE THREAD

**Issue by nautiscarader** [new-xkit/XKit#1924]
![dfdsfdsf](https://user-images.githubusercontent.com/67703250/87877291-ba5f8900-c9dd-11ea-8209-5ad9e0d95638.jpg)

So, I noticed today that the No Recommended was updated, and as far as I can see, all it did in frontend was to add the message that a post has been hidden.

Uhm, why? 

Unlike the extension that lets you block phrases, I can't see the post again by clicking a button, so... it's kinda redundant and it takes space. Would be nice if one could toggle that line as well.

**Comment by vexx32** [comment]
I could be wrong, but I think that was required to prevent breaking the J/K post-by-post scrolling. Something about how it breaks if you completely hide posts or something.

**Comment by AprilSylph** [comment]
correct, there's no reliable way to completely hide posts without triggering the K-takes-you-to-top bug.

**Comment by nautiscarader** [comment]
Okay then.

**Comment by vexx32** [comment]
It might make sense to put in something similar to the blocked's "show it anyway" for consistency at some point, but given all the other fixes needed it's probably a low priority. 🙂

**Comment by citrusella** [comment]
Does this cause a bug if you literally never do J/K scrolling? I don't really want to see it and would rather it be hidden, but I could also just hide it on my own (i.e. with CSS)... but I only wanna do that if it doesn't somehow cause an issue while typing a post or reply or something.

**Comment by citrusella** [comment]
...Also, if this was implemented to fix J/K scrolling, it doesn't appear to have done so anyway unless something else is causing K-to-top on my end...

**Comment by coderpatsy** [comment]
^ If you have Tumblr Savior's hide sponsored posts option on, it breaks k scrolling.

--

Testing with my own userscript (since xkit's editor is still broken...) shows I can hide the recommended posts entirely without breaking k by making them 0-height 0-margin elements with overflow hidden, as long as I also hide the spacer elements after recommended posts in the middle of the flow the same way. I've only tested on Firefox though.

**Comment by AprilSylph** [comment]
(@coderpatsy you can still use the xkit editor on firefox, you just need to set `accessibility.blockautorefresh` to true in about:config)

**Comment by citrusella** [comment]
@coderpatsy I don't have Tumblr Savior at all, but the mention of sponsored posts reminds me it's possible my adblock could have blocked something? Question mark? So thanks for making me think of that!
