### ISSUE TITLE
Post listener doesn't work in peepr for some users

### ISSUE THREAD

**Issue by LunaManar** [new-xkit/XKit#194]
### updated description:

this appears to depend on whether tumblr wants to load the blog sidebar into an iframe (which is easy for us to track) or just raw (which we don't track at all). Whether tumblr wants to load the sidebar into an iframe or not appears to be dependent on your account—it wouldn't for my main account, but would always for my test account. I'm guessing this may also change over time?

we should make sure post_listener works in both scenarios. 

------------------------
### original report:

Since the beginning of August, the Tag/Reply viewer icon has been missing entirely from all posts/blogs when I open them on the sidebar popup. They can be seen on the dash, but nowhere else. This is making it impossible for me to pull up all the tags on my posts without scrolling and scrolling all the way down my post feed in the dash. Postblock and any other similar icons are affected as well (but it's the tag/reply viewer I'm most concerned with). 
![01worksondash](https://cloud.githubusercontent.com/assets/13724970/9159349/cbd0b232-3ef4-11e5-8269-841293986561.PNG)
![02butnotonsidebar](https://cloud.githubusercontent.com/assets/13724970/9159350/cbd1c622-3ef4-11e5-9a38-2c7f983f7bd4.PNG)

I have uninstalled/reinstalled Xkit and tried removing other add-ons one by one, but nothing in particular seems to be "breaking" it. I disabled adblockers, no change. Tried a different computer and even a different account, still having the same problem. 

Not sure if anyone else is experiencing this. Will be happy to provide whatever other info you need.

**Comment by nightpool** [comment]
Did this use to work? If so we probably broke it unintentionally while we were changing how we handled loading new posts. 

I'll look into it.

**Comment by LunaManar** [comment]
Yes, it did. It was especially useful when I would post something, then wake up weeks later to find it had suddenly been reblogged by a popular account and thus had a lot of tags/comments. I liked to click on it from the Activity page and open it in the sidebar, then view the tags from there. Was very easy, now I have to scroll through my dash to find it, which is...less easy. :c 

Thanks, let me know if you need any other info.

**Comment by finagle29** [comment]
Can you post a link to your extension configuration (found in the other tab in XKit) as well as your browser and operating system? I can't repro on Chrome 44 OS X 10.10.4 and these extensions https://gist.github.com/6c23718897231b6e547d

**Comment by nightpool** [comment]
I can confirm this works on firefox and not on chrome. will fix.

**Comment by nightpool** [comment]
wait sorry jumped to conclusions my entire firefox profile is borked nothing is working lol sorry

**Comment by LunaManar** [comment]
https://gist.github.com/5825f9c961a10c9d5795

Currently on a Windows 10 PC (not related; it also occurs on an laptop running Ubuntu).

Tried Chrome 44 and Firefox 39, same problem.

(It will, RANDOMLY, work for one post or two, but then disappear...so yeah I'll mess with it and think it's fixed but then it's...not.)

**Comment by nightpool** [comment]
I can reproduce this, but inconsistently.

this appears to depend on whether tumblr wants to load the blog sidebar into an iframe (which is easy for us to track) or just raw (which we don't track at all). Whether tumblr wants to load the sidebar into an iframe or not appears to be dependent on your account—it wouldn't for my main account, but would always for my test account. I'm guessing this may also change over time? 

anyway that's basically as far as I can look into the issue tonight, but remedies will probably fall into two broad categories: either force tumblr to load peepr into an iframe, or write more post_listener code to listen to a non-iframe peepr. (which I'm guessing we didn't even know was possible when we re-wrote the post listener code)

**Comment by LunaManar** [comment]
Weird. Well that would explain the inconsistency of it, but I wonder what I'm doing to trigger one and not the other. In any case it matters not to me how the sidebar loads, so whatever's easiest! Thanks for looking into it.

**Comment by LunaManar** [comment]
Just checked today after the update, and this appears to be fixed! Hopefully tumblr won't go and break it, again. 

Thanks for your hard work.
