### ISSUE TITLE
Clicking xKit button on Dashboard triggers animation

### ISSUE THREAD

**Issue by MarjaE2** [new-xkit/XKit#1954]
If there's a setting to disable the animation, it's well hidden.

**Comment by marcustyphoon** [comment]
What is your desired functionality? The XKit settings window opening instantly without a fade-in animation?

**Comment by MarjaE2** [comment]
Fade it would be good, instant would be alright, but the sliding up is a problem for me.

**Comment by lihatt** [comment]
I never even thought to ask for this feature. Sliding isn't a _problem_ for me exactly, but generally speaking I do prefer page interactions (not just XKit/Tumblr, globally anywhere) to have only the minimum animation necessary to provide accurate feedback on the action. Sliding, rotating, fading etc. behaviors rarely seem to provide extra useful information IMO.
