### ISSUE TITLE
Outbox only opens if there are messages in the Inbox

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#196]
From an ask:
> ive noticed that outbox will only open if theres something in the inbox. its not a huge problem, but its a little inconvenient! (also "export configuration" is misspelled in the other tab but thats no big deal lmao)

**Comment by gloomykid** [comment]
that was also a problem during xkit times (before new xkit was a thing). just a heads up.

**Comment by blackjackkent** [comment]
Repro'd...I'll look at this when I get home from work.
