### ISSUE TITLE
Quick replies aren't working

### ISSUE THREAD

**Issue by moewrin** [new-xkit/XKit#1989]
New update to the activity feed won't allow me to do quick replies anymore. I have all the settings checked just fine and it worked okay in the past but after this recent update i suddenly couldn't do any quick replies to anything anymore. :(

**Comment by AprilSylph** [comment]
the Activity page update is part of Tumblr's switch to the technology that powers the new dashboard - One-Click Reply being broken is not a unique issue, since every extension needs to be rewritten to adapt to the new site code; see #1802
