### ISSUE TITLE
Tumblr flashing every 30 seconds or so.

### ISSUE THREAD

**Issue by MarjaE2** [new-xkit/XKit#2001]
I have a screencap, but can't post here. A flashing white flash appears on the lower left corner. Checking the screencap, it says "Read assets.tumblr.com".

I also use uBlock origin because I don't enjoy pain and migraines.

**Comment by invalidCards** [comment]
This is your browser notifying you that Tumblr is fetching assets (images etc.) for newly loaded posts. This is not something XKit can fix, I recommend you take a look whether your browser has a setting to turn it off or move it to a more permanent footer bar.
