### ISSUE TITLE
New Activity Page Update No Longer Allows For Activity Extensions 

### ISSUE THREAD

**Issue by x-atalana** [new-xkit/XKit#2002]
Hi! New to this, so not sure if this is where I should be writing stuff, but I wanted to bring this to people's attention if it wasn't already - Is there anything that can be done about tumblr's new activity page update? I'm used to relying a lot on Activity+ and Retags, but they now no longer work with no similar function provided by tumblr itself to replace them, rendering my activity page... pretty much useless. If there's stuff in the works, awesome, I'm cool to wait, but since I haven't found anything already on this page or xkit's tumblr about it, thought I'd mention

**Comment by AprilSylph** [comment]
Tumblr have plans to replace the functionality of Activity+ (unrolling, filter-by-type) and Retags; see #1794 

sadly the confirmation for unrolling and tags on notifications aren't publicly confirmed by any official Tumblr staff blogs, but were both confirmed by a Tumblr engineer in our public Discord server. the public announcement for filtering by activity type was made back in July in [this post](https://engineering.tumblr.com/post/623539522358181888/rolling-out-a-new-activity-backend) on the Tumblr Engineering blog.
