### ISSUE TITLE
unable to queue or reblog

### ISSUE THREAD

**Issue by amartiniglass** [new-xkit/XKit#2005]
Since last night i have not been able to use the quick tags queue/reblog without receiving an error like the attached
![96730731-81400780-1384-11eb-8708-9cd1267322f6](https://user-images.githubusercontent.com/67748408/96730820-974dc800-1384-11eb-95a4-558298e7cb36.png)

This has been on two different computers and two different browsers. I'm not certain its strictly an xkit issue as i cannot reblog by clicking the button for tumblr itself either, but i havne't been able to find any documentation about this anywhere else.

**Comment by AprilSylph** [comment]
if you can't reblog at all then it's not an XKit-specific issue.

some common solutions to this include
- clearing your Tumblr cookies
- disabling your VPN
- disabling adblockers
- disabling any other privacy addons

if you find this issue persists after clearing your cookies, disabling all your addons, and logging back in, the only other thing I can suggest is to [contact Tumblr support](https://www.tumblr.com/support)
