### ISSUE TITLE
Preserve Tags doesn’t work with alt-reblog (instant)

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#201]
If the Keep Tags functionality of Auto Tagger is turned on and the reblog button is alt-clicked, also known as instant reblog, the tags aren't actually kept.

**Comment by ThePsionic** [comment]
@dlmarquis Is this still a thing?

**Comment by ThePsionic** [comment]
Closing since @dlmarquis doesn't have any recollection of this issue. She mentioned @blackjackkent might have some info, but she can re-open if she does.

**Comment by ThePsionic** [comment]
And it's re-opened.

If the Keep Tags functionality of Auto Tagger is turned on and the reblog button is alt-clicked, also known as instant reblog, the tags aren't actually kept.

I don't know whether it's at all possible to make this actually work, but that's something we can look into.

**Comment by nightpool** [comment]
@ThePsionic please edit any relevant information into the ticket description.

**Comment by ThePsionic** [comment]
@nightpool Woop, done.

**Comment by AprilSylph** [comment]
closing since interfering with tumblr's instant-reblog is probably either impossible or a bad idea.
also, this doesn't seem to be an actual problem for users
