### ISSUE TITLE
Search Likes does not show on likes page

### ISSUE THREAD

**Issue by paperprincessai** [new-xkit/XKit#2021]
I have the search likes extension but it no longer shows the option to search! I don't know if it is discontinued or is just in the queue to get fixed (or even that the option has moved?) but I thought I'd point it out

![image](https://user-images.githubusercontent.com/34976339/102424724-629b6d00-3fd1-11eb-9606-c463258828eb.png)
![image](https://user-images.githubusercontent.com/34976339/102424679-4dbed980-3fd1-11eb-976e-732d2cd513c0.png)

**Comment by AprilSylph** [comment]
it's still on the to-update list; see #1802
