### ISSUE TITLE
old blue glitch?

### ISSUE THREAD

**Issue by minuhmunuh** [new-xkit/XKit#2039]
after refreshing my browser, the entire dashboard went white, the text went black, and there were a lot of transparency issues. after some fiddling around, i realized that this stopped when i disabled old blue, meaning this is likely some issue with that. after some more checking, i found that this happens on both chrome AND firefox.
![old blue glitch](https://user-images.githubusercontent.com/79279389/108406627-ab99b880-71f0-11eb-8d49-b4f921ed1acc.png)

**Comment by LordViperagyil** [comment]
I can second to this. The white hurts my eyes.

**Comment by nyna237** [comment]
Same for me. Everything is white and I can't see a dang thing. But now without old blue I have to suffer Tumblr's terrible UI.

**Comment by silvainshadows** [comment]
also having this issue, which is a problem bc i can't focus on reading anything without the old blue extension. (none of tumblrs dashboard color themes hit the right combo of "works with my vision problems" and "works with my adhd")

i wonder what tumblr changed to break things this time...

**Comment by EssayOfThoughts** [comment]
Likewise, this has happened to me too. The Stylish/Stylus extension I had saved as a backup doesn't work to fix it. I have noticed that Old Blue seems to fleetingly work when switched on/off but then returns to the blinding white.

**Comment by invalidCards** [comment]
FYI, this happened because Tumblr made a change to how CSS colors are handled in their theme system. It'll take a little bit to fix, but we hope to have a fix available by the end of tomorrow GMT.

**Comment by EssayOfThoughts** [comment]
invalidCards, you fellows are amazing. Thank you.

**Comment by minuhmunuh** [comment]
> FYI, this happened because Tumblr made a change to how CSS colors are handled in their theme system. It'll take a little bit to fix, but we hope to have a fix available by the end of tomorrow GMT.

awesome!! thank you so much!

**Comment by Infernoflower** [comment]
Happening to me too. Thanks for the fix!

**Comment by invalidCards** [comment]
#2048 has fixed this - please update Old Blue to version 2.1.2 (either manually or automatically) to apply the fix.
