### ISSUE TITLE
Servant makes everything break

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#204]
Full text of ask:

I'm using chrome and for some reason, when the servant extension enabled, everything completely shuts down. My dash won't load, I can't see messages in my inbox, my drafts either won't load or they'll get stuck halfway open when I try to edit. I'm not sure why this is happening, but after some trial and error I figured out it was specifically servant that seemed to cause this and everything's running smoothly now since it's disabled, but it's one I tend to rely on a lot.

**Comment by ThePsionic** [comment]
I've had Chrome with Servant for a long time (still do) and I have never experienced problems with it.

**Comment by 0xazure** [comment]
Closing this given the age of this issue, the fact that it came through an ask which is difficult to follow up on, and that we haven't had any similar reports with any additional information.
