### ISSUE TITLE
quick posting reblog error (HTTP 503)

### ISSUE THREAD

**Issue by disasterjones** [new-xkit/XKit#2046]
Cannot reblog a post by a person I don't believe has blocked me. Refreshing and clearing cache has not improved function.
Further testing indicates that the quick reblog is broken; I cannot reblog any posts using that extension at the moment.
Attached a screenshot of the error message.

![bugreport](https://user-images.githubusercontent.com/80059974/110001992-c88ebb00-7cc9-11eb-9f47-0f364e685721.jpg)

**Comment by AprilSylph** [comment]
503 is a Service Unavailable status code. Many forms of posting, even those unrelated to XKit, return this code right now.

Closing as not an XKit-specific issue.
