### ISSUE TITLE
[Blacklist] Blacklist not completely hiding posts

### ISSUE THREAD

**Issue by lizzyd710** [new-xkit/XKit#2048]
I added a word to my blacklist and changed my settings to enable the "don't display blocked posts at all" option, but when I came across a post with that tag, it still showed up on my dash (albeit hidden/filtered). I then enabled the "don't show why post was blocked" option, figuring maybe that was how to do what I wanted, but same thing. 

I also have this tag added to my filtered tags in my blog settings, so I don't know if that's messing it up, or if I'm not patient enough and have to wait a bit for things to take effect.

**Comment by AprilSylph** [comment]
Blacklist can't activate on posts caught by Tumblr's own filtering since it was designed for the old dashboard and parses the post's HTML to match against the blacklisted terms

**Comment by lizzyd710** [comment]
Understandable. Thank you for clarifying!
