### ISSUE TITLE
Update tumblr interface

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#205]
![img](http://41.media.tumblr.com/e5f2a6a2055d72432b4bc6459bedc881/tumblr_ne9wx0zyXq1qkpozyo1_500.jpg)

All right, it's 2AM, I'll see myself out.

**Comment by Wolvan** [comment]
I second this issue.
It is also 2AM, I'll see myself out as well

**Comment by ThePsionic** [comment]
It's here! [Estufar made this an actual thing](http://estufarextensions.tumblr.com/post/128438346723/i-made-a-tungle-dashboard-theme-the-theme-right). (Pinging @estufar for obvious reasons)
