### ISSUE TITLE
Native One-Click Postage support

### ISSUE THREAD

**Issue by ShutterSpeak** [new-xkit/XKit#2051]
Now that Tumblr rolled out their own native version of one-click posts, I'm wondering if you can add a "native mode" to XKit's version, which basically just brings up Tumblr's version without having to hold down the E key.

Additionally, is there a reason why this extension uses the phrasing "Postage"? Didn't know if that was an inside joke or if I'm just missing a definition. One-Click Post seems more grammatically appropriate.

**Comment by AprilSylph** [comment]
as far as I know, it's not possible to perfectly simulate keydowns/keyups in a way that Tumblr's JS would react to. and since the bubbles are added and removed via JS appropriately, this couldn't be done with just styling

**Comment by ShutterSpeak** [comment]
Ah, shoot. Thanks for the extra info—I appreciate the quick reply!

**Comment by AprilSylph** [comment]
> Additionally, is there a reason why this extension uses the phrasing "Postage"?

you'd have to ask @atesh, the original XKit author, whose web presence vanished after he stopped maintaining XKit, leading to the birth of the New XKit project.

(I renamed it to "Quick Reblog" in XKit Rewritten since that's what people seem to call it anyway)
