### ISSUE TITLE
Tumblr redirects some tags to searches

### ISSUE THREAD

**Issue by MarjaE2** [new-xkit/XKit#2053]
Tumblr tags show up in order. Tumblr search results show up as tiles, which I can't read. Tumblr redirects some tags like transphobia to searches. I installed Classic search, it can't block the redirect or change the layout. I looked to see if there are other add-ons which might affect the layout, but no luck.

**Comment by AprilSylph** [comment]
There's nothing XKit can do about this. Some tags simply do not have "hubs" as Tumblr is now calling them, and redirect to the search page for that term. If you wish to voice this complaint to Tumblr, [file a ticket with Tumblr support](https://www.tumblr.com/support).
