### ISSUE TITLE
Tracked Blogs Have Disappeared

### ISSUE THREAD

**Issue by SageTheStampede** [new-xkit/XKit#2061]
Tracked blogs originally were visible from the Dashboard. A tumblr update made them only visible from the Inbox, which was manageable. The most recent update seems to have made the tracked blog list disappear entirely; I'm not able to locate it anywhere.

Blog Tracker version 0.6.7 (says it's up to date)
Firefox version 88.0.1
MacBook Pro, macOS High Sierra 10.13.6

**Comment by AprilSylph** [comment]
see #1802
