### ISSUE TITLE
one-click postage won't reblog, queue, or draft posts

### ISSUE THREAD

**Issue by rayspoons** [new-xkit/XKit#2070]
![Capture](https://user-images.githubusercontent.com/86135324/122626048-d6e0c700-d06d-11eb-8012-ca7310be64d6.PNG)
It says this whenever I try to use the extension.
Did I install xkit wrong?

**Comment by AprilSylph** [comment]
Your legacy login might be broken. Try clearing your cookies for www.tumblr.com and logging back in.

**Comment by rayspoons** [comment]
I just cleared the cookies, but it's still saying the same thing. The issue happens with both chrome and firefox for me.
