### ISSUE TITLE
custom theme is slightly broken, please help! 

### ISSUE THREAD

**Issue by mdaijean** [new-xkit/XKit#2078]
hiiiiiiii, i run a rp blog on tumblr (url @ **taleinspired**) and my theme is acting a bit funky???? i fixed ONE minor issue but i still have others. here are some examples:  

01.)    my posts (**as seen here**) aren't supposed to be running outside of the box they're confined to but for some reason they are   _??????_ 
![image](https://user-images.githubusercontent.com/80423767/138011298-ea9c3d74-73d6-4ec5-bd1c-0502cf366be8.png)

02.)    there's also the issue of my tags running into my other posts and they didn't do that before? i wonder if all of these issues stem from when i tried to go into my code n' tweak some stuff before i really knew what it was that i was doing. maybe. 
![image](https://user-images.githubusercontent.com/80423767/138011469-1c80d135-3c5a-4250-9415-f08285aca24f.png)

03.)    my autoplay isn't working and i'm not sure why    _????????_ 
![image](https://user-images.githubusercontent.com/80423767/138011558-e33731c3-0528-40fc-a36d-fa38d3de24f8.png)

any help with these issues would be _GREATLY_ appreciated, thank you    _!_

**Comment by mdaijean** [comment]
> @mdaijean do these issues have anything to do with XKit? 

i think so? i'm not TOO sure bc i went 2 inspect the theme itself via dev tools n it had some errors, idk. i just want my theme fixed n functional again.

**Comment by invalidCards** [comment]
@mdaijean do the issues still occur if you disable New XKit in your browser's addon settings?
