### ISSUE TITLE
Enforce code style

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#209]
We don't currently enforce an indentation style, but we probably should through [JSCS linting](http://jscs.info/rule/validateIndentation.html).

Should be easy to do, it's just a config line in `.jscsrc`, but I'll need to check all of our files over to make sure they conform.  I don't know if it all got caught in #175, I was only looking at mixed-indent in that one.

**Comment by Wolvan** [comment]
I don't think setting indentation rules would be that good of an idea, because each dev has their own style of coding

**Comment by 0xazure** [comment]
Wholeheartedly disagree.  Contributors should be conforming to the established code style of a project, not use whatever styling they personally prefer.  Conforming to a style guide is [standard](https://contribute.jquery.org/style-guide/js/) [practice](https://www.mediawiki.org/wiki/Manual:Coding_conventions) across projects [big](https://google.github.io/styleguide/angularjs-google-style.html) and [small](https://github.com/gulpjs/gulp/blob/master/.jscsrc).

**Comment by blackjackkent** [comment]
^ This. Having consistent style guides for the project also reduces the percentage of our PRs that have extraneous whitespace changes to wade through.

**Comment by Wolvan** [comment]
I am not sure how much you want to limit the indetation style though. So far I have been trying to stay true to the current style of XKit

**Comment by finagle29** [comment]
:+1: to using a style guide

**Comment by dlmarquis** [comment]
Thread necro: can we please stop using hard tabs? I hate them. I hate them so much.

**Comment by nightpool** [comment]
stuff that's come up so far:

 - I like trailing commas, but don't think they should be mandatory in *every* possible situation. what options does jscs give us?
 - maybe this is just because I'm biased by python, but I am strongly in favor of "All prefix whitespace should be spaces" (infix whitespace can be tabs in places where that makes sense, like inline structured data literals)

I would prefer something that would just fix codestyle for us automatically like gofmt—does jscs give us that option? Otherwise, I'm down to do a huge PR again.

**Comment by Wolvan** [comment]
Personally not a fan of all prefix whitespace should be spaces. I prefer tabs

**Comment by 0xazure** [comment]
I'm very much of the opinion that tabs are evil, mostly because they're of changeable width, which borks alignment if everyone isn't using the same size tabstops.  However, given that almost the entire codebase uses tabs, I don't think it's in our best interested to try and convert existing code.  The best compromise that I see would be to have a convention of assumed 4-character-wide tabs for indentation and spaces for alignment in existing files, and to use spaces in all newly created files.  We can combine the JSCS rules of [`validateIndentation`](http://jscs.info/rule/validateIndentation) and [`disallowMixedSpacesAndTabs`](http://jscs.info/rule/disallowMixedSpacesAndTabs) with the `"smart"` option to achieve this.

As far as trailing commas, JSCS supports [`requireTrailingComma`](http://jscs.info/rule/requireTrailingComma), but there doesn't appear to be a way to control the reporting level (ie `Warning`, `Error`, etc), enabling the rule would always make it an error and would always fail the CI builds if there were any missing trailing commas.

As far as autofixing, there's options like [jshint/fixmyjs](https://github.com/jshint/fixmyjs) that we could leverage to help us achieve a consistent style.  Whatever we do, there will probably have to be another huge style PR.

I'd also like to draw attention to #529, as I think we should eventually migrate away from the combination of [JSHint](https://github.com/jshint/jshint) and[JSCS](https://github.com/jscs-dev/node-jscs) and instead use one tool.

**Comment by Wolvan** [comment]
Failing Travis is what always happens so far. I say that is functionality should be that way

**Comment by 0xazure** [comment]
@Wolvan for things that are not in line with the enforced style, sure.  But (unless I'm mistaken) @nightpool was inquiring as to options we would have for _optional_ enforcement (ie. not _always_ enforcing trailing commas), which is not functionality that JSCS provides, as I indicated above.

**Comment by Wolvan** [comment]
@0xazure we should either enforce a style or don't enforce it. There shouldn't be a thing as "optional enforcements" at all.

**Comment by nightpool** [comment]
Ftr I was asking about our options for partial enforcement. For example,
always requiring trailing commas in arrays, but not in objects. Or
something like that.

**Comment by 0xazure** [comment]
@nightpool thanks for the clarification.  Per the docs for JSCS' [requireTrailingComma](http://jscs.info/rule/requireTrailingComma) it unfortunately doesn't allow for enforcing objects _or_ arrays, it's both or neither.  There _are_ some options around when to enforce the style, where single-line arrays/objects wouldn't require it, but multi-line ones would.

**Comment by bvtsang** [comment]
Code styles that we could adopt, emulate, or use as inspiration:

- [Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style)
- [Google](https://github.com/google/styleguide)

**Comment by dlmarquis** [comment]
+1 for adapting/adopting Mozilla's style. Besides aesthetics, 2-space indents and 80 char width is barely passable on some of our more nested functions. Google's 4-space indents would be a special kind of hell. I also prefer Mozilla's naming conventions.

A change I'd like is preferring ' over ", but largely because we have a lot of HTML strings containing things like '<div id="xkit_bleh"></div>', and I'd like to keep the doublequotes convention with the HTML we inject. Overall I'd say we have more strings containing HTML quotes than strings containing contractions, etc.

I would also like to delineate a practice for inserting blank lines, which neither of those styles really does. There are a couple of files that are hell to skim through in vim because the next-paragraph key sends me to the end of the file. My immediate thought is at minimum between functions (obviously) and before/after if/then/else blocks, but I dunno.

**Comment by nightpool** [comment]
I like 4 space over 2 space, and 100 chars over 80 chars, although that's
just me.

**Comment by 0xazure** [comment]
https://houndci.com/ may be something we want to look into as well.  From [the FAQ](https://houndci.com/faq):

> **Can I have Hound check my entire repository for style?**

> No, and we don't recommend doing so. Our rule is "Don't rewrite existing code to follow the style guide." See the thoughtbot style guide.

> It can be dangerous to re-write a lot of code for just style reasons. It can introduce functional regressions, which are a higher-level concern than style.

>We believe the right approach is to convert a codebase over time, one pull request at a time, to conform to a style guide. Only focus on style in diffs and make smaller changes that ideally have tests associated with them.

I would tend to agree with the above; trying another touch-everything PR just to conform to a styleguide doesn't strike me as worth the time investment.

**Comment by Dhwty** [comment]
Is this solved by #1236 ?

**Comment by nightpool** [comment]
yep, thanks
