### ISSUE TITLE
Blacklisted words don't filter posts with special trending tags

### ISSUE THREAD

**Issue by ToughPapaya** [new-xkit/XKit#2120]
If a blacklisted word is in a special trending tag (pink and purple) like the one below, the post will not be filtered.

![Tumblr spencial trending tag](https://github.com/new-xkit/XKit/assets/113640163/f6f6e127-d33c-4fe1-8a2f-1cf09e93fa2d)

**Comment by marcustyphoon** [comment]
I actually can't reproduce this! (I know what line of code would do something different, so I can try to fix it blind, but generally I would like to be able to make sure my fix actually worked, obviously.)

You are using New XKit's blacklist extension, right? What text do you have blacklisted exactly? What settings do you have in the extension?

**Comment by ToughPapaya** [comment]
The blacklisted word is fnaf. The checked items are:

- Enable alt + B shortcut for adding new words
- Show type of post when it's blocked
- Don't display blocked posts at all
- Check author blog titles and usernames for blacklisted words
- Don't block my own posts
- Use improved checking

**Comment by marcustyphoon** [comment]
Thanks! Reproduced on fnaf now. No idea why my test was working fine on the good omens post I was using.
