### ISSUE TITLE
Visual bug when using timestamps on search page

### ISSUE THREAD

**Issue by meowmeow-hours** [new-xkit/XKit#2128]
I'll preface this by saying I'm a bit tech illiterate, please let me know if there's more information I can provide.

I've attached a video at the bottom of all my plugins & toggling the timestamps on/off, showing how it affects the post notes.  Basically, when using the timestamps plugin, it causes the notes to misalign with the bottom interaction row.  Relatively minor, but I really struggle to read the number when it gets like this. 

I am using Firefox 116.0.2 (64-bit) & XKit 0.21.14

Video showing the bug.
[https://youtu.be/xXo8JaNqvfA](https://youtu.be/xXo8JaNqvfA)

**Comment by AprilSylph** [comment]
This is the repository for New XKit. The XKit Rewritten issue tracker is [here](https://github.com/AprilSylph/XKit-Rewritten/issues), found under the "Links" tab in the control panel.

Timestamps in XKit Rewritten is deprecated in light of Tumblr's own timestamps everywhere setting, which you can enable in https://www.tumblr.com/settings/dashboard. Use TimeFormat to customise those timestamps.

**Comment by meowmeow-hours** [comment]
Oh! So sorry!
