### ISSUE TITLE
Tweak not working

### ISSUE THREAD

**Issue by snifflng** [new-xkit/XKit#214]
The 'Don't show liked posts on my dashboard' tweak in settings isn't working for some reason and keeps showing liked posts.

**Comment by blackjackkent** [comment]
We're aware of a bug in the Tweaks extension and a fix is already forthcoming. :) Thanks for the submission!

**Comment by digrumpycat** [comment]
Don't know if this is included in the bug you know about, but the 'wrap tags' option seems to not be working either.

**Comment by ThePsionic** [comment]
A bug in Tweaks makes the entire extension not work, it's not on a per-preference basis. We're aware of the issue, and a fix will come soon.
