### ISSUE TITLE
Wrap-around Tags doesn't work with the newest Tweaks update

### ISSUE THREAD

**Issue by blindcat97** [new-xkit/XKit#217]
Since Tweaks updated recently (my version is showing as 3.4.0), tags no longer wrap around despite the setting being turned on. I tried disabling and re-enabling the feature, to no avail. I'd prefer not to have to reinstall xkit, as I have many settings and extensions customised, but perhaps someone else can test this. 

I'm using Google Chrome version 44.0.2403.130 m (newest version), running a fully updated Windows 10, XKit version 7.7.0. I can send my configuration information, if necessary, but I'd prefer to do it privately.

**Comment by bvtsang** [comment]
As of #215, we updated Tweaks to 3.4.1. Let us know if updating to that version fixes your issue.

**Comment by blindcat97** [comment]
The issue is fixed for me, but I don't know about anyone else. I had to force the update; XKit refused to receive the automatic update.

**Comment by nightpool** [comment]
@blindcat xkit checks for new updates every few hours or so. we pushed an
update this morning that broke it (our bad!) and an update this afternoon
that fixed it, and because they're so close together, xkit generally takes
a little longer to start looking for the next version
