### ISSUE TITLE
Tumblr has broken tags in general

### ISSUE THREAD

**Issue by ReddPyramid** [new-xkit/XKit#221]
It now looks like they have to be selected and then delete has to be pressed to delete a tag while posting.  Instead of the original 'click to delete', now there is, yet again, an extra step involved in something for a reason that is not readily apparent to anyone with a lone functioning brain cell.

**Comment by nightpool** [comment]
this was changed so tags can be dragged around and reordered. (which imo was one of my hugest painpoints composing posts)

if someone wants to add a non-default tweak option that'd probably be fine though.

**Comment by nightpool** [comment]
dupe of #218.

**Comment by ReddPyramid** [comment]
That makes more sense.  I'm honestly so burnt out on their pointless 'updates' that I couldn't see any reason why they would do this.  Thanks for clearing it up.
