### ISSUE TITLE
Would you like my GIST for Mass? I can't build a Pull.

### ISSUE THREAD

**Issue by gitfan51484** [new-xkit/XKit#226]
I've been building a popular userscript called Mass Post Features since 2013. Would you like to integrate this into xKit?
https://gist.github.com/gitfan51484/e6ed82eb17d18330a2f9
It's pure javascript, and I've gotten it to run without Greasemonkey as an embedded script.

If this issue is out of line, close it, slap me, forget about me; I'm very foreign to Github. I don't know about making my own build, so I can't make a Pull.

This userscript adds extra features to the Mass Post Editor. Edit Queue/Drafts, Tag/Type Show-Only/Select, and lately 4 kinds of Mass Reblogging features. You can read about it here. http://scripts.b9mx.com/post/91735178964

**Comment by Wolvan** [comment]
It's as good an issue as any, that's what we have the enhancement label for. To make your own build you first have to fork this repository, make the proper edits in your copy then and then come back here and create a pull request. Github tells you when you did changes and suggests a pull request with the proper settings already when you come back to the main page of the repo

**Comment by nightpool** [comment]
why was this closed? its still open for someone to take and address. its
just low priority.
