### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#227]
Microsoft Edge doesn't have extension support as of yet but it should come later down this year. And I heard that it just takes a few extension changes of a chrome version to port it to Edge. Will this be part of the browsers we want to support?

**Comment by nightpool** [comment]
depends on the interest, and what people on the blog say. Too far out to
make any predictions imo.

**Comment by nightpool** [comment]
(closing because there's nothing actionable here until edge gets an extension api)

**Comment by dlmarquis** [comment]
We've already had inquiries into support for Edge. I'd say it depends on how easy the changes to the Chrome extension are, and if we have to pay money for the store.

**Comment by 0xazure** [comment]
As an update to this, the Verge is [reporting](http://www.theverge.com/2015/10/22/9596298/microsoft-edge-extensions-support-2016-release-update) that extensions won't be coming until "a future Windows 10 update in 2016".

**Comment by nightpool** [comment]
someone sent and ask today saying there were some amount of beta extensions
that you could install "but in a weird way". Anyone hear anything about
this?

**Comment by Wolvan** [comment]
@nightpool I have not, no. But I read the ask and googled a but, the only thing I found was a hosts file updater that pulls a list with ad hosts into your local /etc/drivers/hosts file

**Comment by amenantaud** [comment]
I'd be interested in Edge support. I'm not well versed in extension development, but it seems that you can somewhat [convert an already existing Chrome extension into an Edge extension](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions).
