### ISSUE TITLE
Clicking "reply" on fanmail opens a reply and a new tab.

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#228]
As the title says:
if I want to reply to a fanmail in my inbox, it opens on the current tab but also opens a new tab, instead of opening a new tab and leaving the message open in the old tab.
With old xkit it was able to let the reply open in a new tab solely, so you could still read the fanmail while answering. 

I'm using Chrome (latest version).

**Comment by blackjackkent** [comment]
Resolved by https://github.com/new-xkit/XKit/pull/268
