### ISSUE TITLE
Outdated tweaks not as outdated as thought

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#235]
This is RE the changes that were made in #215 - those tweaks were apparently used quite a lot still, and should be re-added.

**Comment by 0xazure** [comment]
Tweaks initially removed in https://github.com/new-xkit/XKit/commit/b8718b6d69945dd0a64280039cef306ddfd154d4, #215 was just cleanup to fix Tweaks not loading.

**Comment by 0xazure** [comment]
Do we know if this is still a concern?  Especially given that this information is now effectively "hidden" while on the Dashboard in the Account drop-down?

**Comment by ThePsionic** [comment]
@0xazure That was the main complaint of the people back then actually, they didn't like the likes and follower counters in their account menu.

**Comment by 0xazure** [comment]
Oh, so they wanted to be able to move them back to the Dashboard?  Because all of the tweaks referenced were about _removing_ information from the Dashboard, which is different functionality.

**Comment by ThePsionic** [comment]
No, they just wanted the links removed from the Account menu altogether, not moved elsewhere.

This issue is almost four months old, though, and I haven't heard any complaints about it since; this issue might not even be relevant anymore.

**Comment by 0xazure** [comment]
We can always re-open this later if there's an increased demand for that feature.
