### ISSUE TITLE
Many complaints about Activity+ not working

### ISSUE THREAD

**Issue by invalidCards** [new-xkit/XKit#248]
Example ask:

> Hi, I dunno if anyone else has reported this, but Activities+ extension isn't working. I updated (reinstalled) Xkit and updated the extension itself, no avail. The extension doesn't seem to be coming on at all

**Comment by dlmarquis** [comment]
I get a couple of errors while Retags is also installed and set to only show retags/responses:

1) Filtering my mentions doesn't do anything. It acts as if I'm still viewing the "all" tab.
2) Under the "all" tab, if "group notes" is turned on in Activity+, then it will break Retags. Really, the "group notes" option just shouldn't be on at the same time as Retags is installed.

**Comment by nightpool** [comment]
@dlmarquis Why shouldn't the group notes option be on at the same time
retags is installed? retags does a bunch of different stuff not just on the
activity page.

@ThePsionic I was just using activity+ this morning and didn't have any
problems, so this definitely isn't widespread.

**Comment by dlmarquis** [comment]
@nightpool At least on the activity page, grouping notes completely defeats the purpose of showing only retags/responses by hiding them along with everything else. It also hid tags on tagged posts at random because of this behavior, even when not in the "all" tab.

**Comment by nightpool** [comment]
@dlmarqius I would think that "group by similar" would override "show only
retags" because then you can open up each individual section and show only
the retags, grouped by post?

**Comment by dlmarquis** [comment]
@nightpool That would be a good way to fix it. As it stands now, clicking the groups will show everything, not just retags/responses.
