### ISSUE TITLE
Open In New Tab does not work through the Notes popup

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#252]
>Open In New Tab doesn't work when the blog is accessed through the Notes popup.

**Comment by gloomykid** [comment]
this also applies for activity page. itll only open the sidebar preview of the blog with the post, despite me having the sidebar preview blocked in first place.

**Comment by blackjackkent** [comment]
Dupe of #237

**Comment by ThePsionic** [comment]
Fair enough.
