### ISSUE TITLE
Donations!

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#256]
I have received MANY asks about people wanting to donate to us. We're gonna need to figure out a way to accept donations and divide it to the places where it's needed.

**Comment by Wolvan** [comment]
Am I wrong or wasn't Xenix absolutely against making XKit give money

**Comment by ThePsionic** [comment]
[Not exactly](http://xkit.info/seven/donate/), no.

**Comment by Wolvan** [comment]
Oh, shit. Well, I guess we could go for donations then. How about the people with the most commits get the most money

**Comment by ThePsionic** [comment]
That'd be rude, because all I ever do is answer asks and make issues :U

**Comment by Wolvan** [comment]
point taken

**Comment by blackjackkent** [comment]
I would recommend against giving it to the staff. Recipe for bad blood, not to mention it probably opens legal issues?

**Comment by Wolvan** [comment]
Donation for Child's Play or some organization similiar to them then? I wouldn't mind

**Comment by ThePsionic** [comment]
Not sure why it would be a legal issue? It's a donation towards the team, we're not selling anything based on Tumblr, we're giving people the free option to help us out.

**Comment by nightpool** [comment]
We don't have the procedural infrastructure setup to handle donations right
now. Maybe sometime in the future, but for now we can just say no.

(Exception to this might be a limited fundraising effort for safari
support, capped at 100 dollars)

**Comment by hobinjk** [comment]
We currently don't have any operational costs outside of the $5 I paid for the Google developer anti-spam thing. A fundraiser for Safari support would definitely be good, some sort of one-off GoFundMe would work.

An idea I've been musing for donations would be to register on Bounty Source. If people want some bug to be fixed they can donate to that bug's bounty. This has the potential to turn us all into heartless, soulless mercenaries, but could be a pretty simple solution.

An even more ridiculous idea I had was for an XKit Patreon where the higher tiers get guaranteed time spent caring about your problems.

**Comment by bvtsang** [comment]
A good question to ask is what do we need money for? Off the top of my head:

- Apple Developer program fee in order to allow us to make a Safari extension (or develop for iOS if we want to do that)
- hosting, domain name costs

**Comment by ThePsionic** [comment]
I think the list ends there.

**Comment by nightpool** [comment]
We don't have a good place to put this discussion at the moment, but I don't believe github is the correct answer. I'm going to close this issue for now but continue to discuss I guess.

**Comment by 0xazure** [comment]
Going to put these here for reference, before I forget their dam names again:

I know that https://flattr.com/ and https://gratipay.com/about/ are used around the FOSS community for supporting creators.  Their models may or may not fit us, though.

**Comment by dlmarquis** [comment]
Paypal's API supports paying multiple people at once:
https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/
https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECParallelPaymens/

The first link says 2-6 receivers, and the second says up to 10. Using the API seems like overkill, but less overkill than registering an organization.
