### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#258]
I was thinking about adding Google Analytics into new XKit for Usage Statistics, with the ability to opt out of course. Might help us analyze extension usage and help us progress

**Comment by Wolvan** [comment]
I would look into it if that sounds like a good idea to others

**Comment by ThePsionic** [comment]
Would be nice. :+1:

**Comment by nightpool** [comment]
I'm working on analytics this week hopefully. Google analytics won't work
for us, but I'm investigating other possibilities.

**Comment by Wolvan** [comment]
@nightpool How come GAnalytics won't work for us?
Also, that might be another thing for #256

**Comment by Wolvan** [comment]
@nightpool Why did you close this issue?

**Comment by nightpool** [comment]
because we're most likely not going to be implementing google analytics
anytime in the near future.

**Comment by Wolvan** [comment]
@nightpool And what about alternative Analytics systems? I just said google analytics because that was the first thing coming to my head
