### ISSUE TITLE
Abstract-ify Satsukimous

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#263]
>Would it be possible to make Satsukimous now abstract and allow us to use a custom image (either local or online) as the anon image?

**Comment by hobinjk** [comment]
I agree with this wholeheartedly. There was also at least one user who also wanted the option to blacklist/replace avatars (example use case: making it seem that we aren't anime trash).

**Comment by ThePsionic** [comment]
But that's outside of the scope of Satsukimous, which only targets anon asks ;)

**Comment by finagle29** [comment]
maybe a general avatar replacement extension that can have a replace with x image if on blacklist as well as a turn all anon icons into y, with a build it option default behavior being to replace anon icons with satsuki

**Comment by dlmarquis** [comment]
@hobinjk I'm working on something for that

**Comment by bvtsang** [comment]
Would we need to rename Satsukimous to something like Replace Anonymous Avatars?

**Comment by ThePsionic** [comment]
It would still default to Satsuki in my opinion. And Satsukimous looks nice.

**Comment by 0xazure** [comment]
I vote for keeping the name, keeping it to default to Lady Sasuki, but make the description really obvious about that it does.
