### ISSUE TITLE
TagViewer button does not display in sidebar view

### ISSUE THREAD

**Issue by blackjackkent** [new-xkit/XKit#270]
![tagviewer](https://cloud.githubusercontent.com/assets/13437011/9266651/bcba00b0-4209-11e5-8301-afab8653ad70.png)

**Comment by nightpool** [comment]
dupe of https://github.com/new-xkit/XKit/issues/194

**Comment by nightpool** [comment]
interesting in that this only happens occasionally: sometimes tumblr decides to load Peepr into an iframe, and sometimes it doesn't.
