### ISSUE TITLE
Satsukimous cannot be installed from the gallery

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#272]
![satsuki-noooo](https://cloud.githubusercontent.com/assets/1041456/9266879/fbff4752-4214-11e5-88b0-4d5ce2dcbb81.PNG)

**Comment by bvtsang** [comment]
In `Extensions/dist` on the `gh-pages` branch, I don't see satsukimous.json. Could this be a reason for this error?

**Comment by finagle29** [comment]
@bvstang i think so, but I'm not 100% sure why because @hobinjk rebuilt gh-pages after #269

**Comment by hobinjk** [comment]
It exists locally, I'm investigating now

**Comment by hobinjk** [comment]
Oh wow, really sneaky bug caused by 3bdff43ee5af51c6386c94e4e28be9d4d31572c5

**Comment by hobinjk** [comment]
Should be fixed now
