### ISSUE TITLE
Make Search Likes functional

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#280]
>For the Search Likes extension, is there any chance you can make it search through all your likes and not just the ten likes that are on the page on the specific moment you search?

**Comment by nightpool** [comment]
also, search likes should show up on the /liked/by pages as well as the
/likes one, no?

**Comment by nightpool** [comment]
and/or maybe we should just refactor this into a general "search" extension
that will search whatever posts are on the page. (search dashboard, search
inbox (which is duplicated in xinbox), search likes, search queue/drafts,
search posts, that kind of thing)

**Comment by ThePsionic** [comment]
:+1:
