### ISSUE TITLE
Soft Refresh doesn't load every new post

### ISSUE THREAD

**Issue by invalidCards** [new-xkit/XKit#281]
> The Soft Refresh for my Dashboard will only show about 5-17 new posts per refresh whereas I should have far more new posts, considering i follow +1000 blogs >__ o am i soft refreshing wrong? When i hard refresh they all show up, normally.

**Comment by nightpool** [comment]
soft refresh has never been 100% complete as far as I know. (maybe it got fixed, the last time I used it was 8 months ago)

**Comment by ThePsionic** [comment]
Confirmed, only ever loads 10 posts.
