### ISSUE TITLE
Add Profiler to the user menu

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#282]
Show a Profiler button in the user menu when hovering over a blog URL.

**Comment by Wolvan** [comment]
![image](https://cloud.githubusercontent.com/assets/1437010/9274713/4422a780-4298-11e5-87a5-efa4eac7694f.png)
There for me in classic Usermenu

**Comment by ThePsionic** [comment]
Not the classic user menu, this user menu.
![a](http://i.imgur.com/3ROEb3b.png)

**Comment by Wolvan** [comment]
Oh, you meant the modern menu, gotcha
We probably should specify that in issues from now on

**Comment by ThePsionic** [comment]
Good point.

**Comment by ThePsionic** [comment]
Closing this as wontfix since there is nothing **to** fix - this option works as expected.
