### ISSUE TITLE
Splitting work between new-xkit-extension and new-xkit-support

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#287]
We should figure out how we're going to split things between new-xkit-extension and new-xkit-support. My original conception was that new-xkit-support would be for troubleshooting, and new-xkit-extension would still recieve bug reports from people unable/unwilling to make a gh account and to ask users to submit details on common errors, but I don't know if that makes sense.

**Comment by ThePsionic** [comment]
In my opinion new-xkit-extension should have its ask box and submissions turned off, as to make it a sole information blog for important changes and new extensions and the likes. new-xkit-support would be more of what new-xkit-extension is now, so bug reporting and the ability to post anon asks without being told off about it. new-xkit-discussion would become the go-to Kill La Kill fandom page.

**Comment by dlmarquis** [comment]
I think new-xkit-discussion could also have things like informal polls about different directions we can take extensions, etc. Just generally make it an informal place where we interact with users.

**Comment by ThePsionic** [comment]
:point_up: :+1:

**Comment by nightpool** [comment]
upset about the homestuck fandom erasure in this thread. klk isn't the only fandom!

on a srs note, I'm basically down for the idea of redirecting all asks and stuff to a separate blog. I still think we should try to batch some amount of asks up, even with a new blog, but w/e as long as its not in our main blog I'm fine. 

I'm very strongly in favor of new-xkit-extension only being for updates and super-important stuff (like when tumblr breaks and we get a million asks about it).

don't think we should turn asks and submissions off, as long as we figure out a way to answer them on another blog.

**Comment by ThePsionic** [comment]
...or we make it easier and just make a faux ask link at the top of the new-xkit-extension blog that leads to the support ask box.

Also, if we do this, move the current new-xkit-extension to new-xkit-support. That way we don't lose the cache of asks we have.

**Comment by nightpool** [comment]
@thepsionic doesn't solve the problem of people who ask from their
dashboard.

**Comment by dlmarquis** [comment]
@nightpool hopefully new-xkit-support will be the more active blog, and that will come up infrequently enough that copying it over won't be a problem. That might be wishful thinking.

**Comment by nightpool** [comment]
@dlmarquis right I just don't want to discourage people by not having the option available to send asks if it would be trivially enough to send them over. (still have to look into that)

**Comment by dlmarquis** [comment]
We could also poll our users to see how they feel about converting the current blog to new-xkit-support and go from there.

@nightpool that's a good point. Just a reply-style copy of the ask would also work, if the actual sending turns out to be a pain.

**Comment by nightpool** [comment]
@dlmarquis problem is that any links that are being reblogged by people
would then become dead. (for example, our most popular post
<http://new-xkit-extension.tumblr.com/post/124311218694/xkit-its-happening>,
which is still being reblogged, would have a dead link at the top of it)
(although the source links update automatically no-one ever checks those)

**Comment by ThePsionic** [comment]
No, because the new-xkit-extension blog would still exist. Post permalinks automatically get converted to use the new URL too if a blog moves.

**Comment by dlmarquis** [comment]
@ThePsionic I've definitely had to manually alter urls when clicking on post links after a user has changed their url. I'm not sure what the conditions are for making it screw up, but at least one major one is if there's a new blog with the old url.

**Comment by dlmarquis** [comment]
Wait, I'm pretty sure we can set custom urls for posts. We could reblog/remake that post over at the new one and set its url to be that exact link.

**Comment by ThePsionic** [comment]
Yep.

**Comment by nightpool** [comment]
@ThePsionic that's not how it works. we could manually make redirects on the new blog, but nothing would redirect by default. 

(the "source" link still works, but nothing else changes)

**Comment by dlmarquis** [comment]
How many posts would we want to move over and preserve? If it's just the major version update posts, the announcement post, and the 5 or so non-ask posts we have currently, moving that way wouldn't be a huge deal to us. I'd still like to get follower opinions on moving a blog with 16,500+ followers first, though. That's a lot of potentially pissed-off people.

**Comment by hobinjk** [comment]
I agree with new-xkit-extension being solely important release documentation. We have all the components required to make a re-asker for XInbox which would convert -extensions asks to anons directed towards -support (that happen to be from -extensions).
Anyway, I'm off to work now. Feel free to take any action you want based on the outcome of this discussion.

**Comment by nightpool** [comment]
yeah also second @dlmarquis I didn't even think of the fact that all of the 16k followers would now be following the new "support" blog. that's basically the exact opposite of what we want to happen, and seems incredibly counter productive.

**Comment by ThePsionic** [comment]
Ah yeah, good point @nightpool. If someone writes up the extension suggested by @hobinjk I am at peace with it.

**Comment by nightpool** [comment]
meta point: i'm still a little unhappy using github for governance issues, but I don't really have any ideas for a better replacement. How do you guys feel about mailing lists?

**Comment by ThePsionic** [comment]
GitHub IS my mailing list ;)

**Comment by finagle29** [comment]
@ThePsionic same
but :+1: for a mailing list thats not github

**Comment by bvtsang** [comment]
I prefer to discuss governance either on Github or Gitter. I don't want to
subscribe to yet another thing to keep up with discussions that we could be
having on existing communication channels

**Comment by 0xazure** [comment]
I second @bvtsang's statement.  GitHub issues would be better, since it's a bit more permanent than Gitter chat (yes, Gitter is searchable and has archives, but they're a little finnicky).  If we don't want these kinds of discussions 'cluttering' up the extension issues list, we could do as the NodeJS community has done and [split other concerns off into separate repos under the same org](https://github.com/nodejs/evangelism).

**Comment by nightpool** [comment]
The question bvtsang was responding to was between github and a standalone
mailing list (probably google groups or some mailman install) or maybe
between github and something like discourse. I think most people are on the
same page that we can't use gitter for stuff like this. (Except in the most
informal capacity)

**Comment by ThePsionic** [comment]
Anyway, unrelated to mailing list, here's the essay I promised you all last night.

We want new-xkit-extension to not publish asks. If we don't turn the ask box off, both anons and non-anons can still ask questions on the main blog. If, however, we answer them with new-xkit-support instead of new-xkit-extension, there is quite a chance that anons have no idea that that is happening, seeing as an anon you'd look on the blog you asked to get your answer.

Say we just turn anon off. Great, now you don't have that problem anymore, and all replies can be private. However if people don't know about the support blog there is a chance that they have nowhere to leave their stuff anonymously and are like "meh w/e then I won't". That would mean missing out on a great deal of issues.

Now we turn ask completely off (submit goes too for each case I guess) and there's no Ask and Submit button any more in the user menus on the dashboard. People click on the blog, and lo and behold! There's a link to a support blog they can click on and dump any questions they have. Everyone is happy.

Conclusion: Turn ask off on -extensions once we split everything up.

**Comment by nightpool** [comment]
seems like consensus is that we feel fine splitting the current blog into three different group blogs. as soon as I get the new xinbox "answer on other blogs" feature working, I'll do the split. 

does anyone here feel strongly about new-xkit.tumblr.com vs. new-xkit-extension.tumblr.com?

**Comment by dlmarquis** [comment]
@nightpool, I've already created new-xkit-support and new-xkit-discussion. You guys should all send me your emails so I can add you. I'd ask @hobinjk for them, but he'll be unavailable for a while.

**Comment by nightpool** [comment]
@dlmarquis i hit you up over gitter.

**Comment by bvtsang** [comment]
@dlmarquis I also hit you up over Gitter.

**Comment by ThePsionic** [comment]
I hit @dlmarquis before it was cool.

*hit up

**Comment by 0xazure** [comment]
This seems to be complete.  Feel free to reopen if there is more discussion to be had, but separating concerns into separate blogs is established.
