### ISSUE TITLE
track blog tumblr is broken on the /following page

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#288]
![image](https://cloud.githubusercontent.com/assets/233815/9283006/e755dd58-4295-11e5-983c-d76abe6ebda6.png)
mousing over it:
![image](https://cloud.githubusercontent.com/assets/233815/9283011/efc27f00-4295-11e5-8aff-adcbb4a62e2b.png)

**Comment by blackjackkent** [comment]
I'll work on this.
