### ISSUE TITLE
Sporadic update error messages

### ISSUE THREAD

**Issue by windykestrel** [new-xkit/XKit#294]
I am receiving an xkit error message "auto update failed". This happens on and off every few days and though I manually go to update everything, I am not sure why this keeps recurring. Some days I do not receive this message at all, and then it will appear on every page for several days in a row. Any idea what this bug could be?

![xkit error](https://cloud.githubusercontent.com/assets/13815335/9291728/944e40a0-439e-11e5-8043-c47c3a9b2367.JPG)

**Comment by Wolvan** [comment]
Might be useful if you give us your Javascript Console Output. Any errors coming up there?

**Comment by windykestrel** [comment]
Getting a couple name not resolved errors in relation to post limit checker and the get extensions page and a content blocked by client error

![java console 2](https://cloud.githubusercontent.com/assets/13815335/9291772/0dc3bfda-43a1-11e5-8747-ec0aaff09ca9.JPG)
![java console1](https://cloud.githubusercontent.com/assets/13815335/9291771/0dc3bc4c-43a1-11e5-84f5-9de3e3c740c7.JPG)

**Comment by Wolvan** [comment]
That's weird, somehow your browser can't connect to our github service

**Comment by Wolvan** [comment]
You have a script blocker or something?

**Comment by windykestrel** [comment]
I use AdBlocker, but never had an issue with it before. Should I try adding Tumblr to it's whitelist? The odd thing about this issue is that it disappears and reappears every few days

**Comment by windykestrel** [comment]
tried disabling adblocker and still received the error.

**Comment by bvtsang** [comment]
Can you view [the extension JSON](https://new-xkit.github.io/XKit/Extensions/dist/post_limit_checker.json) in your browser directly?

**Comment by windykestrel** [comment]
No, it's not letting me do that

**Comment by bvtsang** [comment]
It seems like something is blocking your access to Github on your end. Do you have any other extensions on your browser?

**Comment by windykestrel** [comment]
I'm currently running AdBlock, MuteTab, and Stylish

**Comment by nightpool** [comment]
@windykestrel This is more likely a problem with your ISP or computer
configuration. Are there any filtering services running on your
computer/network connection?

**Comment by windykestrel** [comment]
No, no filters on my end.
