### ISSUE TITLE
Post Limit Checker seems to be broken

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#296]
>So I tried on a sideblog, also public, and for a second it popped up with a weirdly formatted grey “you have ___ posts left you made \_” above some text in white (I’m not typing verbatim what it says because it literally is only there for a second and then it vanishes before I can read the whole thing.)  This is on the https://www.tumblr.com/blog/_______ page and also happens for my main blogs on that page, but on the https://www.tumblr.com/dashboard page I get the error message I originally reported.

https://gist.github.com/058a20efe3bfda875829

**Comment by nightpool** [comment]
There are two issues here—one with private blogs erroring out when we try
to get their posts, and one with bad formatting on /blog/whatever page.

**Comment by ThePsionic** [comment]
This issue is not about private blogs at all. The reporting user had no private blogs.

**Comment by nightpool** [comment]
@thepsionic the error they reported on their dashboard page is a known
problem with post limit checker and private blogs, as far as I know. Which
user was this? I can't find it on the xkit ask answers sheet.

**Comment by ThePsionic** [comment]
@nightpool just-shannonigans

**Comment by gloomykid** [comment]
i think post limit checker used to be only visible if you go to your blogs view like https://www.tumblr.com/blog/(blogname). but now its also on my sidebar when im simply on the dashboard itself.

**Comment by cherwally** [comment]
Still broken

**Comment by gloomykid** [comment]
ah now its broken for me as well. i took a screenshot of the error code in order to help out some more:

![ss 2015-09-05 at 05 39 04](https://cloud.githubusercontent.com/assets/13604430/9700002/0ea1afac-53f5-11e5-9f3f-790666744c34.png)

**Comment by finagle29** [comment]
@gloomykid do you have any password protected blogs?

**Comment by gloomykid** [comment]
@finagle29 i do, but i thought that the post counter only counts the posts for one blog. and the one i checked was without a password.

**Comment by finagle29** [comment]
as of version 0.2.1 it checks all blogs, which introduced errors if you have private blogs. that specific error should be fixed with version 0.3.0
