### ISSUE TITLE
lint:scripts takes 6s on my local computer

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#298]
can't we partial-compile this? there's no reason to lint scripts that haven't changed.

@0xazure

**Comment by nightpool** [comment]
i love my new "nitpick" label.

**Comment by nightpool** [comment]
Also build:server errors out whenever I save with a jslint error on accident. this makes developing hard :( isn't that like the opposite of what watch should be doing?

**Comment by nightpool** [comment]
here's my error:

````
/Users/evan/tumblr/xkit/Extensions/xinbox.js
  line 1091  col 3  Forgotten 'debugger' statement?

  ⚠  1 warning


events.js:85
      throw er; // Unhandled 'error' event
````

**Comment by 0xazure** [comment]
Incremental builds (and linting) is definitely something on my list of things to do. There are also probably some optimizations I can make around loadtimes; some of the linters load configuration files automatically and hardcoding relative paths can speed this up a bit.

@nightpool as far as the errors, can you open a separate issue for that and @ me? I know what's going on and yeah, it's annoying. It'll for sure be a priority for when I get back.

**Comment by nightpool** [comment]
Thxxxx you're the best.

**Comment by nightpool** [comment]
gulp cached probably solved this issue
