### ISSUE TITLE
accesskit doesn't change font to serif

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#300]
from ask box:
>AccessKit's changing of the font to Serif isn't working (on Chrome).

unconfirmed.

**Comment by staraesthetic** [comment]
I'm on Chrome and I just changed the font to Serif, and same. For the actual body of the text, it doesn't change the font to Serif but for the tags/source/notes/blog url, it does. Also if I hit the explore button, none of it at all shows up as Serif.

**Comment by blackjackkent** [comment]
Duped this myself. 

Amusingly, on closer inspection:
```
font: {
    text: "Post Font",
    default: "default",
    value: "default",
    type: "combo",
    values: [
        "Default Font", "default",
        "OpenDyslexic (might take a while to load)", "opendyslexic",
        "Serif", "sans-serif"
    ],
}
```
The value for the dropdown box is actually listed as sans-serif which is the opposite of true. :P But it loads Palatino Linotype which is a serif font.

I can see it changing the headings on posts but not the post text itself. Likely some new Tumblr style is overriding the extension one.

**Comment by nightpool** [comment]
@blackjackkent mind taking this? should probably be just a matter of adding more !importants I'd expect.

**Comment by blackjackkent** [comment]
Yeah, sure. I gotz it.
