### ISSUE TITLE
no recommended in sidebar always enabled

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#303]
from the askbox.
> I don't have the no recommended enabled in tweaks, and even when I completely disable tweaks, it still hides my recommended blogs.

can't reproduce on xkit 7.7.0, normal extensions.

**Comment by afairlypudgycat** [comment]
flamesofcreation tumblr user here.  I have google chrome up to date and the issue on two of my blogs
https://gist.github.com/anonymous/c91ea042de9161d3533b is the extension export from one of them
https://gist.github.com/anonymous/b4a7f7b7dd00b98dec67 is the extension export from a blog with the same problem
and https://gist.github.com/anonymous/7f3c19f30f00ce80f650 is the export from a blog that doesn't have the problem

The two blogs that have the problem were made later with xkit installed later.

**Comment by afairlypudgycat** [comment]
Omg I'm so sorry, I don't know what it is, but it's not xkit.  I just disabled it and I still have the problem.  I'll keep looking into it, but I'm sorry to have taken your time.

**Comment by blackjackkent** [comment]
I was gonna say...all three of those gists are identical so it's not an extension problem probably.

No problem though! Feel free to let us know if you have any further xkit issues. :)

Closing.
