### ISSUE TITLE
block tracker flickering with slim sidebar

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#313]
from the ask box:
>Just a minor thing - after the update to blogtracker, the numbers have started jumping/flickering around when the mouse moves over them. I've got slim sidebar on, if that matters, and I'm on Chromium (so, basically Chrome, I guess).

followup to #311 @bvtsang

**Comment by bvtsang** [comment]
Although this fixes the issue, I'd like to make sure that

- The CSS looks good on both slimmed and non-slimmed versions
- We preserve the behavior of the ✖ bumping the count to the left
