### ISSUE TITLE
idea: patch notes

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#314]
we could put short patch notes here:
![image](https://cloud.githubusercontent.com/assets/233815/9332894/8e65aada-458c-11e5-90d9-60e876863f01.png)

**Comment by Wolvan** [comment]
We probably would have to rewrite the update result thing for that to work. How would we even distribute the changelog

**Comment by nightpool** [comment]
we could just put them in the dist json. it wouldn't be hard

**Comment by 0xazure** [comment]
Superseded by #679.
