### ISSUE TITLE
ArchivePoster extension causing issues

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#324]
got an ask about posts with asks only and no resposne not showing up on dash, and then this followup:
>nevermind, same person asking about asks not showing up, i did a -lot- of experimentation and found out it was a glitch from an extension i had previously! the (chrome) extension was called Archive Poster, offered by qplus io ! might be worth keeping in mind if any other people come to you with a similar/the same problem

might be worth investigating and adding a check for.

**Comment by dlmarquis** [comment]
@nightpool I saw you tagged the xkit_main extension. Currently browser extensions conflict checks are in the main xkit.js, although those only check for old XKit/missing e installs at the moment. Is there a reason to put it in xkit_main instead? I'm removing the tag for now.

**Comment by nightpool** [comment]
Whoops sorry, I thought they were in xkit_main for some reason i guess.
