### ISSUE TITLE
Remove references to Festivus

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#325]
They were put there by Atesh millennia ago, and it's time to remove them.

**Comment by nightpool** [comment]
any particular reason? If they're not hurting anything it seems fine to let them stay in as just a fun easter egg?

**Comment by dlmarquis** [comment]
Way back when we started the project, we had to turn off part of it in xkit_preferences because it slowed everything down to a crawl. Now it doesn't do anything (at least as far as I can tell), so it might as well be removed.

Unless someone's willing to figure out how to optimize it.
