### ISSUE TITLE
make retags show replies

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#326]
>Hi! First of all thanks for doing what you do! New XKit is awesome and so are all of you! Okay to keep this brief - when using "retags" to show tags on notes, there's an option for the activity graph to only show retags/responses. It's a toggleable option on the activity page. It makes it so only notes with reblog comments or tags appear on the activity page. Can you make it so it also shows replies that people leave using the reply button? Currently it hides those.

seems legit. thoughts?

**Comment by blackjackkent** [comment]
This is easy enough to change; I'll grab it. Do we want to make it do this by default?

(I would venture to say yes since I think the general desire when turning this on is to see when you're getting responses to your content, but I could go either way.)

**Comment by nightpool** [comment]
@blackjackkent yeah probably just do it. replies are responses so its basically a bug-ish-thing that we don't do this currently. (it certainly breaks expectations)
