### ISSUE TITLE
wrap around tags dont work

### ISSUE THREAD

**Issue by karatails** [new-xkit/XKit#328]
For a week or so now, the wraparound tags wont work, even though I tried updating the extension that feature is in. 
Chrome Version 44.0.2403.155 (64-bit)
Mac OSX 10.9.5

**Comment by nightpool** [comment]
are you sure you're on 7.7.0 for New XKit? Can you confirm you uninstalled or disabled Old XKit from your Chrome extensions screen?

If both of these are true, then post your extension info export link. see below for where to find it:
![image](https://cloud.githubusercontent.com/assets/233815/9371014/ac1adbd6-469a-11e5-9250-71782d924dc5.png)

**Comment by karatails** [comment]
yep, both of those are true. 
here is the export info. 
https://gist.github.com/4841c543b16613275654

**Comment by blackjackkent** [comment]
Are you experiencing this in the dashboard or the blog preview sidebar? (Or both?)

**Comment by karatails** [comment]
On the dashboard. 
![screen shot 2015-08-20 at 9 47 38 am](https://cloud.githubusercontent.com/assets/13877208/9389547/95842f72-4720-11e5-98a0-20e015b428e1.png)
You can see it in action here. I have had to slide thr tag to read the rest, as the wraparound doesnt work

**Comment by blackjackkent** [comment]
I can't duplicate this. :/

Possibly you have a preference set that's acting in a way we don't expect. Could you disable your extensions one at a time and see if turning one of them off fixes the problem?

**Comment by karatails** [comment]
I fixed it. Found the conflicting preference. Thanks.

**Comment by blackjackkent** [comment]
Can you let us know what the conflict was so that we can address it in a future fix?

**Comment by karatails** [comment]
It was a disabled feature. My mistake. I disabled the tweaks while trying to fix something else out.
