### ISSUE TITLE
Blacklist won't show hidden post in peepr

### ISSUE THREAD

**Issue by invalidCards** [new-xkit/XKit#329]
http://tjb0607.me/video/xkitbug.webm

**Comment by nightpool** [comment]
This is the same bug as "TagViewer doesn't work on peepr", right? We should
rename that and merge these sidebar bugs that keep getting reported.

**Comment by ThePsionic** [comment]
I don't know, but I made a separate issue since it's a separate extension.

**Comment by nightpool** [comment]
okay watching the video, it seems as if the post is blacklisted, but the show doesn't work. that's a separate problem.
