### ISSUE TITLE
Editable Reblogs literally BREAKS THREADS

### ISSUE THREAD

**Issue by paradox0s** [new-xkit/XKit#346]
I don't know how else to describe what's happening other than "shit's broke". I don't know what triggers it or what could possibly be conflicting. In fact, I uninstalled everything else I had (which basically just amounted to Stylish) and it was still broken. When I temporarily turned Editable Reblogs off, it was proven that it was indeed the source of the issue.

Anyway basically what happens is, seemingly at random. non-text symbols on posts will break when I reblog them. This is especially aggravating on my RP blogs, because it seems to retroactively damage the entire thread me and my partners are working on. An example would be the word couldn't showing up as couldnâ€™t. Numbers and letters seem unaffected it's just symbols like ' and ".

I'm using the Chrome version of new xkit if that matters at all.

**Comment by paradox0s** [comment]
UPDATE: At the behest of one of my RP partners I completely uninstalled Stylish, hit "update all" on xkit, and cleared my cache. Aaaand...still nothing. I also did all that only this time I uninstalled editable reblogs and tested the tamper/greasemonkey version of the editable reblogs script but the issue persists. So whatever it is is affecting both scripts in the same manner.

I'm at my wit's end with this, as a roleplayer who enjoys RP threads it's nothing short of intolerable to deal with.

Aforementioned friend of mine thinks it might have to do with a recent Tumblr update that I apparently missed that further messed up text posts. I'm not sure about the validity of that though since very few other people are reporting this particular issue. But due to the apparent randomness of this problem maybe a lot of people just haven't seen or noticed it yet.

Has anyone else seen this happen? Does anyone more tech-smart than me have any clue what could be up? I can provide more information if it's needed, maybe screenshots?

**Comment by nightpool** [comment]
I've seen this happen but still haven't been able to reproduce it. Sounds maybe like an encoding problem on tumblr's side maybe? If you disable XKit, does the same problem still happen?

can you link blog posts that exhibit this behavior? (Both ones you've made with weird characters and ones which look normal but have weird characters in them when you reblog them, ideally)

**Comment by paradox0s** [comment]
@nightpool I haven't turned off Xkit completely, but I did try switching off Editable Reblogs just to see if it was the source of the issue and it definitely is, because nothing breaks if I reblog things without Editable Reblogs.

http://ask-reboot-turbo.tumblr.com/post/126879263464/ Here's an RP thread that was recently broken. Everything on the other writer's end doesn't appear damaged until after I reblog it.

I also have a VERY strong suspicion that it's retroactively damaging threads, because I know for a fact this thread was undamaged until yesterday, then the entire thread exploded. Even more worrying is that a thread that was dropped over a month ago broke. http://ask-reboot-turbo.tumblr.com/post/124488663129/ Nobody's touched this thread since July.

On my personal blog it's only a minor annoyance because it's pretty easy to fix text beneath gifsets I reblog. But on my RP blogs, I'm growing worried about 3 years worth of RP archives I have breaking.

Also idk if it's worth noting at all, but I did notice on broken threads for whatever reason, a link appears with the name of and link to the original post that began the thread at the top. I've gone through threads trying to fix them just for archival's sake and if you attempt to erase this link, the post refuses to fix, but if you leave it it'll let you fix it. You can see this link in both of the broken thread examples I linked. Here's one that hasn't broke for further evidence: http://ask-reboot-turbo.tumblr.com/post/125277325349/

**Comment by gloomykid** [comment]
i have the same problem, but im still wondering if it is a tumblr problem. because ive seen posts on my main blog with the same damage that arent from RP blogs.
it seems also to affect syntaxes (i.e. - , and ' for don't etc).

**Comment by paradox0s** [comment]
UPDATE: Another RP friend of mine who's been having this issue just noticed a lot of her own threads were breaking too, and she thinks she's figured it out. Tumblr updated recently not to allow nested/manually added block quotes...whiiiiich are things that I and a LOT of other writers/artists make use of just because they look nice in some cases.

Buuuut now it seems that every post that used manually added block quotes and has Editable Reblogs installed has exploded, even if it's a very old post. http://ask-reboot-turbo.tumblr.com/post/117460717459/ Here's another example of a picture I reblogged from my primary blog that made use of block quotes.

**Comment by blackjackkent** [comment]
Given that the above was posted months ago (and therefore should not be affected by editable reblogs at all), and based on a couple of other reports we've received as well, we're inclined to say that this is a bug in how Tumblr is handling its own special character encoding. We're keeping an eye on this, though and will find a way to address it if it's not resolved from Tumblr's side.

**Comment by isnerdy** [comment]
I haven't seen your reblog code, but if it involves working directly with the database, you will have to set the encoding right after opening the connection.  Something along the lines of:

// Create connection
        $conn = new mysqli($servername, $username, $password, $dbname);
        $conn->query("SET NAMES 'utf8'");

**Comment by blackjackkent** [comment]
We do not work directly with Tumblr's database, only with client-side Javascript manipulating information already on the dashboard (and occasionally the API).

You might want to give that note to the Tumblr staff though. ;)

**Comment by ThePsionic** [comment]
It has been confirmed by multiple people in the XKit blog askbox that this issue is not XKit related whatsoever, but rather the remnants of an issue Tumblr had on their end.

**Comment by RENPAGE** [comment]
Are you guys still working on a fix then, or are we going to have to wait for Tumblr to (maybe) fix it? Because from what I heard from a few people, this issue started happening days ago, and we've still gotten nothing from Tumblr.

**Comment by paradox0s** [comment]
Tbh given that Tumblr is Tumblr idk if it's worth counting on them to fix this. Assuming it's a bug at all and not some weird intentional update. It'd make about as much sense as their decision to screw up reblogging in the first place.

**Comment by gloomykid** [comment]
I've sent them a report about this issue to which they just replied with this.

![ss 2015-08-26 at 08 32 32](https://cloud.githubusercontent.com/assets/13604430/9486917/27a76224-4bcd-11e5-83a5-c8690c3910ec.png)

I just copy-pasted the same question again to their "support" even though I was sending the first message to them as well. It looks like they are not interested in fixing this, because I have been ignored in the past 48 hours, when usually it takes them less than 24 hours to reply to every bullshit.

I'll just leave this here, because I might as well agree with the others on here that tumblr won't attempt to fix it, after all they aren't supporting nested blockquotes anymore.

**Comment by ThePsionic** [comment]
I'm not sure if we're seriously expecting Tumblr to retroactively fix the formatting issues. I mean, it's Tumblr after all.

**Comment by RENPAGE** [comment]
I think the most important issue to most people right now is to just get working text. I'd like to be able to write something without it turning into a zalgo mess.

**Comment by paradox0s** [comment]
Just NOT using nested blockquotes for now, at least, WORKS, which is good. But people still have entire archives that have been damaged and for finicky RPers like myself it's torture to have to comb through them manually editing them. And I'm sure I'm not the only one upset about posts on their blogs suddenly breaking into unreadable messes.

You'd think Tumblr would feel some kind of pressure to fix this mistake but. It's Tumblr. So.

**Comment by paradox0s** [comment]
UPDATE: It looks like if you go through any posts that have instances of nested blockquotes and delete them (maybe replace them with bullet points or w/e, doesn't matter as long as you erase the blockquote) and then just wait a while, it'll fix the wonky text, even throughout a long RP thread.

I'm testing this on some of my threads rn but it seems to be working. Still, talk about aggravating.

**Comment by nightpool** [comment]
Hmmm. That's... exceedingly odd, given what kind of issue this is.

if you don't remove the blockquotes, but just make a small edit to the text
(add a period or something), does the same thing happen?

**Comment by paradox0s** [comment]
@nightpool I tried that and it doesn't seem to work, no. Getting rid of the blockquote is the only way to fix it.

**Comment by nightpool** [comment]
This bug is super old
