### ISSUE TITLE
Show originals appears not to work

### ISSUE THREAD

**Issue by bvtsang** [new-xkit/XKit#351]
Via the [support Gitter](https://gitter.im/new-xkit/support):

> \<XKit|86653\> Hey. Thanks for reviving this extension  I was wondering if you knew that show originals appears not to work. This is with all other xkit extensions disabled. I've tried in the latest version of Chrome but not Firefox.
> \<XKit|86653\> It doesn't appear to be in the github issue log.
> \<XKit|86653\> Show originals does still work with the old version of Xkit though.

**Comment by nightpool** [comment]
@blackjackkent is this ready or unconfirmed? Issues shouldn't be both!

If you can reproduce this, make sure to leave a comment with any steps you used.

**Comment by blackjackkent** [comment]
Upon closer inspection, Waffle's "Unconfirmed" column doesn't have a tag associated with it, so evidently it doesn't know to remove that tag when you move it to the "ready" column. :/ We'll have to figure out what to do about this (easiest approach is just to dump that tag, I suppose, and assume everything not marked "ready" is unconfirmed).

In any case, I was able to reproduce this:

Non-original post appears on dash:
![default_orig](https://cloud.githubusercontent.com/assets/13437011/9522811/582c7f7c-4c9c-11e5-9d53-7a882d9f25a3.png)

Install Show Originals:

![show originals](https://cloud.githubusercontent.com/assets/13437011/9522821/637e51f2-4c9c-11e5-9c1e-027249eb3a85.png)

Non-original post still appears on dash:

![show orig doesn t work](https://cloud.githubusercontent.com/assets/13437011/9522825/6a7cceca-4c9c-11e5-9b13-d97177246a1a.png)

**Comment by nightpool** [comment]
@blackjackkent shouldn't the "unconfirmed" tag be associated with the "unconfirmed" column in waffle?

**Comment by blackjackkent** [comment]
@nightpool It should, yes, but you cannot associate a tag with that column.

![image](https://cloud.githubusercontent.com/assets/13437011/9526117/23256e7c-4cad-11e5-9629-ad64477acc81.png)

At least as far as I can tell.

**Comment by nightpool** [comment]
This means that all feature requests/style fixes/non-bug issues are going
to show up in "Unconfirmed". Is this what we want?
