### ISSUE TITLE
Hide suggested posts after reblogging

### ISSUE THREAD

**Issue by bvtsang** [new-xkit/XKit#357]
From [an ask](http://new-xkit-support.tumblr.com/post/127616808478/please-help-me-youre-my-only-hope-you-know):

> PLEASE HELP ME. YOU'RE MY ONLY HOPE. You know those four pictures that show up when you reblog something? Well, most of the time, it always shows Sex, which I am triggered by, and Spiders, which I have a massive phobia of. PLEASE PROGRAM SOMETHING THAT REMOVES IT. I'd do it myself, but I don't know how to program.

Example: https://gfycat.com/SpicyMealyIndianskimmer

Steps to reproduce:

1. Visit your dashboard
2. Reblog a post (not using One-Click Postage)
3. Observe that four suggested posts slide out from the side of the post

**Comment by bvtsang** [comment]
This should probably be added to Tweaks.

**Comment by ThePsionic** [comment]
That's part of No Recommended:
![img](http://i.imgur.com/TcZz4v5.png)

**Comment by bvtsang** [comment]
Oh! Well. Now I just feel stupid.

Thanks for letting me know!
