### ISSUE TITLE
Read More Now shows up as 'undefined' when installed.

### ISSUE THREAD

**Issue by rafflesiazero** [new-xkit/XKit#363]

**Comment by rafflesiazero** [comment]
The Read More Now extension installs fine, but in My XKit, it shows up as 'undefined'. Here's a cap of what does show up in its' place: http://puu.sh/jPQ6S/60af4b9e2c.png

**Comment by Wolvan** [comment]
can you go to http://www.tumblr.com/xkit_editor and open the read more now extension there? Maybe the download somehow failed

**Comment by rafflesiazero** [comment]
Am I supposed to be getting a blank page on everything but the JSON tab?

**Comment by Wolvan** [comment]
Nope, you really aren't. That's why it's giving you trouble. Delete the extension from the XKit_editor and try re-downloading

**Comment by rafflesiazero** [comment]
I did and it's still showing up as Undefined in My XKit.

**Comment by Wolvan** [comment]
Does this happen with other extensions as well?

**Comment by rafflesiazero** [comment]
No, not at all. To test this, I installed Mass Deleter, No Recommended, Old Stats and Timestamps, all of which work well.

**Comment by Wolvan** [comment]
Have you tried manually installing Read more now? Like, go to our repository and copy everything from https://raw.githubusercontent.com/new-xkit/XKit/master/Extensions/read_more_now.js and copying it into the editor?

**Comment by rafflesiazero** [comment]
Just did that and it still shows up as Undefined, even though I got an update from XKit saying that it updated an extension. The JSON this time was different. I only got the string {"errors":false,"error":"parse_error", but now I have this in the JSON: http://pastebin.com/rpLU3NPQ I also don't have any text in the Stylesheet or Icon section.

**Comment by Wolvan** [comment]
I mean, delete the extension in the editor and then create a new extension in the editor naming it read_more_now instead of downloading from extension gallery

**Comment by rafflesiazero** [comment]
That's exactly what I did. I still get the "Unable to load extension panel" when loading it from the MyXKit menu. I did not download it from the extension gallery this time. When I inserted the code manually, I get a blank screen on everything except the JSON that reads, "{"errors":true,"error":"parse_error"}."

**Comment by rafflesiazero** [comment]
I'm still having errors with this. I've done everything listed here and it's still showing up as Undefined. I even reset XKit and it's still giving me errors.

**Comment by Dhwty** [comment]
This problem has apparently never been reproduced, and the afflicted extension has been updated several times since this report. (And any affected browsers have probably also updated several times.)
