### ISSUE TITLE
Automate rebuilding distribution

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#365]
It would be nice to take CI a step further and have it automatically rebuild our distribution files after a successful merge into master.  We can create a new `gulp ci` task that does all the linting and test checks, then builds the dist files and commits them back to `gh-pages` for us.  We've even got [NewXKitBot](https://github.com/NewXKitBot) as a member of the org (thanks @Wolvan) that we could use as the 'committer'.

/cc @hobinjk

**Comment by Wolvan** [comment]
Sure, that's do-able. I could make a bot that rebuilds either daily or on commit of a new extension if you guys are cool with that

**Comment by 0xazure** [comment]
We don't even really need a bot.  From my understanding it's perfectly doable to have Travis execute all of this for us.  I only brought up NewXKitBot to suggest we use its credentials to commit, rather that one of our own accounts.

**Comment by Wolvan** [comment]
Oh, I get it. Well, if we can supply travis with NewXKitBot's credentials and Travis does the building on repo change, good enough for me

**Comment by 0xazure** [comment]
Might be slightly trickier than I had anticipated since we're using homu to pre-test our PRs _before_ they get merged, we never actually run tests on `master`.  And I don't exactly like the idea of merging `auto` into `gh-pages` in order to build the extensions.

**Comment by 0xazure** [comment]
Useful reference guide we can possibly tweak for use with the project: http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/

**Comment by Wolvan** [comment]
the problem is still that we aren't running tests on ``master`` with Travis, or are we? Personally I'd say having a nodescript listen for a gh webhook might be a lot easier than having travis built. Or how could we make sure that it builds without running test on master?

**Comment by 0xazure** [comment]
We _are_ currently running tests on master; if you check [the branches on Travis](https://travis-ci.org/new-xkit/XKit/branches) it's right up there at the top as the 'default branch'.  It's just less obivous because homu runs pre-merge tests on a separate branch before merging into `master`.

Setting up CI to do this for us would be _significantly_ easier than setting up a webhook, and would also mean we won't have to spin up or maintain any of our own infrastructure to handle it.

**Comment by Wolvan** [comment]
OK, nevermind, you got me there. All up for having travis rebuild our distribution! I'll look into this.
