### ISSUE TITLE
Blacklisted posts do not get shortened

### ISSUE THREAD

**Issue by invalidCards** [new-xkit/XKit#386]
1. Have Blacklist and Shorten Posts installed.
2. Find a blacklisted post and unhide it.
3. Expected: The just unhidden post gets shortened.
4. Actual: The unhidden post does not get shortened, even if the height is larger than the set treshold.

**Comment by GoesOnGhost** [comment]
If it's any help, these extensions work together if Shorten Posts is installed before Blacklist.
