### ISSUE TITLE
Middle mouse clicking with Open in New Tab opens 2 tabs

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#387]
1. Have Open in New Tab installed
2. Middle-mouse click on a blog link
3. Expected: A new tab opens, going to the specified blog
4. Actual: Two new tabs open, going to the specified blog

**Comment by blackjackkent** [comment]
I can't dupe this; it only opens in one tab for me.

**Comment by ThePsionic** [comment]
Might want to have mentioned this is in Chrome. Testing in Firefox shows it does work correctly.

**Comment by ThePsionic** [comment]
Seems to have been a glitch in the system somewhere. Can't reproduce myself anymore; closing.
