### ISSUE TITLE
Blacklist URL checking is broken

### ISSUE THREAD

**Issue by invalidCards** [new-xkit/XKit#389]
From a set of asks:

> Kind of a report, kind of a question. The Blacklist feature seems to only be working half the time when it comes to blocking stuff when I have it listed. There's one user in a tag that I visit often that has no special characters or anything in their name other than letters, but they always manage to escape being blocked/hidden by Blacklist, and they're very gross. Are there any known issues with the extension at the moment? Do usernames/URLs not get blocked if added to the Blacklist? Thanks!

[time passes]

> Hey there! Sorry to bug (no pun intended) ya again. Just wanted to inquire about the state of the Blacklist feature and if you awesome people had gotten any work done about the bug I sent in a few weeks ago. I saw that a Blacklist update went out but after a bit of testing I can tell the bug is still there, sadly. Thanks for all your work!

**Comment by nightpool** [comment]
i'd actually like to re-write blacklist to make it work more like tumblr
savior, since so many people have problems with it.

**Comment by Wolvan** [comment]
how does tumblr savior work compared to XKit Blacklist, @nightpool ?

**Comment by hobinjk** [comment]
Almost definitely fixed by recent efforts
