### ISSUE TITLE
Make tag blacklisting more strict

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#392]
> I think that #bh guy is running into the same problem I am - I added #ob to my blacklist because someone I follow tags Orphan Black posts with that but Blacklist is hiding every post with a tag that has the letters "ob" in it, like posts tagged "#<something>, probably" or "#wardrobe."

**Comment by AprilSylph** [comment]
closed thanks to tumblr's new "tag filtering" feature
