### ISSUE TITLE
Profiler extension bug

### ISSUE THREAD

**Issue by albinakarambura** [new-xkit/XKit#396]
I noticed that sometimes profiler extension disappears from user menu. 

![image](https://cloud.githubusercontent.com/assets/1273206/9566936/39ed7204-4f22-11e5-8455-78eb4a98ec12.png)
I only have 3803 likes in total, so that can't be right. It appears that the counter is broken too.

and the timezone doesn't show at all.
![image](https://cloud.githubusercontent.com/assets/1273206/9566950/a87a4b3e-4f22-11e5-9a73-13dde927c554.png)
just loading dots

I use both Chrome and Firefox interchangably from time to time, and these issues come up in both,

**Comment by nightpool** [comment]
closed because old
