### ISSUE TITLE
Return to the olds chains... or make them scrollable

### ISSUE THREAD

**Issue by jristz** [new-xkit/XKit#407]
Follow official Tumblr staf page, the next regression is this:
http://support.tumblr.com/post/128127169452/ever-see-a-crazy-long-indecipherable-reblog-chain
This will make chains literally exponentially longers like those from RP blogs.

I post this here before to let know this and prevent complains when the update break the add-ons related to chains.

**Comment by nightpool** [comment]
Closing for now as we don't current know what the situation is going to be code wise or what we're going to try to accomplish. Rest assured that we're committed to doing as much as we can though. 

For more information, check our latest post on [the xkit announcement blog](http://new-xkit-extension.tumblr.com)

**Comment by nightpool** [comment]
We'll make sure to create issues here as soon as we've come up with a plan of attack.

**Comment by jristz** [comment]
The update is here and look like break images in reblogs too.

**Comment by nightpool** [comment]
What do you mean?

**Comment by jristz** [comment]
Reblog blockquote, Tumblr change it, side efects are user blacklist is
broken, colored blockquote broken,  images in blockquotes broken an any
functionality related to reblogs' blockquoting

**Comment by jristz** [comment]
#419 #420 #421 are "duplicated" in the sence, they report problems and breakages with the new reblog blockquote mode, and #416 is noe of the side effects of the problem tumblr-savior work ok in blocking users.
