### ISSUE TITLE
Wrap tags on in-dashboard blog panel

### ISSUE THREAD

**Issue by noahleigh** [new-xkit/XKit#408]
With the "wrap tags" tweak enabled, it doesn't wrap tags in the sidebar-blog-view, and those tags are unscrollable because the tweak disables that.

**Comment by nightpool** [comment]
this is a duplicate of https://github.com/new-xkit/XKit/issues/194

only happens to some users, and inconsistently at that.

**Comment by noahleigh** [comment]
Thanks, I've subscribed to that issue now.

**Comment by nightpool** [comment]
reopening this because further investigation reveals this is a separate issue.

**Comment by noahleigh** [comment]
Details?

**Comment by nightpool** [comment]
Looking into it now, but this seems to be tag wrapping specific—unlike the issue I liked to which was a global issue with all of the blog sidebar and xkit extensions
