### ISSUE TITLE
When browser is unable to load to secure websites, Retags is messed up.

### ISSUE THREAD

**Issue by rafflesiazero** [new-xkit/XKit#411]
More thorough description is when my browser is unable to resolve the connection to sites starting with HTTPS or even HTTP, I get an error message from Retags stating that it has encountered an invalid or illegal string, which it's then strongly recommended to restart XKit because of this. So, I hit the button to reset XKit, but it still stays up, so I have to hit the OK button. 

Normally, a browser restart is all it takes to fix this problem, but it's weird that because of this that the only extension that's giving me this error message is Retags and not the entire addon itself. 

I can see if I can replicate the problem again to get an exact wording of the error screen I get from XKit if you'd like.

**Comment by nightpool** [comment]
If you can't load http sites, then you can't use a browser at all, so I'm
not sure that's what you meant.

if you just can't load https sites, then how are you using tumblr? As far
as I can tell tumblr is https-only.

**Comment by rafflesiazero** [comment]
Right, that's what I meant. This only happens every once in a while, however a simple browser restart fixes everything and Retags doesn't show up as being broken, but it's only with this instance that it does.

**Comment by rafflesiazero** [comment]
Here we go, this just happened a few minutes ago, but now I'm able to connect to Tumblr. 

http://puu.sh/k6zcA/83fb824db1.png

**Comment by 0xazure** [comment]
From your screenshot, I notice that you're trying to run XKit on Pale Moon.  Note that we do not officially support Pale Moon, or anything other than latest Chrome or Firefox releases, at the current time.

A member of the community [has provided Pale Moon installation instructions](http://new-xkit-extension.tumblr.com/post/127647956059/new-xkit-on-pale-moon-kludge), but we do not officially support this method, and are unable to assist with any problems resulting from using XKit with unsupported browsers.

**Comment by nightpool** [comment]
Also, its not just the screenshot—this is a browser/computer/network level
bug. If you can't load Tumblr, then xkit just won't work. simple as that.
