### ISSUE TITLE
AccessKit font increase broken in main post body

### ISSUE THREAD

**Issue by sobekstar** [new-xkit/XKit#424]
Howdy! Since the new reblog changes, AccessKit no longer boosts font sizes in the main post body, though it does appear to still work on other text such as usernames and tags.

And now it appears as though using a quote in the post body makes the font *even smaller*, as seen here: https://i.gyazo.com/fafe4eb0afd46f28cb316ea1c638e9ea.png
It's nearly impossible for me to read.

Here is AccessKit enabled: https://i.gyazo.com/7fba212c5b4359145e4ec93a1d5ae586.png

Disabled: https://i.gyazo.com/3036c29f4a35ba42b0c31fcd3bef71a7.png

I hope someone is able to give AccessKit and Color Quotes a little love for the visually strained among us! Thank you so much for everything you do.

**Comment by nightpool** [comment]
editing out the color quotes stuff since that's a separate issue. AccessKit is a legit bug though.
