### ISSUE TITLE
Post titles not displaying on editor screen when reblogging with Editable Reblogs

### ISSUE THREAD

**Issue by blackjackkent** [new-xkit/XKit#437]
Doesn't actually affect whether title gets posted (it does), but might confuse people.

**Comment by rimbaum** [comment]
Adding to this, I'm wondering if it will be possible to edit the titles again at some point? This is important in some parts of the RP community.

**Comment by nightpool** [comment]
@rimbaum unclear. we're tracking it at issue #441

**Comment by nightpool** [comment]
fixed by #438
