### ISSUE TITLE
Quick Reblog defaults to wrong blog

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#44]
One Click Reblog defaults to incorrect blog. May be fixed.

**Comment by bvtsang** [comment]
I've tried the following steps to reproduce:

1. Ensure One-Click Postage is enabled
2. In its options, select default blog
3. Go to your dashboard and hover over a reblog icon on any post
4. On the reblog popup, expect that the default blog is selected

Unless I'm misunderstanding something, this seems to work.

**Comment by WyohKnott** [comment]
It works. But if you reblog something to a not-default blog, the subsequent One-Click popups will be set on the last blog used. I'm not sure if this is the intended behaviour, nor what most users using this option want.

In order to fix this, we should add a check for ```preferences.default_blog``` in ```open_menu```

**Comment by bvtsang** [comment]
Steps to reproduce:

1. Ensure One-Click Postage is enabled
2. In its options, select default blog
3. Go to your dashboard and hover over a reblog icon on any post
4. Switch to a non-default blog
5. Click Reblog
6. Still on the dashboard, hover over a reblog icon on any post
7. Expect that the default blog is selected
8. Observe that the last picked blog is selected

Upon refresh, the default selected blog reverts back to what you picked in the options.
