### ISSUE TITLE
blank xkit window (chrome)

### ISSUE THREAD

**Issue by 04tobizbits** [new-xkit/XKit#449]
xkit window appears blank in all tabs. chrome and xkit are updated, window still appears blank if any other extensions are disabled/uninstalled. xkit window will sometimes load, but after closing it will return to being blank.

**Comment by KirytheStitchWitch** [comment]
This has been an issue for me for months also. I've uninstalled and reinstalled a bunch of times but no luck. Chrome is always up to date, New Xkit is always up to date, but i've been looking at this for a while now.

![capture](https://cloud.githubusercontent.com/assets/17215885/13027264/5f1c4794-d20d-11e5-8cc2-eea3e71fd16b.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17215885/13027265/5f1d3cbc-d20d-11e5-9605-6b341b8658b0.PNG)
![capture3](https://cloud.githubusercontent.com/assets/17215885/13027266/5f1f56fa-d20d-11e5-8921-48df4fd69151.PNG)

I also can't get any of the xkit blogs to load unless i open them in IE, which is understandably painful. >_>

**Comment by Wolvan** [comment]
You set a wrong filter in adblock. This is not XKit related.
