### ISSUE TITLE
Retags broke with the latest update

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#450]
> The update of Retags actually STOPPED it working for me as it should have. I'm using Firefox 40.0.3 for Mac. Tags show up on the activity page (as they always did), but not in the Notes pop-up in the post on the dashboard.

**Comment by devmackie** [comment]
I submitted this Ask. More info: The greasemonkey script available from http://lx.tumblr.com/post/86030948950/retags works. So I uninstalled the XKit version and used that instead.

**Comment by Wolvan** [comment]
@devmackie I think someone of our team is working on a fix for retags and tagviewer right now

**Comment by Dhwty** [comment]
Pretty sure this issue was fixed in #1006 .

**Comment by nightpool** [comment]
@dhwty thanks!
