### ISSUE TITLE
Pressing J doesn't always navigate to next page

### ISSUE THREAD

**Issue by bvtsang** [new-xkit/XKit#451]
Steps to reproduce:

1. Install J/K Across Pages
2. Settings > Dashboard > Disable endless scrolling
3. Visit your dashboard
4. Keep pressing J until you reach the bottom of the scren
5. Press J
6. Expect to navigate to next page
7. Observe that nothing happens

This doesn't happen all the time, but I can reproduce it fairly reliably.

**Comment by nakengelhardt** [comment]
This happens when the last post on the page is shorter than the screen and the top of the post is still visible. I have a fix for this, let me figure out how to do pull requests...

**Comment by bvtsang** [comment]
@nakengelhardt FYI, I have a working fix for this in #452.

**Comment by nakengelhardt** [comment]
Oh nice, let me try yours then!
