### ISSUE TITLE
editable reblogs can't reblog one-click reply

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#454]
trying to reblog [this post](http://jabyrwock.tumblr.com/post/128351027935/nightpool42-replied-to-your-post-support) fails under editable reblogs:
![image](https://cloud.githubusercontent.com/assets/233815/9693830/758679ac-5321-11e5-91ad-9dfd054da4e6.png)
when I try to reblog:
![image](https://cloud.githubusercontent.com/assets/233815/9693834/8420f744-5321-11e5-814a-baaa35b7497e.png)

**Comment by dlmarquis** [comment]
Is this still true after all the updates (we and) Tumblr pushed?

**Comment by dlmarquis** [comment]
Okay, some bizzareness I've found: the reblogged reply looks bugged out on the dash (with and without Reblog Display Options), but looks fine on individual blogs. So the html isn't getting eaten, but won't display anyway.

Are you sure this is related to Editable Reblogs, @nightpool?

**Comment by nightpool** [comment]
@dlmarquis hmm I guess I've just been thinking about it as "in that problem
area" rather then being an actual ER bug.

**Comment by nightpool** [comment]
ancient enough that this probably still isn't an issue
