### ISSUE TITLE
Servant selection is wrong

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#456]
Pasting from Gitter:
>I've noticed a strange bug in Servant
If you for instance make a servant that says "If I'm on dashboard and the post is original, highlight it" it does activate on the inbox
But if you say "If the post is original and I'm on the dashboard, highlight it" it doesn't activate on the inbox

**Comment by bvtsang** [comment]
This issue is closed as a duplicate of #459, which has actual steps to reproduce. I know this issue number is lower than the other, but I thought I'd include the actual reason in case anyone looking at this bug was wondering why it was closed.
