### ISSUE TITLE
Servant logic ignores all but last condition

### ISSUE THREAD

**Issue by finagle29** [new-xkit/XKit#459]
Steps to repro:
1. make new servant with multiple conditions (e.g. post type is, post is from, post is original, etc.)
2. observe that the action is performed only when the last condition is met

**Comment by ThePsionic** [comment]
I'm fairly sure this bug is the same as I described on #456 but I'll close that one because this one has actual repro steps.

**Comment by blackjackkent** [comment]
Are servant's conditions ANDs or ORs? Cos if they're ors, then this is expected behavior, no?
