### ISSUE TITLE
Themes: Image option is broken

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#46]
This is more a people-should-be-told-how-to-update-themes thing, as Themes+ handles images correctly. Unfortunately the story for updating Themes is currently terrible.

**Comment by gloomykid** [comment]
also using themes+ and it kind of broke the header, too.
http://puu.sh/jlYJ6/cd4360e5fb.jpg
whenever i stopped using themes+ this is not a problem, but as soon as i create a new theme and enter a background image, this happens.

**Comment by ThePsionic** [comment]
Closing because I'm fairly sure this was fixed in #545.
