### ISSUE TITLE
No return type tooltips in Servant

### ISSUE THREAD

**Issue by finagle29** [new-xkit/XKit#460]
according to atesh's [documentation on servant](http://xkit.info/servant/), there should be tooltips explaining return types of cause servants, but when i hover on the icon, there's no tooltip

**Comment by ThePsionic** [comment]
Starting work on this.

**Comment by ThePsionic** [comment]
Ergh, unclaiming. I can't figure out for the life of me why TipTip does what it does.

**Comment by AprilSylph** [comment]
problem was TipTip CSS being set to something visible *before it existed at all*; opening a second "Add Servant" window would allow it to work. resolved in #1536
