### ISSUE TITLE
XCloud downgrades automatically after browser restart.

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#461]
When using the XCloud migration guide to upgrade to 0.3.0. and changing the set ups in the XKit editor, it's all fine.

But as soon as the browser is closed and opened again, tumblr tells me about some "update" to "XCloud 0.2 REV B", which is obviously a downgrade again.

After that, I have to go the XKit editor again, copy paste the 0.3.0 text into XCloud to make it work again, because otherwise it is impossible to sync (figures, because it is using the old version).

When migrating, I did not check the box for "using old servers".

Using Chrome, Win7.

**Comment by Wolvan** [comment]
That is a problem with ``` xkit_updates ``` and I already wrote a fix for that, see #440
