### ISSUE TITLE
Themes: Updating built-in themes is impossible

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#47]
Themes currently live in a .json file pulled off of xkit.info, which is kept [here](https://github.com/hobinjk/XKit/blob/gh-pages/Extensions/dist/page/themes.json) for now. It would be nice to have the same type of rebuilding infrastructure for themes as we have for the extensions themselves.

**Comment by 0xazure** [comment]
I can take this one.

I'm thinking something like the following for a directory structure?

```sh
├── Chrome
├── Extensions
├── Firefox
├── Themes
...
└── LICENSE
```

and then separate out each theme like how the extensions are separated out.
