### ISSUE TITLE
"Get Extensions" never loads

### ISSUE THREAD

**Issue by FluffyLee22** [new-xkit/XKit#472]
Ive been sitting here for over 30 minutes, waiting for the tab to load the extensions so i can get back to posting. I had no problem with Firefox, but Chrome wont load. I have been sitting here for feels like forever for the thing to load the icons. 
Is this a bug or my computer just full of crock?

**Comment by Wolvan** [comment]
Make sure your chrome is updated. The current version is 45, but 44 also works

**Comment by FluffyLee22** [comment]
its all up to date.

**Comment by Wolvan** [comment]
and it's still not working? Can you open https://new-xkit.github.io/XKit/Extensions/dist/page/gallery.json

**Comment by FluffyLee22** [comment]
yup and i get a page full of text... like legit text on the entire page.

**Comment by Wolvan** [comment]
can you press Ctrl+Shift+J and then try open the extension gallery?

**Comment by FluffyLee22** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14176523/9742084/fd4665c0-5612-11e5-9fa5-1db70ddae2da.png)
yeah i did the Ctrl+Shift+J thing and this is where it took me... if you wanted extensions i can get there from my google options thing on the right corner there... 
do i need to be here? is there something missing im  not seeing or... do i need to be in the extensions setting.... im so confused right now i dont code... i see big text and i flip thinking i broke something... sorry if im coming off a bit here im just a little stressed...

**Comment by Wolvan** [comment]
No, you actually opened your downloads (Ctrl+J)
F12 should also be opening the developer console, you just have to click on the "Console" tab then

**Comment by FluffyLee22** [comment]
ok so i have that open now... im in "Console" .... and its blank.

**Comment by Wolvan** [comment]
refresh the page and then open the extension gallery again

**Comment by FluffyLee22** [comment]
dude this litterally did nothing.... all i did was open a little box that is blank at the bottom of my browser and refresh my tumblr page... just to be sure i wasnt messing up i refreshed all of my pages... what did this do? Xkit is working on my Chrome, HOWEVER the "Get Extensions Gallery" just wont load. everything else works.

**Comment by Wolvan** [comment]
The console is there to show some errors that might have happened in the background which we don't properly ctach in XKit.

**Comment by FluffyLee22** [comment]
WHOA HOLY... ok now im scared again. i opened the thing thinking it was for the browser so when it was blank i was confused but now im scared because i opened it on my tumblr page and ther are yellow and red codes all over and i dont know what im looking at

**Comment by Wolvan** [comment]
Don't worry about that, just open the extension gallery and screenshot what you have in the console

**Comment by FluffyLee22** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14176523/9742592/15b23528-5616-11e5-85e2-10a0a700aeeb.png)

**Comment by FluffyLee22** [comment]
is this what you needed?

**Comment by Wolvan** [comment]
yeah. Can you give me the exact version of chrome and XKIt?

**Comment by FluffyLee22** [comment]
my chrome is Version 32.0.1700.102 
and XKit is  7.7.0

**Comment by Wolvan** [comment]
There is your problem, @FluffyLee22.
>Make sure your chrome is updated. The current version is 45, but 44 also works

**Comment by FluffyLee22** [comment]
but it wont let me update... : I  should i just uninstall Chrome and reinstall it? like there is no option to get an update.

**Comment by Wolvan** [comment]
try redownloading chrome, yes. Versions that old have trouble updating by themselves

**Comment by FluffyLee22** [comment]
ok... sorry for the hassle i REALLY dont know computers and i get frustrated when thrown into something like this and nobody helps. 
ill just reinstall chrome and try new...

**Comment by Wolvan** [comment]
If it doesn't work you can always come back here. If it works you can come back as well so we can close this issue, alright?

**Comment by nightpool** [comment]
closing in favor of a new issue tracking warning old chrome users
