### ISSUE TITLE
Replyviewer and Tagviewer icons not available in sideview

### ISSUE THREAD

**Issue by ShareNoMimosa** [new-xkit/XKit#491]
after the new update, when clicking on a note from the activity page it loads multiple posts from that user's blog instead of just the post's permalink like it used to so you can't use the replyviewer or tagviewer extensions from that sideview

**Comment by bonme** [comment]
^^ having the same issue

**Comment by laurajax** [comment]
The icons also do not appear in the sidebar for me.

I don't think it's related to loading multiple posts though; the sidebar loads just one for me and the icons still don't appear.
@k11mamaes As for you loading multiple posts in the sidebar, it might be related to the fact that tumblr staff took out the "see more posts from this blog" button in the sidebar and instead uses the site's "infinite scrolling" function to decide when to load those posts. For me, if I click a notification on the activity page to open a post in the sidebar, it loads the blog sidebar and the post, and then as soon as i scroll the sidebar down at all, it loads the blog's posts. Does this seem like what you're experiencing in that regard?

**Comment by prince-vince** [comment]
I'm having the same problem as @laurajax

**Comment by k11mamaes** [comment]
@laurajax yeah i checked again.  it loads the post and infinite scrolling loads posts to fill any space below if you scroll down.  but yes no icons.

i looked at the html a little.  when posts are loaded in the sideview, the post controls (reblog, like, etc) are contained within a div with class "post_controls".  however, when posts are loaded on the dashboard, within the "post_controls" div, there's another div with the class "post_controls_inner" which contains the post controls.

havent looked at any code for the extensions, but this might be the problem?

**Comment by ShareNoMimosa** [comment]
i just looked at the code, it is in fact a problem with the different class names, but that problem is originating within the XKit.interface.add_control_button function.  ill see what i can do

**Comment by ShareNoMimosa** [comment]
@blackjackkent this issue can be closed
