### ISSUE TITLE
Chrome's GM_listValues looks in the wrong place

### ISSUE THREAD

**Issue by finagle29** [new-xkit/XKit#493]
as noted by @nightpool in [xkit_patches.js#L228](https://github.com/new-xkit/XKit/blob/master/Extensions/xkit_patches.js#L228), chrome's `GM_listValues()` doesn't work; it looks in `window.localStorage` which is empty unless you have Retags.  This causes the check on line 228 to go awry and the full config dump is empty.

**Comment by finagle29** [comment]
A long term fix would include some changes to the Chrome bridge, I have a fix ready if we decide to do this.
A short term fix would probably just be changing `if(values.length === 0)` to `if(XKit.browser().chrome)`.

**Comment by nightpool** [comment]
This isn't really a bug, as we don't use listValues in any user-facing extension. Still would be good to get fixed though!
