### ISSUE TITLE
Readmores converting to hr lines with editable reblogs enabled

### ISSUE THREAD

**Issue by rimbaum** [new-xkit/XKit#507]
[This post] (http://txmekeeper.tumblr.com/post/129317891468/txmekeeper-txmekeeper-test-post-keep) is an example of what I've been getting when I try to insert a readmore into a post with xinbox enabled. My extension configuration export is [here] (https://gist.github.com/anonymous/601c3893bd5ac1ddbef1), and there's a screenshot helpfully provided by @blackjackkent of the offending post on the dash.

Feel free to reblog that post as much as you want to test it, it's on an unused sideblog.

![nolines](https://cloud.githubusercontent.com/assets/4296434/9950345/9f740304-5d87-11e5-9bf8-0996ca959a20.png)

**Comment by selloutoftheshield** [comment]
![capture](https://cloud.githubusercontent.com/assets/14349960/9963920/9643e1c2-5dfb-11e5-9aa0-dcb80910f448.PNG)
That's what mine looks like

**Comment by anakhasilver** [comment]
I can confirm Read Mores are messing up.

**Comment by artist-chan** [comment]
i have the same issue:

![readless](https://cloud.githubusercontent.com/assets/14369115/9980094/ed5aff7c-5f8b-11e5-8ed4-1930c0bab432.png)

**Comment by gloomykid** [comment]
can confirm that too, it's a mess for RPers who need read mores...

**Comment by dlmarquis** [comment]
This isn't related to xinbox, but is likely related to the editor-specific routines added recently by @blackjackkent. This post: http://new-xkit-support.tumblr.com/post/129557893718/hello-loves-we-seem-to-be-experiencing-an-issue covers the details.

**Comment by nightpool** [comment]
reopening because according to @blackjackkent this still happens if you have multiple readmores in the same thread.
