### ISSUE TITLE
Add "more info" button to extensions in gallery

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#510]
Similarly to the "more info" button when an extension is installed, add this to the gallery as well in order to let people know what something does before they install it.

**Comment by Wolvan** [comment]
Just found out that this is actually a part of ``xkit_preferences`` (See https://github.com/new-xkit/XKit/blob/master/Extensions/xkit_preferences.js#L1091-L1093) already, we just have to add a details field to each extension in the gallery.json
