### ISSUE TITLE
Chat post gives "Invalid Editor Type"

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#515]
http://prntscr.com/8hseig
This is the user's gist: https://gist.github.com/anonymous/c325144bd42e17ddedc2
Already went through most of our common trouble shooting, couldn't track down the issue. Can't reproduce locally either
It only seems to happen on creating or reblogging a chat post though

**Comment by nightpool** [comment]
this is a regression introduced by #504 and specifically, not bailing out of running on a post_window when the post doesn't have a reblog_tree.

we should check if the html editor is a thing and bail out at the top of that function

**Comment by nightpool** [comment]
@Wolvan just as an FYI—issues should not have both the "bug" and "unconfirmed" labels at the same time.

either something is a bug, or its an unconfirmed problem people are having. until we can confirm it, it isn't a "bug" yet.

**Comment by Wolvan** [comment]
@nightpool ah ok. I thought unconfirmed was like couldn't reproduce

**Comment by nightpool** [comment]
It is, but we just set it up this way to make the filters work better.
Unconfirmed is "can't reproduce", Bug is "can reproduce".

**Comment by Wolvan** [comment]
gotcha
