### ISSUE TITLE
Don't automatically hide installed extensions from Gallery view

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#517]
Currently,  extensions that are already installed get hidden from the extensions list in the Gallery.

Instead, the Gallery should display the entire list of extensions but extensions that have already been installed should be marked as such and the "install" button should be disabled.

There should also be an option flag somewhere that allows users to hide installed extensions from the gallery view, but this should be _off_ by default.

**Comment by Wolvan** [comment]
I am curious, why should the extensions stay visible?

**Comment by 0xazure** [comment]
Partially related to issues [like this](http://fastcst.tumblr.com/post/129453604167/my-xkit-came-back-but-there-are-loaves-of-bread), where people forget which extensions they have installed and there's no good way, currently, to see a list of what you have and have not installed.

I've actually been tripped up by this in the past when testing extension fixes; I forget what's installed or not, and get confused when something doesn't show up in the gallery doesn't.

Not to mention literally no other extension / app store I'm aware of hides stuff you'v installed, they all mark the entry as "installed" so that you know it's available for use.

**Comment by Wolvan** [comment]
Alright, I get your point. If you want I can look into this tomorrow

**Comment by dlmarquis** [comment]
As a sidenote: make sure core extensions are still hidden unless the user has flipped the viewable switch.

**Comment by Wolvan** [comment]
@dlmarquis Will do!

**Comment by Wolvan** [comment]
![image](https://cloud.githubusercontent.com/assets/1437010/9982555/b1fb634a-5fe0-11e5-9b8a-ccbc7f9526ce.png)
Which design would be better?

**Comment by Dhwty** [comment]
The left is much more readable. On the right, you're running into contrast problems which can keep users with visual difficulties from figuring out which extension that is. ('Sure, I installed it at some point, but WHAT IS THAT?') I can say that because I'm having some difficulty reading it.

**Comment by 0xazure** [comment]
:+1: for the left design.  I've never liked the full-tile state change, it was just less noticeable before because as soon as you clicked away from the Gallery it would hide the tile.
