### ISSUE TITLE
Read more not showing up when using Editable Reblogs

### ISSUE THREAD

**Issue by VixenArgentum** [new-xkit/XKit#519]
Whenever I have the Editable Reblogs extension enabled, I cannot insert a functioning read more break.  When I post it, it shows a little line where the read more should be, and then posts all of the content I wished hidden below it.  It looks like this:
![noreadmore](https://cloud.githubusercontent.com/assets/14366729/9979067/b8b460c8-5f0a-11e5-84c7-ad728a4a1d14.png)

**Comment by dlmarquis** [comment]
Are you sure this is editable reblogs? I can't reproduce this, but I don't have Better Reblogs installed and it looks like you do. Does it also get fixed when you disable Better Reblogs (or whatever you're using to bring back nested reblogs)?

**Comment by paradox0s** [comment]
Actually as far as I can tell this is caused by the Stylish extension, "Classic Editor". When I disabled that read mores started working for me again.

**Comment by Dhwty** [comment]
I'm using 'Classic Editor', and I can't reproduce this problem.

**Comment by VixenArgentum** [comment]
I've been able to get it to work again.  I did have the extension FixMyPosts enabled, and now that I've got that shut off, Editable Reblogs is working for me again.
