### ISSUE TITLE
Editable Reblogs fails when images inserted into posts 

### ISSUE THREAD

**Issue by AuraSweet** [new-xkit/XKit#523]
Whenever I go to input a gif, and then try to put text under it, the text goes away completely. Then when I edit it, the text is still gone.

**Comment by AuraSweet** [comment]
And I also can't reach anybody on Xkit support.

**Comment by blackjackkent** [comment]
I'm looking into this now -- we've had a couple of reports of it and I think I've located the root cause with a brute force fix. I'll be putting together something better tomorrow hopefully.
