### ISSUE TITLE
Replace XCloud

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#53]
Provide a good way of transferring settings between XKit installations. The likely way to do this is by leveraging browsers' built-in addon synchronization primitives. The main blocker is that extension scripts should be stored outside of the synced storage.

**Comment by rimbaum** [comment]
If I can make a recommendation, as someone with multiple browser profiles set to sync with different accounts: Perhaps also an "export preferences" option that will create a file with all of your settings, and can be imported regardless of syncing options.

**Comment by Ledyard** [comment]
Just for a heads up I started to take a whack at getting the old version of xcloud working earlier this week.  Currently it's in a prototype stage and is working on my vps.  https://codeandthings.com:3082

You can see the source here.
https://github.com/Ledyard/XCloud

I set it up to use nodejs since php sounded like more of a pain.

Also I have it set up using AWS S3 and DynamoDB so if we're lucky we can use the free teir if we go this way.

**Comment by Ledyard** [comment]
For a future version, just using the browser's built in sync would be nice and fast.   It just depends if we want to support cross browsers or if there is an enhancement to allow third parties to plug into the xcloud service to say manage their tumblr mail or something.

Another solution I've been thinking of is having the plugins handle what the want to upload and receive.  So each plugin would have something like a dirty flag xcloud would pick up on and upload the settings.  This would allow us to auto sync and merge so we aren't constantly overwriting the plugins.

**Comment by noahleigh** [comment]
Until automatic syncing can be implemented, I agree with @rimbaum that having a manual export & import settings ala Tumblr Savior would be very helpful for getting everything together on the multiple browsers I use.

**Comment by nightpool** [comment]
@noahleigh you can do manual export in the "other" pane.

I've yet to build a manual import, since its a little more involved and
less useful for support, but if there's significant interest I could
probably be persuaded.

**Comment by hobinjk** [comment]
@nightpool There is definitely significant interest for when people are setting up New XKit across multiple browsers/computers. Once we have an XCloud replacement it will be less useful, but given the debilitating effect not having XCloud has had on users this would be a very worthwhile alternative.

**Comment by ChuckL** [comment]
I have an XCloud replacement ready to go and that's also deployed.
https://github.com/new-xkit/XKit/pull/117

On Friday I'll be putting in an option to revert to old xcloud servers then we should be good.
