### ISSUE TITLE
Problem with Post Block on search pages

### ISSUE THREAD

**Issue by citrusella** [new-xkit/XKit#530]
I don't know how much maintenance you guys do on Atesh's extensions, but blocking a post via Post Block on a search page blocks the entire search, at least for me. Not sure how fixable it is but it seems like a really broken thing. :-/

**Comment by blackjackkent** [comment]
Duplicated the problem...looks like we're using the wrong selector to identify which post we want to block and we're grabbing everything on the page. I'll see what I can do about this.
