### ISSUE TITLE
How do you unreverse this?

### ISSUE THREAD

**Issue by xsethxchickx** [new-xkit/XKit#532]
![4](https://cloud.githubusercontent.com/assets/14810602/10056514/9f7380b0-6209-11e5-9b9c-248f15e13bfc.PNG)
I clicked on something before tumblr did all its stuff and now I can't remember what I did to unreverse it, I use Chrome.

**Comment by 0xazure** [comment]
Closing as there isn't enough context to debug.  @xsethxchickx you're more than welcome to add additional information to this issue, and we may re-open it at a later time.
