### ISSUE TITLE
Read More Now not working outside of Dashboard

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#537]
I've mentioned this in another Read More thread, but I've been advised to open a new issue:
When being on drafts, private mode or queues etc., opening the Read More Now link does not work and only re-directs me to the blog with the read more (which is the basic tumblr feature without XKit).

Though, I'd like to add, that using drafts is something necessary for RPers. Therefore it'd be nice to make it work for anything outside the tumblr dashboard.

**Comment by nightpool** [comment]
Ah, this is for drafts. Hmm I don't know if this is going to be trivially
possible for us. We'll probably have to structure things differently on the
backend to allow it access to private posts.

may be a bit of a challenge.

**Comment by gloomykid** [comment]
I just observed this issue on private posts too, but if that isn't possible, that is okay. I think more people would be happy about the Read More Button working for Drafts.
As far as I know, the old XKit Read More worked on drafts. So, I'm not sure if you could compare the HTMLs from the old and new one? Just a thought...
