### ISSUE TITLE
Unable to reblog/like/etc from blog pages

### ISSUE THREAD

**Issue by basilissa** [new-xkit/XKit#550]
The extension seems to have made it so that tumblr acts like you're not logged in when you view people's blogs, so that the only buttons on the top right are "follow ______" and "sign up for tumblr". I use Chrome, and checked Firefox to make sure it was only affecting the browser I have xkit installed in, and it works perfectly fine w/o xkit there.

**Comment by 0xazure** [comment]
Can confirm.  My main browser is Chrome and I've been noticing similar behaviour for a while now.

Interestingly, it appears to be limited to Chrome only.  On Firefox, even with XKit enabled, the reblog/like/etc interactions show up as they're expected to.

**Comment by blackjackkent** [comment]
This seems to vary from person to person; I have'nt been able to duplicate this experience on any of my Chrome installs. :/

**Comment by 0xazure** [comment]
Looks to be a Tumblr thing.  Chrome (seemingly) doesn't work properly at all, Firefox seems to work all the time, and even visiting Tumblr with a browser that doesn't even support XKit exhibits _mixed_ behaviour where some blogs display the interactions properly and others don't, even if they did on Firefox.

**Comment by Jangalian** [comment]
It's happening to me as well, it started on my laptop and now even my Chrome netbook is doing it. It shows the "sign up!" feature as though I'm not logged in, and it's only with Chrome.

**Comment by nightpool** [comment]
If we can trace this back to some XKit behavior we should consider fixing it, but as this is reproducible without xkit installed I'm going to close for now.

**Comment by Jangalian** [comment]
So does this mean it's being dismissed, even though it interferes with xkit? No one has any idea whatsoever how this is happening or why?

**Comment by nightpool** [comment]
@jangalian Its some bug on tumblr's end. Having XKit installed makes no
difference as to whether it happens or not.

Have you reported the problem to Tumblr?
