### ISSUE TITLE
"Answer Time" on top of dashboard visible despite being blocked on New X Kit.

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#568]
![ss 2015-10-01 at 11 16 25](https://cloud.githubusercontent.com/assets/13604430/10234047/73c985f6-6892-11e5-8573-9cfce260d099.png)

Was that feature removed again?! Or is it just a bug hence to new layout changes (?) of tumblr?

**Comment by Wolvan** [comment]
The feature was moved to Anti Capitalism

**Comment by gloomykid** [comment]
Ah, sorry. Didn't know about it. It's hard to keep track of these things if features get moved to other extentions without any notification... thanks for the info.

**Comment by Wolvan** [comment]
It's no problem, glad you found it. We just decided on moving it to anti-capitalism since it belongs there more

**Comment by nightpool** [comment]
@wolvan I thought we were blocking moving it on the extension stuff you
were working on?

**Comment by Wolvan** [comment]
Are you refering to issue #427?
