### ISSUE TITLE
Provide an alternate way to remove a tracked blog

### ISSUE THREAD

**Issue by phidari** [new-xkit/XKit#57]
I'm using Firefox 39 on Ubuntu 14.04. Holding down alt and clicking on a blog name in my tracked blogs section doesn't remove it; it just activates an Ubuntu "feature" that lets me drag the window around.

**Comment by finagle29** [comment]
From my understanding, since its an Ubuntu "feature", the solution is either to change the key that will remove a tracked blog to shift maybe or super or meta, or tell people with Ubuntu to change the mouse button modifier to something besides alt with `dconf write /org/gnome/desktop/wm/preferences/mouse-button-modifier  '"<Super>"'`

**Comment by phidari** [comment]
Can confirm that changing the mouse button modifier like that fixes the problem.

**Comment by bvtsang** [comment]
Alt-clicking correctly removes a tracked blog on Windows 7, Chrome.

Since @phidari fixed their problem, is it safe to close this issue? Or should we reassign the alt key to something else?

**Comment by bvtsang** [comment]
It's been 9 days since anyone responded, so I'm going to close this issue.

**Comment by nightpool** [comment]
Is alt-clicking the *only* way to remove a tracked blog? seems like something we should fix irregardless of how well it works for people

**Comment by bvtsang** [comment]
Maybe we can do something like the following:

1. User clicks on tracked blog
2. Tracked blog content shows up in a modal layer on the screen
3. Somewhere on that modal layer we add an option to remove that tracked blog

**Comment by nightpool** [comment]
why not just showing an "x" when you hover over the blog?

**Comment by nightpool** [comment]
why not just a x when you hover over the button?
![image](https://cloud.githubusercontent.com/assets/233815/9281540/5c5cd63e-428b-11e5-884a-805de669e840.png)

**Comment by bvtsang** [comment]
Is the X where the unread post count usually goes?

I do like the idea though. Maybe have the X slide out from the side on mouseover? Or put it on the left side instead?

**Comment by nightpool** [comment]
it would float:right and move the post count over

**Comment by bvtsang** [comment]
Sounds good, I'll take it. Thanks!
