### ISSUE TITLE
Preferences aren't sanitized

### ISSUE THREAD

**Issue by bvtsang** [new-xkit/XKit#570]
1. Install Satsukimous
2. In the settings for Satsukimous, enable Replace Name
3. In the replacement name, enter `"<script>alert(1);</script>`
4. Click out of the XKit settings to save it
5. Refresh the page
6. Open up the settings for Satsukimous
7. Expect to see `"<script>alert(1);</script>` as the replacement name
8. Observe that the settings aren't rendered properly

![screen shot 2015-10-01 at 3 30 51 pm](https://cloud.githubusercontent.com/assets/370525/10235487/c86829be-6851-11e5-85b8-dc58e48a3aa2.png)

**Comment by nightpool** [comment]
xkit is a giant xss vuln waiting to happen this is basically expected
behavior, at least for me.
