### ISSUE TITLE
View On Dash link doesn't appear in sidebar

### ISSUE THREAD

**Issue by phidari** [new-xkit/XKit#58]
Firefox 39. I do have View On Dash enabled -- it works just fine in conjunction with Blog Tracker. But the "View on dash" link that should be appearing in my sidebar isn't there. Pressing alt+v doesn't bring it up either, it just opens my View menu.

**Comment by just-here-for-xkit** [comment]
Chrome, version 44.0.2403.107. Same issue.

**Comment by dlmarquis** [comment]
@phidari do you mean that the View On Dash extension shows up only when blog tracker is enabled?

**Comment by phidari** [comment]
I mean the extension doesn't show up at all. When I click on a blog name that I'm tracking, it works properly. But there's never a "View on dash" link to check other blogs with.
