### ISSUE TITLE
Autotagger and the queue still do not work together

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#59]
It does not seem to matter whether the user uses quick queue or not.

**Comment by agrunwald82** [comment]
Definitely does not work with regular queueing. All other autotags work.

**Comment by nightpool** [comment]
I think I fixed this in my pull-request? Can someone confirm?

**Comment by ThePsionic** [comment]
As far as I can tell, was fixed by #102. Closing.
