### ISSUE TITLE
Quick Reblog/Queue Error

### ISSUE THREAD

**Issue by contentmint** [new-xkit/XKit#596]
Quick Reblog displays 
"INOCP109-403" when reblogging to certain sideblogs?

**Comment by ThePsionic** [comment]
What browser and version, which XKit version, which One-Click Postage version?

(For future reference: HTTP 403 is Forbidden.)

**Comment by contentmint** [comment]
I figured out the issue was that the sideblog was accidentally blocked, and does not have to do with XKit itself.

**Comment by Wolvan** [comment]
Is the blog you wanted to reblog to either password locked or something?
