### ISSUE TITLE
get_posts() needs better logic for "mine" (affects Quick Tags most prominently)

### ISSUE THREAD

**Issue by contentmint** [new-xkit/XKit#597]
It seems that the Quick Tags icon doesn't show up on posts made by other members on sideblogs. They are still editable, but you have to go through Gear icon > Edit.

**Comment by dandelionnwine** [comment]
The icon shows once an post has been posted but it does not show up in the drafts or the queue.

**Comment by contentmint** [comment]
The icon is not showing up even on posts that have been posted.

**Comment by dandelionnwine** [comment]
It does for me in Chrome. You might want to tell them which browser and version you are using.

**Comment by contentmint** [comment]
I'm using Google Chrome Version 46.0.2490.71 m and XKit Version 7.7.1

**Comment by dandelionnwine** [comment]
That's so weird, because those are the exact versions that I'm using and it shows up in posts for me that were posted. It just doesn't show up in drafts or in the queue.
