### ISSUE TITLE
Text Input capped to 512KB by default

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#600]
That means you are only able to use 524288 characters in any text input from XKit. This becomes a problem especially when you have a lot of posts in post archiver that you want to ex- and afterwards import again, since that can easily exceed the 512KB limit, breaking the import JSON anhd making it impossible to restore the post archive

**Comment by finagle29** [comment]
This issue is specific to Chrome and Safari.  It's [WebKit bug #44883](https://bugs.webkit.org/show_bug.cgi?id=44883)
If we use a `<textarea>` we should be able to avoid this.

**Comment by Wolvan** [comment]
are you going to look into that, @finagle29?

**Comment by finagle29** [comment]
Yes.
