### ISSUE TITLE
Reblog display options, when set to nested style, doesn't implement color quotes' basic functionality

### ISSUE THREAD

**Issue by paramarx** [new-xkit/XKit#606]

**Comment by dlmarquis** [comment]
Sort of tangential, but perhaps we should fold Color Quotes into an option in Reblog Diplay Options while we're at it? It doesn't make much sense on its own anymore.

**Comment by bvtsang** [comment]
Agreed, color quotes won't make sense if nested blockquotes is no longer the default post layout.

**Comment by nightpool** [comment]
sounds good, but this also blocks on extension migrations (so people who
have already color quotes don't just lose them suddenly)

**Comment by dlmarquis** [comment]
They already lose them, though, in the sense that they have to migrate over to RDO before there's a chance to see them anyway.

**Comment by nightpool** [comment]
sure but we could at least make it easier for people who have both
installed (even if we don't want it to be the default)

**Comment by dlmarquis** [comment]
We could push an update to color quotes at the same time as RDO that alerts users of the switch. Would that be good?

**Comment by nightpool** [comment]
yeah sounds fine.

**Comment by Wolvan** [comment]
We could also add the color quotes extension to ``xkit_preferences`` spring cleanup list

**Comment by nightpool** [comment]
@wolvan having it uninstall itself is more flexible and lets it do other
things as well (like showing a pop-up box/asking if they want to install
reblog display options)

**Comment by Wolvan** [comment]
how about having color quotes show the warning message for a few weeks, then we can spring clean it. Or we might have a proper transformation infrastructure by then

**Comment by ThePsionic** [comment]
Was fixed by #666 as far as I'm aware.

**Comment by nightpool** [comment]
fixed by #666
