### ISSUE TITLE
Themes: Does not apply theme

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#610]
None of the themes apply on Firefox or Chrome. This is with version 0.1.3. Originally reported by a user and confirmed by me.

**Comment by 0xazure** [comment]
`dist/page/themes.json` doesn't seem to contain the file contents anymore.  I'm still tracing the commit history to find out why, because when I [introduced the changes](https://github.com/new-xkit/XKit/commit/f04d87e8fb0cc9c87d990a37e3ef93d2a9e31c1d) to the build system it was working as intended.

**Comment by 0xazure** [comment]
Traced the problem back to #475, it looks like I missed the `contents` key when I refactored the Themes [`buildGalleryFile` function](https://github.com/new-xkit/XKit/pull/475/files#diff-8f425bc0a81040ea478a6428ec77de3fR83).
