### ISSUE TITLE
Shrink Posts no longer works in Enhanced Queue

### ISSUE THREAD

**Issue by ChuckL** [new-xkit/XKit#615]
From Support: "After yesterday's Enhanced Queue update, Shrink Posts no longer works."

We've had another person come and and tell us that

**Comment by heatheronlamma** [comment]
I've had the same problem.

**Comment by Arasca** [comment]
Same here. The 'Queue Options' button still switches from ON to OFF (and vice versa) with a click, but the 'Shrink Posts' button stays on OFF. (..and I've already tried uninstalling, resetting etc.. nothing works.)
I really hope this can be fixed soon.. my queue is driving my nuts the way it is now.. :(

**Comment by eizasgonzalez** [comment]
I have the same issue.

**Comment by ThePsionic** [comment]
Okay so as the original writer of this feature, I went to test it out and it does not show the error message that was *intended* to be shown when I wrote it up.

@heatheronlamma, @Arasca, and @eizasgonzalez: Enhanced Queue's Shrink Posts no longer works if Shorten Posts is enabled due to formatting issues. It should work properly when you disable Shorten Posts.

**Comment by Arasca** [comment]
@ThePsionic I saw that message when I checked the XKit Editor and immediately disabled Shorten Posts. Nothing happened, so I reset XKit and only installed the Extensions I really needed, leaving out Shorten Posts, and still nothing.. 
Thanks for the info though, maybe it'll work for the others..

**Comment by eizasgonzalez** [comment]
I actually don't even have Shorten Posts installed and still can't get Shrink Posts to work again.

**Comment by heatheronlamma** [comment]
I don't have Shorten Posts installed. The button will not let me click to turn on Shrink Posts

**Comment by nightpool** [comment]
okay sorry for the false alarm but *this time* it should be working now.

**Comment by Arasca** [comment]
It does! Thanks a lot!
