### ISSUE TITLE
Drafts Mass Deleter does not work

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#620]
From the support Gitter:

> i'm the person who asked about the mass deletion thing. had to reload the page. but the extension gives me the deleting messages as usual and then i get a message that says "Deleted 0 posts. Failed to delete 100 posts. Please refresh the page before deleting more drafts." and that's it

Opening the JavaScript console revealed a plethora of HTTP 401 (Unauthorized) errors as well as messages saying "Unable to unlike post with id *" even though the Mass Unlike functionality was turned off.

**Comment by nightpool** [comment]
bumping this because we got another ask today

**Comment by ThePsionic** [comment]
Bumping again due to a support ask. Also tagging high priority since it's a large part of the extension that's broken right now.

**Comment by ShrineFox** [comment]
Bumping since this still isn't fixed :/

**Comment by bokkobo** [comment]
bump! this has been broke for a long time : ( i used this feature alot when it still worked

**Comment by blackjackkent** [comment]
This should be fixed by #1286 when it's approved. :)

**Comment by nightpool** [comment]
fixed by #1286
