### ISSUE TITLE
Reblog As Text and Reblog Yourself Infinite Loops

### ISSUE THREAD

**Issue by ShareNoMimosa** [new-xkit/XKit#629]
i found these since console logs are being printed in the loops, not sure if an actual issue or these occur by design.

the infinite loops are triggered if you open the normal reblog editor and the loops continue after the editor is closed.  reblog yourself infinite loop occurs when reblogging a post from yourself, reblog as text loop occurs with any reblog.

**Comment by Wolvan** [comment]
what exactly do they say?

**Comment by ShareNoMimosa** [comment]
![screen shot 2015-10-12 at 3 50 31 am](https://cloud.githubusercontent.com/assets/8609540/10426369/82bd5786-7094-11e5-8dfb-c29cf1d0049a.png)

**Comment by Wolvan** [comment]
Yeah, I remember that output spam. It's something we are looking into for a later date

**Comment by finagle29** [comment]
IIRC Reblog as Text is not needed anymore due to a Tumblr-side change: long
posts aren't converted into links anymore.

**Comment by nightpool** [comment]
yeah trust us this annoys noone more then it does the active devs :D

Just something weird/legacy that we haven't gotten around to fixing yet.

pull requests always welcome.

**Comment by 0xazure** [comment]
Per #178 Reblog as Text should probably be removed.
