### ISSUE TITLE
Reblog Display Options duplicates captions in peepr

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#630]
![image](https://cloud.githubusercontent.com/assets/1437010/10441624/52bc8b9e-714b-11e5-9b17-c5b5790a34c4.png)
When the style is set to nested, the caption gets duplicated as you can see in the above screenshot

**Comment by nightpool** [comment]
yes this is a fix I have locally that didn't get pushed before RDO got
merged. I don't have the bandwidth to push this now, but feel free to
assign it to me and I'll deal with it when I'm done with finals.

**Comment by nightpool** [comment]
fixed by #664
