### ISSUE TITLE
Depreciate fallback URLs

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#632]
Ideally this should have gone out with `v7.7.1`, but now that the SSL/TLS certificates on the old XKit servers are dead, we should really remove the [fallback behaviour](https://github.com/new-xkit/XKit/blob/cfc7137ab37d569ccacb59645dcc52d9a03e5df1/xkit.js#L240) since instead of outright failing the download, mixed-content requests seem to cause XKit to hang in most browsers.

**Comment by Wolvan** [comment]
This would either require a core update or we could override ``XKit.download.page`` in either ``xkit_main.js`` or ``xkit_patches.js``. At least until we have enough stuff that is worth a new core release.

**Comment by 0xazure** [comment]
Per discussion on #720 I looked into overriding some of the relevant functions in `xkit_patches`, but the changes necessary to move many of the functions are non-trivial and need some more thought.

**Comment by AprilSylph** [comment]
resolved by #1511
