### ISSUE TITLE
Update JPM to 1.0.2

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#640]
Found out today that JPM 1.0.1 (which we currently specify in our shrinkwrap) produces incompatible Firefox extensions for Nightly 44. I manually updated through ``npm install jpm@latest`` and was able to build a working extension that way.

**Comment by 0xazure** [comment]
Nightly 44 won't be landing until 2016-01-26 as per https://wiki.mozilla.org/RapidRelease/Calendar.

Based on [this diff of `jpm`](https://github.com/mozilla-jetpack/jpm/compare/mozilla-jetpack:b633361...mozilla-jetpack:2a38a0a) it's just version number tweaks for min/max version strings.

**Comment by hobinjk** [comment]
I use Firefox Nightly as my daily browser so this already affected me. It even fails without a descriptive error message. This should definitely be updated eventually

**Comment by Wolvan** [comment]
The only time it ever errors out is when you install/uninstall the extension, and that isn't even userfacing errors

**Comment by 0xazure** [comment]
Probable explanation to this change in Firefox Nightly 44: https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/
