### ISSUE TITLE
Host Firefox Extension as Unlisted

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#643]
Evals are prohibited and Mozilla isn't reviewing us.
- [ ] Create update.rdf
- [ ] Put update.rdf in a place where we will never move it

**Comment by nightpool** [comment]
> Put update.rdf in a place where we will never move it

relative to what? Can old update.rdfs point at new update.rdfs?

seems like the most logical place is new-xkit.github.io/update.rdf but I
just wish we host our whole dist out of repo (and in that one) so that
might just be me

**Comment by hobinjk** [comment]
I think `http://new-xkit.github.io/XKit/Firefox/update.rdf` is the best place to put it.

**Comment by Wolvan** [comment]
I personally think we should do the #364 first and have a special folder in dist/ that contains all our update files

**Comment by hobinjk** [comment]
#364 will take significant time and effort. I think that the `Firefox/` location is logical enough to not be an issue.
