### ISSUE TITLE
Reblog Display Options deletes answers to ask.

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#644]
flat lay out:
![ss 2015-10-17 at 02 54 11](https://cloud.githubusercontent.com/assets/13604430/10556058/6e19f340-747a-11e5-9e2b-491f23039152.png)

nested lay out:
![ss 2015-10-17 at 02 54 23](https://cloud.githubusercontent.com/assets/13604430/10556061/75b8edea-747a-11e5-9047-7a887f30ec0a.png)

**Comment by nightpool** [comment]
@hobinjk you were able to reproduce? If you could put an example post here that would be great.

**Comment by hobinjk** [comment]
@nightpool  http://120983019283-testing.tumblr.com/post/131826469124/teen-stanley-b3-and-stanford-c3-hugging-if

**Comment by nightpool** [comment]
Can't reproduce on my account, hmmm...

do you want to take a shot at debugging this?

**Comment by nightpool** [comment]
fixed in #674
