### ISSUE TITLE
Blacklist interfering with K to previous post!

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#645]
Referencing to #60 (I am talking about the K button feature from tumblr itself, not the J/K across page thing) I have finally found out what is interfering with the K button to get to the previous post feature.

It's the blacklist feature.

As soon as the mini-UI and regular UI show up on the dashboard, using the K button to get to the previous post would result into going only up the same height as the UI's size, not an entire post.
Even if you're in the middle of an un-blocked post, it would only show a part of it. Here an image of what I mean.
Here is how I've seen the dashboard before using the K button:
![ss 2015-10-17 at 05 31 54](https://cloud.githubusercontent.com/assets/13604430/10559604/0d55f1b4-74f5-11e5-8a30-6f692d29e421.jpg)

Here after the K button:
![ss 2015-10-17 at 05 32 01](https://cloud.githubusercontent.com/assets/13604430/10559605/15b321c4-74f5-11e5-88a6-93d6c2703425.jpg)

This happened after I passed the two UIs. And you can compare that the pixel of before and after using the K button would be approximately as much as of the blacklist-UI.

Might there be an interference due to the coding? It would be really helpful to know, because this has been an issue for months now and I've stopped using any other extention, even AdBlocker, and this is the final conclusion I could make for now.

**Comment by ThePsionic** [comment]
Confirmed; when hitting K with blacklisted posts (use "e " for convenience) the dashboard only scrolls up approximately the height of the blacklisted post mini-UI instead of the entirety of the previous post.

**Comment by gloomykid** [comment]
After uninstalling everything and re-installing everything (it took a lot of time to sort things out, I swear), I can 100% confirm that the only issue and how you can reproduce this bug with the issue of "K-button-not-working-to-get-to-the-previous-post" is Enhanced Queue.
It was one son of a gun to find that out, but here we are.
I'm not sure if anyone even use Enhanced Queue as much as I do, but I've tried out a lot to confirm this now.

**Comment by hobinjk** [comment]
Appears to work now
