### ISSUE TITLE
Themes+ background image causes xkit to fail upon refresh

### ISSUE THREAD

**Issue by Evalilith** [new-xkit/XKit#648]
Using Chrome 46.0.2490.71 m and xkit has been force updated, so I'm pretty sure it's not a version thing. When using Themes+ with a background image, xkit as a whole completely fails to load upon going to the next page (no infinite scroll) or refreshing the main dash page (with infinite scroll). All tweaks and options vanish, including the header button for xkit itself. This also happens when opening Tumblr in a new tab; basically, xkit only loads once, when the page first loads upon opening Chrome. Closing Chrome and opening it again causes xkit to load on any tumblr pages open at the time. 

With the background image removed, this does not happen.
ETA: spoke too soon, it does happen? But after multiple refreshes or possibly only after going to one of the pages where xkit automatically doesn't appear and then going back to other parts of Tumblr. Causes it to stop loading in other tabs also, though.

**Comment by nightpool** [comment]
Haven't been able to reproduce this
