### ISSUE TITLE
One click postage keeps posting to the wrong blogs

### ISSUE THREAD

**Issue by RafaelaKlein** [new-xkit/XKit#653]
Hello! I'm having trouble with the one click postage tool. What happens is the following: I have a tumblr account with several side blogs which I use all the time. But everytime I try to reblog something from the dashboard using the one click postage tool selecting one of my side blogs, it ends up posting to my main blog. It only posts to the right sideblog if I have just refreshed the page and if it is the first reblog after refreshing it. I tried changing the default blog for the tool from my main blog to one of my side blogs, but it did nothing to help, it kept posting to the main blog. I should also point out that I have two independent tumblr accounts, made with different emails, and this error occurs with both of them. Also, I have not had the opportunity to test the problem in a different computer or browser. I have the Opera browser but I can't even install xkit there.

Xkit version: 7.4.5
Browser: Firefox 41.0.2

Thanks for the attention!

**Comment by nightpool** [comment]
Old XKit :(
