### ISSUE TITLE
Blocking a post with NotificationBlock then deleting it causes Classic Notifications to malfunction

### ISSUE THREAD

**Issue by Undivide** [new-xkit/XKit#654]
Basically, I posted an image that got over 5000 notifications. The notifications were becoming very spam-y, so I used Notification block to block it, then I deleted the post.

After that, Classic Notifications no longer functions as it should on my primary blog. It works just fine on my other blogs, though.
It does its job only every once in a while on my primary blog. It'll display 2, maybe 5 notifications every now and again, but they only remain up for a few minutes.

Note: I've removed Notification Block and this issue still persists. I've also reset/uninstalled/reinstalled New-Xkit entirely.

**Comment by nightpool** [comment]
Not sure I understand the issue here: closing until there's more info.
