### ISSUE TITLE
Quick Tags 'Tag Bundles' section does not properly display in Xkit interface on /activity page

### ISSUE THREAD

**Issue by exinspired** [new-xkit/XKit#655]
On /activity page
![/activity page has no arrows or other formatting and makes it difficult to reorder the tag bundles](http://i.imgur.com/MBHPCzD.png)

on any other page I've checked so far
![image of tag bundles everywhere else and presumably functioning properly](http://i.imgur.com/ZTKVR0h.png)

Windows 10, Chrome 46.0.2490.71 m, New Xkit 7.7.1

**Comment by izub** [comment]
I can confirm this.

**Comment by 0xazure** [comment]
Confirmed.  Looks like the `xkit-quick-tags-cp-{up,down}` CSS isn't getting injected into the page for some reason.

**Comment by AprilSylph** [comment]
closed by #1253
