### ISSUE TITLE
Gear Icon not visible on inbox anymore...

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#657]
... therefore the "allow full-width *GIFs" section cannot be accessed on the inbox. Asks have to be edited after publishing to access the non-full-width *GIFs feature.

Some tumblr update caused that a few weeks ago, but I wasn't sure if people were aware of it already.

**Comment by nightpool** [comment]
haven't felt any pain on this, feel free to re-open if this is still an issue for you
