### ISSUE TITLE
Reblog Display Options not showing titles at top of post in flat style

### ISSUE THREAD

**Issue by rimbaum** [new-xkit/XKit#667]
Like it says on the tin. When I check "Show post title at top of post", the title disappears entirely. When unchecked, it shows up as normal. When checked, it's just plain gone. Only noticed it today, but I'm pretty sure that wasn't the same behavior that was showing on 1.0.0

**Comment by nightpool** [comment]
fixed by 02beda5943a39678f1726312011bfc662c7d58cd
