### ISSUE TITLE
replies

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#678]
for future reference:

replies are POSTs to https://www.tumblr.com/svc/reply

example reply form data

```
data[reply_text]: test123
data[post_id]: 131960595665
data[tumblelog]: nightpool42
data[tumblelog_key]: [snipped]
data[source]: REPLY_SOURCE_DASHBOARD
```

**Comment by Wolvan** [comment]
What is REPLY_SOURCE_DASHBOARD? Is that just a string?

**Comment by nightpool** [comment]
yeah.

**Comment by ThePsionic** [comment]
Closing as the backend for this has been completely removed by Tumblr.
