### ISSUE TITLE
New change to Tracked Tags

### ISSUE THREAD

**Issue by maswartz** [new-xkit/XKit#686]
Yesterday the tracked tags would show a number showing how many new posts are in the tags. Also when you clicked on them it would go to the page using the "classic search" extension (if you had it)
Today they changed it, the numbers no longer show up and the page once clicked no longer use the "Classic search" extension meaning you have to click on the search bar and hit enter for the extension to apply.
![tumblr1](https://cloud.githubusercontent.com/assets/15185135/10827526/e57349f8-7e45-11e5-8a87-3e9468c10a18.JPG)
![tumblr2](https://cloud.githubusercontent.com/assets/15185135/10827531/e8eafd7e-7e45-11e5-95e8-43595bc16335.JPG)

**Comment by AuraSweet** [comment]
This is exactly how it is for me, too.

**Comment by rimbaum** [comment]
Tags On Sidebar also goes straight to the /seach/tag page instead of the /tagged/tag page, and won't show new posts because of this change.

**Comment by citrusella** [comment]
Was just about to open an issue on this but realized this one was my problem!

**Comment by izub** [comment]
Seems to be partially fixed in 250bd6e and fccdc43
All my tracked tags now look like this after the update though. The counter doesn't reset when I go to view the tagged pages (@jwbay?)
![capture](https://cloud.githubusercontent.com/assets/3972940/10919891/84b4a086-826d-11e5-9b71-653823176dff.PNG)

**Comment by izub** [comment]
I found the issue. Apparently Classic Tags was updated but Patches wasn't up to date. New functionality in Patches was used. A manual update resolved the problem.

Maybe good to think about being able to set dependencies of other extension versions?

**Comment by nightpool** [comment]
Hmm any particular reason why patches didn't update? everything should have
updated at the same time. (maybe we didn't bump version on patches?)
