### ISSUE TITLE
Post Limit Checker: Error?

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#688]
No sideblog with password protection, didn't change anything in my settings whatsoever, it worked today a few hours ago, when suddenly:

![ss 2015-10-29 at 10 40 41](https://cloud.githubusercontent.com/assets/13604430/10832853/28d54c58-7e8e-11e5-8979-c56a8a4eebeb.jpg)

**Comment by nightpool** [comment]
is one of your blogs hidden, perhaps?

**Comment by gloomykid** [comment]
No, all my blogs are public, without password, not hidden. But right now it works again so I guess this can be closed...

**Comment by nightpool** [comment]
Okay sweet. Probably just an intermittent rate limit issue.

**Comment by ThePsionic** [comment]
Closing as the issue seems to be resolved.
