### ISSUE TITLE
Tag Tracking+ takes the person using it to tagged/tag/recent instead of just tagged.

### ISSUE THREAD

**Issue by AuraSweet** [new-xkit/XKit#694]
![xkit issues2](https://cloud.githubusercontent.com/assets/14351360/10853846/ff61ca0c-7efd-11e5-976d-ccf094926a6a.png)

**Comment by ThePsionic** [comment]
#693 has already been made to fix this.

**Comment by Wolvan** [comment]
@ThePsionic the issue is not fixed and thus not to be closed
