### ISSUE TITLE
Inaccurate Timestamps

### ISSUE THREAD

**Issue by contentmint** [new-xkit/XKit#698]
I received a message just now, but the absolute time stamp is six hours behind the actual. The relative time also indicates 6 hours ago. I know tumblr is based in New York, so my guess is that this has to do with the time zone difference?

**Comment by ThePsionic** [comment]
Duplicate of #116.

**Comment by nightpool** [comment]
Yeah this is a long standing issue. We assumed that tumblr was serving
timestamps relative to utc-5, but instead they're served in whichever
timezone you have set on your blog settings, but without any timezone
information.
