### ISSUE TITLE
Unable to edit bigger text post on drafts

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#705]
![ss 2015-11-02 at 09 38 50](https://cloud.githubusercontent.com/assets/13604430/10893705/8071fcb2-81aa-11e5-8d27-d7f73f2b337c.jpg)

I blurred out the text mostly, except to show that
a.) the title looks weirdly chopped off from the body
b.) the text is having 0 pixels to the left and right side of the post
c.) which I can't show on this image, is that if you try to scroll down to the end of it and add a text, you can't -- it scrolls right back up to the title.

I have no idea what kind of update or extension might've caused this, but it's rather pesky, I had to delete the post from my drafts, in order to edit it when finding it on the dashboard again...

**Comment by nightpool** [comment]
I think this a dupe of the RDO/post_window bug. Do you have Editable Reblogs installed?

**Comment by nightpool** [comment]
https://github.com/new-xkit/XKit/issues/676

**Comment by gloomykid** [comment]
I have, yes. I wasn't aware the RDO was the same as this one, sorry!

**Comment by nightpool** [comment]
ancient, probably not a bug anymore
