### ISSUE TITLE
reblogging reblog-like posts breaks ER

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#707]
for example, [this post on -support](http://new-xkit-support.tumblr.com/post/132483032603/my-xkit-button-is-removing-my-account-button)

![image](https://cloud.githubusercontent.com/assets/233815/10917681/02a039b2-8230-11e5-8990-e7de17b9c8aa.png)

reblogging it leads to this:

![image](https://cloud.githubusercontent.com/assets/233815/10917688/0ccffcce-8230-11e5-8026-62488b022423.png)

ideally, it would just work. maybe also affects OCR?

**Comment by dlmarquis** [comment]
Is this not just Tumblr nuking anything that looks like a post edited to look like the old style? Like what happens with OCR reblogs.

**Comment by nightpool** [comment]
It only appears after reblogging the post. I didn't try with er disabled.

**Comment by nightpool** [comment]
Might have been fixed by the merged blockquotes changes I guess.

**Comment by dlmarquis** [comment]
Okay, I just confirmed this is an ER issue using an OCR post. Reblogging a quick reply in vanilla tumblr? Fine. In ER? The content disappears.

@blackjackkent any ideas?

**Comment by blackjackkent** [comment]
@dlmarquis I can't reproduce this. What version of ER and OCR? Can you give me the link to the post where you encountered the issue?

**Comment by nightpool** [comment]
@blackjackkent are you following the steps correctly? I.e. create an ocr post, and *then* try to reblog it.

**Comment by dlmarquis** [comment]
@blackjackkent you can see my test attempts over at
fuckthisshitimsofuckingdone

**Comment by blackjackkent** [comment]
@nightpool Yes, I did that.
@dlmarquis I followed your test blog and looked at your attempts and see this on the dashboard:

![reblog](https://cloud.githubusercontent.com/assets/13437011/11149140/9fc84398-89e6-11e5-95f3-3d41b8e16288.png)

Isn't this the use case you mean? Looks like everything is showing up okay.

**Comment by dlmarquis** [comment]
That was reblogged without ER. Farther down there are broken ones that were
reblogged with ER.

**Comment by nightpool** [comment]
dupe of https://github.com/new-xkit/XKit/issues/707
