### ISSUE TITLE
Depreciate XKit.lang

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#716]
XKit has never really supported proper localization (l18n), and usage of `XKit.lang` seems to be localized to a [commented-out block in `one_click_postage.js`](https://github.com/new-xkit/XKit/blob/55943a7164615141acbb6b0180571d44b5160206/Extensions/one_click_postage.js#L1537-L1539) and a smattering in `xkit_preferences.js` ([as an example](https://github.com/new-xkit/XKit/blob/55943a7164615141acbb6b0180571d44b5160206/Extensions/xkit_preferences.js#L678-L683)).

We should probably look at cleaning up this old attempt before investigating proper l18n.

**Comment by nightpool** [comment]
down with a Pr that just removes it entirely. are there even any other
language packs right now?

**Comment by Wolvan** [comment]
back in the days I wrote a translation system for old xkit which atesh never added. Doubt I still have the files though

**Comment by 0xazure** [comment]
As far as I can tell there aren't any other language packs, no.  It seems as though the system is set up for each extension to define their own localizations individually, rather than supporting drop-in language packs.
