### ISSUE TITLE
RFC: Standardize browser extension version divergence 

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#719]
Firefox should not pay for the sins of the Chrome extension. We should instead be able to distribute new versions whenever needed to fix any bugs as they arise. For example, Chrome currently has a bug that would require a 7.7.2 release. This hasn't been released yet because there are no other changes. We should embrace version divergence to be able to release as bugs appear.

I propose that we allow browser-specific bug fixes only in the patch version, i.e. 7.7.1 -> 7.7.2. Any change to xkit.js or another core extension file necessitates a major version, i.e. 7.7.1 -> 7.8.0. This allows us to release new extension versions freely while still keeping versions at least slightly comparable.

It additionally provides a path for our Github releases to not look too awful, as we can use the 7.8.0 release page to track all browser releases without loss of specificity.

**Comment by ThePsionic** [comment]
:+1:

**Comment by Wolvan** [comment]
@hobinjk didn't we decide something like that already? It's either that we agreed on that already or I am having a deja vu here...

**Comment by bvtsang** [comment]
@Wolvan You may be referring to [this discussion](https://gitter.im/new-xkit/XKit?at=5639506ea530033014e4021b).

**Comment by 0xazure** [comment]
> Any change to xkit.js or another core extension file necessitates a major version, i.e. 7.7.1 -> 7.8.0.

@hobinjk you say major version, but this is a minor version increment.  Could you clarify?

I agree with the sentiment though.  There's no reason for one browser extension version to be tied to the other browsers.

/cc @nightpool though, because they have a different perspective, per the discussion @bvtsang linked above.

I think we need to have a real discussion on branching model and which branches our PRs should target, and then clearly document the process.

**Comment by hobinjk** [comment]
@0xazure That is correct, I meant minor. As far as branches go, my ideal would be to never branch and instead release new extension versions as changes are made.

**Comment by 0xazure** [comment]
> ideal would be to never branch and instead release new extension versions as changes are made

Ideally, yes, but this gets messy when extension changes rely on changes to core or the bridges.  The changes to the extension would get pushed out before the browser extension updates, which would probably bork things.  There's some discussion about this in #494, as well as @hobinjk's own [comment  in #710](https://github.com/new-xkit/XKit/pull/710#issuecomment-154160411).

**Comment by hobinjk** [comment]
In a case like that I would want the browser changes in a PR landed earlier and the extension changes landed with a warning based on XKit's `framework_version`. Users are bad enough at upgrading (some are still on 7.6.x) that there is no branching strategy which would completely fix this case.

**Comment by hobinjk** [comment]
Tabled in Town Hall, discuss here
