### ISSUE TITLE
One-Click Postage tagging doesn't reset after a reblog from search or recommend

### ISSUE THREAD

**Issue by Federer343** [new-xkit/XKit#725]
As recently as yesterday when I would reblog something from a search page or the recommended post page it would reset my tag entry field on the one-click postage feature.  Now suddenly today it has stopped working like that and it keeps the tag entry after a reblog.

![about to rb](https://cloud.githubusercontent.com/assets/13668017/10993153/38d27762-8432-11e5-9f00-1137fa2360c3.png)
![after rb](https://cloud.githubusercontent.com/assets/13668017/10993152/38d1b3a4-8432-11e5-9027-02b036319438.png)

The first picture is when I enter the tags for the post and I'm about to reblog it.

The second picture is hovering over another post after that reblog, with the tags I just used still showing up instead of resetting.

**Comment by AprilSylph** [comment]
resolved by (I think) #1448
