### ISSUE TITLE
AccessKit doesn't load OpenDyslexic

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#733]
It tries to load from http://puaga.com/seven/accesskit/OpenDyslexic-Regular.ttf which is blocked because permissions or something. We should probably host OpenDyslexic-Regular.ttf in our gh-pages somewhere.

**Comment by Wolvan** [comment]
Is it only the opendyslexic font or are there other fonts as well? I agree with you though, we should host them on gh-pages or base64 them and put them in the extension (I think that's what I did when I embedded a font into a website project I did some time ago because linking simply did not work)

**Comment by 0xazure** [comment]
OpenDyslexic is also available via CDN [on jsDelivr](http://www.jsdelivr.com/projects/open-dyslexic), as an alternative to hosting on `gh-pages`.
