### ISSUE TITLE
Weird text format for full-width images on dash.

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#735]
I've noticed that before, but I am still encountering this on my dashboard... it's as if the full-width images aren't working properly anymore.

![ss 2015-11-07 at 03 04 46](https://cloud.githubusercontent.com/assets/13604430/11015497/51ca8ba8-8561-11e5-840a-ca9b10e22666.jpg)

Not that I mind about the full-width images, they were sort of annoying anyway (and I know they're a tumblr feature), but as soon as I disable XKit, it looks like this:

![ss 2015-11-07 at 03 10 06](https://cloud.githubusercontent.com/assets/13604430/11015511/a853e564-8561-11e5-90a5-3fb6323df746.jpg)

**Comment by ThePsionic** [comment]
This looks like it's caused by Reblog Display Option's setting to "Move reblog content to the right", which seems to be a default on. Not sure why that is.

**Comment by gloomykid** [comment]
I decided to uninstall Reblog Display Options for now because it seemed to be the issue for the #705 issue as well... I might be wrong though.

**Comment by nightpool** [comment]
this is working as intended. If you don't like the behavior, turn off "move reblog content to the right"
