### ISSUE TITLE
Editable Reblogs borks on links

### ISSUE THREAD

**Issue by blackjackkent** [new-xkit/XKit#747]
Per a discussion with a user in Gitter...it appears that ER is eating new content added to links when reblogging.

The JSON being sent for the link when ER is disabled is:

```
"post[tags]": "",
"post[two]": "http://thinkprogress.org/economy/2015/11/09/3720495/wisconsin-begin-drug-tests/",
"post[three]": "<p> Of course the management of companies that recieve public funding and/or subsidies should be tested for drugs and of course Wall Street Trader (any licensed stock market trader) should do monthly drug tests.</p>"
```

With `post[two]` being the original link URL and `post[three]` being ONLY the added content.

Since this means that Tumblr's backend will not recognize any changes to the reblog tree above the added content anyway, I believe this means links should be added to the "Abort" list for ER (i.e., like with chats and quotes, the extension should halt and not run on any post-window determined to be of that post type). 

I'll work on getting this turned around unless anyone has any objection.

**Comment by nightpool** [comment]
"and post[three] being ONLY the added content"

this happens for every reblog type, when not using ER. Link types aren't special here

**Comment by blackjackkent** [comment]
@nightpool Not true. (See the current `build_common_svc_request` function in ER:

```
request["post[two]"] = XKit.extensions.editable_reblogs.parse_html(XKit.interface.post_window.get_content_html());
```
Most post types have the entire reblog tree in `post[two]`, which is how ER is able to work at all. Links no longer have this so there's no way for us to send that data up to Tumblr. (as near as I can tell.)

**Comment by nightpool** [comment]
@blackjackkent I meant the vanilla behavior—which is definitely to only include contributed content in post[two]

see this text post reblog I just made:
![image](https://cloud.githubusercontent.com/assets/233815/11151207/b412655a-89f9-11e5-85a6-9484dd9c4944.png)

I can talk to you about why this happens offline (and by that I mean in gitter lol)

**Comment by nightpool** [comment]
(and the returned post object:

![image](https://cloud.githubusercontent.com/assets/233815/11151239/e1ebd2d6-89f9-11e5-8f16-6ac8517e9d5e.png))

**Comment by blackjackkent** [comment]
Paper trail from Gitter discussion: 

>_blackjackkent 10:31_
@nightpool re your comment on #747...I see your point. Although the fact remains that it doesn't seem to work with links.
hmm.  wait, hang on a second
i might be an idiot

>_nightpool 10:33_
@blackjackkent it has to somehow,
because otherwise old posts wouldn’t work

>_blackjackkent 10:33_
stand by
i need to verify my potential idiocy 

>_nightpool 10:33_
that’s why tumblr supports a full reblog-tree in post[two]
to support legacy posts

>_blackjackkent 10:36_
...i am an idiot! \o/

>_Wolvan 10:36_
\o/

>_blackjackkent 10:36_
@nightpool you're absolutely right -- and we were already doing this on asks.
i'm a few fries short of a happy meal
let me do another PR on that
