### ISSUE TITLE
In-blog buttons being pushed out of view by extension buttons

### ISSUE THREAD

**Issue by coderpatsy** [new-xkit/XKit#750]
Steps to reproduce- Get the messaging update, if you haven't already. Activate Go-to-Dash xor Post Archiver, and go to a post page on a Tumblr. Observe that the Dashboard button has disappeared (actually pushed out of view). Install both, and the Post Archiver button disappears too.

I don't know if any other extensions add buttons but surely this affects them as well.

Suggested solution- Remove the text on the Message button, like the Dashboard button. This leaves enough space for both buttons again.

**Comment by nightpool** [comment]
i would prefer the solution to be adding all of the xkit buttons on a
separate line.

**Comment by hobinjk** [comment]
IIRC the way the embedding of the controls iframe is done it can't be resized, which is why XKit clears the text instead of adding it on the same line or a new line.

**Comment by nightpool** [comment]
@hobinjk this isn't the case now that we also are running on blog pages, I
think?

**Comment by AprilSylph** [comment]
resolved by #1380
