### ISSUE TITLE
Classic search isn't working

### ISSUE THREAD

**Issue by schaufel4** [new-xkit/XKit#764]
On both Firefox and Chrome, the search bar still goes to /tagged/, not /search/

**Comment by Wolvan** [comment]
are you searching or clicking on a tag in your tracked tags list?

**Comment by schaufel4** [comment]
Searching. Clicking the search bar on the dash and typing in a search term takes me to /tagged/

**Comment by Wolvan** [comment]
that is exactly what classic search is supposed to do?

**Comment by schaufel4** [comment]
No, it's not. Because disabling Classic Search makes the search bar still do that. Going to /tagged/ is not what the search bar ever did for me until Tumblr changed things and necessitated the creation of the Classic Search extension. It's supposed to go to /search/[thing you searched for]

**Comment by Wolvan** [comment]
Going to ``/search/[thing you searched for]`` is tumblr's native functionality. Did you disable classic search and then refresh the page?

**Comment by schaufel4** [comment]
Yes. I uninstalled it and hard refreshed. Even closed and reopened the tab entirely

**Comment by Wolvan** [comment]
Do you have tag tracking+

**Comment by schaufel4** [comment]
Hmm. Yeah, I do. That seems to be the mix-up. Is there a way to make that part of Tag Tracking+ not apply to the actual search bar?

**Comment by Wolvan** [comment]
so if you disable TT+ it works the way you want it to?

**Comment by schaufel4** [comment]
Yeah, it does.
