### ISSUE TITLE
XKit attempts to run in Firefox even if Tumblr can't be loaded at all

### ISSUE THREAD

**Issue by 00dani** [new-xkit/XKit#765]
This is most easily reproduced by disconnecting from the Internet (disabling wifi or unplugging your Ethernet or whatever) and then loading https://tumblr.com/dashboard in Firefox - although Tumblr won't be able to load and you just get an error page, XKit will start up anyway and throw an error looking like this:

![screen shot 2015-11-14 at 12 23 46 pm](https://cloud.githubusercontent.com/assets/610876/11161212/a54971a4-8aca-11e5-868e-b88ed192c5b9.png)

Note that Retags is the source of the error in my screenshot, but if you check the XKit console there are similar errors from One-Click Postage and Notifications+. As resetting XKit is definitely not going to solve the problem of "no network connectivity" and will destroy your personal settings, it probably shouldn't be recommended!

In Chrome, the expected behaviour from XKit - which is doing absolutely nothing when Tumblr can't load - happens fine.

**Comment by citrusella** [comment]
I get the "I could not update XKit" message every time. :P

**Comment by nightpool** [comment]
This isn't just Firefox—this happens on chrome on some types of pages, like asset error pages. We should be more defensive at the beginning of xkit_main to bail out of these sorts of situations.
