### ISSUE TITLE
so will there ever be a version for safari or are we really just fucked...

### ISSUE THREAD

**Issue by britmus309** [new-xkit/XKit#77]
seems a little unfair..

**Comment by nightpool** [comment]
Unless you want to pay the 100$ per year a development license costs?

**Comment by dlmarquis** [comment]
@britmus309 developing for Safari (and iOS) costs $100/yr. We'd have to discuss the logistics of opening a donations page, how to disperse the extra money if any, etc. It's something we'll eventually discuss, but we have a lot of other things to deal with too at the moment. There isn't really a timeline other than "probably not soon, but eventually".

Unless anyone else has ideas?

**Comment by hobinjk** [comment]
I tried to run the Safari extension today and learned that without having paid the $100 fee you can't even install it. This means that we can't even use the sideloading approach employed by Opera users.

**Comment by hobinjk** [comment]
(buttons are hard)

**Comment by 0xazure** [comment]
Closing as 'wontfix'.  Safari support will have to wait until after we return to the discussion around #256.
