### ISSUE TITLE
Failed auto-update prompts for reset

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#770]
[Per some issues](http://new-xkit-extension.tumblr.com/post/133312389809/server-outage-and-xkit-reset-popup) with GitHub pages at [~ 21:51 EST](https://status.github.com/messages/2015-11-16), a number of users reported being prompted to reset XKit to fix the issue.  This is _shockingly_ poor UX, even by XKit standards.  We should not be prompting the user to reset except in the most dire of circumstances, usually after they've reached out to support.

The relevant line(s) are in [`xkit_updates.js`](https://github.com/new-xkit/XKit/blob/5e6976317ba8835c58bc923e114854676ae0e6ca/Extensions/xkit_updates.js#L135).  Resetting XKit [deletes all values in the storage](https://github.com/new-xkit/XKit/blob/5e6976317ba8835c58bc923e114854676ae0e6ca/xkit.js#L986-L991), with no recourse or undo.

**Comment by ThePsionic** [comment]
Yeah, those errors should not contain the reset button. Should only be available in the Other menu.

**Comment by nightpool** [comment]
This is super-critical—we've had a bunch of users run into this recently. I'm working on a fix.

**Comment by nightpool** [comment]
THIS is the one I meant to link
