### ISSUE TITLE
reply disappearing when editing a post you've already posted.

### ISSUE THREAD

**Issue by geriatricpsychopaths** [new-xkit/XKit#78]
I don't know if this is happening to anyone else or just me. But when you go to edit a post you've already written (say you find a spelling error or something), your entire reply is being removed. The only response still showing is said person you are responding to.

Edit: When you disable editable reblogs, the issue doesn't happen.
I am running Chrome and all my extensions/New xKIT is up to date.

Edit 2: This seems to have been fixed with the update.

**Comment by xxastraxx** [comment]
I seem to be experiencing this issue as well. Particularly with drafts. When you save a draft, then go to edit it later on from your draft page, it gets wild.. It won't let me delete the previous person's text-- or more accurately, when I delete said text and save the draft, the deleted text is still there in the new draft. (My own text is there as well though?) 

I think it's an editing issue similar to the person above, so I thought it best to post in the same thread, but both are definitely confusing issues!

Thanks for all you do, hopefully it gets solved soon.

(Note. All of X-kit, including my extensions, are up to date. I'm running Firefox 39.0)

**Comment by ThePsionic** [comment]
Closing, because OP said it was fixed.
