### ISSUE TITLE
Editable Reblogs: odd spacing between horizontal lines

### ISSUE THREAD

**Issue by bvtsang** [new-xkit/XKit#780]
1. Make sure your default editor is rich text
2. Click the reblog button on a post
3. Add two consecutive horizontal lines
4. Publish the post
5. Expect the spacing between the two horizontal lines to be the same as in the edit window
6. Observe that the spacing between the horizontal lines is wider than expected

Without Editable Reblogs

![Two consecutive horizontal lines posted without Editable Reblogs](https://cloud.githubusercontent.com/assets/370525/11253414/2ff889f2-8df0-11e5-8ec6-35080c9da96a.png)

With Editable Reblogs

![Two consecutive horizontal lines posted with Editable Reblogs](https://cloud.githubusercontent.com/assets/370525/11253419/368e64f8-8df0-11e5-96c2-88827c2b5029.png)

**Comment by AprilSylph** [comment]
horizontal rules are now impossible to create/do not display on the new dashboard, closing
