### ISSUE TITLE
Editable Reblogs doesn't work from the peeper

### ISSUE THREAD

**Issue by bvtsang** [new-xkit/XKit#789]
With the peepr open, reblog a post. This currently only works for people you follow, but fails otherwise.

**Comment by nightpool** [comment]
WFM? is there a more specific failure case then "ER doesn't load?" because
ER seems to be loading for me

**Comment by bvtsang** [comment]
The specific case was [here](https://gitter.im/new-xkit/support?at=5650956ca051fea34242eacc). And now I can't reproduce it anymore? Weird.

**Comment by nightpool** [comment]
Peepr is notoriously shifty. Does ER do a frame_run? There are probably
still some specific legacy situations where you can trigger iframe peepr
rather then div peepr

(what page were you on at the time?)

**Comment by bvtsang** [comment]
There is no `frame_run` method in ER, and I was on the dashboard when I last tried this.

**Comment by nightpool** [comment]
closing until more info pops up.
