### ISSUE TITLE
er doesn't respect after-posting correctly

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#790]
>Thank you for getting the drop down back, I have however noticed that when reblogging from a blog that after the post is reblogged you are back on your dash and not on the page you reblogged from. Is that something that you all will take in consideration and try to fix? When enabling the extension it works normally but with the extension it just sends me back to my dash. Thank you.

other stuff like highlighting the green reblog icon also falls into this category

**Comment by blackjackkent** [comment]
I've got a fix that I will PR shortly regarding the green reblog icon.

However I'm not sure if we have the information available to us in the post window that would allow us to do the redirect back. :/ @bvtsang thoughts?

**Comment by bvtsang** [comment]
@blackjackkent After you visit a post on a blog and click the reblog button, the original post location is visible in the URL as `?redirect_to=$ORIGINAL_POST_URL`.
