### ISSUE TITLE
New XKit Town Hall

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#796]
@new-xkit/admin, we've been at this since [about July of this year](https://github.com/new-xkit/XKit/graphs/contributors) and in that time we've made a lot of progress, with 234 issues and 331 PRs closed at the time of writing.  The Chrome Web Store [reports 259,000 users](https://chrome.google.com/webstore/detail/new-xkit/inobiceghmpkaklcknpniboilbjmlald) of New XKit, Firefox's Addon Store reported a healthy number of users before we were taken down, and we'll soon be releasing a Safari version.

[Many](https://meetings.jquery.org/) other [projects](https://nodejs.org/en/foundation/tsc/), particularly those in the Open Source world, host semi-regular group meetings to discuss the past, present, and future of the project.  You can think of it as a combination of project retrospective and planning meeting to align the core team on project goals and bring visibility to issues that affect the project and team overall.  We're about five months into the project, and I feel we're in a stable enough position that this is a good time to start organizing what I would propose to be the First New XKit Town Hall.

@bvtsang and I have put together a proposed outline and list of topics.  We wanted to put this list together ahead of time so that it can be open for discussion and modification, as well as give time for participants to prepare comments and input.

At this time, we'd ask that discussion revolve around only around Town Hall talking points, as the point of the Town Hall is to have a discussion of these points and comments _addressing_ these points defeats the purpose.

---

**Last Updated**: [2016-01-14](#issuecomment-171778522)

[**New XKit Town Hall Itinerary**](#issuecomment-171778522)

[~~**Topic Ranking Survey**~~](http://goo.gl/forms/DYKjebi8BM)

### Town Hall

- Overview of the discussion topics

### new-xkit Organization

- #719
- Discuss issue management (hat-tip to @nightpool)
  - Is Waffle still in use?
  - What use cases do we currently have for the Waffle board?
- Team member management (hat-tip to @Wolvan)
  - Do we accept new Team members?
  - What do people have to do to be allowed to join the core team?
  - How would we handle members leaving the team?
- Discuss & document infrastructure access and responsibilities
  - Who has access to the blogs/XCloud/NewXKitBot/etc
  - Who is ultimately responsible for the blogs/XCloud/NewXKitBot/etc (who "owns" a given piece)
  - How well are we mitigating the [Bus Factor](https://en.wikipedia.org/wiki/Bus_factor)
- Better use of GtiHub organization teams to organize members and access permissions (hat-tip to @Wolvan)
  - Creation of a Support team to handle asks, GitHub question issues, and support Gitter
- "Side projects"
  - Pipeline
- Adoption of http://todogroup.org/opencodeofconduct/ or equivalent (hat-tip to @hobinjk)

### Chrome

- General comments

### Firefox 

- Going unlisted
  - What this means to users
  - What this means to developers
- #216
- #775

### Safari

- #572

### Mobile

- No current plans for a mobile app (Android or iOS)
- Process around mobile-focused PRs (hat-tip to @dlmarquis)
  - Are they/how are they being tested
  - Should we expect things like UI design to be critiqued or just does-it-function-type stuff

## XKit 8.0.0 (GMP)

- Please see [the proposed milestone](https://github.com/new-xkit/XKit/milestones/v8.0.0) (hat-tip to @0xazure)
  - Suggested tweaks to the milestone are welcome

## Future XKit Versions

- Explore the process of defining features for future releases/milestones

## New Initiatives

- [The Papercut Project](https://wiki.ubuntu.com/One%20Hundred%20Papercuts/Mission) (hat-tip to @bvtsang)
  - Fixing many tiny things to improve the XKit experience. Our fixes tend to be reactionary, where we try to fix whatever Tumblr breaks or adds, rather than proactive. In this process, many smaller issues may fall by the wayside; in starting this papercut project, we can start on those small fixes.
  - Think of it as paying technical debt, for example:
    - Updating XKit branding
    - Adding documentation for existing functions
  - Easy onboarding of new contributors.  Introduce people interested in contributing to the project to XKit development through fixing easy bugs
  - Might bring in new contributors if we can label a ton of easy fixed issues and make it easy for people to make pull requests (with good documentation on the contribution process, see #487)
  - If this initial attempt is successful, we can run it again periodically in the future. For example, if we had a good run in December with this attempt, we could go on and have every X months be a Papercut Month. In doing so, we could start a culture where we encourage contributions (even more than we do now), resulting in a friendlier project overall
- Analytics (see #730 or #258 for example)

## State of the Project

- State of infrastructure
  - XCloud
  - NewXKitBot
  - -extension, -support, -discussion blogs
- From each participant, briefly:
  - Where is New XKit succeeding?
  - Where are we failing?
  - How can we improve?

## Open Floor

Any short questions / statements not related to any of the above topics, from both the core team and any interested community members.

---

### Post-Town Hall TODOs:

- [x] Publish a transcript somewhere
- [x] Publish a public summary of the state of the Town Hall to the blog(s)

> **NOTE**: Please do not comment on this issue with _answers_ to the above, as those will be discussed during the Town Hall.  Comments should be additions to the topics proposed, or requests for clarification on the above topics.

**Comment by 0xazure** [comment]
We will periodically update the master list with suggestions from the comments below, see _Last Updated_ for a timestamp and a link to the last comment at the time of update.

**Comment by 0xazure** [comment]
Additional points that need discussion:

- Setting and time and date for the Town Hall
- Setting a length for the meeting
- The medium through which we will hold the meeting
  - I would suggest creating a dedicated Gitter room that is only used for the Town Halls.  Gitter preserves chat history, so this would be an excellent way to keep a full transcript of the meeting

**Comment by Wolvan** [comment]
@0xazure will that gitter chat be public?

**Comment by Wolvan** [comment]
Additional point to discuss:
- Adding new members to the official team
  - Do we accept new Team members
  - What do people have to do to be allowed to join the core team
- Other NXKit Org Projects (\*cough\*pipeline\*cough\*)

**Comment by nightpool** [comment]
I would like a public-but-moderated channel (where only org member can chat
for at least part of the meeting). I dislike trying to keep up with chat in
gitter though, it's too easy to have people talking over each other. With
that in mind I propose another discussion topic for this issue: what the
structure of the meeting is going to be (how long will it take, who will
keep track of the discussion, how will we ensure people don't talk over
each other, stuff like that, who's going to keep order, stuff like that)

Additionally I'd like to add a meeting topic: the state of our
infrastructure, including XCloud, NewXKitBot, our blogs, and discussion any
infrastructure projects we want to handle in the future.

**Comment by Wolvan** [comment]
I second the infrastructure discussion. Also, having people be able to read what we discuss but not be able to type is what I'd find a good idea

**Comment by Wolvan** [comment]
@nightpool do you haev an alternative to gitter? Also, we should probably decide voice(+recorded) or text-only

**Comment by nightpool** [comment]
@wolvan the only other solution would be hangouts or something, I guess.
not sure if people want to go that way though.

**Comment by Wolvan** [comment]
You mean Google Hangouts? Not really a fan of that, unstable as hell. Or do you mean because of recording?
Recording definitely is not a big deal, I have tools to record any program on my PC

**Comment by nightpool** [comment]
@wolvan do you know of a better voice chat application that doesn't require
yet another thick client?

**Comment by Wolvan** [comment]
@ThePsionic 
>/me butts in with Discord

Discord has a very well functioning web interface, @nightpool. No client required

**Comment by bvtsang** [comment]
I've added the following topics:

- Adding new members
- Analytics collection
- Infrastructure

@Wolvan I don't want to include Pipeline because it's separate from New XKit. If we're going with @nightpool's suggestion to make this public-but-moderated, then I really don't want to give the public any false hopes that Pipeline could be finished anytime soon.

RE Discord: We already have a [Discord server](https://discord.gg/0a2AI1yBgWncTzSK) up. Feel free to join to test it out, look around, etc.

**Comment by Wolvan** [comment]
@bvtsang Pipeline was just an example project that our team is working on apart from New XKit. I just want to address how we handle other projects in general

**Comment by bvtsang** [comment]
@Wolvan As of this writing, the new-xkit organization has the following projects:

- XKit
- NewXKitBot
- pipeline
- XCloud

Three of the four are related to XKit and will be discussed (as part of infrastructure). If we generalize, we could say that only XKit-related projects are viable for discussion in the Town Hall.

**Comment by Wolvan** [comment]
fair enough I suppose, @bvtsang

**Comment by nightpool** [comment]
I would also prefer to address the full governance of all new-xkit
associated projects.

**Comment by Wolvan** [comment]
Another point that @0xazure reminded me of (thanks bud):
Distribution of control over for example the bot, the extension pages in the appstores, the organization itself....

**Comment by hobinjk** [comment]
I agree with the importance of these topics. Discord looks like a great way to have a spoken discussion. Scheduling will probably end up being the chief difficulty with this.

**Comment by dlmarquis** [comment]
Re: meeting infrastructure:

We should designate a note-taker so that we have a written record of things we discussed. This can be done during the meeting, or someone can volunteer to go over the recording later. Format could be anything from full notes to "discussed Edible Reblogs: 01:23:00--01:35:45"-style bullets. Just something more convenient than having to listen to the whole thing each time we need to reference it.

For mobile: We have no plans for apps, but I've been adding mobile site support & features for the browser. This is largely for my own sanity, but I'd like to know a bit about how y'all handle those PRs. Are they being tested/should I expect things like ui design to be critiqued or just does-it-function-type stuff/etc.

**Comment by Wolvan** [comment]
If we don't do text-only chat I agree with @dlmarquis. Having a good transcript of what's being said to publish for people to read would help a lot, not only them but also us

**Comment by nightpool** [comment]
If we can figure out a general timeline for this (probably after
thanksgiving?) I can set up a when2meet

**Comment by Wolvan** [comment]
I propose the Town Hall to be on a saturday. I think the middle of the weekend might help us with timezones

**Comment by Wolvan** [comment]
@bvtsang and me have been talking about this, but since the Town Hall is going to be public, how about we give the people who are there the chance to ask questions after we finish the core of the town hall (as kind of an extension to the open floor or something)

Additionally, I propose the 12th december to be our date for the town hall

**Comment by nightpool** [comment]
yeah, I was assuming we'd have some sort of open floor.

**Comment by Wolvan** [comment]
Should we talk about donations as well?

**Comment by 0xazure** [comment]
I think we always anticipated having some kind of moderator, regardless of what means of hosting we decided on.  Though @nightpool you said
> [in Gitter] it's too easy to have people talking over each other

I'd actually disagree.  It would be _significantly_ easier for people to "talk over" each other over a voice communication solution.  At least with text there's a non-transient form of what was said that could be referred back to at the individual's own pace, rather than the pace of the (oral) conversation.

I'm rather ambivalent around text vs voice, but I'd just like to note that I think text-only would make it more difficult to lose discussion and would also preserve an easier record to turn into meeting notes.  On the other hand, Discord does provide some nice functionality in terms of muting users and controlling permissions in both voice and text channels, which Gitter (and other text-only mediums) lack.  If we go with voice chat, there would need to be agreement from all participating parties to allow recordings to be taken, even if those recordings are simply for generating meeting notes and a written documentation of the meeting. (This may also be a [Legal Thing](https://en.wikipedia.org/wiki/Legality_of_recording_by_civilians), particularly since we're international.)

Regarding date, time, length, I would tentatively second scheduling some time around the Christmas period.  Given the number of topics and the size of the team, we're probably looking at ~2h+, but I think  once we've firmed up the topics we should look at prioritizing them so that if we run over time we can be sure we've covered the most important ones.  We could set up a [Strawpoll](https://strawpoll.me/) or something to that effect for ranking.

As far as the project scope of this Town Hall, I'd like to limit it to XKit-related projects (XKit itself, XKit infrastructure like NewXKitBot, and XCloud) only.  My understanding (@blackjackkent correct me if I'm off base here) is that Pipeline needs to have an internal discussion regarding the org and governance and get itself straightened out.

@Wolvan
> Distribution of control

This is an interesting point, I'll update the master list with something to this effect.

> how about we give the people who are there the chance to ask questions

I've updated the "Open Floor" section to hopefully clarify this.  Provided there are community members that want to get involved and/or ask questions, I don't see any reason we can't include them.

> donations

I don't think there's anything to talk about?  We don't have any operating costs as far as I'm aware, and we've covered the cost of the Apple Developer Program (though that _will_ come up for renewal on an annual basis).

**Comment by Wolvan** [comment]
I meant donations that we distribute under us team members. Also, @ChuckL does in fact have operation costs (even if they're tiny) and as you mentioned, the developer program costs yearly

**Comment by bvtsang** [comment]
@nightpool Do the weekends + Fridays in 12/6-12/20 work as a viable range for a when2meet?

@Wolvan Do you mean to add to the list of Town Hall topics the _potential_ to accept and distribute donations (to overrule our current "we're not accepting donations" stance)? Or the logistics of distribution for existing and future operation costs? Or something else?

**Comment by Wolvan** [comment]
I meant the potential to accept and distribute donations, yeah

**Comment by rosalindwills** [comment]
@0xazure Yes, Pipeline should probably be discussed in a different context; that's got its own set of issues and I don't want to add scope creep to the discussion.

I've been sort of out of the loop here bc traveling/company, but I'm inclined to lean towards text rather than voice for the discussion bc A) paper trail and B) easier to have everyone be heard and not talked over. I think we should definitely still have a moderator though (and everyone agree to be directed by that moderator as far as organizing the conversation).

**Comment by blackjackkent** [comment]
@0xazure Yes, Pipeline should probably be discussed in a different context; that's got its own set of issues and I don't want to add scope creep to the discussion.

I've been sort of out of the loop here bc traveling/company, but I'm inclined to lean towards text rather than voice for the discussion bc A) paper trail and B) easier to have everyone be heard and not talked over. I think we should definitely still have a moderator though (and everyone agree to be directed by that moderator as far as organizing the conversation).

**Comment by Wolvan** [comment]
Discussing pipeline is out of the question, but I would definitely like to discuss on how we will distribute our time between all the projects

**Comment by Wolvan** [comment]
Another suggestion: Organization of new-xkit org itself. As in, management of the org teams. Right now we only have the admins team afaik. What if we have "support" teams and something the like as well, people who don't handle coding but are responsible for helping users out. This is just an example group, I'd like to discuss this more in dev in the town hall meeting

**Comment by nightpool** [comment]
Would love to add more people without having to trust them with reviewer
rights.

**Comment by bvtsang** [comment]
I've set up a [when2meet](http://www.when2meet.com/?3964076-mcgOQ). Note that the times listed are in UTC.

Here is a summary of other things we've touched upon, but haven't finalized:

- Length of meeting (looks to be about 2 hours)
  - We may want to [prioritize meeting topics](#issuecomment-161160813) in case the meeting goes over
- Medium
  - Gitter
    - +We already use it
    - +No permission controls
    - +Preserves chat history
    - No voice
  - Discord
    - People have to try/get used to this new service
    - +Client not required (available via web and apps for all platforms)
    - +Voice (will require [meeting notes](#issuecomment-159462508))
    - +Permission controls
    - +Preserves chat history
- Roles
  - Moderator

Suggestion: use Discord, but without voice chat. This will preserve chat history, allow us to have a period where only developers can talk before [opening discussion to the public](#issuecomment-160685903), and not require meeting notes.

**Comment by 0xazure** [comment]
> discuss on how we will distribute our time between all the projects

I don't feel this should even be up for discussion.  I would expect core team members contributing to side projects to be responsible for their own time management, and I don't think they should have their contribution time micro-managed.  I can understand concerns about future "brain drain" as core team members cycle off to work on other projects, but we aren't in a position yet where that is a concern, and that discussion is closely linked with discussing projects like Pipeline "in a different context", as @blackjackkent said.

> Suggestion: use Discord, but without voice chat.

:+1: from me.  It's unfortunate that Gitter lacks chat controls like controlling who can speak at a given time in a channel.

**Comment by 0xazure** [comment]
I'd like to close the suggestions for additional topics on this issue on 2015-12-12, so if you have any topic suggestions to add please try and get them in before then. I'd like to get the order of discussion hammered out, and I'll be sending a link for a ranking poll on the same day [via Gitter](https://gitter.im/new-xkit/XKit) so we can start to prioritize topics to fit into the time window so we can cover the most important and/or pressing items first should we start to go over time.

**Comment by hobinjk** [comment]
I'm adding an additional topic to cover the adoption of http://todogroup.org/opencodeofconduct/. Sorry for the delay in proposing this.

**Comment by nightpool** [comment]
was just about to say that same thing about a code of conduct for both our
repos and, more importantly, our chat.

**Comment by 0xazure** [comment]
Meant to comment on 2015-12-12, but since we haven't settled on a date yet I thought I'd leave discussion open for a bit longer.

With this, I'd like to freeze the addition of new topics and instead continue refining the existing topics that have been put forward.

I have also [prepared a survey](http://goo.gl/forms/DYKjebi8BM) to gather feedback on prioritizing the current topics for discussion.  Would really appreciate everyone's input so we can cover the most important ground first during the allotted time, once we've set a date.

---

**Comment by nightpool** [comment]
few questions:

 - if we haven’t decided on a time, why have we frozen the topics?
- what voting method are we using to compile the rankings?
 - why are Future XKit Versions and XKit 8.0.0 separate topics, but the new initiatives aren't? the grouping feels weird here. definitely XKit 8 and Future Versions should go together, but before we discuss XKit 8 we have to discuss future projects that could *make up* XKit 8, no?
 - also I don’t really like the state of the project topic as it is. I would rather infrastructure discussion go under org management. (And the other stuff under "New Initiatives" maybe?)

**Comment by Wolvan** [comment]
Going unlisted isn't really working anymore, since we already tried and failed that, right?

**Comment by bvtsang** [comment]
The topics are frozen because there are too many things to discuss, and we may not have enough time to go through them all. With the number of members we have right now, we may easily keep talking for more than two hours, and based on our first when2meet we can't guarantee two hours for everyone.

The XKit 8.0.0 topic is about things that will go into that specific release. The Future XKit Versions is a generalized discussion of XKit 8.0.0 where we decide the _process_ of defining what goes into XKit 9.0.0, 10.0.0, etc. They are separate topics because one is about the present and the other is about the future.

**Comment by 0xazure** [comment]
@nightpool:

> if we haven’t decided on a time, why have we frozen the topics?

We've frozen the topics so we can start prioritizing them.  I'm already concerned about fitting everything we already have into a reasonable meeting window; I think sticking with what we have so far will be the best use of the time.  Additionally, there hasn't been much movement on this issue (barring @hobinjk's addition 2 days ago) within the last week, I feel it's unlikely that we'll be getting any more additions.  If this _isn't_ the case, by all means, but I _did_ give sufficient notice (and some extra).

> what voting method are we using to compile the rankings?

Not sure I understand.  It's a ranking system. The survey itself has details.

> [...] separate topics, but the new initiatives aren't?

Do you mean why the Papercut Project and Analytics aren't separate topics?

> but before we discuss XKit 8 we have to discuss future projects that could make up XKit 8, no?

We've (I've) already started compiling a Milestone of features for v8.0.0.  There are already a lot of feature requests that can get taken care of together as we implement certain changes for v8.0.0.  Have a look at the milestone.

As @bvtsang said, "Future XKit Versions" is about defining a process for major release changes going forward, as opposed to dealing with a specific release and its features.

> infrastructure discussion go under org management

Yes, I actually like that better too (probably because I didn't make the edit that added those points).

> other stuff under "New Initiatives"

But they aren't new initiatives.  It's a during-this-Town-Hall where-are-we-currently gathering of feedback.  They're fine as a separate topic, but we could nitpick the topic name, sure.

**Comment by bvtsang** [comment]
@new-xkit/admin The times everyone has agreed to is **1/16, 10-11 PM UTC**. But before then, a couple of notes:

- If you haven't already, please join [our Discord](https://discord.gg/0a2AI1yBgWncTzSK) so we can set up the permissions stuff early (and so you can get a feel of how it works)
  - The general public is also invited to join.
  - For simple moderation and note-taking, there will be no voice chat for the Town Hall.
- @0xazure, we'll need the results of [the survey](http://goo.gl/forms/DYKjebi8BM) you passed out so we can properly prioritize our topics. Note that we only have an hour.
- If you have any other concerns, please let us all know in this issue or in our org chat.

That's it! I'll see you all there!

**Comment by nightpool** [comment]
:+1

**Comment by 0xazure** [comment]
I've gone through the [results of the survey](https://docs.google.com/spreadsheets/d/1x-TH5tqcxfVt7OVscA-BdI5Z-EYmHfoM9YfFuWkix3U) and, based on the responses, put together the meeting itinerary below.  Note that some (minor) executive decision-making has been exercised in order to ensure topic flow, as well as some tweaks because of changes between when the survey was created and now.

---

## New XKit Organization

- Team member management (`Wolvan`)
  - Do we accept new Team members?
  - What do people have to do to be allowed to join the core team?
  - How would we handle members leaving the team?
- Discuss & document infrastructure access and responsibilities
  - Who has access to the blogs/XCloud/NewXKitBot/etc
  - Who is ultimately responsible for the blogs/XCloud/NewXKitBot/etc (who "owns" a given piece)
  - How well are we mitigating the Bus Factor
- New XKit project scope
  - "Side projects" like Pipeline
- Better use of GtiHub organization teams to organize members and access permissions (`Wolvan`)
- State of the Project
  - State of infrastructure
    - XCloud
    - NewXKitBot
    - -extension, -support, -discussion blogs
  - From each participant, briefly:
    - Where is New XKit succeeding?
    - Where are we failing?
    - How can we improve?
- Discuss issue management (`nightpool`)
  - Is Waffle still in use?
  - What use cases do we currently have for the Waffle board?
- Adoption of a Code of Conduct (`hobinjk`)
- #719 Standardize browser extension divergence (`hobinjk`)

## Future XKit Versions

- Explore the process of defining features for future releases/milestones
- #478 The Great Modularization Project

## Platforms

- Firefox
  - State of the Firefox version
  - Re-list extension & #216 New XKit does not pass Mozilla's automated validation for the app store
- Mobile
  - No current plans for a mobile app (Android or iOS)
  - Process around mobile-focused PRs (`dlmarquis`)
    - Should we expect things like UI design to be critiqued or just does-it-function-type stuff
    - Are they/how are they being tested
- Safari
  - #572 Release Safari version
- Chrome
  - General comments

## New Project Initiatives

- Papercut Project
- Analytics, for example #730, #258

---

As always, let me know if there are any comments/questions/(constructive) criticisms.

**Comment by Wolvan** [comment]
This just came to me, @0xazure, but should we discuss palemoon real quick as part of platform as well? Nothing big, just a quick talk over (5-10min maybe)

**Comment by 0xazure** [comment]
> should we discuss palemoon real quick

Per my [comment on Dec 17th](https://github.com/new-xkit/XKit/issues/796#issuecomment-165547616) I'd really rather not be adding additional topics to our already-lengthy list.

The discussion around Pale Moon isn't something that can be taken care of "real quick", and I don't feel that sufficient discussion has been had on #900 for it to be promoted to a Town Hall topic.  I'd actually like to see #900 pushed back to a feature request issue for discussion instead of its current existence as just a PR.

I feel there are currently too many outstanding questions for Pale Moon to be a productive discussion topic for the PR.

**Comment by bvtsang** [comment]
Summary posted here: http://new-xkit-extension.tumblr.com/post/139751926379/2016-01-16-town-hall-summary
