### ISSUE TITLE
Ext: Auto Tagger does not correctly tag new posts that require a url or upload.

### ISSUE THREAD

**Issue by namanix** [new-xkit/XKit#807]
Hi,

There seems to be a bug in the Auto Tagger extension. When i set my auto tags for posts i create (This is also the case in: "Tags by type") it works for regular text or quote posts. But when i create a new image post. And upload a photo or place a url i only see my last tag that i added in the settings. And when i actually post it. It doesn't show any tags at all. I've attached a screenshot as a reference to my problem. I hope you guys can fix this problem so i can start using it :).

Kind regards,
Kevin Walter

![preview2](https://cloud.githubusercontent.com/assets/1583377/11497965/b8bf50c8-981c-11e5-8586-70ad7cba7533.PNG)

![preview1](https://cloud.githubusercontent.com/assets/1583377/11497966/b8c90d8e-981c-11e5-9896-a6342d2206e6.PNG)

**Comment by ThePsionic** [comment]
Fixed by #808.
