### ISSUE TITLE
Add tweak to block video upload notifications

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#81]
We've had reports of the video upload notification not disappearing after a set amount of time and lasting forever and across blogs.

**Comment by nightpool** [comment]
do we have any extensions that affect videos or should I just start testing randomly?

**Comment by hobinjk** [comment]
This is a problem that happens with vanilla Tumblr. I believe the desired outcome of this is a tweak/extension that implements a way of blocking the video upload notifications.

**Comment by nightpool** [comment]
@hobinjk ah thanks for clarifying.

**Comment by ThePsionic** [comment]
Closing, since the video upload notification seems to have been removed altogether.
