### ISSUE TITLE
One Click Postage: automatically remove image captions

### ISSUE THREAD

**Issue by bvtsang** [new-xkit/XKit#814]
So that [a user](https://gitter.im/new-xkit/support?at=565e6e6a5993bcb005d2dd89) won't have to click "remove caption" all the time in the One Click Postage popup.

**Comment by nightpool** [comment]
please dont :/

**Comment by xThreeh** [comment]
Is a great idea!

**Comment by ThePsionic** [comment]
I'm not a fan of the "remove caption" button as is, seeing it makes it pretty easy for anyone to delete people's captions (although I guess with Tumblr's new way of doing it it's not made a lot harder). I wouldn't want to see this as an automated thing though.

**Comment by nightpool** [comment]
Oppose per @thepsionic

**Comment by bvtsang** [comment]
Thanks for your feedback. Closing because the devs don't support this idea.

**Comment by Wolvan** [comment]
I agree with both @ThePsionic and @nightpool
