### ISSUE TITLE
playing pokés with two tabs can lead to losing some large part of your library

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#822]
Haven't had time to repro this, but there was someone who had lost a large part of their collected pokémon, and they thought it was possibly because they had two tabs open that were both collecting pokemon? 

worth investigating.

**Comment by nightpool** [comment]
@ThePsionic

**Comment by ThePsionic** [comment]
I'm not sure what the internal workings of the storage are, which I think are more at play here.

When a Pokémon is clicked, the extension loads the current storage, which is a JSON array of objects, or makes a new empty array if the storage is either empty or somehow invalidated. Then it tries to find if a Pokémon of the same species and gender already exists; if it doesn't, it adds it as a new object into the array, and if it does, the amount on that species and gender is just bumped up by one. After that the array is JSONified again and stored.

**Comment by Wolvan** [comment]
I honestly blame XKit's storage as well. XKit instantiates a storage object once on startup and then never reads from storage again until you reload the page. Writing does happen though

**Comment by ThePsionic** [comment]
Which is probably why this goes wrong.

**Comment by Wolvan** [comment]
Which is EXACTLY why this goes wrong.

**Comment by AprilSylph** [comment]
eaten by
