### ISSUE TITLE
on-blog controls broken

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#831]
from the ask box:

>Hi! :) I just wanted to let you know that I've been having trouble with the tumblr controls since a few days ago. This issue only happens on my own blog. The "slim" buttons are not working, I've got the big buttons now (aka the ones that say "reblog" and "follow", for instance) And the quick reblog, quick queue and quick draft buttons are missing. As I said, this happens on my own blog, it works on others. I use them a lot on my own blog so I'd appreciate it A LOT if you could look into it :)

and

>the quick reblog icons for xkit are missing in the upper right hand corner of the pages. Can you please repair it?

probably due to messaging, but "a few days ago" sounds fishy. 

extensions that are affected:

- [ ] find blogs
- [x] ~~go-to-dash~~
- [ ] mute
- [x] ~~one-click postage~~
- [ ] post archiver
- [ ] profiler
- [ ] reblog yourself
- [ ] view on dash

**Comment by nightpool** [comment]
confirmed not related to messaging:

this blog exhibits the issue: http://picsiaminlovewith.tumblr.com/post/134497681508 (NSFW)
while this blog doesn't: http://photoclivities.tumblr.com/post/134511512582 (NSFW)

**Comment by nightpool** [comment]
my intuitions tell me this will probably require a new extension version :/

**Comment by nightpool** [comment]
nevermind that's almost certainly wrong.

**Comment by Wolvan** [comment]
I did find a blog that exhibited this behaviour as well, but I forgot which one it was. Something's certainly fishy with the IFrame here though

**Comment by izub** [comment]
The thing that is breaking the on blog controls is the rolling out of a new iframe of controls. where the buttons and layout have different classes and everything.
The old iframe url is like:
https://www.tumblr.com/dashboard/iframe?src=[POST_URL]&rk=[...]&lang=en_US&name=[BLOG_NAME]&avatar=[AVATAR_URL]&title=[BLOG_TITLE]&url=[BLOG_URL]&page_slide=slide&_v=[...]

The new iframe url is:
https://www.tumblr.com/dashboard/iframe?tumblelogName=[BLOG_NAME]&singlePostId=[POST_ID]

**Comment by nightpool** [comment]
That was my assumption, but it seems weird they're rolling this out blog by
blog instead of user by user.

**Comment by nightpool** [comment]
okay basically all blogs are exhibiting this issue now. I'll work on a fix tonight

**Comment by nightpool** [comment]
Still planning to work on a fix for the rest of these, but anyone else is free to take if they want

**Comment by nightpool** [comment]
there are enough issues here that it's hard to triage this bug. We should probably open issues for individual extensions that are still broken as we get reports about them
