### ISSUE TITLE
Find Inactives doesn't work

### ISSUE THREAD

**Issue by xThreeh** [new-xkit/XKit#833]
I was reviewing this extension for 15 minutes and never gave me a result. 
To others could be added the option to search inactive blog 1 week pls

I follow only 48 blogs and 15 minutes for 48 blogs is so much or not? :cry: 

![screenshot_44](https://cloud.githubusercontent.com/assets/16139465/11592671/c2a42b54-9a7e-11e5-958c-4c48a4d621bc.png)

PS: Excuse my English, I speak Spanish but I try to help.

**Comment by Wolvan** [comment]
Find inactives works perfectly fine for me, and I follow 1710 blogs. I'll add the 1 week though

**Comment by xThreeh** [comment]
@nightpool No show result, I have selected the one week in Find Inactives. 
New XKit 7.7.1 and i used Google Chrome 47.0.2526.73 m

![screenshot_47](https://cloud.githubusercontent.com/assets/16139465/11611481/2bbe1880-9baf-11e5-9675-5f0fd62dfb06.png)

**Comment by nightpool** [comment]
Oh yeah, sorry, just to be clear, that was just the suggestion that was implemented, we haven't be able to fix this issue yet

**Comment by ChuckL** [comment]
This is an issue when the language is not English.

You can repo this issue by going into your settings and changing your language.  (and a work around for the time being is switching your language to English, running it, then switching it back.)

These lines are where the bug is.
https://github.com/new-xkit/XKit/blob/master/Extensions/find_inactives.js#L160-L182

I'll work on a fix.

**Comment by nightpool** [comment]
yeah I just had put that together myself. feel free to go ahead on the fix

**Comment by xThreeh** [comment]
@ChuckL @nightpool  thanks :heart_eyes: 

PS: Excuse my English, I speak Spanish but I try to help.

**Comment by xThreeh** [comment]
@ChuckL up

**Comment by ChuckL** [comment]
It's fixed but needs to be merged into the project.
https://github.com/new-xkit/XKit/pull/846

**Comment by xThreeh** [comment]
@ChuckL u'r the master <3
