### ISSUE TITLE
ER breaks audio posts

### ISSUE THREAD

**Issue by blackjackkent** [new-xkit/XKit#834]
>*talesofchatnoir* has joined.
*talesofchatnoir* hi! my username is my blog name
*talesofchatnoir* i'm having a problem with audio posts and i'm not sure if it's anything to do with xkit but i thought i'd ask
*talesofchatnoir* i reblogged some audio posts from the search page to test my theme
*talesofchatnoir* but they're orphaned, no sound inside, song name and everything cleared, no album art
*talesofchatnoir* not even a thing saying i reblogged it from someone
*talesofchatnoir* http://talesofchatnoir.tumblr.com/ ok if you look, the first two work, the second two don't work. the one at the top is me reblogging from the search page with editable reblogs turned off
*talesofchatnoir* and it works if editable reblogs is turned off
*talesofchatnoir* it doesn't work if they're on
*talesofchatnoir* so from the top: from search page with editable reblogs turned off, from actual person's page, from search page with editable reblogs turned on
*talesofchatnoir* all the same post

**Comment by gloomykid** [comment]
can confirm that

**Comment by nightpool** [comment]
also ancient, and haven't heard anything about this recently.
