### ISSUE TITLE
"New" Extension XKit: Delta Checker and Mutual Checker

### ISSUE THREAD

**Issue by xThreeh** [new-xkit/XKit#843]
Hey guys, today I care to know who did not follow me back, look at xkit an extension to that, but could not find it and I remembered that before there was a flame "Delta Checker and Mutual Checker" believe that they could re-create this extension. :cry: 
![screenshot_49](https://cloud.githubusercontent.com/assets/16139465/11613343/bae330d4-9bfc-11e5-8d67-1b276bbf4483.png)

**Comment by Wolvan** [comment]
Delta Checker and Mutual Follower Checkers will not happen, due to chances of being abused
