### ISSUE TITLE
New Extension: Follower Checker

### ISSUE THREAD

**Issue by xThreeh** [new-xkit/XKit#845]
I tested this extension and really loved it, would be created for new- xkit
https://chrome.google.com/webstore/detail/tumblr-follower-checker/fpneflnjiifpgbefacneaoadpogjdnco

![screenshot_54](https://cloud.githubusercontent.com/assets/16139465/11615115/84187fac-9c36-11e5-927f-4a401df8fe6b.png)

**Comment by Wolvan** [comment]
We already said in #843 that we will not implement any kind of mutual OR delta followers checker. Please do not open further issues that request these kind of features

**Comment by xThreeh** [comment]
qlo fomeke :dancers:
