### ISSUE TITLE
Add shiny Pokémon

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#848]
These would only be denoted by an icon rather than a separate sprite, seeing Nintendo did not care to make separate menu sprites for shinies.

**Comment by Wolvan** [comment]
just an icon? Isn't that kinda... you know, boring?

**Comment by ThePsionic** [comment]
If you have a better idea feel free to throw it at me. As I said there are no shiny menu sprites by Nintendo, and I don't really fancy editing ~900 icons myself to make them that way.

**Comment by Wolvan** [comment]
Alright, fair enough. What ratio should shiny pokemon spawn with?

**Comment by ThePsionic** [comment]
As of Gen6, shiny Pokémon have a [1 in 4096 chance of spawning in the wild](http://bulbapedia.bulbagarden.net/wiki/Shiny_Pok%C3%A9mon#Generation_VI).

**Comment by Wolvan** [comment]
Closing in favor of #855
