### ISSUE TITLE
"null" tags

### ISSUE THREAD

**Issue by sorrytryagain** [new-xkit/XKit#85]
Sometimes when I reblog, the tag "null" is automatically added onto my post after it's been submitted.

**Comment by dlmarquis** [comment]
Around the time of the Tumblr update to reblogs, I also saw "null" being added to the titles of previously untitled text posts, and as a comment on reblogs as well. This is likely either purely a tumblr update thing, or the recent update broke part of XKit.

**Comment by nightpool** [comment]
this is the same bug as #76, I believe. (tumblr changed some part of their API). Do you have auto-tagger enabled?

@dlmarquis I saw that to, but that's probably something else. I'm pretty sure it was happening to people who didn't have xkit installed at all.

**Comment by 0xazure** [comment]
Is this issue still happening, or has it resolved itself?

**Comment by sorrytryagain** [comment]
The issue resolved itself, thank you

**Comment by 0xazure** [comment]
Closing as resolved.
