### ISSUE TITLE
 'go to activity page when clicking on a sideblog' no longer works

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#851]
from chat:
activity+: option "go to activity page when clicking on a sideblog" doesn't work.

unverified, haven't reproduced

Windows 10, Chrome v46

https://gist.github.com/anonymous/8660f98e12b2f3398420

**Comment by AprilSylph** [comment]
confirmed; stale feature which relies on the old sidebar layout. this option should be removed and/or revived via enhancements to Old Stats
