### ISSUE TITLE
Rethink Pokés interface

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#854]
With future plans like trading and so on, I think we should rethink the interface. For example move the Pokemon list out of the preferences and into an actual page element. Or at least have a button that opens the list.

**Comment by ThePsionic** [comment]
Mockup ft. pro MSPaint skills
![untitled](https://cloud.githubusercontent.com/assets/842080/11652451/2c4ad820-9d98-11e5-867a-484563ed51af.png)

**Comment by Wolvan** [comment]
Regarding a Dashboard Button, should we have the button just directly open Pokés' extension control panel?

**Comment by ThePsionic** [comment]
I don't think so. Everything's already accessible through the control panel, and making a new button saves exactly 1 click and a bit of scrolling.

**Comment by Wolvan** [comment]
fair enough

**Comment by lizzledpink** [comment]
So in this professionally made MS Paint mock-up, would we want "Pokémon" to open the Pokedex, or your list of Pokemon? Are we planning to distinguish the Pokedex from your Pokemon, or keep it more or less as is now, where you can view the Pokemon you own and that counts as your Pokedex? (Which might make more sense if/when sorting is implemented.)

Do we want to reduce the interface grid from 8 buttons to 6 until such time as we actually have more than 6 things planned out?

(Please pretend the accent is in the word Pokemon every time I type it.)

**Comment by nightpool** [comment]
Love that design @thepsionic

**Comment by Wolvan** [comment]
I'll see if I can get it to work shortly. And I agree with @lizzledpink to have 3 buttons per row until we really need 4

**Comment by ThePsionic** [comment]
Fair enough. @lizzledpink Pokémon would open your list of Pokémon. I'm not sure whether I want a list of all possible Pokémon, but it's worth considering.
