### ISSUE TITLE
Editable Reblogs mess up queue/scheduling (still happening)

### ISSUE THREAD

**Issue by maswartz** [new-xkit/XKit#858]
The problem mentioned in this https://github.com/new-xkit/XKit/issues/804#issuecomment-161731461 Has return/never left. I just tried to schedule a post for 12 on Wed and it set it for 8 AM on Tue. I turned off Editable Reblogs and it worked fine and I know this time that I put the time in.

**Comment by nightpool** [comment]
Hmm maybe this is a timezone thing @blackjackkent?

**Comment by blackjackkent** [comment]
Might be. @maswartz Where are you located? (roughly -- time zone is enough)

**Comment by maswartz** [comment]
Massachusetts so EST

**Comment by blackjackkent** [comment]
You've mentioned this only happens on certain posts. Does it ALWAYS happen on those particular posts or is it intermittent even on a per-post basis? Does it seem to happen on a particular type of post?

**Comment by maswartz** [comment]
I just scheduled three posts, one from a person I'm following via my dash, one from a side blog of myself and one from scratch. The one from the other person and from the side blog both defaulted to Tue at 8 AM (I entered thursday and friday times respectively) but the one from scratch kept it's time (I set it for a time on saturday)

**Comment by nightpool** [comment]
Can you post your extension info dump? Thanks.

**Comment by maswartz** [comment]
If I knew what that meant I could

**Comment by nightpool** [comment]
Oh, sorry, its a list of all the extensions you have installed. To generate one, open the XKit control panel, click the Other tab, and go to Export Configuration > Extension Info Export.

**Comment by maswartz** [comment]
https://gist.github.com/686b77f43e771ba7197a This?

**Comment by maswartz** [comment]
This issue is still happening.

**Comment by nightpool** [comment]
ancient, no additional info to try diagnosing.
