### ISSUE TITLE
XKit icon, New Post icons + paper plane icon bug?

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#866]
I'm not sure what is happening anymore but here are screenshots.

![ss 2015-12-10 at 11 04 06](https://cloud.githubusercontent.com/assets/13604430/11729980/7cd5b804-9f92-11e5-95ed-09f2c3f94750.jpg)

![ss 2015-12-10 at 11 04 19](https://cloud.githubusercontent.com/assets/13604430/11729982/7fa85eec-9f92-11e5-8bb8-b293d3906d9c.png)

EDIT:
Just realised it's the search bar icon too...

**Comment by nightpool** [comment]
this is reproducible with xkit disabled.
