### ISSUE TITLE
Autotagger not working

### ISSUE THREAD

**Issue by rl1426** [new-xkit/XKit#875]
Tags entered in settings do not show up on posts.
Nothing happens when i "enter value and hit enter" in settings.

**Comment by Wolvan** [comment]
This sounds like you want to have already posted and queued posts to be tagged once you hit enter. Nothing is supposed to happen, hit enter just saves the value, there's no confirmation or anything.
Furthermore, the queue tag only works with Quick Reblog's Queuing function

**Comment by nightpool** [comment]
unclear whether this is a new feature or a bug—can someone clarify? 

@Wolvan I'm pretty sure it also works with OCP, right?

**Comment by Wolvan** [comment]
Quick Reblog is part of OCP, I use the blog buttons to Quick Reblog rarely though so I forgot to mention them

**Comment by Wolvan** [comment]
Might be, I haven't tried so far
