### ISSUE TITLE
New Reblog/Like/Share Icons

### ISSUE THREAD

**Issue by ClaudiaDonovan** [new-xkit/XKit#876]
![image](https://cloud.githubusercontent.com/assets/16121582/11901625/8f11162e-a57a-11e5-90ce-2b9c1dea82f0.png)

User requested: Please change them back

**Comment by boynedmaster** [comment]
Do you by any chance have/can get the old icon images?

**Comment by AprilSylph** [comment]
the old icons still seem to be present in the `tumblr-icons` font (not sure about the old like icon) but i think at this point it's too late to be worth doing; closing as "missed the chance"
