### ISSUE TITLE
"delete caption" wont work

### ISSUE THREAD

**Issue by gaycabbage** [new-xkit/XKit#88]
hi! whenever i wanna delete a caption, i use the button when hovering over the reblog button.. besides it doesnt delete the actual caption! and i've tried updating, but none of it seem to work..

**Comment by nightpool** [comment]
yep this is related to the most recent tumblr update.

**Comment by bootyquanda** [comment]
Yeah this is pretty much the only thing I want fixed.

**Comment by blackjackkent** [comment]
Had a go at this tonight and I BELIEVE I figured it out. PR is at #147 :)

**Comment by blackjackkent** [comment]
Resolved by #147
