### ISSUE TITLE
Text going over the post line when continuing an ask thread

### ISSUE THREAD

**Issue by patty85** [new-xkit/XKit#880]
Hello I wanted to see if a solution could be made for this lease, this issue started to happen after the update that added that little icon replacing the reply, what happens is when a thread is continued from an ask the text is gone, my reply is gone on my dash and the text goes over the sides from the post lines. Since I'm not the best at explaining you have a screencap here to see it, I noticed this only happens with the asks. And yes I have the reblog option from xkit and I have tried every single option in there and only when that option is enable does things looks normal but that means no blockquotes and back to the icons on the posts and that annoying line so of course I would want to keep the Reblog Display Options but also have this problem fixed if possible. Thank you.

![capturar](https://cloud.githubusercontent.com/assets/16366879/11916123/bdb24be6-a6c0-11e5-969a-7e7b0e701a9e.JPG)

**Comment by Wolvan** [comment]
Please provide an extension dump

**Comment by patty85** [comment]
I'm sorry I'm new here could you tell me what that is?

If you mean what extension might be making the text like that I think that is the Reblog Display Option

**Comment by Wolvan** [comment]
XKit Control Panel -> Other Tab -> Export Configuration -> Extension Info Export

**Comment by patty85** [comment]
https://gist.github.com/7d8b0b16953e5fb7c83a

**Comment by Wolvan** [comment]
Does this happen to every post or just a selected few? Can you link us to that post?

**Comment by patty85** [comment]
It just shows on the dash on mine as far as I know, in all the blogs I have and only on asks.

If you go to the blog will look fine but here this is one of the many that has that problem: http://rebelliousxbeauty.tumblr.com/post/134967786819/its-positive-rebelliousxbeauty

**Comment by Wolvan** [comment]
And you said it is with Reblog Display Options enabled that it happens? What settings do you use there

**Comment by patty85** [comment]
Yes, if I remove it goes to the last update which I dislike but the text gets on its place not over the line like I showed. 

I have nestled with the removed green reblogged icon, move reblog content to the right under username, add border to the left, put post titles above posts and remove avatars.

In the tweaks I have slim block quotes for easier reading

**Comment by Wolvan** [comment]
I didn't manage to replicate, @nightpool do you have an idea?

**Comment by patty85** [comment]
Honestly no, all I know is that is started after they did that update to replace the reply on threads.FixMyPost used to work properly but even that stopped so then I went for the Reblog Display Options and no matter what I do it stays like that and is very frustrating

**Comment by nightpool** [comment]
I'm guessing this has to do with whatever theme you have installed. Can you tell me which one it is? (Do you have any non-XKit extensions installed, such as Stylish?)

**Comment by patty85** [comment]
Yeah I do have but have enabled all of them and still happens

**Comment by patty85** [comment]
Wait I went one by one and I noticed that when I disable Tumblr theme update fix borders and header the text goes back in place

**Comment by nightpool** [comment]
@patty85 Is that an XKit option? I can't find it

**Comment by nightpool** [comment]
closing as non-xkit related
