### ISSUE TITLE
Autotagger Not Tagging Queued Posts

### ISSUE THREAD

**Issue by smoshea** [new-xkit/XKit#899]
This may be related to another unconfirmed issue, but none of my queued posts are being tagged appropriately, despite my having specified a value for all queued posts. 

I'm on chrome, with umatrix running, but I don't believe that any filters are currently blocking xkit.

Is there any known workaround, such as a mass queue editor that I don't know about?

**Comment by Wolvan** [comment]
How do you queue posts exactly?

**Comment by smoshea** [comment]
Oh, sorry, should have specified that! I use One Click Reblog. If I do a regular reblog using that extension, it tags fine when I enter it manually. I don't currently have any autotags specified for non-queue posts though.

**Comment by smoshea** [comment]
Update - somehow, this issue seems to have resolved itself. Maybe forcing an update helped. (Now just to go back and manually tag my entire queue ugh.) Thanks!
