### ISSUE TITLE
ER: scrolling is borked

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#903]
1. make a post on your dash with Markdown
2. Try to edit it
3. ER kicks you out as expected (although it *should* just let you edit the post, but without editable reblogs :/)
4. okay here's the bug: after ER kicks you out, you can't scroll
5. every time you scroll up or down, it snaps you back to the post you got kicked out of.

:((

**Comment by nightpool** [comment]
wouldn't be surprised if this is still an issue, but marking it unconfirmed until someone tests it

**Comment by ThePsionic** [comment]
Seems to be fixed - ER lets me edit the post in Markdown as it should.
