### ISSUE TITLE
Blacklist autopopulate terms need updating

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#906]
From an ask on -discussion, it makes no sense to include 'gay*' and 'lesbian*' in the autopopulate terms, especially given tumblr's userbase. I proposed adding 'blood' and 'gore' in their place, but maybe we could poll for common blacklist terms or something?

**Comment by nightpool** [comment]
I.... Huh. Yeah, I have no idea what could have possessed atesh to put
those there. Maybe from porn spam?

I'd prefer just to do something simple—I really doubt many people actually
use the feature, its just supposed to be examples of stuff mainly.

**Comment by nightpool** [comment]
I'll do this tomorrow.
