### ISSUE TITLE
Reblogged text posts are broken

### ISSUE THREAD

**Issue by ospreysoul** [new-xkit/XKit#911]
I have Reblog Display Options and Editable Reblogs enabled. (Also XInbox, One-Click Reply, Tweaks, Go-To-Dash, Activity+, Enhanced Queue, Header Options, Iconified Notifications, No Recommended, Outbox, Read More Now, Reblog as Text, Search Likes, Timestamps, View On Dash, Retags, Tag Replacer, Mass+, Tag Tracking+, and Messaging Tweaks.)

Posts that should look like this:
![bug01](https://cloud.githubusercontent.com/assets/13602881/12223060/cd9ae3c0-b79a-11e5-9947-d0a4c869b786.jpg)

Look like this:
![bug02](https://cloud.githubusercontent.com/assets/13602881/12223062/d801a010-b79a-11e5-96a9-ea7e104dc427.jpg)

**Comment by citrusella** [comment]
Is masiewilliams deactivated? Does the post look normal on your blog? I think this is an error in how ER handles deactivated blogs, but I'm not privy to the inner workings of New XKit, so that's really all I know. XP

**Comment by maswartz** [comment]
This has been a frequent issue on and off for a while now and has been mentioned before.
