### ISSUE TITLE
Blank Xkit

### ISSUE THREAD

**Issue by gigigaga** [new-xkit/XKit#912]
Hi, I've been experiencing some problems with New Xkit for a while now. The Xkit itself appears to be working, but I cannot access the Xkit extensions, etc.
![screen shot 2016-01-09 at 4 25 44 pm](https://cloud.githubusercontent.com/assets/16645126/12229762/97eb2e0a-b7ff-11e5-91c6-c35ad1859df5.png)
![screen shot 2016-01-09 at 4 25 51 pm](https://cloud.githubusercontent.com/assets/16645126/12229765/9b6ae746-b7ff-11e5-9c9e-f870e055a0af.png)
I don't quite know what seems to be the problem. But lately my tumblr has been acting funny in where the reblog button disappears and the pop-up blogs on tumblr cut off the top half of the blog. 
![screen shot 2016-01-09 at 4 26 56 pm](https://cloud.githubusercontent.com/assets/16645126/12229784/c46ff0d2-b7ff-11e5-8bb4-1b4f0c85ed24.png)
![screen shot 2016-01-11 at 1 09 27 am](https://cloud.githubusercontent.com/assets/16645126/12229816/06ad0642-b800-11e5-9cdf-e1689f138f48.png)

Can anyone please help me? I'm using Chrome.

**Comment by Wolvan** [comment]
Please try disabling adblock

**Comment by gigigaga** [comment]
Oh that just did the trick!! Thank you. I wonder if there is a way to still keep using adblock but have it so my xkit will still work?

**Comment by Wolvan** [comment]
It is most likely an issue with a custom filter you set in Adblock. Please check the filter list, if you need help gimme a heads up by commenting here. I'll close this issue now, but you can still write stuff afterwards
