### ISSUE TITLE
XInbox mass delete svc call 404s

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#913]
From support gitter
>`Kelsi-SBD` has joined.
`Kelsi-SBD` Hello?
`Wolvan` hello
`Kelsi-SBD` I'm new to this...can you answer my question about the mass edit mode? I keep getting an error message
`Wolvan` and which one
`Kelsi-SBD` https://www.filepicker.io/api/file/glvP7JOITRqZSqvFJsaU
`Kelsi-SBD` https://www.filepicker.io/api/file/cABpos8TaQVHABIKWoyw
`Kelsi-SBD` Sorry. I sent it twice >.<
`Wolvan` chrome, right?
`Kelsi-SBD` Yes
`Wolvan` can you press ctrl+shift+j
`Wolvan` and do whatever you do to get this error message again
`Kelsi-SBD` https://www.filepicker.io/api/file/7JOaGa0nSkeVAJwMqeVx
`Wolvan` We'll have to look into this
`Kelsi-SBD` If it matters, it works on my main blog but not my sideblogs.
`Wolvan` that's good to know, I'll open an issue on GitHub to track this

**Comment by nightpool** [comment]
this is tracked somewhere else IIRC. it hasn't worked in at least three
months.

(unless it got fixed and then broke again since I remember it not working)

**Comment by Wolvan** [comment]
haven't found an issue when I had a quick check over the issue list but I think you're right. Once we find that we can close this

**Comment by nightpool** [comment]
https://github.com/new-xkit/XKit/issues/766

(hint, try filtering by label :D)

looks like there's no information there though, so maybe edit the
description to add the images?

**Comment by Wolvan** [comment]
Do whatever you seem better to you. We could also close #766 in favor to this one
