### ISSUE TITLE
SVC seems to be broken somehow

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#920]
10:50:05 <NewXKitBot> *Okeiro has joined.*
10:50:32 <NewXKitBot> `Okeiro` Hello?
10:50:57 <ThePsionic> Hey
10:51:28 <NewXKitBot> `Okeiro` I'm having an issue with reblogging things with xkit on google chrome ; ;
10:52:07 <ThePsionic> The issue being?
10:52:12 <NewXKitBot> `Okeiro` It keeps giving me an  xer sr error.
10:53:17 <ThePsionic> Hmm
10:53:22 <ThePsionic> What is your XKit version?
10:53:42 <NewXKitBot> `Okeiro` 7.7.1
10:54:01 <ThePsionic> And your Editable Reblogs version?
10:54:20 <NewXKitBot> `Okeiro` 3.0.5
10:54:48 <ThePsionic> And finally your Chrome version? :P
10:55:31 <NewXKitBot> `Okeiro` Version 47.0.2526.111 m
10:57:16 <ThePsionic> Hmmm
10:57:48 <NewXKitBot> `Okeiro` and windows 10 if that helps..
10:58:09 <ThePsionic> Could you open your Javascript console with Ctrl+Shift+J and try reblogging something again
10:58:23 <ThePsionic> If anything goes wrong it should give an error in there
10:58:52 <NewXKitBot> `Okeiro` Sure, one moment.
10:59:48 <NewXKitBot> `Okeiro` POST https://www.tumblr.com/svc/post/update net::ERR_EMPTY_RESPONSE(anonymous function) @ bridge.js:270
10:59:49 <NewXKitBot> `Okeiro` xkit/editable_reblogs.js:362 editable_reblogs.send_request:
10:59:49 <NewXKitBot> `Okeiro`  XMLHttpRequest {}

**Comment by nightpool** [comment]
@thePsionic this needs a little more detail. Can you reproduce it on your
machine?

**Comment by ThePsionic** [comment]
I cannot. I forgot to ask them whether their blog was in any way hidden, which might have been the source of the issue. Feel free to close if you want, or keep it open if you somehow see something here you need to fix.

**Comment by nightpool** [comment]
Sorry, but there isn't enough detail here to even begin to judge whether there's something here to fix.
