### ISSUE TITLE
blog tracker doesn't sync across tabs

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#929]
- Open two tabs
- add a blog (1) in tab A,
- add a blog (2) in tab B
- refresh tab A
- see that only blog 2 shows up, and blog 1 is lost.

blog tracker should always load blogs from storage before modifying and saving the blog structure.

**Comment by Wolvan** [comment]
Doesn't work. Storage gets initialized with data on load and doesn't call localstorage for reading anymore until the tab is refreshed. It's the same Problem Pokés has

**Comment by nightpool** [comment]
We need to figure out the storage situation
