### ISSUE TITLE
View My Tags

### ISSUE THREAD

**Issue by roxrollin** [new-xkit/XKit#93]
View My Tags won't allow me to add on tags to posts I'm trying to edit, when I click on the tags I use, it simply won't register onto the post I'm making/editing and it won't let me add the tags I wanna use.

**Comment by finagle29** [comment]
cannot reproduce, can you post a link to your extension configuration in the other tab as well as browser version and os?

**Comment by roxrollin** [comment]
Actually everything is working now, thanks!

**Comment by nightpool** [comment]
Thanks for following up!
