### ISSUE TITLE
Anti-Capitalism: new type of sponsored post needs to be blocked?

### ISSUE THREAD

**Issue by soren121** [new-xkit/XKit#931]
Using Firefox 43.0.4 and New XKit 7.7.3.

I have the Anti-Capitalism extension installed, and as of today there seems to be a new kind of sponsored banner present that the extension doesn't catch. It seems to be blockable via the class .takedown-container; I've done that through uBlock Origin and it doesn't appear to have caused any side effects.

I've attached a screenshot of the new sponsored banner with the Inspector opened to the side:

![capture](https://cloud.githubusercontent.com/assets/295939/12543239/83b06304-c2fb-11e5-96be-a3eb1c3be788.PNG)

**Comment by soren121** [comment]
The 'hide asktime banner' option blocks it.

**Comment by nightpool** [comment]
:D
