### ISSUE TITLE
Adding a custom tag with Quick Tags also adds a "#null" tag

### ISSUE THREAD

**Issue by TheGlassesGirl** [new-xkit/XKit#933]
If I'm viewing a post and I type in a different tag that isn't in a tag bundle, it also adds a tag called "#null" to the post.
![tags](https://cloud.githubusercontent.com/assets/16903470/12589112/2e20c520-c42a-11e5-87c8-05b173a9be67.PNG)

**Comment by nightpool** [comment]
this happens every time you add an other tag?

**Comment by TheGlassesGirl** [comment]
Not every time. I can't figure out what causes it to have a "#null" tag or not though.

**Comment by nyna237** [comment]
I've submitted this to the support blog on Tumblr several times with screenshots. I can confirm this happens to me frequently when adding tags in Drafts. It does it with the custom tag box or with selecting a tag bundle. I have no idea what causes it. I have tried testing different things but nothing is consistent,.

**Comment by nightpool** [comment]
@nyna237 so, if you add a tag in drafts via Tag Bundles, it always produces a null tag? is that correct?

**Comment by TheGlassesGirl** [comment]
I can't reproduce it every time, but only sometimes, adding in a custom tag with Quick Tags is what makes it happen.

So if I'm viewing a post when I go to www.tumblr.com/blog/[my-blog], and I use the "Other" function to type in a custom tag that isn't part of a tag bundle, occasionally it adds in a tag that just says "#null" along with the new tag I added. I can't accurately reproduce it because it happens so randomly.

**Comment by nyna237** [comment]
For me it happens most often when I go into my Drafts and use Quick Tags to add a bundle. I would say it happens probably 70% of the time. I don't add that many custom tags, but I have seen it happen then as well. I can say that with custom tags I see it when I string multiple tags together with commas as opposed to adding one tag.

**Comment by nyna237** [comment]
I've been doing some testing this afternoon and I can very consistently reproduce the issue when adding more than one tag via the custom tag box, or when selecting a tag bundle that has multiple tags in them (as most do). I created a tag bundle that had only 1 word in it (testing) and I was able to add it to 14 posts in a row with no issue. I switched to a bundle with multiple words and the next 10 all ended up with the null. The same was true for the custom tag box, though it was less consistent and seemed to generate the null tag less for me. I smell a null point issue somewhere...

I'm on Chrome  48.0.2564.109 on a Win7 laptop. I've tried disabling all extensions except New X-kit and no change. I will try to test this same way on Firefox when I am back at my desktop, though I pretty much only use Chrome.

**Comment by nyna237** [comment]
Sorry sorry. I forgot to mention that this only happens when you don't "open" the post. I.e. you just go into Drafts or whatever and use the Quick Tags button. I've never seen this issue when I hit reblog and use Quick Tags.

Also, I just noticed that it doesn't do the #null tag if I add one tag that is one word. However, if I add one tag that is 2 words, like someone's first and last name, it will add the null tag almost every time.

**Comment by nightpool** [comment]
Unfortunately I still can't reproduce this on my end. These were the steps
I took:

 - Install Quick Tags
 - Create a tag bundle with three tags "this, is a, test"
 - try to add that to every post in my draft
 - Notice that every post got the correct tag, with no null tag

Same with adding multiple tags or tags with multiple words via the custom
tag box.

**Comment by nyna237** [comment]
I am not able to reproduce in Firefox. I tried 25 draft posts. Is there something I can run or do to see what might be going on in Chrome?

**Comment by TheGlassesGirl** [comment]
Just as an addendum to what you guys have tested:

- This is happening to me in Firefox
- This happens only when I manually type in a tag into the Other section, NOT when I click on a tag bundle I've already made
- This happens whether I have a tag with one word or multiple words, or multiple tags at once. This has happened with one tag with one word (as seen in my screenshot above) and multiple tags with more than one word

Like Myna said, this has only happened to me if I don't open a post and edit it.

**Comment by nyna237** [comment]
It's great how you're having the opposite problems I am. Makes testing fun!

**Comment by TheGlassesGirl** [comment]
I'm sorry. :P I've tried recreating but I honestly cannot figure out the conditions for when it happens. It's completely random for me and I have no idea what the cause might be.

**Comment by nyna237** [comment]
Don't be sorry! It is so random. Like right now it's working fine and I've tagged probably 20 posts without the stupid #null tag. But later it will go back to hating me.

**Comment by nightpool** [comment]
Still unreproducable. possibly related to extant peepr/autotagger issues
