### ISSUE TITLE
Date recorded by Outbox is not sufficient

### ISSUE THREAD

**Issue by realityfabric** [new-xkit/XKit#952]
It only displays the day of the week and the time that the message was sent. This fits the official Tumblr Queue format, but is not detailed enough. I was hoping that the timestamp was at least kept in the JSON, but it appears to only store the day and time as strings.

**Comment by realityfabric** [comment]
The date/time format for Outbox is determined with the variables ```m_date``` and ```m_day```, at [outbox.js line 394](https://github.com/new-xkit/XKit/blob/d8e7f46a2fd3108d6c67d63eae98d53d14b2201f/Extensions/outbox.js#L394) and several other sections (which appear to be organized by message type).

I tested changing the format of m_date from ```"hh:mm a"``` to ```"MM/DD/YY hh:mm a"``` and that solved this problem. It would need to be updated for all post types.

I'm not sure if it would be better to create a new div with the month/day/year, or to keep that in the same div with the time.

**Comment by nightpool** [comment]
probably in the same div is fine. we should really be recording a full
timestamp though....

**Comment by realityfabric** [comment]
Sorry I should have corrected my mistake in the original issue. Outbox uses ```m_obj.time = new Date().getTime()``` to store the timestamp, the real issue is how it's formated when it's displayed.
