### ISSUE TITLE
View On Dash is missing "like"/heart button

### ISSUE THREAD

**Issue by SophiaNOTLoren** [new-xkit/XKit#953]
Possibly same cause as #831 -- I haven't been active on tumblr for a while, and just noticed this. Screenshot attached should illustrate the issue -- this is with no other XKit extensions enabled but View On Dash.

Tested on Firefox and Chrome, same result.

![view on dash issue](https://cloud.githubusercontent.com/assets/13694190/12882036/73c7a87c-ce03-11e5-9f20-942c641cf7e5.jpg)

**Comment by blackjackkent** [comment]
I'm looking into this; haven't figured out quite how to get around it yet but it's being looked into. :)

**Comment by nightpool** [comment]
@blackjackkent can't check but is this a dupe?

**Comment by SophiaNOTLoren** [comment]
@nightpool @blackjackkent Looked through all open issues, hunting for anything relevant, the closest I could find was #831 which IIRC you were already addressing, just less able to work on because of school. If this is a dupe, feel free to close!

**Comment by nightpool** [comment]
Nah, that's something completely different. Thanks!

**Comment by SophiaNOTLoren** [comment]
@blackjackkent any chance you've been able to figure this one out? Really hoping to get back to using tumblr; missing ViewOnDash has pretty much broken my workflow...

**Comment by SophiaNOTLoren** [comment]
Just curious whether @nightpool or @blackjackkent have any further input on this, or if there's anyone else who has the capability to tackle this issue.

**Comment by sexlibris** [comment]
I've been hoping for a fix to this issue for a long time now, too. I understand it might be complicated to fix, people are busy, etc, but to go three months without any updates seems ridiculous. Please update your progress on this issue if you're working on it, @blackjackkent, or give it to someone who can.

**Comment by heytherenikita** [comment]
Is there a fix for this yet? I've been experiencing this problem for months now, and neither resetting XKit nor switching browsers fixes it.

**Comment by SophiaNOTLoren** [comment]
If this is *not* being worked on by @blackjackkent then perhaps it can be unassigned, and maybe there's someone else who can take it? If it *is* being worked on, is there any update?

I'd echo the now-deleted sentiments of the previous commenter: "I understand it might be complicated to fix, people are busy, etc," -- but this has been assigned and "looking into" for over 6 months.

**Comment by ThePsionic** [comment]
I'm now also looking into this. @SophiaNOTLoren apologies for the delay.

**Comment by SophiaNOTLoren** [comment]
@ThePsionic Much appreciated. And hey, it happens; just glad things are being looked into now.
