### ISSUE TITLE
Remove Waffle from the project

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#959]
Per discussion from the Town Hall, it was decided to drop the use of Waffle as part of our issue/PR workflow.

This includes:
- [x] Removing the Waffle badge from the README
- [x] Unlinking and removing Waffle permissions from the org (/cc @hobinjk)
  - Org page > Settings > Third-party access > Revoke Waffle
- [x] Remove any Waffle-specific tags (`waffle:bug` and `waffle:enhancement`) and ensuring the proper labels get applied to those issues (e.g. adding `bug` to issues carrying the `waffle:bug` tag if they aren't already)
- [x] Remove links to the Waffle board from any of the blogs (e.x. -support)

/cc @blackjackkent if memory serves you set Waffle up for us, is there anything I'm missing?

**Comment by AprilSylph** [comment]
@hobinjk did you ever do point no. 2 above? it's odd seeing this issue still listed

**Comment by hobinjk** [comment]
Yep, this can be resolved
