### ISSUE TITLE
Bug: vanilla videos unmutes other Vines on the page.

### ISSUE THREAD

**Issue by benetherington** [new-xkit/XKit#961]
OS X 10.11.13, Chrome 48.0.2564.109 (64-bit).

This issue occurs when Vanilla Videos is enabled, and stops when it's disabled. If you unmute an embedded Vine, then pause it (not mute it, mind), then scroll down until a Vine and unmute another Vine, the first one will start playing, and since it's not muted, you'll hear both Vines at once.

**Comment by hobinjk** [comment]
Thanks for the report! Unfortunately, I can get this to happen on Tumblr even without XKit installed by letting the first vine loop a couple times unmuted, pausing, scrolling a long distance, unmuting another Vine, and scrolling some more if it hasn't happened yet.

I may end up writing an update to Hermes which fixes this.
