### ISSUE TITLE
Blacklist issues

### ISSUE THREAD

**Issue by ryulong** [new-xkit/XKit#97]
A while ago, XKit used to be able to blacklist posts based on the source blog, and after Tumblr updated and the original XKit extension went dead this feature dropped. When you guys picked it back up again, this little side feature returned, but I think within the past few days this just plain stopped working again. Is there a way for the blacklist to recognize the source blog again?

**Comment by WyohKnott** [comment]
It works over here. Does it happen all the time?

Can you specify your browser/blacklist version and check if you have the correct option checked (ie check_authors)?

**Comment by ryulong** [comment]
It was happening when I first sent this request but it seems to have been fixed by now? I know that this was a persistent problem when the original Xkit was abandoned because of how Tumblr refers to theor iginal post, I would assume.

**Comment by nightpool** [comment]
We'll keep an eye on it, but if its working for you I'm gonna close the issue for now. Let us know if it happens again though!

**Comment by hobinjk** [comment]
This was fixed in https://github.com/new-xkit/XKit/commit/61cf63cd4382a7c306c5db2e8d61942680b4e82d. Sorry for not updating this issue when I pushed that.

**Comment by WyohKnott** [comment]
If the Original Poster has set up an external website as the source, or if the Original Poster manually added his URL but subsequently change his blog name, it could fail.
