### ISSUE TITLE
post_window.origin().is_original is always true

### ISSUE THREAD

**Issue by andy-lang** [new-xkit/XKit#970]
I have found that `XKit.interface.post_window.origin()` has a nasty bug -- the `is_original` flag is always set to true, and conversely the `is_reblog` flag is always false. I have written a script as proof: [test_origin.js](https://gist.github.com/andy-lang/e759c088dd16dcac35ca)

I have tested this on the following systems:    
* Firefox 44.0.2 with XKit 7.7.3 - with extensions enabled    
* Chrome 48.0.2564.116 m, with XKit 7.7.1 - no extensions enabled aside from defaults (XInbox, One-Click Postage, One-Click Reply, Tweaks, Go-To-Dash, and the test extension above)

In both cases only the `is_original` path is followed.

**Comment by 0xazure** [comment]
Looks like Tumblr's changed their CSS classnames again.

The relevant code is [`Extensions/xkit_patches.js#L1017-L1026`](https://github.com/new-xkit/XKit/blob/f89ac280a02991b0dd67fe188f9ca81970f29c62/Extensions/xkit_patches.js#L1017-L1026) and the class appears to have changed from `.post-header` to `.post-form--header`.

Should be pretty straight-forward to fix, thanks for the report!

**Comment by nightpool** [comment]
will be fixed in XKit Patches 6.2.5 when it gets reviewed.
