### ISSUE TITLE
Servant not Activating on Reblogs

### ISSUE THREAD

**Issue by ElliSpeaks** [new-xkit/XKit#972]
Before, I had Servant colourise posts that contained certain names, so that I could watch for particular content even if I wasn't actively part of a thread and it could colourise (or highlight or whatever I chose) that post whenever that word was in the post. I had it set up, for example, as:

When post contains **Quinn** Colorize the post **purple**

All posts on the dash that had the word Quinn in it would have a purple bar at the top.

Well, now only original posts will colourise. Reblogged posts do not.

**Comment by nightpool** [comment]
will be fixed in servant version 0.5.10

(FWIW, this bug seems to be approximately 6 months old, as far as I know. it should have happened around the same time that the reblog layout changed)
