### ISSUE TITLE
Editable Reblogs not closing the post form

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#974]
from the askbox:
>Okay, so, whenever I try to use xkit, and I reblog a post, I'll click the reblog button, and it will reblog the post but not close the reblog screen or show that I reblogged it, so I end up clicking the button again waiting for it to close and it reblogs the post ten times, and I have to manually close it. It seems that xkit is causing this problem, as I didn't have a problem before I got it.

can anyone confirm?

**Comment by fionaroleplays** [comment]
I have discovered this only happens with Firefox and not Chrome.

**Comment by BabblingFishes** [comment]
Can confirm for Firefox 44.0.2. Turning off my adblocker does not seem to fix it either.

The bug occurs consistently when hitting _Reblog_, _Save as Draft_, _Post Privately_, etc on the reblog editor. (Does not occur at all on new posts.) When trying to exit via _Cancel_, the "Discard this post?" dialogue as though the post was not saved.

If you need more elaborate debugging information, feel free to ask!

**Comment by nightpool** [comment]
I know a few people have been having this issue, but as of yet we're still
unable to reproduce it. What other chrome extensions do you have installed?
Please list all of them (or even better, provide a screenshot)

**Comment by engineer-pearl** [comment]
Double confirmation for firefeox 44.0.2 on ubuntu.

browser extensions: chatzilla, New Exkit (duh), Ubuntu Modifications (probably pepperflash), and Youtube all HTML5 (disabled).
Xkit extensions: https://gist.github.com/979f4bf3bf7acce0b401

**Comment by BabblingFishes** [comment]
I've tried disabling all Firefox extensions with no results, so I don't think that's the problem.
Anyway, here's a screenshot and more environment info:
[xkit_settings.txt](https://github.com/new-xkit/XKit/files/170198/xkit_settings.txt)
![untitled](https://cloud.githubusercontent.com/assets/14933600/13719555/330c16f2-e7ac-11e5-86b9-27c78ad3b302.png)

**Comment by maswartz** [comment]
This has happened to the last three posts in the last three minutes for me.

**Comment by lavacano201014** [comment]
Confirming, Firefox 44.0.2 on Windows 10, 64 bit browser, 64 bit operating system.

![Amazon Smile Redirect, Avira Browser Safety, Classic Theme Restorer, MEGA, New XKit, UAControl, uBlock Origin, XMarks](http://i.imgur.com/HbQGG88.png)

UAControl is not configured for Tumblr (default useragent). No unusual binary plugins. [Here's my full XKit configuration](https://gist.github.com/62120df71aa931134af9) (my XCloud password didn't come up in a Ctrl-F, so I'm assuming it's reasonably sanitized). Willing to upload a sanitized version of my browser profile if necessary.

**Comment by nightpool** [comment]
Thanks @lavacano201014 I've taken down your config, but I have a copy of it for debugging, which will be helpful.

(its not at all sanitized lol your xcloud password is just b64 encoded iirc)

**Comment by nightpool** [comment]
we've re-written ER enough times since now that i'm closing this bug unless anyone can confirm it still happens to them
