### ISSUE TITLE
Already Reblogged not functioning

### ISSUE THREAD

**Issue by Pichu0102** [new-xkit/XKit#980]
I've been having an issue for about a month or so where the already reblogged function just doesn't work.
![screenshot 2483](https://cloud.githubusercontent.com/assets/4944941/13489744/bc9ae82e-e0f6-11e5-8aa6-6f7c1fbffbad.png)
This screenshot doesn't show it, but I've already reblogged this post. It can get confusing rather quickly.

**Comment by Aquaj** [comment]
Hi @Pichu0102 

I must say I fail to see the issue, on your screenshot, the reblog icon is green, as made by AlreadyReblogged on an already reblogged post.

Is it that the post just shouldn't have been there ? (as in: you checked the "Hide posts if they are AlreadyReblogged on my dash")

**Comment by Pichu0102** [comment]
Sorry, I can't seem to see the green icon, as it looks gray to me. Might
just be my problem, sorry about the false report.

**Comment by Aquaj** [comment]
Probably a monitor setting problem on your side then yes.
No problem, glad to have been able to help :smile:

**Comment by Pichu0102** [comment]
Ah, seems to actually be that I can't see that particular shade of green. Once again, my mistake.

**Comment by Pichu0102** [comment]
I apologize for being way out of line here, but would it be possible to make an option to add a checkmark to alreadyreblogged posts? Just an option, not default.
Kind of like this:
![bc9ae82e-e0f6-11e5-8aa6-6f7c1fbffbad](https://cloud.githubusercontent.com/assets/4944941/15214169/84c41290-1819-11e6-8e63-6f7bff8d29f0.png)

**Comment by Aquaj** [comment]
That seems reasonable and actually very accessibilty-aware, I'll try to get on that tonight or tomorrow ! 😉

**Comment by Pichu0102** [comment]
Ok, thanks!

**Comment by Pichu0102** [comment]
Thanks a lot for this!

**Comment by icpgithub** [comment]
Hi, I'm having the same issue, but this time it's really not working. None of my previously reblogged posts are displaying as "reblogged" (no green checkmark as before when it worked), so I guess it has something to do with the database going corrupt or something. I have backups of my google chrome profile, so I could restore it if I knew what file or folder should I look for, and what would be the procedure. Is there any way I could restore the database (if that's the problem?)
