### ISSUE TITLE
reblogging a post with a deactivated blog vanishes it

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#981]
reblogging this post: http://space-wifi.tumblr.com/post/140585730449/fridakahllo-im-sorry-you-were-not-loved with ER produces this html

```html
<p><a class="tumblr_blog" href="http://fridakahllo.tumblr.com">fridakahllo</a>:</p>
<blockquote>
    <p>I’m sorry you were not loved properly and that it made you cruel.</p>
</blockquote>
```
this is parsed by tumblr as such:

![image](https://cloud.githubusercontent.com/assets/233815/13557073/adceb48e-e3b6-11e5-835d-303bc1b8d5da.png)

ideally, it should be producing this HTML:

```html
<p><a class="tumblr_blog" href="http://fridakahllo.tumblr.com/post/66349760280">fridakahllo</a>:</p>
<blockquote>
    <p>I’m sorry you were not loved properly and that it made you cruel.</p>
</blockquote>
```

which is the original source html and is parsed by tumblr as such:

![image](https://cloud.githubusercontent.com/assets/233815/13557077/b3001f56-e3b6-11e5-93d4-ba1ca8ff6d73.png)

This will probably necessitate an additional SVC call. On the plus side, this will fix a whole class of extant issues related to deactivated and otherwise improperly parsed reblog trees, hopefully.

**Comment by ospreysoul** [comment]
Just to add to this, I've been unable to even draft posts that were reblogged from a deactivated blog while Editable Reblogs is switched on.

**Comment by ospreysoul** [comment]
I've noticed the same thing happening to me.

Okay, so let's say I wanted to reblog this post. The original post came from my blog before I changed my username. So the blog is deactivated. With xkit disabled, it looks like this:
![bug01](https://cloud.githubusercontent.com/assets/13602881/14037167/1f4be910-f217-11e5-88fa-8d9848a38832.jpg)
Not the design I like, but at least all the copy shows up as it should.

And if I save it as a draft, boom, there it is.
![bug02](https://cloud.githubusercontent.com/assets/13602881/14037168/27aa987c-f217-11e5-912c-00bee4571676.jpg)

Now, this is what it looks like with Xkit enabled. (For the sake of sorting this out, I'm working off Chrome 49.0.2623.87 m on Windows 10 and I have the following extensions enabled: XInbox, One-Click Reply, Tweaks, Go-To-Dash, Activity+, Enhanced Queue, Header Options, Iconifed Notifications, No Recommended, Outbox, Read More Now, Search Likes, Timestamps, View on Dash, Retags, Tag Replacer, Mass+, **Reblog Display Options**, Tag Tracking+, Messaging Tweaks, and Blacklist.) It's important to note here that my Reblog Display Options are set to "Nested." 
![bug03](https://cloud.githubusercontent.com/assets/13602881/14037172/32c74570-f217-11e5-9329-567958e9ec74.jpg)

And it shows up in my drafts.
![bug04](https://cloud.githubusercontent.com/assets/13602881/14037200/80c9abb4-f217-11e5-8ee9-a20f4875ac8b.jpg)

Now, if I try to reblog it with Editable Reblogs turned on...
![bug05](https://cloud.githubusercontent.com/assets/13602881/14037270/13f25242-f218-11e5-9b2b-5b0c3592ec0b.jpg)
That isn't nested **or ** editable. And, if I hit Save to Drafts, it doesn't show up in my drafts. At all.

Okay, so I turn off Editable Reblogs and save it to drafts and then I try to add to it in the drafts...
![bug06](https://cloud.githubusercontent.com/assets/13602881/14037341/cb17f800-f218-11e5-8e28-f9acf14aa786.jpg)
Oh.

If I turn off Editable Reblogs, save the post to my drafts, then turn Editable Reblogs back on and try to trim the post, the same blank post appears.

And turning off both Editable Reblogs and Reblog Display Options after this causes me to be unable to even save the post to my drafts.

I also updated to Chrome 49.0.2623.108 m after this, but the same errors persisted.

**Comment by ospreysoul** [comment]
These problems don't happen when I reblog a post from myself with my new, active username, only with the deactivated blog.

**Comment by soren121** [comment]
Well, I just spent a couple hours trying to debug this myself.

I did manage to fix a bug related to Editable Reblogs not loading when you reblog a deactivated post. The replies parser expects an <a> element for the author's name, but deactivated users' names are displayed with a <span>. That caused a TypeError that wasn't thrown for some reason, so the function just dies, I guess. I can provide a PR for this fix if you want it.

After I fixed that, I came across the bug that this report is for, and I did figure out how to fix it, but I'm at a loss as to how to implement it.

In order to get deactivated reblogs to show up, you need to build the full URL for the deactivated post, in the `reblog_url` key that's set in the `process_existing_content` function. If you don't do this, Tumblr won't be able to parse it. 

@nightpool: any idea how to get the post ID of the original post? I know that Tumblr returns it in the response after you submit, but that's too late obviously...

**Comment by nightpool** [comment]
fixed already
