### ISSUE TITLE
Doesn't work in Firefox 45

### ISSUE THREAD

**Issue by Tumblrgirl** [new-xkit/XKit#982]
It returns an error when I reblog in firefox 45.

**Comment by Wolvan** [comment]
there is not a lot we can do with this little information. Give us a list of installed extensions AND the error code at least

**Comment by Tumblrgirl** [comment]
extensions list:
XInbox, One click postage, one-click reply, tweaks, go-to-dash, AccessKit, Anti-Capitalism, Blacklist, Drafts+, Editable Reblogs, Post Block, Notification Block, Post Crushes, Pokes, Reblog As Text, Reply Viewer, Old Sidebar, Old Stats, Reblog Post Options, Read More Now, Soft Refresh, No Recommended, Hermes, Messaging Tweaks, Mirror Button, User+ Menus, Profiler, Tag Tracking+, Shorten Posts, Reblog Yourself, Mass and Notifications+.
Error:XER-SR There was an error reblogging your post. Please try again shortly. If you continue to receive this, please contact XKit staff.

**Comment by nightpool** [comment]
I got this error once yesterday, but I wasn't able to grab logs in time.
(Chrome)

**Comment by Tumblrgirl** [comment]
I don't know what extension it is, but I saw editable reblogs is bugged.

**Comment by engineer-pearl** [comment]
Hey Tumblrgirl, can you do me a favor? Whatever you're trying to reblog, can you open that in another browser and attempt to reblog it from there?

**Comment by Tumblrgirl** [comment]
Sure I can...I got something to reblog in Firefox just now...from my followers list.

**Comment by engineer-pearl** [comment]
Okay, just making sure you weren't getting that error because the op blocked you (it took me forever to figure out that was why I was getting the error)

**Comment by Tumblrgirl** [comment]
could be because I changed the other blog's name since I own all the blogs I use there...

**Comment by nightpool** [comment]
can't reproduce, no additional info
