### ISSUE TITLE
Xkit completely blank in chrome

### ISSUE THREAD

**Issue by icarusis** [new-xkit/XKit#985]
OK hi this is a bit of an odd one? It doesn't seem to be something anyone else I know is experiencing.
I tried uninstalling and reinstalling and it just..made it worse. Oops.
Basically opening up xkit just results in a blank box. The xcloud "hey you dont have xcloud installed" is there, and the About+Support tab works, but thats it unfortunately.
I'll include a couple screencaps so you get an idea! Hopefully someone knows how to fix my problem haha.

![3dfcc3ad20ab0f6e172e238b4fb3b033](https://cloud.githubusercontent.com/assets/17820007/13734551/f298d7b8-e9ea-11e5-8c9d-0ad6c6178ecc.png)
![6dc037c71842539333488a792d3c910f](https://cloud.githubusercontent.com/assets/17820007/13734555/f38bad58-e9ea-11e5-96e2-3b7937553029.png)
![a1b4726d4d8ede7b877b52eecdfd0724](https://cloud.githubusercontent.com/assets/17820007/13734557/f4c4e360-e9ea-11e5-8372-dc0ea1d991a0.png)

**Comment by finagle29** [comment]
What version of Chrome are you using?  Also what version of XKit does this say it is on the About + Support tab?

**Comment by nightpool** [comment]
You blocked a selector in AdBlockPlus that XKit uses—usually its something very very general, like ".content"

**Comment by nightpool** [comment]
This issue was not deleted, it was just closed because it wasn't relevant to the coding
