### ISSUE TITLE
MS Edge port

### ISSUE THREAD

**Issue by lavacano201014** [new-xkit/XKit#988]
As you may or may not be aware of by now, Microsoft's browser developers have stopped huffing paint, and have completely thrown out the old Internet Explorer code and made a new browser, Microsoft Edge. (Which is actually not too bad)

[It's getting extensions soon.](https://blogs.windows.com/windowsexperience/2016/03/17/bringing-extensions-to-microsoft-edge/) A Microsoft Edge version of XKit would be nice, if only for those days when I don't feel like dealing with the superbloat that Firefox and Chrome bring to the table.

**Comment by nightpool** [comment]
closing for now because its not actually actionable, but feel free to repoen when edge has an extension API :D

**Comment by Wolvan** [comment]
Actually, @nightpool, it already seems to. I did see in one of the xkit tags that someone managed to get the extension work on edge

**Comment by nightpool** [comment]
Hmm. send me a link?

**Comment by Wolvan** [comment]
http://lil-spoon-lexa.tumblr.com/post/141243021938/ooh-ooh-ooh-i-got-new-xkit-to-work-with-the
http://lil-spoon-lexa.tumblr.com/post/141270494663/nice-work-on-getting-nxkit-run-on-edge-how-did

**Comment by shinoamakusa** [comment]
I just tried the port steps and it add extension fine, but it doesnt work ... no xKit button or functionality ... any news on official Edge port extension?

Thanks

**Comment by eladavron** [comment]
Also tried giving the port a chance but no go.
Anyone got any success with this?
