### ISSUE TITLE
Soft Refresh breaks Like buttons

### ISSUE THREAD

**Issue by Hyratel** [new-xkit/XKit#991]
after performing a Soft Refresh, Like buttons no longer work. untested whether it's only SR-added posts, or all in dashboard. Firefox 45 and earlier

**Comment by hobinjk** [comment]
Thanks for the report! It looks like Tumblr changed the event it uses to notify itself of new posts from "posts:load" every time a group of posts gets loaded (i.e. during scrolling) to one "postsView:createPost" event per post.

This will also break parts of drafts_plus, postarchive, and tweaks.

For posterity, the snippet I used to identify this was
```javascript
var oldTrigger = Tumblr.Events.trigger;
Tumblr.Events.trigger = function() {
  console.log([].slice.call(arguments));
  return oldTrigger.apply(Tumblr.Events, arguments);
};
```

The code to fix this will look something like this (yes, this has officially turned into my notes on how to eventually fix this):
```javascript
var data = Object.create(Tumblr.PostView.prototype);
data.el = document.getElementById("post_141232323232");
data.$el = $(data.el);
data.$reblog_list = data.$el.find(".reblog-list");
data._listenId = "l267"; // dubious, real events were "l267" and "l262"
data._listeningTo = difficult_object; // dubious, real event had {l1: nonsense, l266: more nonsense}
data.capture_web_instream = a_more_difficult_object;
data.cid = "view265"; // dubious
data.controls = {
  like: data.$el.find(".post_control.like"),
  reblog: data.$el.find(".post_control.like"),
};
data.current_link = true;
data.is_click_trigger = false;
data.is_reblogged = false;
data.less_link = false;
data.like_heart_timeout = null;
data.loggingData = weird_object;
data.model = weirder_object;
data.modelForTinyGreyFollowButton = weirder_object_how_is_this_a_thing;
data.more_link = false;
data.note_count = data.$el.find(".note_count");
Tumblr.Events.trigger("postsView:createPost", data);
```

Okay, this actually looks like a bit too much fun. Current hope is that shoving the fake event into Tumblr will fix it, but this might be a good time to figure out how to fake Tumblr objects more reliably.

**Comment by hobinjk** [comment]
On a post getting created, it's created with something like
```javascript
var view = new Tumblr.PostView({
  el: $(postElement),
  model: Tumblr.PostsView.prototype.createPostModelFromEl($(postElement))
});
```

Hopefully this works, reverse engineering is difficult
