### ISSUE TITLE
Editable Reblogs Deletes Previous Interaction.

### ISSUE THREAD

**Issue by ElliSpeaks** [new-xkit/XKit#992]
I'm having a strange thing happen where my partner's post is deleting when Editable Reblogs is happening. All accounts are active (nothing deactivated, for the example I used two of MY accounts), and I don't have Reblog Display Options in my extensions since I don't mind the "Noted" look on my dash. After doing some testing, I **think** it's the ER extension that's doing it. And it literally was working 2 days ago when I was reblogging posts.

Here is me responding with an active window:
![image](https://cloud.githubusercontent.com/assets/15959327/13965056/e8f4ffe4-f029-11e5-9ea0-9bdf3d868ff7.png)

and here is the HTML if needed:
`<p><a href="http://quixoticquinn.tumblr.com/post/141091307155" class="tumblr_blog"> quixoticquinn </a>:</p><blockquote><p><b><b><b><b>❝</b></b></b></b><small><b>They come into MY city, disrupting MY House…where is the accountability in it all?<b><b><b><b><b><b><b><b><b><b><b><b>❞</b></b></b></b></b></b></b></b></b></b></b></b></b> Quinn said mostly to herself, although she wasn’t ignoring the person falling into step beside her. <b><b><b><b>❝</b></b></b></b><b>One of their actives goes rogue but I am the one who is expected to clean up the mess when we can’t even get a decent relay on what she’s imprinted with. How they honestly expect me to put my actives and staff in danger is baffling,<b><b><b><b><b><b><b><b><b><b><b><b>❞</b></b></b></b></b></b></b></b></b></b></b></b></b> the blonde remarked, shaking her head as she made her way to the imprint room.<br><br></small></p>
<figure><img src="https://38.media.tumblr.com/485d95f1bff8e9713c898e34e30fe763/tumblr_inline_o2u490tL7u1tv2jdx_500.gif"></figure></blockquote><p>Here is my text that I would like to respond with...and then my icon...</p><figure data-orig-height="100" data-orig-width="177"><img src="https://33.media.tumblr.com/c44dd640e698299510c42945bfa3891a/tumblr_inline_o469tfIB8y1tf0drc_500.gif" data-orig-height="100" data-orig-width="177"></figure>`

Here is my response on the dash:
![image](https://cloud.githubusercontent.com/assets/15959327/13965079/0ebdfeba-f02a-11e5-8f1b-025de508c61d.png)

And the code:
`<p><a class="tumblr_blog" href="http:// caffeinatedcarroll .tumblr.com"> caffeinatedcarroll </a>:</p><blockquote></blockquote><p>Here is my text that I would like to respond with...and then my icon...<br></p><figure data-orig-width="177" data-orig-height="100"><img src="https://33.media.tumblr.com/c44dd640e698299510c42945bfa3891a/tumblr_inline_o469tfIB8y1tf0drc_500.gif" alt="image" data-orig-width="177" data-orig-height="100"></figure>`

HALP!

**Comment by ElliSpeaks** [comment]
Troubleshooting: Updated ER, Deleted ER. Deleting ER doesn't delete the partner's previous response. Reinstalled ER, response gone again.

**Comment by kitsunegari101** [comment]
Having the same issues and tried the same fixes, to no avail.

**Comment by sequintrainwreck** [comment]
I'm having the same issues, however, the posts appear perfectly fine on my actual blogs. It's only on the dashboard that they're gone. This only began today. Have also tried the same fixes.

**Comment by gloomykid** [comment]
I'm having the same issue, just once it was also deleted from my actual blog, so I had to delete the post and make it anew, and then the post was fine on my blog, but still messed up on the dashboard... yikes... 8(

**Comment by nightpool** [comment]
Looks like we just pushed a new version that should address SOME of this
problem. Let us know if you keep seeing it!

**Comment by nightpool** [comment]
The new version is ER 3.0.7

**Comment by ElliSpeaks** [comment]
Fix works on my end. Thank you so much you guys. You're perfection ^_^
