### ISSUE TITLE
Tumblr's CSP breaks script injection in Firefox

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#995]
It's `script-src https://www.tumblr.com https://secure.assets.tumblr.com https://assets.tumblr.com https://sb.scorecardresearch.com https://*.google-analytics.com https://*.cedexis.com https://*.cedexis-test.com 'unsafe-eval' 'nonce-BsRuxURLVk50IN3my8ETjha6znU' https://fc.yahoo.com https://s.yimg.com`

Note that it has 'unsafe-eval' but not 'unsafe-inline'. There's probably a one-liner to get Firefox to pretend 'unsafe-inline' is there. Chrome's default behavior is to allow 'unsafe-eval' by default for some reason.

extensions that need to be updated:
- [x] ~~add_function~~
- [ ] outbox
- [x] reblog_as_text (should probably just be nuked unless we want to fix this to reblog images/photosets/links/etc. (something we actually get a lot of requests for fwiw))
- [x] soft_refresh
- [ ] xinbox
- [x] xkit_patches.blog_get

**Comment by nightpool** [comment]
added a list of extensions that need fixing/updating. 

(blog_get doesn't use add_function, and that's my fault, but it has to do with weird parts of how xkit_patches is structured)
